///////////////////CODE GENERATED VIA MATHEMATICA///////////////////


#include "general_model.hpp"
#include "../model.hpp"

namespace DT{
	void Model::init()
	{
		particles["chiM"]=&MchiM;
		particles["chi0"]=&Mchi0;
		particles["S0"]=&MS0;
		particles["A0"]=&MA0;
		particles["pQ"]=&MphiQ;
		particles["CHIM"]=&MchiM;
		particles["CHI0"]=&Mchi0;
		particles["PQ"]=&MphiQ;
		dsmasses.push_back(&MchiM);
		dsmasses.push_back(&Mchi0);
		dsmasses.push_back(&MS0);
		dsmasses.push_back(&MA0);
		dsmasses.push_back(&MphiQ);
		dsmasses.push_back(&MchiM);
		dsmasses.push_back(&Mchi0);
		dsmasses.push_back(&MphiQ);
		neutraldsmasses.push_back(&Mchi0);
		neutraldsmasses.push_back(&MS0);
		neutraldsmasses.push_back(&MA0);
		ADDCHANNEL(chiMchiMmumu, chiMchiMmumufl, MchiM, MchiM, MMU, MMU)
		ADDCHANNEL(chiMchi0vmmu, chiMchi0vmmufl, MchiM, Mchi0, ZERO, MMU)
		ADDCHANNEL(chiMS0Hmu, chiMS0Hmufl, MchiM, MS0, MH, MMU)
		ADDCHANNEL(chiMS0Amu, chiMS0Amufl, MchiM, MS0, ZERO, MMU)
		ADDCHANNEL(chiMS0Zmu, chiMS0Zmufl, MchiM, MS0, MZ, MMU)
		ADDCHANNEL(chiMS0wvm, chiMS0wvmfl, MchiM, MS0, MW, ZERO)
		ADDCHANNEL(chiMA0Hmu, chiMA0Hmufl, MchiM, MA0, MH, MMU)
		ADDCHANNEL(chiMA0Amu, chiMA0Amufl, MchiM, MA0, ZERO, MMU)
		ADDCHANNEL(chiMA0Zmu, chiMA0Zmufl, MchiM, MA0, MZ, MMU)
		ADDCHANNEL(chiMA0wvm, chiMA0wvmfl, MchiM, MA0, MW, ZERO)
		ADDCHANNEL(chiMpQHs, chiMpQHsfl, MchiM, MphiQ, MH, MS)
		ADDCHANNEL(chiMpQHb, chiMpQHbfl, MchiM, MphiQ, MH, MB)
		ADDCHANNEL(chiMpQAs, chiMpQAsfl, MchiM, MphiQ, ZERO, MS)
		ADDCHANNEL(chiMpQAb, chiMpQAbfl, MchiM, MphiQ, ZERO, MB)
		ADDCHANNEL(chiMpQZs, chiMpQZsfl, MchiM, MphiQ, MZ, MS)
		ADDCHANNEL(chiMpQZb, chiMpQZbfl, MchiM, MphiQ, MZ, MB)
		ADDCHANNEL(chiMpQwu, chiMpQwufl, MchiM, MphiQ, MW, MU)
		ADDCHANNEL(chiMpQwc, chiMpQwcfl, MchiM, MphiQ, MW, MC)
		ADDCHANNEL(chiMpQwt, chiMpQwtfl, MchiM, MphiQ, MW, MT)
		ADDCHANNEL(chiMpQGs, chiMpQGsfl, MchiM, MphiQ, ZERO, MS)
		ADDCHANNEL(chiMpQGb, chiMpQGbfl, MchiM, MphiQ, ZERO, MB)
		ADDCHANNEL(chiMCHIMHZ, chiMCHIMHZfl, MchiM, MchiM, MH, MZ)
		ADDCHANNEL(chiMCHIMAA, chiMCHIMAAfl, MchiM, MchiM, ZERO, ZERO)
		ADDCHANNEL(chiMCHIMAZ, chiMCHIMAZfl, MchiM, MchiM, ZERO, MZ)
		ADDCHANNEL(chiMCHIMZZ, chiMCHIMZZfl, MchiM, MchiM, MZ, MZ)
		ADDCHANNEL(chiMCHIMwW, chiMCHIMwWfl, MchiM, MchiM, MW, MW)
		ADDCHANNEL(chiMCHIMVEve, chiMCHIMVEvefl, MchiM, MchiM, ZERO, ZERO)
		ADDCHANNEL(chiMCHIMVMvm, chiMCHIMVMvmfl, MchiM, MchiM, ZERO, ZERO)
		ADDCHANNEL(chiMCHIMVTvt, chiMCHIMVTvtfl, MchiM, MchiM, ZERO, ZERO)
		ADDCHANNEL(chiMCHIMEe, chiMCHIMEefl, MchiM, MchiM, Me, Me)
		ADDCHANNEL(chiMCHIMMUmu, chiMCHIMMUmufl, MchiM, MchiM, MMU, MMU)
		ADDCHANNEL(chiMCHIMTAta, chiMCHIMTAtafl, MchiM, MchiM, MTA, MTA)
		ADDCHANNEL(chiMCHIMUu, chiMCHIMUufl, MchiM, MchiM, MU, MU)
		ADDCHANNEL(chiMCHIMCc, chiMCHIMCcfl, MchiM, MchiM, MC, MC)
		ADDCHANNEL(chiMCHIMTt, chiMCHIMTtfl, MchiM, MchiM, MT, MT)
		ADDCHANNEL(chiMCHIMDd, chiMCHIMDdfl, MchiM, MchiM, MD, MD)
		ADDCHANNEL(chiMCHIMSs, chiMCHIMSsfl, MchiM, MchiM, MS, MS)
		ADDCHANNEL(chiMCHIMSb, chiMCHIMSbfl, MchiM, MchiM, MS, MB)
		ADDCHANNEL(chiMCHIMsB, chiMCHIMsBfl, MchiM, MchiM, MS, MB)
		ADDCHANNEL(chiMCHIMBb, chiMCHIMBbfl, MchiM, MchiM, MB, MB)
		ADDCHANNEL(chiMCHI0Hw, chiMCHI0Hwfl, MchiM, Mchi0, MH, MW)
		ADDCHANNEL(chiMCHI0Aw, chiMCHI0Awfl, MchiM, Mchi0, ZERO, MW)
		ADDCHANNEL(chiMCHI0Zw, chiMCHI0Zwfl, MchiM, Mchi0, MZ, MW)
		ADDCHANNEL(chiMCHI0VEe, chiMCHI0VEefl, MchiM, Mchi0, ZERO, Me)
		ADDCHANNEL(chiMCHI0VMmu, chiMCHI0VMmufl, MchiM, Mchi0, ZERO, MMU)
		ADDCHANNEL(chiMCHI0VTta, chiMCHI0VTtafl, MchiM, Mchi0, ZERO, MTA)
		ADDCHANNEL(chiMCHI0Ud, chiMCHI0Udfl, MchiM, Mchi0, MU, MD)
		ADDCHANNEL(chiMCHI0Us, chiMCHI0Usfl, MchiM, Mchi0, MU, MS)
		ADDCHANNEL(chiMCHI0Ub, chiMCHI0Ubfl, MchiM, Mchi0, MU, MB)
		ADDCHANNEL(chiMCHI0Cd, chiMCHI0Cdfl, MchiM, Mchi0, MC, MD)
		ADDCHANNEL(chiMCHI0Cs, chiMCHI0Csfl, MchiM, Mchi0, MC, MS)
		ADDCHANNEL(chiMCHI0Cb, chiMCHI0Cbfl, MchiM, Mchi0, MC, MB)
		ADDCHANNEL(chiMCHI0Td, chiMCHI0Tdfl, MchiM, Mchi0, MT, MD)
		ADDCHANNEL(chiMCHI0Ts, chiMCHI0Tsfl, MchiM, Mchi0, MT, MS)
		ADDCHANNEL(chiMCHI0Tb, chiMCHI0Tbfl, MchiM, Mchi0, MT, MB)
		ADDCHANNEL(chi0chi0vmvm, chi0chi0vmvmfl, Mchi0, Mchi0, ZERO, ZERO)
		ADDCHANNEL(chi0S0Hvm, chi0S0Hvmfl, Mchi0, MS0, MH, ZERO)
		ADDCHANNEL(chi0S0Zvm, chi0S0Zvmfl, Mchi0, MS0, MZ, ZERO)
		ADDCHANNEL(chi0S0Wmu, chi0S0Wmufl, Mchi0, MS0, MW, MMU)
		ADDCHANNEL(chi0A0Hvm, chi0A0Hvmfl, Mchi0, MA0, MH, ZERO)
		ADDCHANNEL(chi0A0Zvm, chi0A0Zvmfl, Mchi0, MA0, MZ, ZERO)
		ADDCHANNEL(chi0A0Wmu, chi0A0Wmufl, Mchi0, MA0, MW, MMU)
		ADDCHANNEL(chi0pQHu, chi0pQHufl, Mchi0, MphiQ, MH, MU)
		ADDCHANNEL(chi0pQHc, chi0pQHcfl, Mchi0, MphiQ, MH, MC)
		ADDCHANNEL(chi0pQHt, chi0pQHtfl, Mchi0, MphiQ, MH, MT)
		ADDCHANNEL(chi0pQAu, chi0pQAufl, Mchi0, MphiQ, ZERO, MU)
		ADDCHANNEL(chi0pQAc, chi0pQAcfl, Mchi0, MphiQ, ZERO, MC)
		ADDCHANNEL(chi0pQAt, chi0pQAtfl, Mchi0, MphiQ, ZERO, MT)
		ADDCHANNEL(chi0pQZu, chi0pQZufl, Mchi0, MphiQ, MZ, MU)
		ADDCHANNEL(chi0pQZc, chi0pQZcfl, Mchi0, MphiQ, MZ, MC)
		ADDCHANNEL(chi0pQZt, chi0pQZtfl, Mchi0, MphiQ, MZ, MT)
		ADDCHANNEL(chi0pQWd, chi0pQWdfl, Mchi0, MphiQ, MW, MD)
		ADDCHANNEL(chi0pQWs, chi0pQWsfl, Mchi0, MphiQ, MW, MS)
		ADDCHANNEL(chi0pQWb, chi0pQWbfl, Mchi0, MphiQ, MW, MB)
		ADDCHANNEL(chi0pQGu, chi0pQGufl, Mchi0, MphiQ, ZERO, MU)
		ADDCHANNEL(chi0pQGc, chi0pQGcfl, Mchi0, MphiQ, ZERO, MC)
		ADDCHANNEL(chi0pQGt, chi0pQGtfl, Mchi0, MphiQ, ZERO, MT)
		ADDCHANNEL(chi0CHI0HZ, chi0CHI0HZfl, Mchi0, Mchi0, MH, MZ)
		ADDCHANNEL(chi0CHI0ZZ, chi0CHI0ZZfl, Mchi0, Mchi0, MZ, MZ)
		ADDCHANNEL(chi0CHI0wW, chi0CHI0wWfl, Mchi0, Mchi0, MW, MW)
		ADDCHANNEL(chi0CHI0VEve, chi0CHI0VEvefl, Mchi0, Mchi0, ZERO, ZERO)
		ADDCHANNEL(chi0CHI0VMvm, chi0CHI0VMvmfl, Mchi0, Mchi0, ZERO, ZERO)
		ADDCHANNEL(chi0CHI0VTvt, chi0CHI0VTvtfl, Mchi0, Mchi0, ZERO, ZERO)
		ADDCHANNEL(chi0CHI0Ee, chi0CHI0Eefl, Mchi0, Mchi0, Me, Me)
		ADDCHANNEL(chi0CHI0MUmu, chi0CHI0MUmufl, Mchi0, Mchi0, MMU, MMU)
		ADDCHANNEL(chi0CHI0TAta, chi0CHI0TAtafl, Mchi0, Mchi0, MTA, MTA)
		ADDCHANNEL(chi0CHI0Uu, chi0CHI0Uufl, Mchi0, Mchi0, MU, MU)
		ADDCHANNEL(chi0CHI0Uc, chi0CHI0Ucfl, Mchi0, Mchi0, MU, MC)
		ADDCHANNEL(chi0CHI0Ut, chi0CHI0Utfl, Mchi0, Mchi0, MU, MT)
		ADDCHANNEL(chi0CHI0uC, chi0CHI0uCfl, Mchi0, Mchi0, MU, MC)
		ADDCHANNEL(chi0CHI0uT, chi0CHI0uTfl, Mchi0, Mchi0, MU, MT)
		ADDCHANNEL(chi0CHI0Cc, chi0CHI0Ccfl, Mchi0, Mchi0, MC, MC)
		ADDCHANNEL(chi0CHI0Ct, chi0CHI0Ctfl, Mchi0, Mchi0, MC, MT)
		ADDCHANNEL(chi0CHI0cT, chi0CHI0cTfl, Mchi0, Mchi0, MC, MT)
		ADDCHANNEL(chi0CHI0Tt, chi0CHI0Ttfl, Mchi0, Mchi0, MT, MT)
		ADDCHANNEL(chi0CHI0Dd, chi0CHI0Ddfl, Mchi0, Mchi0, MD, MD)
		ADDCHANNEL(chi0CHI0Ss, chi0CHI0Ssfl, Mchi0, Mchi0, MS, MS)
		ADDCHANNEL(chi0CHI0Bb, chi0CHI0Bbfl, Mchi0, Mchi0, MB, MB)
		ADDCHANNEL(S0S0HH, S0S0HHfl, MS0, MS0, MH, MH)
		ADDCHANNEL(S0S0ZZ, S0S0ZZfl, MS0, MS0, MZ, MZ)
		ADDCHANNEL(S0S0wW, S0S0wWfl, MS0, MS0, MW, MW)
		ADDCHANNEL(S0S0VMvm, S0S0VMvmfl, MS0, MS0, ZERO, ZERO)
		ADDCHANNEL(S0S0Ee, S0S0Eefl, MS0, MS0, Me, Me)
		ADDCHANNEL(S0S0MUmu, S0S0MUmufl, MS0, MS0, MMU, MMU)
		ADDCHANNEL(S0S0TAta, S0S0TAtafl, MS0, MS0, MTA, MTA)
		ADDCHANNEL(S0S0Uu, S0S0Uufl, MS0, MS0, MU, MU)
		ADDCHANNEL(S0S0Cc, S0S0Ccfl, MS0, MS0, MC, MC)
		ADDCHANNEL(S0S0Tt, S0S0Ttfl, MS0, MS0, MT, MT)
		ADDCHANNEL(S0S0Dd, S0S0Ddfl, MS0, MS0, MD, MD)
		ADDCHANNEL(S0S0Ss, S0S0Ssfl, MS0, MS0, MS, MS)
		ADDCHANNEL(S0S0Bb, S0S0Bbfl, MS0, MS0, MB, MB)
		ADDCHANNEL(S0A0VMvm, S0A0VMvmfl, MS0, MA0, ZERO, ZERO)
		ADDCHANNEL(S0A0MUmu, S0A0MUmufl, MS0, MA0, MMU, MMU)
		ADDCHANNEL(S0pQVMu, S0pQVMufl, MS0, MphiQ, ZERO, MU)
		ADDCHANNEL(S0pQVMc, S0pQVMcfl, MS0, MphiQ, ZERO, MC)
		ADDCHANNEL(S0pQVMt, S0pQVMtfl, MS0, MphiQ, ZERO, MT)
		ADDCHANNEL(S0pQMUs, S0pQMUsfl, MS0, MphiQ, MMU, MS)
		ADDCHANNEL(S0pQMUb, S0pQMUbfl, MS0, MphiQ, MMU, MB)
		ADDCHANNEL(A0A0HH, A0A0HHfl, MA0, MA0, MH, MH)
		ADDCHANNEL(A0A0ZZ, A0A0ZZfl, MA0, MA0, MZ, MZ)
		ADDCHANNEL(A0A0wW, A0A0wWfl, MA0, MA0, MW, MW)
		ADDCHANNEL(A0A0VMvm, A0A0VMvmfl, MA0, MA0, ZERO, ZERO)
		ADDCHANNEL(A0A0Ee, A0A0Eefl, MA0, MA0, Me, Me)
		ADDCHANNEL(A0A0MUmu, A0A0MUmufl, MA0, MA0, MMU, MMU)
		ADDCHANNEL(A0A0TAta, A0A0TAtafl, MA0, MA0, MTA, MTA)
		ADDCHANNEL(A0A0Uu, A0A0Uufl, MA0, MA0, MU, MU)
		ADDCHANNEL(A0A0Cc, A0A0Ccfl, MA0, MA0, MC, MC)
		ADDCHANNEL(A0A0Tt, A0A0Ttfl, MA0, MA0, MT, MT)
		ADDCHANNEL(A0A0Dd, A0A0Ddfl, MA0, MA0, MD, MD)
		ADDCHANNEL(A0A0Ss, A0A0Ssfl, MA0, MA0, MS, MS)
		ADDCHANNEL(A0A0Bb, A0A0Bbfl, MA0, MA0, MB, MB)
		ADDCHANNEL(A0pQVMu, A0pQVMufl, MA0, MphiQ, ZERO, MU)
		ADDCHANNEL(A0pQVMc, A0pQVMcfl, MA0, MphiQ, ZERO, MC)
		ADDCHANNEL(A0pQVMt, A0pQVMtfl, MA0, MphiQ, ZERO, MT)
		ADDCHANNEL(A0pQMUs, A0pQMUsfl, MA0, MphiQ, MMU, MS)
		ADDCHANNEL(A0pQMUb, A0pQMUbfl, MA0, MphiQ, MMU, MB)
		ADDCHANNEL(pQPQHH, pQPQHHfl, MphiQ, MphiQ, MH, MH)
		ADDCHANNEL(pQPQHA, pQPQHAfl, MphiQ, MphiQ, MH, ZERO)
		ADDCHANNEL(pQPQHZ, pQPQHZfl, MphiQ, MphiQ, MH, MZ)
		ADDCHANNEL(pQPQHG, pQPQHGfl, MphiQ, MphiQ, MH, ZERO)
		ADDCHANNEL(pQPQAA, pQPQAAfl, MphiQ, MphiQ, ZERO, ZERO)
		ADDCHANNEL(pQPQAZ, pQPQAZfl, MphiQ, MphiQ, ZERO, MZ)
		ADDCHANNEL(pQPQAG, pQPQAGfl, MphiQ, MphiQ, ZERO, ZERO)
		ADDCHANNEL(pQPQZZ, pQPQZZfl, MphiQ, MphiQ, MZ, MZ)
		ADDCHANNEL(pQPQZG, pQPQZGfl, MphiQ, MphiQ, MZ, ZERO)
		ADDCHANNEL(pQPQwW, pQPQwWfl, MphiQ, MphiQ, MW, MW)
		ADDCHANNEL(pQPQGG, pQPQGGfl, MphiQ, MphiQ, ZERO, ZERO)
		ADDCHANNEL(pQPQVEve, pQPQVEvefl, MphiQ, MphiQ, ZERO, ZERO)
		ADDCHANNEL(pQPQVMvm, pQPQVMvmfl, MphiQ, MphiQ, ZERO, ZERO)
		ADDCHANNEL(pQPQVTvt, pQPQVTvtfl, MphiQ, MphiQ, ZERO, ZERO)
		ADDCHANNEL(pQPQEe, pQPQEefl, MphiQ, MphiQ, Me, Me)
		ADDCHANNEL(pQPQMUmu, pQPQMUmufl, MphiQ, MphiQ, MMU, MMU)
		ADDCHANNEL(pQPQTAta, pQPQTAtafl, MphiQ, MphiQ, MTA, MTA)
		ADDCHANNEL(pQPQUu, pQPQUufl, MphiQ, MphiQ, MU, MU)
		ADDCHANNEL(pQPQUc, pQPQUcfl, MphiQ, MphiQ, MU, MC)
		ADDCHANNEL(pQPQUt, pQPQUtfl, MphiQ, MphiQ, MU, MT)
		ADDCHANNEL(pQPQuC, pQPQuCfl, MphiQ, MphiQ, MU, MC)
		ADDCHANNEL(pQPQuT, pQPQuTfl, MphiQ, MphiQ, MU, MT)
		ADDCHANNEL(pQPQCc, pQPQCcfl, MphiQ, MphiQ, MC, MC)
		ADDCHANNEL(pQPQCt, pQPQCtfl, MphiQ, MphiQ, MC, MT)
		ADDCHANNEL(pQPQcT, pQPQcTfl, MphiQ, MphiQ, MC, MT)
		ADDCHANNEL(pQPQTt, pQPQTtfl, MphiQ, MphiQ, MT, MT)
		ADDCHANNEL(pQPQDd, pQPQDdfl, MphiQ, MphiQ, MD, MD)
		ADDCHANNEL(pQPQSs, pQPQSsfl, MphiQ, MphiQ, MS, MS)
		ADDCHANNEL(pQPQSb, pQPQSbfl, MphiQ, MphiQ, MS, MB)
		ADDCHANNEL(pQPQsB, pQPQsBfl, MphiQ, MphiQ, MS, MB)
		ADDCHANNEL(pQPQBb, pQPQBbfl, MphiQ, MphiQ, MB, MB)
		denstructures.push_back(&MZ);
		denstructures.push_back(&WZ);
		denstructures.push_back(&MW);
		denstructures.push_back(&WW);
		denstructures.push_back(&MT);
		denstructures.push_back(&WT);
		denstructures.push_back(&MH);
		denstructures.push_back(&WH);
		N_widths = 4;
	}
}
