(* Patched for use with FeynCalc *)
(* * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * *)
(*                                                                             *)
(*         This file has been automatically generated by FeynRules.            *)
(*                                                                             *)
(* * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * *)


FR$ModelInformation={
  ModelName->"Dark Doublet Phase (N2HDM)",
  Authors -> {"Andreas Goudelis, Bjoern Herrmann, Oscal Stal"},
  Version -> "1.0",
  Date -> "04. 10. 2013",
  Institutions -> {"LAPTh-Annecy, Oscar Klein Center-Stockholm"},
  Emails -> {"andreas.goudelis@lapth.cnrs.fr"}};

FR$ClassesTranslation={ve -> F[1], vm -> F[2], vt -> F[3], e -> F[4], m -> F[5], ta -> F[6], u -> F[7], c -> F[8], t -> F[9], d -> F[10], s -> F[11], b -> F[12], A -> V[1], Z -> V[2], W -> V[3], G -> V[4], ghA -> U[1], ghZ -> U[2], ghWp -> U[3], ghWm -> U[4], ghG -> U[5], H1 -> S[1], H2 -> S[2], H3 -> S[3], G0 -> S[4], Gch -> S[5], A0 -> S[6], Hch -> S[7]};

FR$InteractionOrderPerturbativeExpansion={{HIG, 0}, {QCD, 0}, {QED, 0}};

FR$GoldstoneList={S[4], S[5]};

(*     Declared indices    *)

IndexRange[ Index[Generation] ] = Range[ 3 ]

IndexRange[ Index[Colour] ] = NoUnfold[ Range[ 3 ] ]

IndexRange[ Index[Gluon] ] = NoUnfold[ Range[ 8 ] ]

IndexRange[ Index[SU2W] ] = Range[ 3 ]

(*     Declared particles    *)

M$ClassesDescription = {
F[1] == {
    SelfConjugate -> False,
    PropagatorType -> Straight,
    PropagatorArrow -> Forward,
    Mass -> Mnue,
    Indices -> {},
    PropagatorLabel -> "ve" },

F[2] == {
    SelfConjugate -> False,
    PropagatorType -> Straight,
    PropagatorArrow -> Forward,
    Mass -> Mnum,
    Indices -> {},
    PropagatorLabel -> "vm" },

F[3] == {
    SelfConjugate -> False,
    PropagatorType -> Straight,
    PropagatorArrow -> Forward,
    Mass -> Mnut,
    Indices -> {},
    PropagatorLabel -> "vt" },

F[4] == {
    SelfConjugate -> False,
    QuantumNumbers -> {-Q},
    PropagatorType -> Straight,
    PropagatorArrow -> Forward,
    Mass -> Me,
    Indices -> {},
    PropagatorLabel -> "e" },

F[5] == {
    SelfConjugate -> False,
    QuantumNumbers -> {-Q},
    PropagatorType -> Straight,
    PropagatorArrow -> Forward,
    Mass -> FCGV["MM"],
    Indices -> {},
    PropagatorLabel -> "m" },

F[6] == {
    SelfConjugate -> False,
    QuantumNumbers -> {-Q},
    PropagatorType -> Straight,
    PropagatorArrow -> Forward,
    Mass -> MTA,
    Indices -> {},
    PropagatorLabel -> "ta" },

F[7] == {
    SelfConjugate -> False,
    QuantumNumbers -> {(2*Q)/3},
    PropagatorType -> Straight,
    PropagatorArrow -> Forward,
    Mass -> FCGV["MU"],
    Indices -> {Index[Colour]},
    PropagatorLabel -> "u" },

F[8] == {
    SelfConjugate -> False,
    QuantumNumbers -> {(2*Q)/3},
    PropagatorType -> Straight,
    PropagatorArrow -> Forward,
    Mass -> FCGV["MC"],
    Indices -> {Index[Colour]},
    PropagatorLabel -> "c" },

F[9] == {
    SelfConjugate -> False,
    QuantumNumbers -> {(2*Q)/3},
    PropagatorType -> Straight,
    PropagatorArrow -> Forward,
    Mass -> FCGV["MT"],
    Indices -> {Index[Colour]},
    PropagatorLabel -> "t" },

F[10] == {
    SelfConjugate -> False,
    QuantumNumbers -> {-1/3*Q},
    PropagatorType -> Straight,
    PropagatorArrow -> Forward,
    Mass -> FCGV["MD"],
    Indices -> {Index[Colour]},
    PropagatorLabel -> "d" },

F[11] == {
    SelfConjugate -> False,
    QuantumNumbers -> {-1/3*Q},
    PropagatorType -> Straight,
    PropagatorArrow -> Forward,
    Mass -> FCGV["MS"],
    Indices -> {Index[Colour]},
    PropagatorLabel -> "s" },

F[12] == {
    SelfConjugate -> False,
    QuantumNumbers -> {-1/3*Q},
    PropagatorType -> Straight,
    PropagatorArrow -> Forward,
    Mass -> FCGV["MB"],
    Indices -> {Index[Colour]},
    PropagatorLabel -> "b" },

V[1] == {
    SelfConjugate -> True,
    PropagatorType -> Sine,
    PropagatorArrow -> None,
    Mass -> 0,
    Indices -> {},
    PropagatorLabel -> "A" },

V[2] == {
    SelfConjugate -> True,
    PropagatorType -> Sine,
    PropagatorArrow -> None,
    Mass -> FCGV["MZ"],
    Indices -> {},
    PropagatorLabel -> "Z" },

V[3] == {
    SelfConjugate -> False,
    QuantumNumbers -> {Q},
    PropagatorType -> Sine,
    PropagatorArrow -> Forward,
    Mass -> FCGV["MW"],
    Indices -> {},
    PropagatorLabel -> "W" },

V[4] == {
    SelfConjugate -> True,
    PropagatorType -> Cycles,
    PropagatorArrow -> None,
    Mass -> 0,
    Indices -> {Index[Gluon]},
    PropagatorLabel -> "G" },

U[1] == {
    SelfConjugate -> False,
    QuantumNumbers -> {GhostNumber},
    PropagatorType -> GhostDash,
    PropagatorArrow -> Forward,
    Mass -> 0,
    Indices -> {},
    PropagatorLabel -> "ghA" },

U[2] == {
    SelfConjugate -> False,
    QuantumNumbers -> {GhostNumber},
    PropagatorType -> GhostDash,
    PropagatorArrow -> Forward,
    Mass -> FCGV["MZ"],
    Indices -> {},
    PropagatorLabel -> "ghZ" },

U[3] == {
    SelfConjugate -> False,
    QuantumNumbers -> {Q, GhostNumber},
    PropagatorType -> GhostDash,
    PropagatorArrow -> Forward,
    Mass -> FCGV["MW"],
    Indices -> {},
    PropagatorLabel -> "ghWp" },

U[4] == {
    SelfConjugate -> False,
    QuantumNumbers -> {-Q, GhostNumber},
    PropagatorType -> GhostDash,
    PropagatorArrow -> Forward,
    Mass -> FCGV["MW"],
    Indices -> {},
    PropagatorLabel -> "ghWm" },

U[5] == {
    SelfConjugate -> False,
    QuantumNumbers -> {GhostNumber},
    PropagatorType -> GhostDash,
    PropagatorArrow -> Forward,
    Mass -> 0,
    Indices -> {Index[Gluon]},
    PropagatorLabel -> "ghG" },

S[1] == {
    SelfConjugate -> True,
    PropagatorType -> ScalarDash,
    PropagatorArrow -> None,
    Mass -> MH1,
    Indices -> {},
    PropagatorLabel -> "H1" },

S[2] == {
    SelfConjugate -> True,
    PropagatorType -> ScalarDash,
    PropagatorArrow -> None,
    Mass -> MH2,
    Indices -> {},
    PropagatorLabel -> "H2" },

S[3] == {
    SelfConjugate -> True,
    PropagatorType -> ScalarDash,
    PropagatorArrow -> None,
    Mass -> MH3,
    Indices -> {},
    PropagatorLabel -> "H3" },

S[4] == {
    SelfConjugate -> True,
    PropagatorType -> ScalarDash,
    PropagatorArrow -> None,
    Mass -> FCGV["MZ"],
    Indices -> {},
    PropagatorLabel -> "G0" },

S[5] == {
    SelfConjugate -> False,
    PropagatorType -> ScalarDash,
    PropagatorArrow -> None,
    QuantumNumbers -> {Q},
    Mass -> FCGV["MW"],
    Indices -> {},
    PropagatorLabel -> "Gch" },

S[6] == {
    SelfConjugate -> True,
    PropagatorType -> ScalarDash,
    PropagatorArrow -> None,
    Mass -> MA0,
    Indices -> {},
    PropagatorLabel -> "A0" },

S[7] == {
    SelfConjugate -> False,
    QuantumNumbers -> {Q},
    PropagatorType -> ScalarDash,
    PropagatorArrow -> Forward,
    Mass -> MHch,
    Indices -> {},
    PropagatorLabel -> "Hch" }
}


(*        Definitions       *)


Mnue[ ___ ] := Mnue;
Mnum[ ___ ] := Mnum;
Mnut[ ___ ] := Mnut;
Me[ ___ ] := Me;
FCGV["MM"][ ___ ] := FCGV["MM"];
MTA[ ___ ] := MTA;
FCGV["MU"][ ___ ] := FCGV["MU"];
FCGV["MC"][ ___ ] := FCGV["MC"];
FCGV["MT"][ ___ ] := FCGV["MT"];
FCGV["MD"][ ___ ] := FCGV["MD"];
FCGV["MS"][ ___ ] := FCGV["MS"];
FCGV["MB"][ ___ ] := FCGV["MB"];
FCGV["MZ"][ ___ ] := FCGV["MZ"];
FCGV["MW"][ ___ ] := FCGV["MW"];
MH1[ ___ ] := MH1;
MH2[ ___ ] := MH2;
MH3[ ___ ] := MH3;
MA0[ ___ ] := MA0;
MHch[ ___ ] := MHch;


TheLabel[ F[7, {__}] ] := TheLabel[F[7]];
TheLabel[ F[8, {__}] ] := TheLabel[F[8]];
TheLabel[ F[9, {__}] ] := TheLabel[F[9]];
TheLabel[ F[10, {__}] ] := TheLabel[F[10]];
TheLabel[ F[11, {__}] ] := TheLabel[F[11]];
TheLabel[ F[12, {__}] ] := TheLabel[F[12]];
TheLabel[ V[4, {__}] ] := TheLabel[V[4]];
TheLabel[ U[5, {__}] ] := TheLabel[U[5]];


(*      Couplings (calculated by FeynRules)      *)

M$CouplingMatrices = {

C[ S[6] , S[6] , S[6] , S[6] ] == {{(-3*I)*lam1, 0}},

C[ S[6] , S[6] , S[3] , S[3] ] == {{(-I)*lam1, 0}},

C[ S[3] , S[3] , S[3] , S[3] ] == {{(-3*I)*lam1, 0}},

C[ S[6] , S[6] , S[7] , -S[7] ] == {{(-I)*lam1, 0}},

C[ S[3] , S[3] , S[7] , -S[7] ] == {{(-I)*lam1, 0}},

C[ S[7] , S[7] , -S[7] , -S[7] ] == {{(-2*I)*lam1, 0}},

C[ S[6] , S[6] , S[4] , S[4] ] == {{(I*(2*m11^2 - 2*MH3^2 + lam7*vs^2))/v^2, 0}},

C[ S[6] , S[6] , S[5] , -S[5] ] == {{(I*(2*m11^2 - 2*MHch^2 + lam7*vs^2))/v^2, 0}},

C[ S[4] , S[4] , S[3] , S[3] ] == {{(I*(2*m11^2 - 2*MA0^2 + lam7*vs^2))/v^2, 0}},

C[ S[5] , -S[5] , S[3] , S[3] ] == {{(I*(2*m11^2 - 2*MHch^2 + lam7*vs^2))/v^2, 0}},

C[ S[4] , S[4] , S[7] , -S[7] ] == {{(I*(2*m11^2 - 2*MHch^2 + lam7*vs^2))/v^2, 0}},

C[ S[5] , -S[5] , S[7] , -S[7] ] == {{(I*(2*m11^2 - MA0^2 - MH3^2 + lam7*vs^2))/v^2, 0}},

C[ S[4] , -S[5] , S[3] , S[7] ] == {{(-MA0^2 + MHch^2)/v^2, 0}},

C[ -S[5] , -S[5] , S[7] , S[7] ] == {{((2*I)*(MA0 - MH3)*(MA0 + MH3))/v^2, 0}},

C[ S[4] , S[5] , S[3] , -S[7] ] == {{((MA0 - MHch)*(MA0 + MHch))/v^2, 0}},

C[ S[5] , S[5] , -S[7] , -S[7] ] == {{((2*I)*(MA0 - MH3)*(MA0 + MH3))/v^2, 0}},

C[ S[6] , S[4] , -S[5] , S[7] ] == {{((-I)*(MH3 - MHch)*(MH3 + MHch))/v^2, 0}},

C[ S[6] , S[4] , S[5] , -S[7] ] == {{((-I)*(MH3 - MHch)*(MH3 + MHch))/v^2, 0}},

C[ S[6] , S[4] , S[3] ] == {{((-I)*(MA0 - MH3)*(MA0 + MH3))/v, 0}},

C[ S[6] , -S[5] , S[7] ] == {{(-MA0^2 + MHch^2)/v, 0}},

C[ S[6] , S[5] , -S[7] ] == {{((MA0 - MHch)*(MA0 + MHch))/v, 0}},

C[ -S[5] , S[3] , S[7] ] == {{(I*(MH3 - MHch)*(MH3 + MHch))/v, 0}},

C[ S[5] , S[3] , -S[7] ] == {{(I*(MH3 - MHch)*(MH3 + MHch))/v, 0}},

C[ S[5] , -S[5] , V[1] , V[1] ] == {{(2*I)*FCGV["EL"]^2, 0}},

C[ S[7] , -S[7] , V[1] , V[1] ] == {{(2*I)*FCGV["EL"]^2, 0}},

C[ S[6] , S[4] , S[1] , S[3] ] == {{((-I)*(MA0 - MH3)*(MA0 + MH3)*Cos[aDM])/v^2, 0}},

C[ S[6] , -S[5] , S[1] , S[7] ] == {{-(((MA0 - MHch)*(MA0 + MHch)*Cos[aDM])/v^2), 0}},

C[ S[6] , S[5] , S[1] , -S[7] ] == {{((MA0 - MHch)*(MA0 + MHch)*Cos[aDM])/v^2, 0}},

C[ -S[5] , S[1] , S[3] , S[7] ] == {{(I*(MH3 - MHch)*(MH3 + MHch)*Cos[aDM])/v^2, 0}},

C[ S[5] , S[1] , S[3] , -S[7] ] == {{(I*(MH3 - MHch)*(MH3 + MHch)*Cos[aDM])/v^2, 0}},

C[ S[6] , S[6] , S[1] ] == {{(I*((2*m11^2 - 2*MA0^2 + lam7*vs^2)*Cos[aDM] - lam7*v*vs*Sin[aDM]))/v, 0}},

C[ S[1] , S[3] , S[3] ] == {{(I*((2*m11^2 - 2*MH3^2 + lam7*vs^2)*Cos[aDM] - lam7*v*vs*Sin[aDM]))/v, 0}},

C[ S[1] , S[7] , -S[7] ] == {{(I*((2*m11^2 - 2*MHch^2 + lam7*vs^2)*Cos[aDM] - lam7*v*vs*Sin[aDM]))/v, 0}},

C[ S[6] , S[6] , S[2] ] == {{((-I)*(lam7*v*vs*Cos[aDM] + (2*m11^2 - 2*MA0^2 + lam7*vs^2)*Sin[aDM]))/v, 0}},

C[ S[2] , S[3] , S[3] ] == {{((-I)*(lam7*v*vs*Cos[aDM] + (2*m11^2 - 2*MH3^2 + lam7*vs^2)*Sin[aDM]))/v, 0}},

C[ S[2] , S[7] , -S[7] ] == {{((-I)*(lam7*v*vs*Cos[aDM] + (2*m11^2 - 2*MHch^2 + lam7*vs^2)*Sin[aDM]))/v, 0}},

C[ S[6] , S[6] , S[2] , S[2] ] == {{(-I)*lam7*Cos[aDM]^2 + (I*(2*m11^2 - 2*MA0^2 + lam7*vs^2)*Sin[aDM]^2)/v^2, 0}},

C[ S[2] , S[2] , S[3] , S[3] ] == {{(-I)*lam7*Cos[aDM]^2 + (I*(2*m11^2 - 2*MH3^2 + lam7*vs^2)*Sin[aDM]^2)/v^2, 0}},

C[ S[2] , S[2] , S[7] , -S[7] ] == {{(-I)*lam7*Cos[aDM]^2 + (I*(2*m11^2 - 2*MHch^2 + lam7*vs^2)*Sin[aDM]^2)/v^2, 0}},

C[ S[6] , S[6] , S[1] , S[1] ] == {{I*(((2*m11^2 - 2*MA0^2 + lam7*vs^2)*Cos[aDM]^2)/v^2 - lam7*Sin[aDM]^2), 0}},

C[ S[1] , S[1] , S[3] , S[3] ] == {{I*(((2*m11^2 - 2*MH3^2 + lam7*vs^2)*Cos[aDM]^2)/v^2 - lam7*Sin[aDM]^2), 0}},

C[ S[1] , S[1] , S[7] , -S[7] ] == {{I*(((2*m11^2 - 2*MHch^2 + lam7*vs^2)*Cos[aDM]^2)/v^2 - lam7*Sin[aDM]^2), 0}},

C[ S[4] , S[4] , S[4] , S[4] ] == {{((-3*I)*(MH1^2*Cos[aDM]^2 + MH2^2*Sin[aDM]^2))/v^2, 0}},

C[ S[4] , S[4] , S[5] , -S[5] ] == {{((-I)*(MH1^2*Cos[aDM]^2 + MH2^2*Sin[aDM]^2))/v^2, 0}},

C[ S[5] , S[5] , -S[5] , -S[5] ] == {{((-2*I)*(MH1^2*Cos[aDM]^2 + MH2^2*Sin[aDM]^2))/v^2, 0}},

C[ S[4] , S[4] , S[1] ] == {{((-I)*MH1^2*Cos[aDM])/v, 0}},

C[ S[5] , -S[5] , S[1] ] == {{((-I)*MH1^2*Cos[aDM])/v, 0}},

C[ S[4] , S[4] , S[1] , S[1] ] == {{((-I)*Cos[aDM]*(MH1^2*vs*Cos[aDM]^3 + MH2^2*vs*Cos[aDM]*Sin[aDM]^2 + (MH1^2 - MH2^2)*v*Sin[aDM]^3))/(v^2*vs), 0}},

C[ S[5] , -S[5] , S[1] , S[1] ] == {{((-I)*Cos[aDM]*(MH1^2*vs*Cos[aDM]^3 + MH2^2*vs*Cos[aDM]*Sin[aDM]^2 + (MH1^2 - MH2^2)*v*Sin[aDM]^3))/(v^2*vs), 0}},

C[ S[1] , S[1] , S[1] ] == {{((-3*I)*MH1^2*(vs*Cos[aDM]^3 + v*Sin[aDM]^3))/(v*vs), 0}},

C[ S[2] , S[2] , S[2] ] == {{((-3*I)*MH2^2*(v*Cos[aDM]^3 - vs*Sin[aDM]^3))/(v*vs), 0}},

C[ S[1] , S[1] , S[1] , S[1] ] == {{((-3*I)*(MH1^2*vs^2*Cos[aDM]^6 + MH2^2*vs^2*Cos[aDM]^4*Sin[aDM]^2 + 2*(MH1^2 - MH2^2)*v*vs*Cos[aDM]^3*Sin[aDM]^3 + MH2^2*v^2*Cos[aDM]^2*Sin[aDM]^4 + MH1^2*v^2*Sin[aDM]^6))/(v^2*vs^2), 0}},

C[ S[2] , S[2] , S[2] , S[2] ] == {{((-3*I)*(MH2^2*v^2*Cos[aDM]^6 + MH1^2*v^2*Cos[aDM]^4*Sin[aDM]^2 + 2*(MH1^2 - MH2^2)*v*vs*Cos[aDM]^3*Sin[aDM]^3 + MH1^2*vs^2*Cos[aDM]^2*Sin[aDM]^4 + MH2^2*vs^2*Sin[aDM]^6))/(v^2*vs^2), 0}},

C[ S[5] , -S[5] , V[1] ] == {{(-I)*gc54, 0}, {I*gc54, 0}},

C[ S[7] , -S[7] , V[1] ] == {{(-I)*gc55, 0}, {I*gc55, 0}},

C[ -U[1] , U[4] , V[3] ] == {{I*gc56, 0}, {I*gc56, 0}, {0, 0}},

C[ -U[1] , U[3] , -V[3] ] == {{I*gc57, 0}, {I*gc57, 0}, {0, 0}},

C[ -S[5] , -U[4] , U[1] ] == {{((-1/2*I)*FCGV["EL"]^2*v)/FCGV["SW"], 0}},

C[ -U[4] , U[1] , -V[3] ] == {{I*gc59, 0}, {I*gc59, 0}, {0, 0}},

C[ S[4] , -U[4] , U[4] ] == {{-1/4*(FCGV["EL"]^2*v)/FCGV["SW"]^2, 0}},

C[ S[1] , -U[4] , U[4] ] == {{((-1/4*I)*FCGV["EL"]^2*v*Cos[aDM])/FCGV["SW"]^2, 0}},

C[ -U[4] , U[4] , V[1] ] == {{I*gc62, 0}, {I*gc62, 0}, {0, 0}},

C[ -U[4] , U[4] , V[2] ] == {{I*gc63, 0}, {I*gc63, 0}, {0, 0}},

C[ -S[5] , -U[4] , U[2] ] == {{((-1/4*I)*FCGV["EL"]^2*(FCGV["CW"] - FCGV["SW"])*(FCGV["CW"] + FCGV["SW"])*v)/(FCGV["CW"]*FCGV["SW"]^2), 0}},

C[ -U[4] , U[2] , -V[3] ] == {{I*gc65, 0}, {I*gc65, 0}, {0, 0}},

C[ S[5] , -U[3] , U[1] ] == {{((-1/2*I)*FCGV["EL"]^2*v)/FCGV["SW"], 0}},

C[ -U[3] , U[1] , V[3] ] == {{I*gc67, 0}, {I*gc67, 0}, {0, 0}},

C[ S[4] , -U[3] , U[3] ] == {{(FCGV["EL"]^2*v)/(4*FCGV["SW"]^2), 0}},

C[ S[1] , -U[3] , U[3] ] == {{((-1/4*I)*FCGV["EL"]^2*v*Cos[aDM])/FCGV["SW"]^2, 0}},

C[ -U[3] , U[3] , V[1] ] == {{I*gc70, 0}, {I*gc70, 0}, {0, 0}},

C[ -U[3] , U[3] , V[2] ] == {{I*gc71, 0}, {I*gc71, 0}, {0, 0}},

C[ S[5] , -U[3] , U[2] ] == {{((-1/4*I)*FCGV["EL"]^2*(FCGV["CW"] - FCGV["SW"])*(FCGV["CW"] + FCGV["SW"])*v)/(FCGV["CW"]*FCGV["SW"]^2), 0}},

C[ -U[3] , U[2] , V[3] ] == {{I*gc73, 0}, {I*gc73, 0}, {0, 0}},

C[ S[5] , -U[2] , U[4] ] == {{((I/4)*FCGV["EL"]^2*(FCGV["CW"]^2 + FCGV["SW"]^2)*v)/(FCGV["CW"]*FCGV["SW"]^2), 0}},

C[ -U[2] , U[4] , V[3] ] == {{I*gc75, 0}, {I*gc75, 0}, {0, 0}},

C[ -S[5] , -U[2] , U[3] ] == {{((I/4)*FCGV["EL"]^2*(FCGV["CW"]^2 + FCGV["SW"]^2)*v)/(FCGV["CW"]*FCGV["SW"]^2), 0}},

C[ -U[2] , U[3] , -V[3] ] == {{I*gc77, 0}, {I*gc77, 0}, {0, 0}},

C[ S[1] , -U[2] , U[2] ] == {{((-1/4*I)*FCGV["EL"]^2*(FCGV["CW"]^2 + FCGV["SW"]^2)^2*v*Cos[aDM])/(FCGV["CW"]^2*FCGV["SW"]^2), 0}},

C[ -U[5, {e1x1}] , U[5, {e2x1}] , V[4, {e3x2}] ] == {{gc79*FASUNF[e3x2, e1x1, e2x1], 0}, {gc79*FASUNF[e3x2, e1x1, e2x1], 0}, {0, 0}},

C[ V[4, {e1x2}] , V[4, {e2x2}] , V[4, {e3x2}] ] == {{-(gc80*FASUNF[e1x2, e2x2, e3x2]), 0}, {gc80*FASUNF[e1x2, e2x2, e3x2], 0}, {gc80*FASUNF[e1x2, e2x2, e3x2], 0}, {-(gc80*FASUNF[e1x2, e2x2, e3x2]), 0}, {-(gc80*FASUNF[e1x2, e2x2, e3x2]), 0}, {gc80*FASUNF[e1x2, e2x2, e3x2], 0}},

C[ V[4, {e1x2}] , V[4, {e2x2}] , V[4, {e3x2}] , V[4, {e4x2}] ] == {{(-I)*gc81*(FASUNF[e1x2, e2x2, e3x2, e4x2] + FASUNF[e1x2, e3x2, e2x2, e4x2]), 0}, {I*gc81*(FASUNF[e1x2, e2x2, e3x2, e4x2] - FASUNF[e1x2, e4x2, e2x2, e3x2]), 0}, {I*gc81*(FASUNF[e1x2, e3x2, e2x2, e4x2] + FASUNF[e1x2, e4x2, e2x2, e3x2]), 0}},

C[ -F[12, {e1x2}] , F[12, {e2x2}] , S[4] ] == {{gc82L*IndexDelta[e1x2, e2x2], 0}, {gc82R*IndexDelta[e1x2, e2x2], 0}},

C[ -F[12, {e1x2}] , F[12, {e2x2}] , S[1] ] == {{I*gc83*IndexDelta[e1x2, e2x2], 0}, {I*gc83*IndexDelta[e1x2, e2x2], 0}},

C[ -F[10, {e1x2}] , F[10, {e2x2}] , S[4] ] == {{gc84L*IndexDelta[e1x2, e2x2], 0}, {gc84R*IndexDelta[e1x2, e2x2], 0}},

C[ -F[10, {e1x2}] , F[10, {e2x2}] , S[1] ] == {{I*gc85*IndexDelta[e1x2, e2x2], 0}, {I*gc85*IndexDelta[e1x2, e2x2], 0}},

C[ -F[11, {e1x2}] , F[11, {e2x2}] , S[4] ] == {{gc86L*IndexDelta[e1x2, e2x2], 0}, {gc86R*IndexDelta[e1x2, e2x2], 0}},

C[ -F[11, {e1x2}] , F[11, {e2x2}] , S[1] ] == {{I*gc87*IndexDelta[e1x2, e2x2], 0}, {I*gc87*IndexDelta[e1x2, e2x2], 0}},

C[ -F[12, {e1x2}] , F[8, {e2x2}] , -S[5] ] == {{I*gc88L*IndexDelta[e1x2, e2x2], 0}, {I*gc88R*IndexDelta[e1x2, e2x2], 0}},

C[ -F[12, {e1x2}] , F[9, {e2x2}] , -S[5] ] == {{I*gc89L*IndexDelta[e1x2, e2x2], 0}, {I*gc89R*IndexDelta[e1x2, e2x2], 0}},

C[ -F[12, {e1x2}] , F[7, {e2x2}] , -S[5] ] == {{I*gc90L*IndexDelta[e1x2, e2x2], 0}, {I*gc90R*IndexDelta[e1x2, e2x2], 0}},

C[ -F[10, {e1x2}] , F[8, {e2x2}] , -S[5] ] == {{I*gc91L*IndexDelta[e1x2, e2x2], 0}, {I*gc91R*IndexDelta[e1x2, e2x2], 0}},

C[ -F[10, {e1x2}] , F[9, {e2x2}] , -S[5] ] == {{I*gc92L*IndexDelta[e1x2, e2x2], 0}, {I*gc92R*IndexDelta[e1x2, e2x2], 0}},

C[ -F[10, {e1x2}] , F[7, {e2x2}] , -S[5] ] == {{I*gc93L*IndexDelta[e1x2, e2x2], 0}, {I*gc93R*IndexDelta[e1x2, e2x2], 0}},

C[ -F[11, {e1x2}] , F[8, {e2x2}] , -S[5] ] == {{I*gc94L*IndexDelta[e1x2, e2x2], 0}, {I*gc94R*IndexDelta[e1x2, e2x2], 0}},

C[ -F[11, {e1x2}] , F[9, {e2x2}] , -S[5] ] == {{I*gc95L*IndexDelta[e1x2, e2x2], 0}, {I*gc95R*IndexDelta[e1x2, e2x2], 0}},

C[ -F[11, {e1x2}] , F[7, {e2x2}] , -S[5] ] == {{I*gc96L*IndexDelta[e1x2, e2x2], 0}, {I*gc96R*IndexDelta[e1x2, e2x2], 0}},

C[ -F[4] , F[4] , S[4] ] == {{gc97L, 0}, {gc97R, 0}},

C[ -F[4] , F[4] , S[1] ] == {{I*gc98, 0}, {I*gc98, 0}},

C[ -F[5] , F[5] , S[4] ] == {{gc99L, 0}, {gc99R, 0}},

C[ -F[5] , F[5] , S[1] ] == {{I*gc100, 0}, {I*gc100, 0}},

C[ -F[6] , F[6] , S[4] ] == {{gc101L, 0}, {gc101R, 0}},

C[ -F[6] , F[6] , S[1] ] == {{I*gc102, 0}, {I*gc102, 0}},

C[ -F[4] , F[1] , -S[5] ] == {{I*gc103, 0}, {0, 0}},

C[ -F[5] , F[2] , -S[5] ] == {{I*gc104, 0}, {0, 0}},

C[ -F[6] , F[3] , -S[5] ] == {{I*gc105, 0}, {0, 0}},

C[ -F[8, {e1x2}] , F[12, {e2x2}] , S[5] ] == {{I*gc106L*IndexDelta[e1x2, e2x2], 0}, {I*gc106R*IndexDelta[e1x2, e2x2], 0}},

C[ -F[8, {e1x2}] , F[10, {e2x2}] , S[5] ] == {{I*gc107L*IndexDelta[e1x2, e2x2], 0}, {I*gc107R*IndexDelta[e1x2, e2x2], 0}},

C[ -F[8, {e1x2}] , F[11, {e2x2}] , S[5] ] == {{I*gc108L*IndexDelta[e1x2, e2x2], 0}, {I*gc108R*IndexDelta[e1x2, e2x2], 0}},

C[ -F[9, {e1x2}] , F[12, {e2x2}] , S[5] ] == {{I*gc109L*IndexDelta[e1x2, e2x2], 0}, {I*gc109R*IndexDelta[e1x2, e2x2], 0}},

C[ -F[9, {e1x2}] , F[10, {e2x2}] , S[5] ] == {{I*gc110L*IndexDelta[e1x2, e2x2], 0}, {I*gc110R*IndexDelta[e1x2, e2x2], 0}},

C[ -F[9, {e1x2}] , F[11, {e2x2}] , S[5] ] == {{I*gc111L*IndexDelta[e1x2, e2x2], 0}, {I*gc111R*IndexDelta[e1x2, e2x2], 0}},

C[ -F[7, {e1x2}] , F[12, {e2x2}] , S[5] ] == {{I*gc112L*IndexDelta[e1x2, e2x2], 0}, {I*gc112R*IndexDelta[e1x2, e2x2], 0}},

C[ -F[7, {e1x2}] , F[10, {e2x2}] , S[5] ] == {{I*gc113L*IndexDelta[e1x2, e2x2], 0}, {I*gc113R*IndexDelta[e1x2, e2x2], 0}},

C[ -F[7, {e1x2}] , F[11, {e2x2}] , S[5] ] == {{I*gc114L*IndexDelta[e1x2, e2x2], 0}, {I*gc114R*IndexDelta[e1x2, e2x2], 0}},

C[ -F[8, {e1x2}] , F[8, {e2x2}] , S[4] ] == {{gc115L*IndexDelta[e1x2, e2x2], 0}, {gc115R*IndexDelta[e1x2, e2x2], 0}},

C[ -F[8, {e1x2}] , F[8, {e2x2}] , S[1] ] == {{I*gc116*IndexDelta[e1x2, e2x2], 0}, {I*gc116*IndexDelta[e1x2, e2x2], 0}},

C[ -F[9, {e1x2}] , F[9, {e2x2}] , S[4] ] == {{gc117L*IndexDelta[e1x2, e2x2], 0}, {gc117R*IndexDelta[e1x2, e2x2], 0}},

C[ -F[9, {e1x2}] , F[9, {e2x2}] , S[1] ] == {{I*gc118*IndexDelta[e1x2, e2x2], 0}, {I*gc118*IndexDelta[e1x2, e2x2], 0}},

C[ -F[7, {e1x2}] , F[7, {e2x2}] , S[4] ] == {{gc119L*IndexDelta[e1x2, e2x2], 0}, {gc119R*IndexDelta[e1x2, e2x2], 0}},

C[ -F[7, {e1x2}] , F[7, {e2x2}] , S[1] ] == {{I*gc120*IndexDelta[e1x2, e2x2], 0}, {I*gc120*IndexDelta[e1x2, e2x2], 0}},

C[ -F[1] , F[4] , S[5] ] == {{0, 0}, {I*gc121R, 0}},

C[ -F[2] , F[5] , S[5] ] == {{0, 0}, {I*gc122R, 0}},

C[ -F[3] , F[6] , S[5] ] == {{0, 0}, {I*gc123R, 0}},

C[ S[6] , S[4] , S[2] , S[3] ] == {{(I*(MA0 - MH3)*(MA0 + MH3)*Sin[aDM])/v^2, 0}},

C[ S[6] , -S[5] , S[2] , S[7] ] == {{((MA0 - MHch)*(MA0 + MHch)*Sin[aDM])/v^2, 0}},

C[ S[6] , S[5] , S[2] , -S[7] ] == {{-(((MA0 - MHch)*(MA0 + MHch)*Sin[aDM])/v^2), 0}},

C[ -S[5] , S[2] , S[3] , S[7] ] == {{((-I)*(MH3 - MHch)*(MH3 + MHch)*Sin[aDM])/v^2, 0}},

C[ S[5] , S[2] , S[3] , -S[7] ] == {{((-I)*(MH3 - MHch)*(MH3 + MHch)*Sin[aDM])/v^2, 0}},

C[ S[6] , S[6] , S[1] , S[2] ] == {{((-I)*(2*m11^2 - 2*MA0^2 + lam7*(v^2 + vs^2))*Cos[aDM]*Sin[aDM])/v^2, 0}},

C[ S[1] , S[2] , S[3] , S[3] ] == {{((-I)*(2*m11^2 - 2*MH3^2 + lam7*(v^2 + vs^2))*Cos[aDM]*Sin[aDM])/v^2, 0}},

C[ S[1] , S[2] , S[7] , -S[7] ] == {{((-I)*(2*m11^2 - 2*MHch^2 + lam7*(v^2 + vs^2))*Cos[aDM]*Sin[aDM])/v^2, 0}},

C[ S[4] , S[4] , S[2] ] == {{(I*MH2^2*Sin[aDM])/v, 0}},

C[ S[5] , -S[5] , S[2] ] == {{(I*MH2^2*Sin[aDM])/v, 0}},

C[ S[4] , S[4] , S[1] , S[2] ] == {{(I*Cos[aDM]*Sin[aDM]*(MH1^2*vs*Cos[aDM]^2 - (MH1^2 - MH2^2)*v*Cos[aDM]*Sin[aDM] + MH2^2*vs*Sin[aDM]^2))/(v^2*vs), 0}},

C[ S[5] , -S[5] , S[1] , S[2] ] == {{(I*Cos[aDM]*Sin[aDM]*(MH1^2*vs*Cos[aDM]^2 - (MH1^2 - MH2^2)*v*Cos[aDM]*Sin[aDM] + MH2^2*vs*Sin[aDM]^2))/(v^2*vs), 0}},

C[ S[4] , S[4] , S[2] , S[2] ] == {{((-I)*Sin[aDM]*((MH1^2 - MH2^2)*v*Cos[aDM]^3 + MH1^2*vs*Cos[aDM]^2*Sin[aDM] + MH2^2*vs*Sin[aDM]^3))/(v^2*vs), 0}},

C[ S[5] , -S[5] , S[2] , S[2] ] == {{((-I)*Sin[aDM]*((MH1^2 - MH2^2)*v*Cos[aDM]^3 + MH1^2*vs*Cos[aDM]^2*Sin[aDM] + MH2^2*vs*Sin[aDM]^3))/(v^2*vs), 0}},

C[ S[1] , S[1] , S[2] ] == {{(I*(2*MH1^2 + MH2^2)*Cos[aDM]*Sin[aDM]*(vs*Cos[aDM] - v*Sin[aDM]))/(v*vs), 0}},

C[ S[1] , S[2] , S[2] ] == {{((-I)*(MH1^2 + 2*MH2^2)*Cos[aDM]*Sin[aDM]*(v*Cos[aDM] + vs*Sin[aDM]))/(v*vs), 0}},

C[ S[1] , S[1] , S[1] , S[2] ] == {{((3*I)*Cos[aDM]*Sin[aDM]*(vs*Cos[aDM] - v*Sin[aDM])*(MH1^2*vs*Cos[aDM]^3 + MH2^2*v*Cos[aDM]^2*Sin[aDM] + MH2^2*vs*Cos[aDM]*Sin[aDM]^2 + MH1^2*v*Sin[aDM]^3))/(v^2*vs^2), 0}},

C[ S[1] , S[2] , S[2] , S[2] ] == {{((3*I)*Cos[aDM]*Sin[aDM]*(v*Cos[aDM] + vs*Sin[aDM])*(-(MH2^2*v*Cos[aDM]^3) + MH1^2*vs*Cos[aDM]^2*Sin[aDM] - MH1^2*v*Cos[aDM]*Sin[aDM]^2 + MH2^2*vs*Sin[aDM]^3))/(v^2*vs^2), 0}},

C[ S[1] , S[1] , S[2] , S[2] ] == {{((-I)*Cos[aDM]*Sin[aDM]*((MH1^2 - MH2^2)*v*vs*Cos[aDM]^4 + 3*(MH2^2*v^2 + MH1^2*vs^2)*Cos[aDM]^3*Sin[aDM] - ((MH1^2 - MH2^2)*v*vs*(3 + 5*Cos[2*aDM])*Sin[aDM]^2)/2 + 3*(MH1^2*v^2 + MH2^2*vs^2)*Cos[aDM]*Sin[aDM]^3))/(v^2*vs^2), 0}},

C[ S[2] , -U[4] , U[4] ] == {{((I/4)*FCGV["EL"]^2*v*Sin[aDM])/FCGV["SW"]^2, 0}},

C[ S[2] , -U[3] , U[3] ] == {{((I/4)*FCGV["EL"]^2*v*Sin[aDM])/FCGV["SW"]^2, 0}},

C[ S[2] , -U[2] , U[2] ] == {{((I/4)*FCGV["EL"]^2*(FCGV["CW"]^2 + FCGV["SW"]^2)^2*v*Sin[aDM])/(FCGV["CW"]^2*FCGV["SW"]^2), 0}},

C[ -F[12, {e1x2}] , F[12, {e2x2}] , S[2] ] == {{I*gc146*IndexDelta[e1x2, e2x2], 0}, {I*gc146*IndexDelta[e1x2, e2x2], 0}},

C[ -F[10, {e1x2}] , F[10, {e2x2}] , S[2] ] == {{I*gc147*IndexDelta[e1x2, e2x2], 0}, {I*gc147*IndexDelta[e1x2, e2x2], 0}},

C[ -F[11, {e1x2}] , F[11, {e2x2}] , S[2] ] == {{I*gc148*IndexDelta[e1x2, e2x2], 0}, {I*gc148*IndexDelta[e1x2, e2x2], 0}},

C[ -F[4] , F[4] , S[2] ] == {{I*gc149, 0}, {I*gc149, 0}},

C[ -F[5] , F[5] , S[2] ] == {{I*gc150, 0}, {I*gc150, 0}},

C[ -F[6] , F[6] , S[2] ] == {{I*gc151, 0}, {I*gc151, 0}},

C[ -F[8, {e1x2}] , F[8, {e2x2}] , S[2] ] == {{I*gc152*IndexDelta[e1x2, e2x2], 0}, {I*gc152*IndexDelta[e1x2, e2x2], 0}},

C[ -F[9, {e1x2}] , F[9, {e2x2}] , S[2] ] == {{I*gc153*IndexDelta[e1x2, e2x2], 0}, {I*gc153*IndexDelta[e1x2, e2x2], 0}},

C[ -F[7, {e1x2}] , F[7, {e2x2}] , S[2] ] == {{I*gc154*IndexDelta[e1x2, e2x2], 0}, {I*gc154*IndexDelta[e1x2, e2x2], 0}},

C[ -F[12, {e1x2}] , F[12, {e2x2}] , V[4, {e3x2}] ] == {{I*gc155*FASUNT[e3x2, e1x2, e2x2], 0}, {I*gc155*FASUNT[e3x2, e1x2, e2x2], 0}},

C[ -F[10, {e1x2}] , F[10, {e2x2}] , V[4, {e3x2}] ] == {{I*gc156*FASUNT[e3x2, e1x2, e2x2], 0}, {I*gc156*FASUNT[e3x2, e1x2, e2x2], 0}},

C[ -F[11, {e1x2}] , F[11, {e2x2}] , V[4, {e3x2}] ] == {{I*gc157*FASUNT[e3x2, e1x2, e2x2], 0}, {I*gc157*FASUNT[e3x2, e1x2, e2x2], 0}},

C[ -F[8, {e1x2}] , F[8, {e2x2}] , V[4, {e3x2}] ] == {{I*gc158*FASUNT[e3x2, e1x2, e2x2], 0}, {I*gc158*FASUNT[e3x2, e1x2, e2x2], 0}},

C[ -F[9, {e1x2}] , F[9, {e2x2}] , V[4, {e3x2}] ] == {{I*gc159*FASUNT[e3x2, e1x2, e2x2], 0}, {I*gc159*FASUNT[e3x2, e1x2, e2x2], 0}},

C[ -F[7, {e1x2}] , F[7, {e2x2}] , V[4, {e3x2}] ] == {{I*gc160*FASUNT[e3x2, e1x2, e2x2], 0}, {I*gc160*FASUNT[e3x2, e1x2, e2x2], 0}},

C[ S[4] , -S[5] , V[1] , V[3] ] == {{-1/2*FCGV["EL"]^2/FCGV["SW"], 0}},

C[ S[6] , -S[7] , V[1] , V[3] ] == {{-1/2*FCGV["EL"]^2/FCGV["SW"], 0}},

C[ S[3] , -S[7] , V[1] , V[3] ] == {{((-1/2*I)*FCGV["EL"]^2)/FCGV["SW"], 0}},

C[ -S[5] , V[1] , V[3] ] == {{((I/2)*FCGV["EL"]^2*v)/FCGV["SW"], 0}},

C[ -S[5] , S[1] , V[1] , V[3] ] == {{((I/2)*FCGV["EL"]^2*Cos[aDM])/FCGV["SW"], 0}},

C[ S[6] , -S[7] , V[3] ] == {{-gc166, 0}, {gc166, 0}},

C[ S[4] , -S[5] , V[3] ] == {{-gc167, 0}, {gc167, 0}},

C[ -S[5] , S[1] , V[3] ] == {{(-I)*gc168, 0}, {I*gc168, 0}},

C[ S[3] , -S[7] , V[3] ] == {{(-I)*gc169, 0}, {I*gc169, 0}},

C[ V[1] , V[3] , -V[3] ] == {{(-I)*gc170, 0}, {I*gc170, 0}, {I*gc170, 0}, {(-I)*gc170, 0}, {(-I)*gc170, 0}, {I*gc170, 0}},

C[ -S[5] , S[2] , V[1] , V[3] ] == {{((-1/2*I)*FCGV["EL"]^2*Sin[aDM])/FCGV["SW"], 0}},

C[ -S[5] , S[2] , V[3] ] == {{(-I)*gc172, 0}, {I*gc172, 0}},

C[ S[4] , S[5] , V[1] , -V[3] ] == {{FCGV["EL"]^2/(2*FCGV["SW"]), 0}},

C[ S[6] , S[7] , V[1] , -V[3] ] == {{FCGV["EL"]^2/(2*FCGV["SW"]), 0}},

C[ S[3] , S[7] , V[1] , -V[3] ] == {{((-1/2*I)*FCGV["EL"]^2)/FCGV["SW"], 0}},

C[ S[5] , V[1] , -V[3] ] == {{((I/2)*FCGV["EL"]^2*v)/FCGV["SW"], 0}},

C[ S[5] , S[1] , V[1] , -V[3] ] == {{((I/2)*FCGV["EL"]^2*Cos[aDM])/FCGV["SW"], 0}},

C[ S[6] , S[7] , -V[3] ] == {{-gc178, 0}, {gc178, 0}},

C[ S[4] , S[5] , -V[3] ] == {{-gc179, 0}, {gc179, 0}},

C[ S[5] , S[1] , -V[3] ] == {{(-I)*gc180, 0}, {I*gc180, 0}},

C[ S[3] , S[7] , -V[3] ] == {{(-I)*gc181, 0}, {I*gc181, 0}},

C[ S[5] , S[2] , V[1] , -V[3] ] == {{((-1/2*I)*FCGV["EL"]^2*Sin[aDM])/FCGV["SW"], 0}},

C[ S[5] , S[2] , -V[3] ] == {{(-I)*gc183, 0}, {I*gc183, 0}},

C[ S[6] , S[6] , V[3] , -V[3] ] == {{((I/2)*FCGV["EL"]^2)/FCGV["SW"]^2, 0}},

C[ S[4] , S[4] , V[3] , -V[3] ] == {{((I/2)*FCGV["EL"]^2)/FCGV["SW"]^2, 0}},

C[ S[5] , -S[5] , V[3] , -V[3] ] == {{((I/2)*FCGV["EL"]^2)/FCGV["SW"]^2, 0}},

C[ S[3] , S[3] , V[3] , -V[3] ] == {{((I/2)*FCGV["EL"]^2)/FCGV["SW"]^2, 0}},

C[ S[7] , -S[7] , V[3] , -V[3] ] == {{((I/2)*FCGV["EL"]^2)/FCGV["SW"]^2, 0}},

C[ V[1] , V[1] , V[3] , -V[3] ] == {{(-I)*gc189, 0}, {(-I)*gc189, 0}, {(2*I)*gc189, 0}},

C[ S[1] , V[3] , -V[3] ] == {{((I/2)*FCGV["EL"]^2*v*Cos[aDM])/FCGV["SW"]^2, 0}},

C[ S[1] , S[1] , V[3] , -V[3] ] == {{((I/2)*FCGV["EL"]^2*Cos[aDM]^2)/FCGV["SW"]^2, 0}},

C[ S[2] , V[3] , -V[3] ] == {{((-1/2*I)*FCGV["EL"]^2*v*Sin[aDM])/FCGV["SW"]^2, 0}},

C[ S[1] , S[2] , V[3] , -V[3] ] == {{((-1/2*I)*FCGV["EL"]^2*Cos[aDM]*Sin[aDM])/FCGV["SW"]^2, 0}},

C[ S[2] , S[2] , V[3] , -V[3] ] == {{((I/2)*FCGV["EL"]^2*Sin[aDM]^2)/FCGV["SW"]^2, 0}},

C[ V[3] , -V[3] , V[2] ] == {{(-I)*gc195, 0}, {I*gc195, 0}, {I*gc195, 0}, {(-I)*gc195, 0}, {(-I)*gc195, 0}, {I*gc195, 0}},

C[ V[3] , V[3] , -V[3] , -V[3] ] == {{(-I)*gc196, 0}, {(-I)*gc196, 0}, {(2*I)*gc196, 0}},

C[ S[5] , -S[5] , V[1] , V[2] ] == {{(I*FCGV["EL"]^2*(FCGV["CW"] - FCGV["SW"])*(FCGV["CW"] + FCGV["SW"]))/(FCGV["CW"]*FCGV["SW"]), 0}},

C[ S[7] , -S[7] , V[1] , V[2] ] == {{(I*FCGV["EL"]^2*(FCGV["CW"] - FCGV["SW"])*(FCGV["CW"] + FCGV["SW"]))/(FCGV["CW"]*FCGV["SW"]), 0}},

C[ S[6] , S[3] , V[2] ] == {{-gc199, 0}, {gc199, 0}},

C[ S[4] , S[1] , V[2] ] == {{-gc200, 0}, {gc200, 0}},

C[ S[5] , -S[5] , V[2] ] == {{(-I)*gc201, 0}, {I*gc201, 0}},

C[ S[7] , -S[7] , V[2] ] == {{(-I)*gc202, 0}, {I*gc202, 0}},

C[ S[4] , S[2] , V[2] ] == {{-gc203, 0}, {gc203, 0}},

C[ S[4] , -S[5] , V[3] , V[2] ] == {{FCGV["EL"]^2/(2*FCGV["CW"]), 0}},

C[ S[6] , -S[7] , V[3] , V[2] ] == {{FCGV["EL"]^2/(2*FCGV["CW"]), 0}},

C[ S[3] , -S[7] , V[3] , V[2] ] == {{((I/2)*FCGV["EL"]^2)/FCGV["CW"], 0}},

C[ -S[5] , V[3] , V[2] ] == {{((-1/2*I)*FCGV["EL"]^2*v)/FCGV["CW"], 0}},

C[ -S[5] , S[1] , V[3] , V[2] ] == {{((-1/2*I)*FCGV["EL"]^2*Cos[aDM])/FCGV["CW"], 0}},

C[ -S[5] , S[2] , V[3] , V[2] ] == {{((I/2)*FCGV["EL"]^2*Sin[aDM])/FCGV["CW"], 0}},

C[ S[4] , S[5] , -V[3] , V[2] ] == {{-1/2*FCGV["EL"]^2/FCGV["CW"], 0}},

C[ S[6] , S[7] , -V[3] , V[2] ] == {{-1/2*FCGV["EL"]^2/FCGV["CW"], 0}},

C[ S[3] , S[7] , -V[3] , V[2] ] == {{((I/2)*FCGV["EL"]^2)/FCGV["CW"], 0}},

C[ S[5] , -V[3] , V[2] ] == {{((-1/2*I)*FCGV["EL"]^2*v)/FCGV["CW"], 0}},

C[ S[5] , S[1] , -V[3] , V[2] ] == {{((-1/2*I)*FCGV["EL"]^2*Cos[aDM])/FCGV["CW"], 0}},

C[ S[5] , S[2] , -V[3] , V[2] ] == {{((I/2)*FCGV["EL"]^2*Sin[aDM])/FCGV["CW"], 0}},

C[ V[1] , V[3] , -V[3] , V[2] ] == {{(-2*I)*gc216, 0}, {I*gc216, 0}, {I*gc216, 0}},

C[ S[6] , S[6] , V[2] , V[2] ] == {{((I/2)*FCGV["EL"]^2*(FCGV["CW"]^2 + FCGV["SW"]^2)^2)/(FCGV["CW"]^2*FCGV["SW"]^2), 0}},

C[ S[4] , S[4] , V[2] , V[2] ] == {{((I/2)*FCGV["EL"]^2*(FCGV["CW"]^2 + FCGV["SW"]^2)^2)/(FCGV["CW"]^2*FCGV["SW"]^2), 0}},

C[ S[5] , -S[5] , V[2] , V[2] ] == {{((I/2)*FCGV["EL"]^2*(FCGV["CW"] - FCGV["SW"])^2*(FCGV["CW"] + FCGV["SW"])^2)/(FCGV["CW"]^2*FCGV["SW"]^2), 0}},

C[ S[3] , S[3] , V[2] , V[2] ] == {{((I/2)*FCGV["EL"]^2*(FCGV["CW"]^2 + FCGV["SW"]^2)^2)/(FCGV["CW"]^2*FCGV["SW"]^2), 0}},

C[ S[7] , -S[7] , V[2] , V[2] ] == {{((I/2)*FCGV["EL"]^2*(FCGV["CW"] - FCGV["SW"])^2*(FCGV["CW"] + FCGV["SW"])^2)/(FCGV["CW"]^2*FCGV["SW"]^2), 0}},

C[ S[1] , V[2] , V[2] ] == {{((I/2)*FCGV["EL"]^2*(FCGV["CW"]^2 + FCGV["SW"]^2)^2*v*Cos[aDM])/(FCGV["CW"]^2*FCGV["SW"]^2), 0}},

C[ S[1] , S[1] , V[2] , V[2] ] == {{((I/2)*FCGV["EL"]^2*(FCGV["CW"]^2 + FCGV["SW"]^2)^2*Cos[aDM]^2)/(FCGV["CW"]^2*FCGV["SW"]^2), 0}},

C[ S[2] , V[2] , V[2] ] == {{((-1/2*I)*FCGV["EL"]^2*(FCGV["CW"]^2 + FCGV["SW"]^2)^2*v*Sin[aDM])/(FCGV["CW"]^2*FCGV["SW"]^2), 0}},

C[ S[1] , S[2] , V[2] , V[2] ] == {{((-1/4*I)*FCGV["EL"]^2*(FCGV["CW"]^2 + FCGV["SW"]^2)^2*Sin[2*aDM])/(FCGV["CW"]^2*FCGV["SW"]^2), 0}},

C[ S[2] , S[2] , V[2] , V[2] ] == {{((I/2)*FCGV["EL"]^2*(FCGV["CW"]^2 + FCGV["SW"]^2)^2*Sin[aDM]^2)/(FCGV["CW"]^2*FCGV["SW"]^2), 0}},

C[ V[3] , -V[3] , V[2] , V[2] ] == {{(-I)*gc227, 0}, {(-I)*gc227, 0}, {(2*I)*gc227, 0}},

C[ -F[12, {e1x2}] , F[12, {e2x2}] , V[1] ] == {{I*gc228*IndexDelta[e1x2, e2x2], 0}, {I*gc228*IndexDelta[e1x2, e2x2], 0}},

C[ -F[10, {e1x2}] , F[10, {e2x2}] , V[1] ] == {{I*gc229*IndexDelta[e1x2, e2x2], 0}, {I*gc229*IndexDelta[e1x2, e2x2], 0}},

C[ -F[11, {e1x2}] , F[11, {e2x2}] , V[1] ] == {{I*gc230*IndexDelta[e1x2, e2x2], 0}, {I*gc230*IndexDelta[e1x2, e2x2], 0}},

C[ -F[4] , F[4] , V[1] ] == {{I*gc231, 0}, {I*gc231, 0}},

C[ -F[5] , F[5] , V[1] ] == {{I*gc232, 0}, {I*gc232, 0}},

C[ -F[6] , F[6] , V[1] ] == {{I*gc233, 0}, {I*gc233, 0}},

C[ -F[8, {e1x2}] , F[8, {e2x2}] , V[1] ] == {{I*gc234*IndexDelta[e1x2, e2x2], 0}, {I*gc234*IndexDelta[e1x2, e2x2], 0}},

C[ -F[9, {e1x2}] , F[9, {e2x2}] , V[1] ] == {{I*gc235*IndexDelta[e1x2, e2x2], 0}, {I*gc235*IndexDelta[e1x2, e2x2], 0}},

C[ -F[7, {e1x2}] , F[7, {e2x2}] , V[1] ] == {{I*gc236*IndexDelta[e1x2, e2x2], 0}, {I*gc236*IndexDelta[e1x2, e2x2], 0}},

C[ -F[1] , F[4] , V[3] ] == {{I*gc237, 0}, {0, 0}},

C[ -F[2] , F[5] , V[3] ] == {{I*gc238, 0}, {0, 0}},

C[ -F[3] , F[6] , V[3] ] == {{I*gc239, 0}, {0, 0}},

C[ -F[8, {e1x2}] , F[12, {e2x2}] , V[3] ] == {{I*gc240*IndexDelta[e1x2, e2x2], 0}, {0, 0}},

C[ -F[8, {e1x2}] , F[10, {e2x2}] , V[3] ] == {{I*gc241*IndexDelta[e1x2, e2x2], 0}, {0, 0}},

C[ -F[8, {e1x2}] , F[11, {e2x2}] , V[3] ] == {{I*gc242*IndexDelta[e1x2, e2x2], 0}, {0, 0}},

C[ -F[9, {e1x2}] , F[12, {e2x2}] , V[3] ] == {{I*gc243*IndexDelta[e1x2, e2x2], 0}, {0, 0}},

C[ -F[9, {e1x2}] , F[10, {e2x2}] , V[3] ] == {{I*gc244*IndexDelta[e1x2, e2x2], 0}, {0, 0}},

C[ -F[9, {e1x2}] , F[11, {e2x2}] , V[3] ] == {{I*gc245*IndexDelta[e1x2, e2x2], 0}, {0, 0}},

C[ -F[7, {e1x2}] , F[12, {e2x2}] , V[3] ] == {{I*gc246*IndexDelta[e1x2, e2x2], 0}, {0, 0}},

C[ -F[7, {e1x2}] , F[10, {e2x2}] , V[3] ] == {{I*gc247*IndexDelta[e1x2, e2x2], 0}, {0, 0}},

C[ -F[7, {e1x2}] , F[11, {e2x2}] , V[3] ] == {{I*gc248*IndexDelta[e1x2, e2x2], 0}, {0, 0}},

C[ -F[4] , F[1] , -V[3] ] == {{I*gc249, 0}, {0, 0}},

C[ -F[5] , F[2] , -V[3] ] == {{I*gc250, 0}, {0, 0}},

C[ -F[6] , F[3] , -V[3] ] == {{I*gc251, 0}, {0, 0}},

C[ -F[12, {e1x2}] , F[8, {e2x2}] , -V[3] ] == {{I*gc252*IndexDelta[e1x2, e2x2], 0}, {0, 0}},

C[ -F[12, {e1x2}] , F[9, {e2x2}] , -V[3] ] == {{I*gc253*IndexDelta[e1x2, e2x2], 0}, {0, 0}},

C[ -F[12, {e1x2}] , F[7, {e2x2}] , -V[3] ] == {{I*gc254*IndexDelta[e1x2, e2x2], 0}, {0, 0}},

C[ -F[10, {e1x2}] , F[8, {e2x2}] , -V[3] ] == {{I*gc255*IndexDelta[e1x2, e2x2], 0}, {0, 0}},

C[ -F[10, {e1x2}] , F[9, {e2x2}] , -V[3] ] == {{I*gc256*IndexDelta[e1x2, e2x2], 0}, {0, 0}},

C[ -F[10, {e1x2}] , F[7, {e2x2}] , -V[3] ] == {{I*gc257*IndexDelta[e1x2, e2x2], 0}, {0, 0}},

C[ -F[11, {e1x2}] , F[8, {e2x2}] , -V[3] ] == {{I*gc258*IndexDelta[e1x2, e2x2], 0}, {0, 0}},

C[ -F[11, {e1x2}] , F[9, {e2x2}] , -V[3] ] == {{I*gc259*IndexDelta[e1x2, e2x2], 0}, {0, 0}},

C[ -F[11, {e1x2}] , F[7, {e2x2}] , -V[3] ] == {{I*gc260*IndexDelta[e1x2, e2x2], 0}, {0, 0}},

C[ -F[12, {e1x2}] , F[12, {e2x2}] , V[2] ] == {{I*gc261L*IndexDelta[e1x2, e2x2], 0}, {I*gc261R*IndexDelta[e1x2, e2x2], 0}},

C[ -F[10, {e1x2}] , F[10, {e2x2}] , V[2] ] == {{I*gc262L*IndexDelta[e1x2, e2x2], 0}, {I*gc262R*IndexDelta[e1x2, e2x2], 0}},

C[ -F[11, {e1x2}] , F[11, {e2x2}] , V[2] ] == {{I*gc263L*IndexDelta[e1x2, e2x2], 0}, {I*gc263R*IndexDelta[e1x2, e2x2], 0}},

C[ -F[4] , F[4] , V[2] ] == {{I*gc264L, 0}, {I*gc264R, 0}},

C[ -F[5] , F[5] , V[2] ] == {{I*gc265L, 0}, {I*gc265R, 0}},

C[ -F[6] , F[6] , V[2] ] == {{I*gc266L, 0}, {I*gc266R, 0}},

C[ -F[8, {e1x2}] , F[8, {e2x2}] , V[2] ] == {{I*gc267L*IndexDelta[e1x2, e2x2], 0}, {I*gc267R*IndexDelta[e1x2, e2x2], 0}},

C[ -F[9, {e1x2}] , F[9, {e2x2}] , V[2] ] == {{I*gc268L*IndexDelta[e1x2, e2x2], 0}, {I*gc268R*IndexDelta[e1x2, e2x2], 0}},

C[ -F[7, {e1x2}] , F[7, {e2x2}] , V[2] ] == {{I*gc269L*IndexDelta[e1x2, e2x2], 0}, {I*gc269R*IndexDelta[e1x2, e2x2], 0}},

C[ -F[1] , F[1] , V[2] ] == {{I*gc270, 0}, {0, 0}},

C[ -F[2] , F[2] , V[2] ] == {{I*gc271, 0}, {0, 0}},

C[ -F[3] , F[3] , V[2] ] == {{I*gc272, 0}, {0, 0}}

}

(* * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * *)

(* Parameter replacement lists (These lists were created by FeynRules) *)

(* FA Couplings *)

M$FACouplings = {
     gc54 -> -FCGV["EL"],
     gc55 -> -FCGV["EL"],
     gc56 -> FCGV["EL"],
     gc57 -> -FCGV["EL"],
     gc59 -> FCGV["EL"],
     gc62 -> -FCGV["EL"],
     gc63 -> -((FCGV["CW"]*FCGV["EL"])/FCGV["SW"]),
     gc65 -> (FCGV["CW"]*FCGV["EL"])/FCGV["SW"],
     gc67 -> -FCGV["EL"],
     gc70 -> FCGV["EL"],
     gc71 -> (FCGV["CW"]*FCGV["EL"])/FCGV["SW"],
     gc73 -> -((FCGV["CW"]*FCGV["EL"])/FCGV["SW"]),
     gc75 -> (FCGV["CW"]*FCGV["EL"])/FCGV["SW"],
     gc77 -> -((FCGV["CW"]*FCGV["EL"])/FCGV["SW"]),
     gc79 -> FAGS,
     gc80 -> -FAGS,
     gc81 -> -FAGS^2,
     gc82L -> -(FCGV["MB"]/v),
     gc82R -> FCGV["MB"]/v,
     gc83 -> -((FCGV["MB"]*Cos[aDM])/v),
     gc84L -> -(FCGV["MD"]/v),
     gc84R -> FCGV["MD"]/v,
     gc85 -> -((FCGV["MD"]*Cos[aDM])/v),
     gc86L -> -(FCGV["MS"]/v),
     gc86R -> FCGV["MS"]/v,
     gc87 -> -((FCGV["MS"]*Cos[aDM])/v),
     gc88L -> -((Sqrt[2]*FCGV["MS"]*Conjugate[CKM2x3])/v),
     gc88R -> (Sqrt[2]*FCGV["MT"]*Conjugate[CKM2x3])/v,
     gc89L -> -((Sqrt[2]*FCGV["MB"]*Conjugate[CKM3x3])/v),
     gc89R -> (Sqrt[2]*FCGV["MT"]*Conjugate[CKM3x3])/v,
     gc90L -> -((Sqrt[2]*FCGV["MD"]*Conjugate[CKM1x3])/v),
     gc90R -> (Sqrt[2]*FCGV["MT"]*Conjugate[CKM1x3])/v,
     gc91L -> -((Sqrt[2]*FCGV["MS"]*Conjugate[CKM2x1])/v),
     gc91R -> (Sqrt[2]*FCGV["MU"]*Conjugate[CKM2x1])/v,
     gc92L -> -((Sqrt[2]*FCGV["MB"]*Conjugate[CKM3x1])/v),
     gc92R -> (Sqrt[2]*FCGV["MU"]*Conjugate[CKM3x1])/v,
     gc93L -> -((Sqrt[2]*FCGV["MD"]*Conjugate[CKM1x1])/v),
     gc93R -> (Sqrt[2]*FCGV["MU"]*Conjugate[CKM1x1])/v,
     gc94L -> -((Sqrt[2]*FCGV["MS"]*Conjugate[CKM2x2])/v),
     gc94R -> (Sqrt[2]*FCGV["MC"]*Conjugate[CKM2x2])/v,
     gc95L -> -((Sqrt[2]*FCGV["MB"]*Conjugate[CKM3x2])/v),
     gc95R -> (Sqrt[2]*FCGV["MC"]*Conjugate[CKM3x2])/v,
     gc96L -> -((Sqrt[2]*FCGV["MD"]*Conjugate[CKM1x2])/v),
     gc96R -> (Sqrt[2]*FCGV["MC"]*Conjugate[CKM1x2])/v,
     gc97L -> -(Me/v),
     gc97R -> Me/v,
     gc98 -> -((Me*Cos[aDM])/v),
     gc99L -> -(FCGV["MM"]/v),
     gc99R -> FCGV["MM"]/v,
     gc100 -> -((FCGV["MM"]*Cos[aDM])/v),
     gc101L -> -(MTA/v),
     gc101R -> MTA/v,
     gc102 -> -((MTA*Cos[aDM])/v),
     gc103 -> -((Sqrt[2]*Me)/v),
     gc104 -> -((Sqrt[2]*FCGV["MM"])/v),
     gc105 -> -((Sqrt[2]*MTA)/v),
     gc106L -> (Sqrt[2]*CKM2x3*FCGV["MT"])/v,
     gc106R -> -((Sqrt[2]*CKM2x3*FCGV["MS"])/v),
     gc107L -> (Sqrt[2]*CKM2x1*FCGV["MU"])/v,
     gc107R -> -((Sqrt[2]*CKM2x1*FCGV["MS"])/v),
     gc108L -> (Sqrt[2]*CKM2x2*FCGV["MC"])/v,
     gc108R -> -((Sqrt[2]*CKM2x2*FCGV["MS"])/v),
     gc109L -> (Sqrt[2]*CKM3x3*FCGV["MT"])/v,
     gc109R -> -((Sqrt[2]*CKM3x3*FCGV["MB"])/v),
     gc110L -> (Sqrt[2]*CKM3x1*FCGV["MU"])/v,
     gc110R -> -((Sqrt[2]*CKM3x1*FCGV["MB"])/v),
     gc111L -> (Sqrt[2]*CKM3x2*FCGV["MC"])/v,
     gc111R -> -((Sqrt[2]*CKM3x2*FCGV["MB"])/v),
     gc112L -> (Sqrt[2]*CKM1x3*FCGV["MT"])/v,
     gc112R -> -((Sqrt[2]*CKM1x3*FCGV["MD"])/v),
     gc113L -> (Sqrt[2]*CKM1x1*FCGV["MU"])/v,
     gc113R -> -((Sqrt[2]*CKM1x1*FCGV["MD"])/v),
     gc114L -> (Sqrt[2]*CKM1x2*FCGV["MC"])/v,
     gc114R -> -((Sqrt[2]*CKM1x2*FCGV["MD"])/v),
     gc115L -> FCGV["MC"]/v,
     gc115R -> -(FCGV["MC"]/v),
     gc116 -> -((FCGV["MC"]*Cos[aDM])/v),
     gc117L -> FCGV["MT"]/v,
     gc117R -> -(FCGV["MT"]/v),
     gc118 -> -((FCGV["MT"]*Cos[aDM])/v),
     gc119L -> FCGV["MU"]/v,
     gc119R -> -(FCGV["MU"]/v),
     gc120 -> -((FCGV["MU"]*Cos[aDM])/v),
     gc121R -> -((Sqrt[2]*Me)/v),
     gc122R -> -((Sqrt[2]*FCGV["MM"])/v),
     gc123R -> -((Sqrt[2]*MTA)/v),
     gc146 -> (FCGV["MB"]*Sin[aDM])/v,
     gc147 -> (FCGV["MD"]*Sin[aDM])/v,
     gc148 -> (FCGV["MS"]*Sin[aDM])/v,
     gc149 -> (Me*Sin[aDM])/v,
     gc150 -> (FCGV["MM"]*Sin[aDM])/v,
     gc151 -> (MTA*Sin[aDM])/v,
     gc152 -> (FCGV["MC"]*Sin[aDM])/v,
     gc153 -> (FCGV["MT"]*Sin[aDM])/v,
     gc154 -> (FCGV["MU"]*Sin[aDM])/v,
     gc155 -> FAGS,
     gc156 -> FAGS,
     gc157 -> FAGS,
     gc158 -> FAGS,
     gc159 -> FAGS,
     gc160 -> FAGS,
     gc166 -> FCGV["EL"]/(2*FCGV["SW"]),
     gc167 -> FCGV["EL"]/(2*FCGV["SW"]),
     gc168 -> (FCGV["EL"]*Cos[aDM])/(2*FCGV["SW"]),
     gc169 -> FCGV["EL"]/(2*FCGV["SW"]),
     gc170 -> FCGV["EL"],
     gc172 -> -1/2*(FCGV["EL"]*Sin[aDM])/FCGV["SW"],
     gc178 -> FCGV["EL"]/(2*FCGV["SW"]),
     gc179 -> FCGV["EL"]/(2*FCGV["SW"]),
     gc180 -> -1/2*(FCGV["EL"]*Cos[aDM])/FCGV["SW"],
     gc181 -> -1/2*FCGV["EL"]/FCGV["SW"],
     gc183 -> (FCGV["EL"]*Sin[aDM])/(2*FCGV["SW"]),
     gc189 -> -FCGV["EL"]^2,
     gc195 -> (FCGV["CW"]*FCGV["EL"])/FCGV["SW"],
     gc196 -> FCGV["EL"]^2/FCGV["SW"]^2,
     gc199 -> (FCGV["EL"]*(FCGV["CW"]^2 + FCGV["SW"]^2))/(2*FCGV["CW"]*FCGV["SW"]),
     gc200 -> -1/2*(FCGV["EL"]*(FCGV["CW"]^2 + FCGV["SW"]^2)*Cos[aDM])/(FCGV["CW"]*FCGV["SW"]),
     gc201 -> -1/2*(FCGV["CW"]*FCGV["EL"])/FCGV["SW"] + (FCGV["EL"]*FCGV["SW"])/(2*FCGV["CW"]),
     gc202 -> -1/2*(FCGV["CW"]*FCGV["EL"])/FCGV["SW"] + (FCGV["EL"]*FCGV["SW"])/(2*FCGV["CW"]),
     gc203 -> (FCGV["EL"]*(FCGV["CW"]^2 + FCGV["SW"]^2)*Sin[aDM])/(2*FCGV["CW"]*FCGV["SW"]),
     gc216 -> (FCGV["CW"]*FCGV["EL"]^2)/FCGV["SW"],
     gc227 -> -((FCGV["CW"]^2*FCGV["EL"]^2)/FCGV["SW"]^2),
     gc228 -> -1/3*FCGV["EL"],
     gc229 -> -1/3*FCGV["EL"],
     gc230 -> -1/3*FCGV["EL"],
     gc231 -> -FCGV["EL"],
     gc232 -> -FCGV["EL"],
     gc233 -> -FCGV["EL"],
     gc234 -> (2*FCGV["EL"])/3,
     gc235 -> (2*FCGV["EL"])/3,
     gc236 -> (2*FCGV["EL"])/3,
     gc237 -> FCGV["EL"]/(Sqrt[2]*FCGV["SW"]),
     gc238 -> FCGV["EL"]/(Sqrt[2]*FCGV["SW"]),
     gc239 -> FCGV["EL"]/(Sqrt[2]*FCGV["SW"]),
     gc240 -> (CKM2x3*FCGV["EL"])/(Sqrt[2]*FCGV["SW"]),
     gc241 -> (CKM2x1*FCGV["EL"])/(Sqrt[2]*FCGV["SW"]),
     gc242 -> (CKM2x2*FCGV["EL"])/(Sqrt[2]*FCGV["SW"]),
     gc243 -> (CKM3x3*FCGV["EL"])/(Sqrt[2]*FCGV["SW"]),
     gc244 -> (CKM3x1*FCGV["EL"])/(Sqrt[2]*FCGV["SW"]),
     gc245 -> (CKM3x2*FCGV["EL"])/(Sqrt[2]*FCGV["SW"]),
     gc246 -> (CKM1x3*FCGV["EL"])/(Sqrt[2]*FCGV["SW"]),
     gc247 -> (CKM1x1*FCGV["EL"])/(Sqrt[2]*FCGV["SW"]),
     gc248 -> (CKM1x2*FCGV["EL"])/(Sqrt[2]*FCGV["SW"]),
     gc249 -> FCGV["EL"]/(Sqrt[2]*FCGV["SW"]),
     gc250 -> FCGV["EL"]/(Sqrt[2]*FCGV["SW"]),
     gc251 -> FCGV["EL"]/(Sqrt[2]*FCGV["SW"]),
     gc252 -> (FCGV["EL"]*Conjugate[CKM2x3])/(Sqrt[2]*FCGV["SW"]),
     gc253 -> (FCGV["EL"]*Conjugate[CKM3x3])/(Sqrt[2]*FCGV["SW"]),
     gc254 -> (FCGV["EL"]*Conjugate[CKM1x3])/(Sqrt[2]*FCGV["SW"]),
     gc255 -> (FCGV["EL"]*Conjugate[CKM2x1])/(Sqrt[2]*FCGV["SW"]),
     gc256 -> (FCGV["EL"]*Conjugate[CKM3x1])/(Sqrt[2]*FCGV["SW"]),
     gc257 -> (FCGV["EL"]*Conjugate[CKM1x1])/(Sqrt[2]*FCGV["SW"]),
     gc258 -> (FCGV["EL"]*Conjugate[CKM2x2])/(Sqrt[2]*FCGV["SW"]),
     gc259 -> (FCGV["EL"]*Conjugate[CKM3x2])/(Sqrt[2]*FCGV["SW"]),
     gc260 -> (FCGV["EL"]*Conjugate[CKM1x2])/(Sqrt[2]*FCGV["SW"]),
     gc261L -> -1/6*(FCGV["EL"]*(3*FCGV["CW"]^2 + FCGV["SW"]^2))/(FCGV["CW"]*FCGV["SW"]),
     gc261R -> (FCGV["EL"]*FCGV["SW"])/(3*FCGV["CW"]),
     gc262L -> -1/6*(FCGV["EL"]*(3*FCGV["CW"]^2 + FCGV["SW"]^2))/(FCGV["CW"]*FCGV["SW"]),
     gc262R -> (FCGV["EL"]*FCGV["SW"])/(3*FCGV["CW"]),
     gc263L -> -1/6*(FCGV["EL"]*(3*FCGV["CW"]^2 + FCGV["SW"]^2))/(FCGV["CW"]*FCGV["SW"]),
     gc263R -> (FCGV["EL"]*FCGV["SW"])/(3*FCGV["CW"]),
     gc264L -> -1/2*(FCGV["EL"]*(FCGV["CW"]^2 - FCGV["SW"]^2))/(FCGV["CW"]*FCGV["SW"]),
     gc264R -> (FCGV["EL"]*FCGV["SW"])/FCGV["CW"],
     gc265L -> -1/2*(FCGV["EL"]*(FCGV["CW"]^2 - FCGV["SW"]^2))/(FCGV["CW"]*FCGV["SW"]),
     gc265R -> (FCGV["EL"]*FCGV["SW"])/FCGV["CW"],
     gc266L -> -1/2*(FCGV["EL"]*(FCGV["CW"]^2 - FCGV["SW"]^2))/(FCGV["CW"]*FCGV["SW"]),
     gc266R -> (FCGV["EL"]*FCGV["SW"])/FCGV["CW"],
     gc267L -> (FCGV["CW"]*FCGV["EL"])/(2*FCGV["SW"]) - (FCGV["EL"]*FCGV["SW"])/(6*FCGV["CW"]),
     gc267R -> (-2*FCGV["EL"]*FCGV["SW"])/(3*FCGV["CW"]),
     gc268L -> (FCGV["CW"]*FCGV["EL"])/(2*FCGV["SW"]) - (FCGV["EL"]*FCGV["SW"])/(6*FCGV["CW"]),
     gc268R -> (-2*FCGV["EL"]*FCGV["SW"])/(3*FCGV["CW"]),
     gc269L -> (FCGV["CW"]*FCGV["EL"])/(2*FCGV["SW"]) - (FCGV["EL"]*FCGV["SW"])/(6*FCGV["CW"]),
     gc269R -> (-2*FCGV["EL"]*FCGV["SW"])/(3*FCGV["CW"]),
     gc270 -> (FCGV["EL"]*(FCGV["CW"]^2 + FCGV["SW"]^2))/(2*FCGV["CW"]*FCGV["SW"]),
     gc271 -> (FCGV["EL"]*(FCGV["CW"]^2 + FCGV["SW"]^2))/(2*FCGV["CW"]*FCGV["SW"]),
     gc272 -> (FCGV["EL"]*(FCGV["CW"]^2 + FCGV["SW"]^2))/(2*FCGV["CW"]*FCGV["SW"])};

