(* Patched for use with FeynCalc *)
(* * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * *)
(*                                                                             *)
(*         This file has been automatically generated by FeynRules.            *)
(*                                                                             *)
(* * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * *)


FR$ModelInformation={
  ModelName->"Dark Doublet Phase (N2HDM)",
  Authors -> {"Andreas Goudelis, Bjoern Herrmann, Oscal Stal"},
  Version -> "1.0",
  Date -> "04. 10. 2013",
  Institutions -> {"LAPTh-Annecy, Oscar Klein Center-Stockholm"},
  Emails -> {"andreas.goudelis@lapth.cnrs.fr"}};

FR$ClassesTranslation={ve -> F[1], vm -> F[2], vt -> F[3], e -> F[4], m -> F[5], ta -> F[6], u -> F[7], c -> F[8], t -> F[9], d -> F[10], s -> F[11], b -> F[12], A -> V[1], Z -> V[2], W -> V[3], G -> V[4], ghA -> U[1], ghZ -> U[2], ghWp -> U[3], ghWm -> U[4], ghG -> U[5], H1 -> S[1], H2 -> S[2], H3 -> S[3], G0 -> S[4], Gch -> S[5], A0 -> S[6], Hch -> S[7]};

FR$InteractionOrderPerturbativeExpansion={{HIG, 0}, {QCD, 0}, {QED, 0}};

FR$GoldstoneList={S[4], S[5]};

(*     Declared indices    *)

IndexRange[ Index[Generation] ] = Range[ 3 ]

IndexRange[ Index[Colour] ] = NoUnfold[ Range[ 3 ] ]

IndexRange[ Index[Gluon] ] = NoUnfold[ Range[ 8 ] ]

IndexRange[ Index[SU2W] ] = Range[ 3 ]

(*     Declared particles    *)

M$ClassesDescription = {
F[1] == {
    SelfConjugate -> False,
    PropagatorType -> Straight,
    PropagatorArrow -> Forward,
    Mass -> Mnue,
    Indices -> {},
    PropagatorLabel -> "ve" },

F[2] == {
    SelfConjugate -> False,
    PropagatorType -> Straight,
    PropagatorArrow -> Forward,
    Mass -> Mnum,
    Indices -> {},
    PropagatorLabel -> "vm" },

F[3] == {
    SelfConjugate -> False,
    PropagatorType -> Straight,
    PropagatorArrow -> Forward,
    Mass -> Mnut,
    Indices -> {},
    PropagatorLabel -> "vt" },

F[4] == {
    SelfConjugate -> False,
    QuantumNumbers -> {-Q},
    PropagatorType -> Straight,
    PropagatorArrow -> Forward,
    Mass -> Me,
    Indices -> {},
    PropagatorLabel -> "e" },

F[5] == {
    SelfConjugate -> False,
    QuantumNumbers -> {-Q},
    PropagatorType -> Straight,
    PropagatorArrow -> Forward,
    Mass -> FCGV["MM"],
    Indices -> {},
    PropagatorLabel -> "m" },

F[6] == {
    SelfConjugate -> False,
    QuantumNumbers -> {-Q},
    PropagatorType -> Straight,
    PropagatorArrow -> Forward,
    Mass -> MTA,
    Indices -> {},
    PropagatorLabel -> "ta" },

F[7] == {
    SelfConjugate -> False,
    QuantumNumbers -> {(2*Q)/3},
    PropagatorType -> Straight,
    PropagatorArrow -> Forward,
    Mass -> FCGV["MU"],
    Indices -> {Index[Colour]},
    PropagatorLabel -> "u" },

F[8] == {
    SelfConjugate -> False,
    QuantumNumbers -> {(2*Q)/3},
    PropagatorType -> Straight,
    PropagatorArrow -> Forward,
    Mass -> FCGV["MC"],
    Indices -> {Index[Colour]},
    PropagatorLabel -> "c" },

F[9] == {
    SelfConjugate -> False,
    QuantumNumbers -> {(2*Q)/3},
    PropagatorType -> Straight,
    PropagatorArrow -> Forward,
    Mass -> FCGV["MT"],
    Indices -> {Index[Colour]},
    PropagatorLabel -> "t" },

F[10] == {
    SelfConjugate -> False,
    QuantumNumbers -> {-1/3*Q},
    PropagatorType -> Straight,
    PropagatorArrow -> Forward,
    Mass -> FCGV["MD"],
    Indices -> {Index[Colour]},
    PropagatorLabel -> "d" },

F[11] == {
    SelfConjugate -> False,
    QuantumNumbers -> {-1/3*Q},
    PropagatorType -> Straight,
    PropagatorArrow -> Forward,
    Mass -> FCGV["MS"],
    Indices -> {Index[Colour]},
    PropagatorLabel -> "s" },

F[12] == {
    SelfConjugate -> False,
    QuantumNumbers -> {-1/3*Q},
    PropagatorType -> Straight,
    PropagatorArrow -> Forward,
    Mass -> FCGV["MB"],
    Indices -> {Index[Colour]},
    PropagatorLabel -> "b" },

V[1] == {
    SelfConjugate -> True,
    PropagatorType -> Sine,
    PropagatorArrow -> None,
    Mass -> 0,
    Indices -> {},
    PropagatorLabel -> "A" },

V[2] == {
    SelfConjugate -> True,
    PropagatorType -> Sine,
    PropagatorArrow -> None,
    Mass -> FCGV["MZ"],
    Indices -> {},
    PropagatorLabel -> "Z" },

V[3] == {
    SelfConjugate -> False,
    QuantumNumbers -> {Q},
    PropagatorType -> Sine,
    PropagatorArrow -> Forward,
    Mass -> FCGV["MW"],
    Indices -> {},
    PropagatorLabel -> "W" },

V[4] == {
    SelfConjugate -> True,
    PropagatorType -> Cycles,
    PropagatorArrow -> None,
    Mass -> 0,
    Indices -> {Index[Gluon]},
    PropagatorLabel -> "G" },

U[1] == {
    SelfConjugate -> False,
    QuantumNumbers -> {GhostNumber},
    PropagatorType -> GhostDash,
    PropagatorArrow -> Forward,
    Mass -> 0,
    Indices -> {},
    PropagatorLabel -> "ghA" },

U[2] == {
    SelfConjugate -> False,
    QuantumNumbers -> {GhostNumber},
    PropagatorType -> GhostDash,
    PropagatorArrow -> Forward,
    Mass -> FCGV["MZ"],
    Indices -> {},
    PropagatorLabel -> "ghZ" },

U[3] == {
    SelfConjugate -> False,
    QuantumNumbers -> {Q, GhostNumber},
    PropagatorType -> GhostDash,
    PropagatorArrow -> Forward,
    Mass -> FCGV["MW"],
    Indices -> {},
    PropagatorLabel -> "ghWp" },

U[4] == {
    SelfConjugate -> False,
    QuantumNumbers -> {-Q, GhostNumber},
    PropagatorType -> GhostDash,
    PropagatorArrow -> Forward,
    Mass -> FCGV["MW"],
    Indices -> {},
    PropagatorLabel -> "ghWm" },

U[5] == {
    SelfConjugate -> False,
    QuantumNumbers -> {GhostNumber},
    PropagatorType -> GhostDash,
    PropagatorArrow -> Forward,
    Mass -> 0,
    Indices -> {Index[Gluon]},
    PropagatorLabel -> "ghG" },

S[1] == {
    SelfConjugate -> True,
    PropagatorType -> ScalarDash,
    PropagatorArrow -> None,
    Mass -> MH1,
    Indices -> {},
    PropagatorLabel -> "H1" },

S[2] == {
    SelfConjugate -> True,
    PropagatorType -> ScalarDash,
    PropagatorArrow -> None,
    Mass -> MH2,
    Indices -> {},
    PropagatorLabel -> "H2" },

S[3] == {
    SelfConjugate -> True,
    PropagatorType -> ScalarDash,
    PropagatorArrow -> None,
    Mass -> MH3,
    Indices -> {},
    PropagatorLabel -> "H3" },

S[4] == {
    SelfConjugate -> True,
    PropagatorType -> ScalarDash,
    PropagatorArrow -> None,
    Mass -> FCGV["MZ"],
    Indices -> {},
    PropagatorLabel -> "G0" },

S[5] == {
    SelfConjugate -> False,
    PropagatorType -> ScalarDash,
    PropagatorArrow -> None,
    QuantumNumbers -> {Q},
    Mass -> FCGV["MW"],
    Indices -> {},
    PropagatorLabel -> "Gch" },

S[6] == {
    SelfConjugate -> True,
    PropagatorType -> ScalarDash,
    PropagatorArrow -> None,
    Mass -> MA0,
    Indices -> {},
    PropagatorLabel -> "A0" },

S[7] == {
    SelfConjugate -> False,
    QuantumNumbers -> {Q},
    PropagatorType -> ScalarDash,
    PropagatorArrow -> Forward,
    Mass -> MHch,
    Indices -> {},
    PropagatorLabel -> "Hch" }
}


(*        Definitions       *)


Mnue[ ___ ] := Mnue;
Mnum[ ___ ] := Mnum;
Mnut[ ___ ] := Mnut;
Me[ ___ ] := Me;
FCGV["MM"][ ___ ] := FCGV["MM"];
MTA[ ___ ] := MTA;
FCGV["MU"][ ___ ] := FCGV["MU"];
FCGV["MC"][ ___ ] := FCGV["MC"];
FCGV["MT"][ ___ ] := FCGV["MT"];
FCGV["MD"][ ___ ] := FCGV["MD"];
FCGV["MS"][ ___ ] := FCGV["MS"];
FCGV["MB"][ ___ ] := FCGV["MB"];
FCGV["MZ"][ ___ ] := FCGV["MZ"];
FCGV["MW"][ ___ ] := FCGV["MW"];
MH1[ ___ ] := MH1;
MH2[ ___ ] := MH2;
MH3[ ___ ] := MH3;
MA0[ ___ ] := MA0;
MHch[ ___ ] := MHch;


TheLabel[ F[7, {__}] ] := TheLabel[F[7]];
TheLabel[ F[8, {__}] ] := TheLabel[F[8]];
TheLabel[ F[9, {__}] ] := TheLabel[F[9]];
TheLabel[ F[10, {__}] ] := TheLabel[F[10]];
TheLabel[ F[11, {__}] ] := TheLabel[F[11]];
TheLabel[ F[12, {__}] ] := TheLabel[F[12]];
TheLabel[ V[4, {__}] ] := TheLabel[V[4]];
TheLabel[ U[5, {__}] ] := TheLabel[U[5]];


(*      Couplings (calculated by FeynRules)      *)

M$CouplingMatrices = {

C[ S[6] , S[6] , S[6] , S[6] ] == {{(-3*I)*lam2, 0}},

C[ S[6] , S[6] , S[3] , S[3] ] == {{(-I)*lam2, 0}},

C[ S[3] , S[3] , S[3] , S[3] ] == {{(-3*I)*lam2, 0}},

C[ S[6] , S[6] , S[7] , -S[7] ] == {{(-I)*lam2, 0}},

C[ S[3] , S[3] , S[7] , -S[7] ] == {{(-I)*lam2, 0}},

C[ S[7] , S[7] , -S[7] , -S[7] ] == {{(-2*I)*lam2, 0}},

C[ S[6] , S[6] , S[4] , S[4] ] == {{(I*(2*m22^2 - 2*MH3^2 + lam8*vs^2))/v^2, 0}},

C[ S[6] , S[6] , S[5] , -S[5] ] == {{(I*(2*m22^2 - 2*MHch^2 + lam8*vs^2))/v^2, 0}},

C[ S[4] , S[4] , S[3] , S[3] ] == {{(I*(2*m22^2 - 2*MA0^2 + lam8*vs^2))/v^2, 0}},

C[ S[5] , -S[5] , S[3] , S[3] ] == {{(I*(2*m22^2 - 2*MHch^2 + lam8*vs^2))/v^2, 0}},

C[ S[4] , S[4] , S[7] , -S[7] ] == {{(I*(2*m22^2 - 2*MHch^2 + lam8*vs^2))/v^2, 0}},

C[ S[5] , -S[5] , S[7] , -S[7] ] == {{(I*(2*m22^2 - MA0^2 - MH3^2 + lam8*vs^2))/v^2, 0}},

C[ S[4] , -S[5] , S[3] , S[7] ] == {{(-MA0^2 + MHch^2)/v^2, 0}},

C[ -S[5] , -S[5] , S[7] , S[7] ] == {{((2*I)*(MA0 - MH3)*(MA0 + MH3))/v^2, 0}},

C[ S[4] , S[5] , S[3] , -S[7] ] == {{((MA0 - MHch)*(MA0 + MHch))/v^2, 0}},

C[ S[5] , S[5] , -S[7] , -S[7] ] == {{((2*I)*(MA0 - MH3)*(MA0 + MH3))/v^2, 0}},

C[ S[6] , S[4] , -S[5] , S[7] ] == {{((-I)*(MH3 - MHch)*(MH3 + MHch))/v^2, 0}},

C[ S[6] , S[4] , S[5] , -S[7] ] == {{((-I)*(MH3 - MHch)*(MH3 + MHch))/v^2, 0}},

C[ S[6] , S[4] , S[3] ] == {{((-I)*(MA0 - MH3)*(MA0 + MH3))/v, 0}},

C[ S[6] , -S[5] , S[7] ] == {{(-MA0^2 + MHch^2)/v, 0}},

C[ S[6] , S[5] , -S[7] ] == {{((MA0 - MHch)*(MA0 + MHch))/v, 0}},

C[ -S[5] , S[3] , S[7] ] == {{(I*(MH3 - MHch)*(MH3 + MHch))/v, 0}},

C[ S[5] , S[3] , -S[7] ] == {{(I*(MH3 - MHch)*(MH3 + MHch))/v, 0}},

C[ S[5] , -S[5] , V[1] , V[1] ] == {{(2*I)*FCGV["EL"]^2, 0}},

C[ S[7] , -S[7] , V[1] , V[1] ] == {{(2*I)*FCGV["EL"]^2, 0}},

C[ S[6] , S[4] , S[1] , S[3] ] == {{((-I)*(MA0 - MH3)*(MA0 + MH3)*Cos[aDM])/v^2, 0}},

C[ S[6] , -S[5] , S[1] , S[7] ] == {{-(((MA0 - MHch)*(MA0 + MHch)*Cos[aDM])/v^2), 0}},

C[ S[6] , S[5] , S[1] , -S[7] ] == {{((MA0 - MHch)*(MA0 + MHch)*Cos[aDM])/v^2, 0}},

C[ -S[5] , S[1] , S[3] , S[7] ] == {{(I*(MH3 - MHch)*(MH3 + MHch)*Cos[aDM])/v^2, 0}},

C[ S[5] , S[1] , S[3] , -S[7] ] == {{(I*(MH3 - MHch)*(MH3 + MHch)*Cos[aDM])/v^2, 0}},

C[ S[6] , S[6] , S[1] ] == {{(I*((2*m22^2 - 2*MA0^2 + lam8*vs^2)*Cos[aDM] - lam8*v*vs*Sin[aDM]))/v, 0}},

C[ S[1] , S[3] , S[3] ] == {{(I*((2*m22^2 - 2*MH3^2 + lam8*vs^2)*Cos[aDM] - lam8*v*vs*Sin[aDM]))/v, 0}},

C[ S[1] , S[7] , -S[7] ] == {{(I*((2*m22^2 - 2*MHch^2 + lam8*vs^2)*Cos[aDM] - lam8*v*vs*Sin[aDM]))/v, 0}},

C[ S[6] , S[6] , S[2] ] == {{((-I)*(lam8*v*vs*Cos[aDM] + (2*m22^2 - 2*MA0^2 + lam8*vs^2)*Sin[aDM]))/v, 0}},

C[ S[2] , S[3] , S[3] ] == {{((-I)*(lam8*v*vs*Cos[aDM] + (2*m22^2 - 2*MH3^2 + lam8*vs^2)*Sin[aDM]))/v, 0}},

C[ S[2] , S[7] , -S[7] ] == {{((-I)*(lam8*v*vs*Cos[aDM] + (2*m22^2 - 2*MHch^2 + lam8*vs^2)*Sin[aDM]))/v, 0}},

C[ S[6] , S[6] , S[2] , S[2] ] == {{(-I)*lam8*Cos[aDM]^2 + (I*(2*m22^2 - 2*MA0^2 + lam8*vs^2)*Sin[aDM]^2)/v^2, 0}},

C[ S[2] , S[2] , S[3] , S[3] ] == {{(-I)*lam8*Cos[aDM]^2 + (I*(2*m22^2 - 2*MH3^2 + lam8*vs^2)*Sin[aDM]^2)/v^2, 0}},

C[ S[2] , S[2] , S[7] , -S[7] ] == {{(-I)*lam8*Cos[aDM]^2 + (I*(2*m22^2 - 2*MHch^2 + lam8*vs^2)*Sin[aDM]^2)/v^2, 0}},

C[ S[6] , S[6] , S[1] , S[1] ] == {{I*(((2*m22^2 - 2*MA0^2 + lam8*vs^2)*Cos[aDM]^2)/v^2 - lam8*Sin[aDM]^2), 0}},

C[ S[1] , S[1] , S[3] , S[3] ] == {{I*(((2*m22^2 - 2*MH3^2 + lam8*vs^2)*Cos[aDM]^2)/v^2 - lam8*Sin[aDM]^2), 0}},

C[ S[1] , S[1] , S[7] , -S[7] ] == {{I*(((2*m22^2 - 2*MHch^2 + lam8*vs^2)*Cos[aDM]^2)/v^2 - lam8*Sin[aDM]^2), 0}},

C[ S[4] , S[4] , S[4] , S[4] ] == {{((-3*I)*(MH1^2*Cos[aDM]^2 + MH2^2*Sin[aDM]^2))/v^2, 0}},

C[ S[4] , S[4] , S[5] , -S[5] ] == {{((-I)*(MH1^2*Cos[aDM]^2 + MH2^2*Sin[aDM]^2))/v^2, 0}},

C[ S[5] , S[5] , -S[5] , -S[5] ] == {{((-2*I)*(MH1^2*Cos[aDM]^2 + MH2^2*Sin[aDM]^2))/v^2, 0}},

C[ S[4] , S[4] , S[1] ] == {{((-I)*MH1^2*Cos[aDM])/v, 0}},

C[ S[5] , -S[5] , S[1] ] == {{((-I)*MH1^2*Cos[aDM])/v, 0}},

C[ S[4] , S[4] , S[1] , S[1] ] == {{((-I)*Cos[aDM]*(MH1^2*vs*Cos[aDM]^3 + MH2^2*vs*Cos[aDM]*Sin[aDM]^2 + (MH1^2 - MH2^2)*v*Sin[aDM]^3))/(v^2*vs), 0}},

C[ S[5] , -S[5] , S[1] , S[1] ] == {{((-I)*Cos[aDM]*(MH1^2*vs*Cos[aDM]^3 + MH2^2*vs*Cos[aDM]*Sin[aDM]^2 + (MH1^2 - MH2^2)*v*Sin[aDM]^3))/(v^2*vs), 0}},

C[ S[1] , S[1] , S[1] ] == {{((-3*I)*MH1^2*(vs*Cos[aDM]^3 + v*Sin[aDM]^3))/(v*vs), 0}},

C[ S[2] , S[2] , S[2] ] == {{((-3*I)*MH2^2*(v*Cos[aDM]^3 - vs*Sin[aDM]^3))/(v*vs), 0}},

C[ S[1] , S[1] , S[1] , S[1] ] == {{((-3*I)*(MH1^2*vs^2*Cos[aDM]^6 + MH2^2*vs^2*Cos[aDM]^4*Sin[aDM]^2 + 2*MH1^2*v*vs*Cos[aDM]^3*Sin[aDM]^3 - 2*MH2^2*v*vs*Cos[aDM]^3*Sin[aDM]^3 + MH2^2*v^2*Cos[aDM]^2*Sin[aDM]^4 + MH1^2*v^2*Sin[aDM]^6))/(v^2*vs^2), 0}},

C[ S[2] , S[2] , S[2] , S[2] ] == {{((-3*I)*(MH2^2*v^2*Cos[aDM]^6 + MH1^2*v^2*Cos[aDM]^4*Sin[aDM]^2 + 2*(MH1^2 - MH2^2)*v*vs*Cos[aDM]^3*Sin[aDM]^3 + MH1^2*vs^2*Cos[aDM]^2*Sin[aDM]^4 + MH2^2*vs^2*Sin[aDM]^6))/(v^2*vs^2), 0}},

C[ S[5] , -S[5] , V[1] ] == {{(-I)*gc54, 0}, {I*gc54, 0}},

C[ S[7] , -S[7] , V[1] ] == {{(-I)*gc55, 0}, {I*gc55, 0}},

C[ S[1] , V[4, {e1x2}] , V[4, {e2x2}] ] == {{(-I)*gc56*IndexDelta[e1x2, e2x2], 0}, {I*gc56*IndexDelta[e1x2, e2x2], 0}, {0, 0}},

C[ -U[1] , U[4] , V[3] ] == {{I*gc57, 0}, {I*gc57, 0}, {0, 0}},

C[ -U[1] , U[3] , -V[3] ] == {{I*gc58, 0}, {I*gc58, 0}, {0, 0}},

C[ -S[5] , -U[4] , U[1] ] == {{((-1/2*I)*FCGV["EL"]^2*v)/FCGV["SW"], 0}},

C[ -U[4] , U[1] , -V[3] ] == {{I*gc60, 0}, {I*gc60, 0}, {0, 0}},

C[ S[4] , -U[4] , U[4] ] == {{-1/4*(FCGV["EL"]^2*v)/FCGV["SW"]^2, 0}},

C[ S[1] , -U[4] , U[4] ] == {{((-1/4*I)*FCGV["EL"]^2*v*Cos[aDM])/FCGV["SW"]^2, 0}},

C[ -U[4] , U[4] , V[1] ] == {{I*gc63, 0}, {I*gc63, 0}, {0, 0}},

C[ -U[4] , U[4] , V[2] ] == {{I*gc64, 0}, {I*gc64, 0}, {0, 0}},

C[ -S[5] , -U[4] , U[2] ] == {{((-1/4*I)*FCGV["EL"]^2*(FCGV["CW"] - FCGV["SW"])*(FCGV["CW"] + FCGV["SW"])*v)/(FCGV["CW"]*FCGV["SW"]^2), 0}},

C[ -U[4] , U[2] , -V[3] ] == {{I*gc66, 0}, {I*gc66, 0}, {0, 0}},

C[ S[5] , -U[3] , U[1] ] == {{((-1/2*I)*FCGV["EL"]^2*v)/FCGV["SW"], 0}},

C[ -U[3] , U[1] , V[3] ] == {{I*gc68, 0}, {I*gc68, 0}, {0, 0}},

C[ S[4] , -U[3] , U[3] ] == {{(FCGV["EL"]^2*v)/(4*FCGV["SW"]^2), 0}},

C[ S[1] , -U[3] , U[3] ] == {{((-1/4*I)*FCGV["EL"]^2*v*Cos[aDM])/FCGV["SW"]^2, 0}},

C[ -U[3] , U[3] , V[1] ] == {{I*gc71, 0}, {I*gc71, 0}, {0, 0}},

C[ -U[3] , U[3] , V[2] ] == {{I*gc72, 0}, {I*gc72, 0}, {0, 0}},

C[ S[5] , -U[3] , U[2] ] == {{((-1/4*I)*FCGV["EL"]^2*(FCGV["CW"] - FCGV["SW"])*(FCGV["CW"] + FCGV["SW"])*v)/(FCGV["CW"]*FCGV["SW"]^2), 0}},

C[ -U[3] , U[2] , V[3] ] == {{I*gc74, 0}, {I*gc74, 0}, {0, 0}},

C[ S[5] , -U[2] , U[4] ] == {{((I/4)*FCGV["EL"]^2*(FCGV["CW"]^2 + FCGV["SW"]^2)*v)/(FCGV["CW"]*FCGV["SW"]^2), 0}},

C[ -U[2] , U[4] , V[3] ] == {{I*gc76, 0}, {I*gc76, 0}, {0, 0}},

C[ -S[5] , -U[2] , U[3] ] == {{((I/4)*FCGV["EL"]^2*(FCGV["CW"]^2 + FCGV["SW"]^2)*v)/(FCGV["CW"]*FCGV["SW"]^2), 0}},

C[ -U[2] , U[3] , -V[3] ] == {{I*gc78, 0}, {I*gc78, 0}, {0, 0}},

C[ S[1] , -U[2] , U[2] ] == {{((-1/4*I)*FCGV["EL"]^2*(FCGV["CW"]^2 + FCGV["SW"]^2)^2*v*Cos[aDM])/(FCGV["CW"]^2*FCGV["SW"]^2), 0}},

C[ -U[5, {e1x1}] , U[5, {e2x1}] , V[4, {e3x2}] ] == {{gc80*FASUNF[e3x2, e1x1, e2x1], 0}, {gc80*FASUNF[e3x2, e1x1, e2x1], 0}, {0, 0}},

C[ V[4, {e1x2}] , V[4, {e2x2}] , V[4, {e3x2}] ] == {{-(gc81*FASUNF[e1x2, e2x2, e3x2]), 0}, {gc81*FASUNF[e1x2, e2x2, e3x2], 0}, {gc81*FASUNF[e1x2, e2x2, e3x2], 0}, {-(gc81*FASUNF[e1x2, e2x2, e3x2]), 0}, {-(gc81*FASUNF[e1x2, e2x2, e3x2]), 0}, {gc81*FASUNF[e1x2, e2x2, e3x2], 0}},

C[ V[4, {e1x2}] , V[4, {e2x2}] , V[4, {e3x2}] , V[4, {e4x2}] ] == {{(-I)*gc82*(FASUNF[e1x2, e2x2, e3x2, e4x2] + FASUNF[e1x2, e3x2, e2x2, e4x2]), 0}, {I*gc82*(FASUNF[e1x2, e2x2, e3x2, e4x2] - FASUNF[e1x2, e4x2, e2x2, e3x2]), 0}, {I*gc82*(FASUNF[e1x2, e3x2, e2x2, e4x2] + FASUNF[e1x2, e4x2, e2x2, e3x2]), 0}},

C[ S[1] , V[4, {e1x2}] , V[4, {e2x2}] , V[4, {e3x2}] ] == {{-(gc83*FASUNF[e1x2, e2x2, e3x2]), 0}, {gc83*FASUNF[e1x2, e2x2, e3x2], 0}, {gc83*FASUNF[e1x2, e2x2, e3x2], 0}, {-(gc83*FASUNF[e1x2, e2x2, e3x2]), 0}, {-(gc83*FASUNF[e1x2, e2x2, e3x2]), 0}, {gc83*FASUNF[e1x2, e2x2, e3x2], 0}},

C[ S[1] , V[4, {e1x2}] , V[4, {e2x2}] , V[4, {e3x2}] , V[4, {e4x2}] ] == {{(-I)*gc84*(FASUNF[e1x2, e2x2, e3x2, e4x2] + FASUNF[e1x2, e3x2, e2x2, e4x2]), 0}, {I*gc84*(FASUNF[e1x2, e2x2, e3x2, e4x2] - FASUNF[e1x2, e4x2, e2x2, e3x2]), 0}, {I*gc84*(FASUNF[e1x2, e3x2, e2x2, e4x2] + FASUNF[e1x2, e4x2, e2x2, e3x2]), 0}},

C[ -F[12, {e1x2}] , F[12, {e2x2}] , S[4] ] == {{gc85L*IndexDelta[e1x2, e2x2], 0}, {gc85R*IndexDelta[e1x2, e2x2], 0}},

C[ -F[12, {e1x2}] , F[12, {e2x2}] , S[1] ] == {{I*gc86*IndexDelta[e1x2, e2x2], 0}, {I*gc86*IndexDelta[e1x2, e2x2], 0}},

C[ -F[10, {e1x2}] , F[10, {e2x2}] , S[4] ] == {{gc87L*IndexDelta[e1x2, e2x2], 0}, {gc87R*IndexDelta[e1x2, e2x2], 0}},

C[ -F[10, {e1x2}] , F[10, {e2x2}] , S[1] ] == {{I*gc88*IndexDelta[e1x2, e2x2], 0}, {I*gc88*IndexDelta[e1x2, e2x2], 0}},

C[ -F[11, {e1x2}] , F[11, {e2x2}] , S[4] ] == {{gc89L*IndexDelta[e1x2, e2x2], 0}, {gc89R*IndexDelta[e1x2, e2x2], 0}},

C[ -F[11, {e1x2}] , F[11, {e2x2}] , S[1] ] == {{I*gc90*IndexDelta[e1x2, e2x2], 0}, {I*gc90*IndexDelta[e1x2, e2x2], 0}},

C[ -F[12, {e1x2}] , F[8, {e2x2}] , -S[5] ] == {{I*gc91L*IndexDelta[e1x2, e2x2], 0}, {I*gc91R*IndexDelta[e1x2, e2x2], 0}},

C[ -F[12, {e1x2}] , F[9, {e2x2}] , -S[5] ] == {{I*gc92L*IndexDelta[e1x2, e2x2], 0}, {I*gc92R*IndexDelta[e1x2, e2x2], 0}},

C[ -F[12, {e1x2}] , F[7, {e2x2}] , -S[5] ] == {{I*gc93L*IndexDelta[e1x2, e2x2], 0}, {I*gc93R*IndexDelta[e1x2, e2x2], 0}},

C[ -F[10, {e1x2}] , F[8, {e2x2}] , -S[5] ] == {{I*gc94L*IndexDelta[e1x2, e2x2], 0}, {I*gc94R*IndexDelta[e1x2, e2x2], 0}},

C[ -F[10, {e1x2}] , F[9, {e2x2}] , -S[5] ] == {{I*gc95L*IndexDelta[e1x2, e2x2], 0}, {I*gc95R*IndexDelta[e1x2, e2x2], 0}},

C[ -F[10, {e1x2}] , F[7, {e2x2}] , -S[5] ] == {{I*gc96L*IndexDelta[e1x2, e2x2], 0}, {I*gc96R*IndexDelta[e1x2, e2x2], 0}},

C[ -F[11, {e1x2}] , F[8, {e2x2}] , -S[5] ] == {{I*gc97L*IndexDelta[e1x2, e2x2], 0}, {I*gc97R*IndexDelta[e1x2, e2x2], 0}},

C[ -F[11, {e1x2}] , F[9, {e2x2}] , -S[5] ] == {{I*gc98L*IndexDelta[e1x2, e2x2], 0}, {I*gc98R*IndexDelta[e1x2, e2x2], 0}},

C[ -F[11, {e1x2}] , F[7, {e2x2}] , -S[5] ] == {{I*gc99L*IndexDelta[e1x2, e2x2], 0}, {I*gc99R*IndexDelta[e1x2, e2x2], 0}},

C[ -F[4] , F[4] , S[4] ] == {{gc100L, 0}, {gc100R, 0}},

C[ -F[4] , F[4] , S[1] ] == {{I*gc101, 0}, {I*gc101, 0}},

C[ -F[5] , F[5] , S[4] ] == {{gc102L, 0}, {gc102R, 0}},

C[ -F[5] , F[5] , S[1] ] == {{I*gc103, 0}, {I*gc103, 0}},

C[ -F[6] , F[6] , S[4] ] == {{gc104L, 0}, {gc104R, 0}},

C[ -F[6] , F[6] , S[1] ] == {{I*gc105, 0}, {I*gc105, 0}},

C[ -F[4] , F[1] , -S[5] ] == {{I*gc106, 0}, {0, 0}},

C[ -F[5] , F[2] , -S[5] ] == {{I*gc107, 0}, {0, 0}},

C[ -F[6] , F[3] , -S[5] ] == {{I*gc108, 0}, {0, 0}},

C[ -F[8, {e1x2}] , F[12, {e2x2}] , S[5] ] == {{I*gc109L*IndexDelta[e1x2, e2x2], 0}, {I*gc109R*IndexDelta[e1x2, e2x2], 0}},

C[ -F[8, {e1x2}] , F[10, {e2x2}] , S[5] ] == {{I*gc110L*IndexDelta[e1x2, e2x2], 0}, {I*gc110R*IndexDelta[e1x2, e2x2], 0}},

C[ -F[8, {e1x2}] , F[11, {e2x2}] , S[5] ] == {{I*gc111L*IndexDelta[e1x2, e2x2], 0}, {I*gc111R*IndexDelta[e1x2, e2x2], 0}},

C[ -F[9, {e1x2}] , F[12, {e2x2}] , S[5] ] == {{I*gc112L*IndexDelta[e1x2, e2x2], 0}, {I*gc112R*IndexDelta[e1x2, e2x2], 0}},

C[ -F[9, {e1x2}] , F[10, {e2x2}] , S[5] ] == {{I*gc113L*IndexDelta[e1x2, e2x2], 0}, {I*gc113R*IndexDelta[e1x2, e2x2], 0}},

C[ -F[9, {e1x2}] , F[11, {e2x2}] , S[5] ] == {{I*gc114L*IndexDelta[e1x2, e2x2], 0}, {I*gc114R*IndexDelta[e1x2, e2x2], 0}},

C[ -F[7, {e1x2}] , F[12, {e2x2}] , S[5] ] == {{I*gc115L*IndexDelta[e1x2, e2x2], 0}, {I*gc115R*IndexDelta[e1x2, e2x2], 0}},

C[ -F[7, {e1x2}] , F[10, {e2x2}] , S[5] ] == {{I*gc116L*IndexDelta[e1x2, e2x2], 0}, {I*gc116R*IndexDelta[e1x2, e2x2], 0}},

C[ -F[7, {e1x2}] , F[11, {e2x2}] , S[5] ] == {{I*gc117L*IndexDelta[e1x2, e2x2], 0}, {I*gc117R*IndexDelta[e1x2, e2x2], 0}},

C[ -F[8, {e1x2}] , F[8, {e2x2}] , S[4] ] == {{gc118L*IndexDelta[e1x2, e2x2], 0}, {gc118R*IndexDelta[e1x2, e2x2], 0}},

C[ -F[8, {e1x2}] , F[8, {e2x2}] , S[1] ] == {{I*gc119*IndexDelta[e1x2, e2x2], 0}, {I*gc119*IndexDelta[e1x2, e2x2], 0}},

C[ -F[9, {e1x2}] , F[9, {e2x2}] , S[4] ] == {{gc120L*IndexDelta[e1x2, e2x2], 0}, {gc120R*IndexDelta[e1x2, e2x2], 0}},

C[ -F[9, {e1x2}] , F[9, {e2x2}] , S[1] ] == {{I*gc121*IndexDelta[e1x2, e2x2], 0}, {I*gc121*IndexDelta[e1x2, e2x2], 0}},

C[ -F[7, {e1x2}] , F[7, {e2x2}] , S[4] ] == {{gc122L*IndexDelta[e1x2, e2x2], 0}, {gc122R*IndexDelta[e1x2, e2x2], 0}},

C[ -F[7, {e1x2}] , F[7, {e2x2}] , S[1] ] == {{I*gc123*IndexDelta[e1x2, e2x2], 0}, {I*gc123*IndexDelta[e1x2, e2x2], 0}},

C[ -F[1] , F[4] , S[5] ] == {{0, 0}, {I*gc124R, 0}},

C[ -F[2] , F[5] , S[5] ] == {{0, 0}, {I*gc125R, 0}},

C[ -F[3] , F[6] , S[5] ] == {{0, 0}, {I*gc126R, 0}},

C[ S[6] , S[4] , S[2] , S[3] ] == {{(I*(MA0 - MH3)*(MA0 + MH3)*Sin[aDM])/v^2, 0}},

C[ S[6] , -S[5] , S[2] , S[7] ] == {{((MA0 - MHch)*(MA0 + MHch)*Sin[aDM])/v^2, 0}},

C[ S[6] , S[5] , S[2] , -S[7] ] == {{-(((MA0 - MHch)*(MA0 + MHch)*Sin[aDM])/v^2), 0}},

C[ -S[5] , S[2] , S[3] , S[7] ] == {{((-I)*(MH3 - MHch)*(MH3 + MHch)*Sin[aDM])/v^2, 0}},

C[ S[5] , S[2] , S[3] , -S[7] ] == {{((-I)*(MH3 - MHch)*(MH3 + MHch)*Sin[aDM])/v^2, 0}},

C[ S[6] , S[6] , S[1] , S[2] ] == {{((-I)*(2*m22^2 - 2*MA0^2 + lam8*(v^2 + vs^2))*Cos[aDM]*Sin[aDM])/v^2, 0}},

C[ S[1] , S[2] , S[3] , S[3] ] == {{((-I)*(2*m22^2 - 2*MH3^2 + lam8*(v^2 + vs^2))*Cos[aDM]*Sin[aDM])/v^2, 0}},

C[ S[1] , S[2] , S[7] , -S[7] ] == {{((-I)*(2*m22^2 - 2*MHch^2 + lam8*(v^2 + vs^2))*Cos[aDM]*Sin[aDM])/v^2, 0}},

C[ S[4] , S[4] , S[2] ] == {{(I*MH2^2*Sin[aDM])/v, 0}},

C[ S[5] , -S[5] , S[2] ] == {{(I*MH2^2*Sin[aDM])/v, 0}},

C[ S[4] , S[4] , S[1] , S[2] ] == {{(I*Cos[aDM]*Sin[aDM]*(MH1^2*vs*Cos[aDM]^2 - (MH1^2 - MH2^2)*v*Cos[aDM]*Sin[aDM] + MH2^2*vs*Sin[aDM]^2))/(v^2*vs), 0}},

C[ S[5] , -S[5] , S[1] , S[2] ] == {{(I*Cos[aDM]*Sin[aDM]*(MH1^2*vs*Cos[aDM]^2 - (MH1^2 - MH2^2)*v*Cos[aDM]*Sin[aDM] + MH2^2*vs*Sin[aDM]^2))/(v^2*vs), 0}},

C[ S[4] , S[4] , S[2] , S[2] ] == {{((-I)*Sin[aDM]*((MH1^2 - MH2^2)*v*Cos[aDM]^3 + MH1^2*vs*Cos[aDM]^2*Sin[aDM] + MH2^2*vs*Sin[aDM]^3))/(v^2*vs), 0}},

C[ S[5] , -S[5] , S[2] , S[2] ] == {{((-I)*Sin[aDM]*((MH1^2 - MH2^2)*v*Cos[aDM]^3 + MH1^2*vs*Cos[aDM]^2*Sin[aDM] + MH2^2*vs*Sin[aDM]^3))/(v^2*vs), 0}},

C[ S[1] , S[1] , S[2] ] == {{(I*(2*MH1^2 + MH2^2)*Cos[aDM]*Sin[aDM]*(vs*Cos[aDM] - v*Sin[aDM]))/(v*vs), 0}},

C[ S[1] , S[2] , S[2] ] == {{((-I)*(MH1^2 + 2*MH2^2)*Cos[aDM]*Sin[aDM]*(v*Cos[aDM] + vs*Sin[aDM]))/(v*vs), 0}},

C[ S[1] , S[1] , S[1] , S[2] ] == {{((3*I)*Cos[aDM]*Sin[aDM]*(vs*Cos[aDM] - v*Sin[aDM])*(MH1^2*vs*Cos[aDM]^3 + MH2^2*v*Cos[aDM]^2*Sin[aDM] + MH2^2*vs*Cos[aDM]*Sin[aDM]^2 + MH1^2*v*Sin[aDM]^3))/(v^2*vs^2), 0}},

C[ S[1] , S[2] , S[2] , S[2] ] == {{((3*I)*Cos[aDM]*Sin[aDM]*(v*Cos[aDM] + vs*Sin[aDM])*(-(MH2^2*v*Cos[aDM]^3) + MH1^2*vs*Cos[aDM]^2*Sin[aDM] - MH1^2*v*Cos[aDM]*Sin[aDM]^2 + MH2^2*vs*Sin[aDM]^3))/(v^2*vs^2), 0}},

C[ S[1] , S[1] , S[2] , S[2] ] == {{((-I)*Cos[aDM]*Sin[aDM]*((MH1^2 - MH2^2)*v*vs*Cos[aDM]^4 + 3*(MH2^2*v^2 + MH1^2*vs^2)*Cos[aDM]^3*Sin[aDM] - ((MH1^2 - MH2^2)*v*vs*(3 + 5*Cos[2*aDM])*Sin[aDM]^2)/2 + 3*(MH1^2*v^2 + MH2^2*vs^2)*Cos[aDM]*Sin[aDM]^3))/(v^2*vs^2), 0}},

C[ S[2] , -U[4] , U[4] ] == {{((I/4)*FCGV["EL"]^2*v*Sin[aDM])/FCGV["SW"]^2, 0}},

C[ S[2] , -U[3] , U[3] ] == {{((I/4)*FCGV["EL"]^2*v*Sin[aDM])/FCGV["SW"]^2, 0}},

C[ S[2] , -U[2] , U[2] ] == {{((I/4)*FCGV["EL"]^2*(FCGV["CW"]^2 + FCGV["SW"]^2)^2*v*Sin[aDM])/(FCGV["CW"]^2*FCGV["SW"]^2), 0}},

C[ -F[12, {e1x2}] , F[12, {e2x2}] , S[2] ] == {{I*gc149*IndexDelta[e1x2, e2x2], 0}, {I*gc149*IndexDelta[e1x2, e2x2], 0}},

C[ -F[10, {e1x2}] , F[10, {e2x2}] , S[2] ] == {{I*gc150*IndexDelta[e1x2, e2x2], 0}, {I*gc150*IndexDelta[e1x2, e2x2], 0}},

C[ -F[11, {e1x2}] , F[11, {e2x2}] , S[2] ] == {{I*gc151*IndexDelta[e1x2, e2x2], 0}, {I*gc151*IndexDelta[e1x2, e2x2], 0}},

C[ -F[4] , F[4] , S[2] ] == {{I*gc152, 0}, {I*gc152, 0}},

C[ -F[5] , F[5] , S[2] ] == {{I*gc153, 0}, {I*gc153, 0}},

C[ -F[6] , F[6] , S[2] ] == {{I*gc154, 0}, {I*gc154, 0}},

C[ -F[8, {e1x2}] , F[8, {e2x2}] , S[2] ] == {{I*gc155*IndexDelta[e1x2, e2x2], 0}, {I*gc155*IndexDelta[e1x2, e2x2], 0}},

C[ -F[9, {e1x2}] , F[9, {e2x2}] , S[2] ] == {{I*gc156*IndexDelta[e1x2, e2x2], 0}, {I*gc156*IndexDelta[e1x2, e2x2], 0}},

C[ -F[7, {e1x2}] , F[7, {e2x2}] , S[2] ] == {{I*gc157*IndexDelta[e1x2, e2x2], 0}, {I*gc157*IndexDelta[e1x2, e2x2], 0}},

C[ -F[12, {e1x2}] , F[12, {e2x2}] , V[4, {e3x2}] ] == {{I*gc158*FASUNT[e3x2, e1x2, e2x2], 0}, {I*gc158*FASUNT[e3x2, e1x2, e2x2], 0}},

C[ -F[10, {e1x2}] , F[10, {e2x2}] , V[4, {e3x2}] ] == {{I*gc159*FASUNT[e3x2, e1x2, e2x2], 0}, {I*gc159*FASUNT[e3x2, e1x2, e2x2], 0}},

C[ -F[11, {e1x2}] , F[11, {e2x2}] , V[4, {e3x2}] ] == {{I*gc160*FASUNT[e3x2, e1x2, e2x2], 0}, {I*gc160*FASUNT[e3x2, e1x2, e2x2], 0}},

C[ -F[8, {e1x2}] , F[8, {e2x2}] , V[4, {e3x2}] ] == {{I*gc161*FASUNT[e3x2, e1x2, e2x2], 0}, {I*gc161*FASUNT[e3x2, e1x2, e2x2], 0}},

C[ -F[9, {e1x2}] , F[9, {e2x2}] , V[4, {e3x2}] ] == {{I*gc162*FASUNT[e3x2, e1x2, e2x2], 0}, {I*gc162*FASUNT[e3x2, e1x2, e2x2], 0}},

C[ -F[7, {e1x2}] , F[7, {e2x2}] , V[4, {e3x2}] ] == {{I*gc163*FASUNT[e3x2, e1x2, e2x2], 0}, {I*gc163*FASUNT[e3x2, e1x2, e2x2], 0}},

C[ S[4] , -S[5] , V[1] , V[3] ] == {{-1/2*FCGV["EL"]^2/FCGV["SW"], 0}},

C[ S[6] , -S[7] , V[1] , V[3] ] == {{-1/2*FCGV["EL"]^2/FCGV["SW"], 0}},

C[ S[3] , -S[7] , V[1] , V[3] ] == {{((-1/2*I)*FCGV["EL"]^2)/FCGV["SW"], 0}},

C[ -S[5] , V[1] , V[3] ] == {{0, 0}, {0, 0}, {I*gc167, 0}},

C[ -S[5] , S[1] , V[1] , V[3] ] == {{((I/2)*FCGV["EL"]^2*Cos[aDM])/FCGV["SW"], 0}},

C[ S[6] , -S[7] , V[3] ] == {{-gc169, 0}, {gc169, 0}},

C[ S[4] , -S[5] , V[3] ] == {{-gc170, 0}, {gc170, 0}},

C[ -S[5] , S[1] , V[3] ] == {{(-I)*gc171, 0}, {I*gc171, 0}},

C[ S[3] , -S[7] , V[3] ] == {{(-I)*gc172, 0}, {I*gc172, 0}},

C[ V[1] , V[3] , -V[3] ] == {{(-I)*gc173, 0}, {I*gc173, 0}, {I*gc173, 0}, {(-I)*gc173, 0}, {(-I)*gc173, 0}, {I*gc173, 0}},

C[ -S[5] , S[2] , V[1] , V[3] ] == {{((-1/2*I)*FCGV["EL"]^2*Sin[aDM])/FCGV["SW"], 0}},

C[ -S[5] , S[2] , V[3] ] == {{(-I)*gc175, 0}, {I*gc175, 0}},

C[ S[4] , S[5] , V[1] , -V[3] ] == {{FCGV["EL"]^2/(2*FCGV["SW"]), 0}},

C[ S[6] , S[7] , V[1] , -V[3] ] == {{FCGV["EL"]^2/(2*FCGV["SW"]), 0}},

C[ S[3] , S[7] , V[1] , -V[3] ] == {{((-1/2*I)*FCGV["EL"]^2)/FCGV["SW"], 0}},

C[ S[5] , V[1] , -V[3] ] == {{0, 0}, {0, 0}, {I*gc179, 0}},

C[ S[5] , S[1] , V[1] , -V[3] ] == {{((I/2)*FCGV["EL"]^2*Cos[aDM])/FCGV["SW"], 0}},

C[ S[6] , S[7] , -V[3] ] == {{-gc181, 0}, {gc181, 0}},

C[ S[4] , S[5] , -V[3] ] == {{-gc182, 0}, {gc182, 0}},

C[ S[5] , S[1] , -V[3] ] == {{(-I)*gc183, 0}, {I*gc183, 0}},

C[ S[3] , S[7] , -V[3] ] == {{(-I)*gc184, 0}, {I*gc184, 0}},

C[ S[5] , S[2] , V[1] , -V[3] ] == {{((-1/2*I)*FCGV["EL"]^2*Sin[aDM])/FCGV["SW"], 0}},

C[ S[5] , S[2] , -V[3] ] == {{(-I)*gc186, 0}, {I*gc186, 0}},

C[ S[6] , S[6] , V[3] , -V[3] ] == {{((I/2)*FCGV["EL"]^2)/FCGV["SW"]^2, 0}},

C[ S[4] , S[4] , V[3] , -V[3] ] == {{((I/2)*FCGV["EL"]^2)/FCGV["SW"]^2, 0}},

C[ S[5] , -S[5] , V[3] , -V[3] ] == {{((I/2)*FCGV["EL"]^2)/FCGV["SW"]^2, 0}},

C[ S[3] , S[3] , V[3] , -V[3] ] == {{((I/2)*FCGV["EL"]^2)/FCGV["SW"]^2, 0}},

C[ S[7] , -S[7] , V[3] , -V[3] ] == {{((I/2)*FCGV["EL"]^2)/FCGV["SW"]^2, 0}},

C[ V[1] , V[1] , V[3] , -V[3] ] == {{(-I)*gc192, 0}, {(-I)*gc192, 0}, {(2*I)*gc192, 0}},

C[ S[1] , V[3] , -V[3] ] == {{0, 0}, {0, 0}, {I*gc193, 0}},

C[ S[1] , S[1] , V[3] , -V[3] ] == {{((I/2)*FCGV["EL"]^2*Cos[aDM]^2)/FCGV["SW"]^2, 0}},

C[ S[2] , V[3] , -V[3] ] == {{0, 0}, {0, 0}, {I*gc195, 0}},

C[ S[1] , S[2] , V[3] , -V[3] ] == {{((-1/2*I)*FCGV["EL"]^2*Cos[aDM]*Sin[aDM])/FCGV["SW"]^2, 0}},

C[ S[2] , S[2] , V[3] , -V[3] ] == {{((I/2)*FCGV["EL"]^2*Sin[aDM]^2)/FCGV["SW"]^2, 0}},

C[ V[3] , -V[3] , V[2] ] == {{(-I)*gc198, 0}, {I*gc198, 0}, {I*gc198, 0}, {(-I)*gc198, 0}, {(-I)*gc198, 0}, {I*gc198, 0}},

C[ V[3] , V[3] , -V[3] , -V[3] ] == {{(-I)*gc199, 0}, {(-I)*gc199, 0}, {(2*I)*gc199, 0}},

C[ S[5] , -S[5] , V[1] , V[2] ] == {{(I*FCGV["EL"]^2*(FCGV["CW"] - FCGV["SW"])*(FCGV["CW"] + FCGV["SW"]))/(FCGV["CW"]*FCGV["SW"]), 0}},

C[ S[7] , -S[7] , V[1] , V[2] ] == {{(I*FCGV["EL"]^2*(FCGV["CW"] - FCGV["SW"])*(FCGV["CW"] + FCGV["SW"]))/(FCGV["CW"]*FCGV["SW"]), 0}},

C[ S[6] , S[3] , V[2] ] == {{-gc202, 0}, {gc202, 0}},

C[ S[4] , S[1] , V[2] ] == {{-gc203, 0}, {gc203, 0}},

C[ S[5] , -S[5] , V[2] ] == {{(-I)*gc204, 0}, {I*gc204, 0}},

C[ S[7] , -S[7] , V[2] ] == {{(-I)*gc205, 0}, {I*gc205, 0}},

C[ S[4] , S[2] , V[2] ] == {{-gc206, 0}, {gc206, 0}},

C[ S[4] , -S[5] , V[3] , V[2] ] == {{FCGV["EL"]^2/(2*FCGV["CW"]), 0}},

C[ S[6] , -S[7] , V[3] , V[2] ] == {{FCGV["EL"]^2/(2*FCGV["CW"]), 0}},

C[ S[3] , -S[7] , V[3] , V[2] ] == {{((I/2)*FCGV["EL"]^2)/FCGV["CW"], 0}},

C[ -S[5] , V[3] , V[2] ] == {{0, 0}, {0, 0}, {I*gc210, 0}},

C[ -S[5] , S[1] , V[3] , V[2] ] == {{((-1/2*I)*FCGV["EL"]^2*Cos[aDM])/FCGV["CW"], 0}},

C[ -S[5] , S[2] , V[3] , V[2] ] == {{((I/2)*FCGV["EL"]^2*Sin[aDM])/FCGV["CW"], 0}},

C[ S[4] , S[5] , -V[3] , V[2] ] == {{-1/2*FCGV["EL"]^2/FCGV["CW"], 0}},

C[ S[6] , S[7] , -V[3] , V[2] ] == {{-1/2*FCGV["EL"]^2/FCGV["CW"], 0}},

C[ S[3] , S[7] , -V[3] , V[2] ] == {{((I/2)*FCGV["EL"]^2)/FCGV["CW"], 0}},

C[ S[5] , -V[3] , V[2] ] == {{0, 0}, {0, 0}, {I*gc216, 0}},

C[ S[5] , S[1] , -V[3] , V[2] ] == {{((-1/2*I)*FCGV["EL"]^2*Cos[aDM])/FCGV["CW"], 0}},

C[ S[5] , S[2] , -V[3] , V[2] ] == {{((I/2)*FCGV["EL"]^2*Sin[aDM])/FCGV["CW"], 0}},

C[ V[1] , V[3] , -V[3] , V[2] ] == {{(-2*I)*gc219, 0}, {I*gc219, 0}, {I*gc219, 0}},

C[ S[6] , S[6] , V[2] , V[2] ] == {{((I/2)*FCGV["EL"]^2*(FCGV["CW"]^2 + FCGV["SW"]^2)^2)/(FCGV["CW"]^2*FCGV["SW"]^2), 0}},

C[ S[4] , S[4] , V[2] , V[2] ] == {{((I/2)*FCGV["EL"]^2*(FCGV["CW"]^2 + FCGV["SW"]^2)^2)/(FCGV["CW"]^2*FCGV["SW"]^2), 0}},

C[ S[5] , -S[5] , V[2] , V[2] ] == {{((I/2)*FCGV["EL"]^2*(FCGV["CW"] - FCGV["SW"])^2*(FCGV["CW"] + FCGV["SW"])^2)/(FCGV["CW"]^2*FCGV["SW"]^2), 0}},

C[ S[3] , S[3] , V[2] , V[2] ] == {{((I/2)*FCGV["EL"]^2*(FCGV["CW"]^2 + FCGV["SW"]^2)^2)/(FCGV["CW"]^2*FCGV["SW"]^2), 0}},

C[ S[7] , -S[7] , V[2] , V[2] ] == {{((I/2)*FCGV["EL"]^2*(FCGV["CW"] - FCGV["SW"])^2*(FCGV["CW"] + FCGV["SW"])^2)/(FCGV["CW"]^2*FCGV["SW"]^2), 0}},

C[ S[1] , V[2] , V[2] ] == {{0, 0}, {0, 0}, {I*gc225, 0}},

C[ S[1] , S[1] , V[2] , V[2] ] == {{((I/2)*FCGV["EL"]^2*(FCGV["CW"]^2 + FCGV["SW"]^2)^2*Cos[aDM]^2)/(FCGV["CW"]^2*FCGV["SW"]^2), 0}},

C[ S[2] , V[2] , V[2] ] == {{0, 0}, {0, 0}, {I*gc227, 0}},

C[ S[1] , S[2] , V[2] , V[2] ] == {{((-1/4*I)*FCGV["EL"]^2*(FCGV["CW"]^2 + FCGV["SW"]^2)^2*Sin[2*aDM])/(FCGV["CW"]^2*FCGV["SW"]^2), 0}},

C[ S[2] , S[2] , V[2] , V[2] ] == {{((I/2)*FCGV["EL"]^2*(FCGV["CW"]^2 + FCGV["SW"]^2)^2*Sin[aDM]^2)/(FCGV["CW"]^2*FCGV["SW"]^2), 0}},

C[ V[3] , -V[3] , V[2] , V[2] ] == {{(-I)*gc230, 0}, {(-I)*gc230, 0}, {(2*I)*gc230, 0}},

C[ -F[12, {e1x2}] , F[12, {e2x2}] , V[1] ] == {{I*gc231*IndexDelta[e1x2, e2x2], 0}, {I*gc231*IndexDelta[e1x2, e2x2], 0}},

C[ -F[10, {e1x2}] , F[10, {e2x2}] , V[1] ] == {{I*gc232*IndexDelta[e1x2, e2x2], 0}, {I*gc232*IndexDelta[e1x2, e2x2], 0}},

C[ -F[11, {e1x2}] , F[11, {e2x2}] , V[1] ] == {{I*gc233*IndexDelta[e1x2, e2x2], 0}, {I*gc233*IndexDelta[e1x2, e2x2], 0}},

C[ -F[4] , F[4] , V[1] ] == {{I*gc234, 0}, {I*gc234, 0}},

C[ -F[5] , F[5] , V[1] ] == {{I*gc235, 0}, {I*gc235, 0}},

C[ -F[6] , F[6] , V[1] ] == {{I*gc236, 0}, {I*gc236, 0}},

C[ -F[8, {e1x2}] , F[8, {e2x2}] , V[1] ] == {{I*gc237*IndexDelta[e1x2, e2x2], 0}, {I*gc237*IndexDelta[e1x2, e2x2], 0}},

C[ -F[9, {e1x2}] , F[9, {e2x2}] , V[1] ] == {{I*gc238*IndexDelta[e1x2, e2x2], 0}, {I*gc238*IndexDelta[e1x2, e2x2], 0}},

C[ -F[7, {e1x2}] , F[7, {e2x2}] , V[1] ] == {{I*gc239*IndexDelta[e1x2, e2x2], 0}, {I*gc239*IndexDelta[e1x2, e2x2], 0}},

C[ -F[1] , F[4] , V[3] ] == {{I*gc240, 0}, {0, 0}},

C[ -F[2] , F[5] , V[3] ] == {{I*gc241, 0}, {0, 0}},

C[ -F[3] , F[6] , V[3] ] == {{I*gc242, 0}, {0, 0}},

C[ -F[8, {e1x2}] , F[12, {e2x2}] , V[3] ] == {{I*gc243*IndexDelta[e1x2, e2x2], 0}, {0, 0}},

C[ -F[8, {e1x2}] , F[10, {e2x2}] , V[3] ] == {{I*gc244*IndexDelta[e1x2, e2x2], 0}, {0, 0}},

C[ -F[8, {e1x2}] , F[11, {e2x2}] , V[3] ] == {{I*gc245*IndexDelta[e1x2, e2x2], 0}, {0, 0}},

C[ -F[9, {e1x2}] , F[12, {e2x2}] , V[3] ] == {{I*gc246*IndexDelta[e1x2, e2x2], 0}, {0, 0}},

C[ -F[9, {e1x2}] , F[10, {e2x2}] , V[3] ] == {{I*gc247*IndexDelta[e1x2, e2x2], 0}, {0, 0}},

C[ -F[9, {e1x2}] , F[11, {e2x2}] , V[3] ] == {{I*gc248*IndexDelta[e1x2, e2x2], 0}, {0, 0}},

C[ -F[7, {e1x2}] , F[12, {e2x2}] , V[3] ] == {{I*gc249*IndexDelta[e1x2, e2x2], 0}, {0, 0}},

C[ -F[7, {e1x2}] , F[10, {e2x2}] , V[3] ] == {{I*gc250*IndexDelta[e1x2, e2x2], 0}, {0, 0}},

C[ -F[7, {e1x2}] , F[11, {e2x2}] , V[3] ] == {{I*gc251*IndexDelta[e1x2, e2x2], 0}, {0, 0}},

C[ -F[4] , F[1] , -V[3] ] == {{I*gc252, 0}, {0, 0}},

C[ -F[5] , F[2] , -V[3] ] == {{I*gc253, 0}, {0, 0}},

C[ -F[6] , F[3] , -V[3] ] == {{I*gc254, 0}, {0, 0}},

C[ -F[12, {e1x2}] , F[8, {e2x2}] , -V[3] ] == {{I*gc255*IndexDelta[e1x2, e2x2], 0}, {0, 0}},

C[ -F[12, {e1x2}] , F[9, {e2x2}] , -V[3] ] == {{I*gc256*IndexDelta[e1x2, e2x2], 0}, {0, 0}},

C[ -F[12, {e1x2}] , F[7, {e2x2}] , -V[3] ] == {{I*gc257*IndexDelta[e1x2, e2x2], 0}, {0, 0}},

C[ -F[10, {e1x2}] , F[8, {e2x2}] , -V[3] ] == {{I*gc258*IndexDelta[e1x2, e2x2], 0}, {0, 0}},

C[ -F[10, {e1x2}] , F[9, {e2x2}] , -V[3] ] == {{I*gc259*IndexDelta[e1x2, e2x2], 0}, {0, 0}},

C[ -F[10, {e1x2}] , F[7, {e2x2}] , -V[3] ] == {{I*gc260*IndexDelta[e1x2, e2x2], 0}, {0, 0}},

C[ -F[11, {e1x2}] , F[8, {e2x2}] , -V[3] ] == {{I*gc261*IndexDelta[e1x2, e2x2], 0}, {0, 0}},

C[ -F[11, {e1x2}] , F[9, {e2x2}] , -V[3] ] == {{I*gc262*IndexDelta[e1x2, e2x2], 0}, {0, 0}},

C[ -F[11, {e1x2}] , F[7, {e2x2}] , -V[3] ] == {{I*gc263*IndexDelta[e1x2, e2x2], 0}, {0, 0}},

C[ -F[12, {e1x2}] , F[12, {e2x2}] , V[2] ] == {{I*gc264L*IndexDelta[e1x2, e2x2], 0}, {I*gc264R*IndexDelta[e1x2, e2x2], 0}},

C[ -F[10, {e1x2}] , F[10, {e2x2}] , V[2] ] == {{I*gc265L*IndexDelta[e1x2, e2x2], 0}, {I*gc265R*IndexDelta[e1x2, e2x2], 0}},

C[ -F[11, {e1x2}] , F[11, {e2x2}] , V[2] ] == {{I*gc266L*IndexDelta[e1x2, e2x2], 0}, {I*gc266R*IndexDelta[e1x2, e2x2], 0}},

C[ -F[4] , F[4] , V[2] ] == {{I*gc267L, 0}, {I*gc267R, 0}},

C[ -F[5] , F[5] , V[2] ] == {{I*gc268L, 0}, {I*gc268R, 0}},

C[ -F[6] , F[6] , V[2] ] == {{I*gc269L, 0}, {I*gc269R, 0}},

C[ -F[8, {e1x2}] , F[8, {e2x2}] , V[2] ] == {{I*gc270L*IndexDelta[e1x2, e2x2], 0}, {I*gc270R*IndexDelta[e1x2, e2x2], 0}},

C[ -F[9, {e1x2}] , F[9, {e2x2}] , V[2] ] == {{I*gc271L*IndexDelta[e1x2, e2x2], 0}, {I*gc271R*IndexDelta[e1x2, e2x2], 0}},

C[ -F[7, {e1x2}] , F[7, {e2x2}] , V[2] ] == {{I*gc272L*IndexDelta[e1x2, e2x2], 0}, {I*gc272R*IndexDelta[e1x2, e2x2], 0}},

C[ -F[1] , F[1] , V[2] ] == {{I*gc273, 0}, {0, 0}},

C[ -F[2] , F[2] , V[2] ] == {{I*gc274, 0}, {0, 0}},

C[ -F[3] , F[3] , V[2] ] == {{I*gc275, 0}, {0, 0}}

}

(* * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * *)

(* Parameter replacement lists (These lists were created by FeynRules) *)

(* FA Couplings *)

M$FACouplings = {
     gc54 -> -FCGV["EL"],
     gc55 -> -FCGV["EL"],
     gc56 -> GH,
     gc57 -> FCGV["EL"],
     gc58 -> -FCGV["EL"],
     gc60 -> FCGV["EL"],
     gc63 -> -FCGV["EL"],
     gc64 -> -((FCGV["CW"]*FCGV["EL"])/FCGV["SW"]),
     gc66 -> (FCGV["CW"]*FCGV["EL"])/FCGV["SW"],
     gc68 -> -FCGV["EL"],
     gc71 -> FCGV["EL"],
     gc72 -> (FCGV["CW"]*FCGV["EL"])/FCGV["SW"],
     gc74 -> -((FCGV["CW"]*FCGV["EL"])/FCGV["SW"]),
     gc76 -> (FCGV["CW"]*FCGV["EL"])/FCGV["SW"],
     gc78 -> -((FCGV["CW"]*FCGV["EL"])/FCGV["SW"]),
     gc80 -> FAGS,
     gc81 -> -FAGS,
     gc82 -> -FAGS^2,
     gc83 -> -(GH*FAGS),
     gc84 -> -(GH*FAGS^2),
     gc85L -> -(FCGV["MB"]/v),
     gc85R -> FCGV["MB"]/v,
     gc86 -> -((FCGV["MB"]*Cos[aDM])/v),
     gc87L -> -(FCGV["MD"]/v),
     gc87R -> FCGV["MD"]/v,
     gc88 -> -((FCGV["MD"]*Cos[aDM])/v),
     gc89L -> -(FCGV["MS"]/v),
     gc89R -> FCGV["MS"]/v,
     gc90 -> -((FCGV["MS"]*Cos[aDM])/v),
     gc91L -> -((Sqrt[2]*FCGV["MS"]*Conjugate[CKM2x3])/v),
     gc91R -> (Sqrt[2]*FCGV["MT"]*Conjugate[CKM2x3])/v,
     gc92L -> -((Sqrt[2]*FCGV["MB"]*Conjugate[CKM3x3])/v),
     gc92R -> (Sqrt[2]*FCGV["MT"]*Conjugate[CKM3x3])/v,
     gc93L -> -((Sqrt[2]*FCGV["MD"]*Conjugate[CKM1x3])/v),
     gc93R -> (Sqrt[2]*FCGV["MT"]*Conjugate[CKM1x3])/v,
     gc94L -> -((Sqrt[2]*FCGV["MS"]*Conjugate[CKM2x1])/v),
     gc94R -> (Sqrt[2]*FCGV["MU"]*Conjugate[CKM2x1])/v,
     gc95L -> -((Sqrt[2]*FCGV["MB"]*Conjugate[CKM3x1])/v),
     gc95R -> (Sqrt[2]*FCGV["MU"]*Conjugate[CKM3x1])/v,
     gc96L -> -((Sqrt[2]*FCGV["MD"]*Conjugate[CKM1x1])/v),
     gc96R -> (Sqrt[2]*FCGV["MU"]*Conjugate[CKM1x1])/v,
     gc97L -> -((Sqrt[2]*FCGV["MS"]*Conjugate[CKM2x2])/v),
     gc97R -> (Sqrt[2]*FCGV["MC"]*Conjugate[CKM2x2])/v,
     gc98L -> -((Sqrt[2]*FCGV["MB"]*Conjugate[CKM3x2])/v),
     gc98R -> (Sqrt[2]*FCGV["MC"]*Conjugate[CKM3x2])/v,
     gc99L -> -((Sqrt[2]*FCGV["MD"]*Conjugate[CKM1x2])/v),
     gc99R -> (Sqrt[2]*FCGV["MC"]*Conjugate[CKM1x2])/v,
     gc100L -> -(Me/v),
     gc100R -> Me/v,
     gc101 -> -((Me*Cos[aDM])/v),
     gc102L -> -(FCGV["MM"]/v),
     gc102R -> FCGV["MM"]/v,
     gc103 -> -((FCGV["MM"]*Cos[aDM])/v),
     gc104L -> -(MTA/v),
     gc104R -> MTA/v,
     gc105 -> -((MTA*Cos[aDM])/v),
     gc106 -> -((Sqrt[2]*Me)/v),
     gc107 -> -((Sqrt[2]*FCGV["MM"])/v),
     gc108 -> -((Sqrt[2]*MTA)/v),
     gc109L -> (Sqrt[2]*CKM2x3*FCGV["MT"])/v,
     gc109R -> -((Sqrt[2]*CKM2x3*FCGV["MS"])/v),
     gc110L -> (Sqrt[2]*CKM2x1*FCGV["MU"])/v,
     gc110R -> -((Sqrt[2]*CKM2x1*FCGV["MS"])/v),
     gc111L -> (Sqrt[2]*CKM2x2*FCGV["MC"])/v,
     gc111R -> -((Sqrt[2]*CKM2x2*FCGV["MS"])/v),
     gc112L -> (Sqrt[2]*CKM3x3*FCGV["MT"])/v,
     gc112R -> -((Sqrt[2]*CKM3x3*FCGV["MB"])/v),
     gc113L -> (Sqrt[2]*CKM3x1*FCGV["MU"])/v,
     gc113R -> -((Sqrt[2]*CKM3x1*FCGV["MB"])/v),
     gc114L -> (Sqrt[2]*CKM3x2*FCGV["MC"])/v,
     gc114R -> -((Sqrt[2]*CKM3x2*FCGV["MB"])/v),
     gc115L -> (Sqrt[2]*CKM1x3*FCGV["MT"])/v,
     gc115R -> -((Sqrt[2]*CKM1x3*FCGV["MD"])/v),
     gc116L -> (Sqrt[2]*CKM1x1*FCGV["MU"])/v,
     gc116R -> -((Sqrt[2]*CKM1x1*FCGV["MD"])/v),
     gc117L -> (Sqrt[2]*CKM1x2*FCGV["MC"])/v,
     gc117R -> -((Sqrt[2]*CKM1x2*FCGV["MD"])/v),
     gc118L -> FCGV["MC"]/v,
     gc118R -> -(FCGV["MC"]/v),
     gc119 -> -((FCGV["MC"]*Cos[aDM])/v),
     gc120L -> FCGV["MT"]/v,
     gc120R -> -(FCGV["MT"]/v),
     gc121 -> -((FCGV["MT"]*Cos[aDM])/v),
     gc122L -> FCGV["MU"]/v,
     gc122R -> -(FCGV["MU"]/v),
     gc123 -> -((FCGV["MU"]*Cos[aDM])/v),
     gc124R -> -((Sqrt[2]*Me)/v),
     gc125R -> -((Sqrt[2]*FCGV["MM"])/v),
     gc126R -> -((Sqrt[2]*MTA)/v),
     gc149 -> (FCGV["MB"]*Sin[aDM])/v,
     gc150 -> (FCGV["MD"]*Sin[aDM])/v,
     gc151 -> (FCGV["MS"]*Sin[aDM])/v,
     gc152 -> (Me*Sin[aDM])/v,
     gc153 -> (FCGV["MM"]*Sin[aDM])/v,
     gc154 -> (MTA*Sin[aDM])/v,
     gc155 -> (FCGV["MC"]*Sin[aDM])/v,
     gc156 -> (FCGV["MT"]*Sin[aDM])/v,
     gc157 -> (FCGV["MU"]*Sin[aDM])/v,
     gc158 -> FAGS,
     gc159 -> FAGS,
     gc160 -> FAGS,
     gc161 -> FAGS,
     gc162 -> FAGS,
     gc163 -> FAGS,
     gc167 -> (FCGV["EL"]^2*v)/(2*FCGV["SW"]),
     gc169 -> FCGV["EL"]/(2*FCGV["SW"]),
     gc170 -> FCGV["EL"]/(2*FCGV["SW"]),
     gc171 -> (FCGV["EL"]*Cos[aDM])/(2*FCGV["SW"]),
     gc172 -> FCGV["EL"]/(2*FCGV["SW"]),
     gc173 -> FCGV["EL"],
     gc175 -> -1/2*(FCGV["EL"]*Sin[aDM])/FCGV["SW"],
     gc179 -> (FCGV["EL"]^2*v)/(2*FCGV["SW"]),
     gc181 -> FCGV["EL"]/(2*FCGV["SW"]),
     gc182 -> FCGV["EL"]/(2*FCGV["SW"]),
     gc183 -> -1/2*(FCGV["EL"]*Cos[aDM])/FCGV["SW"],
     gc184 -> -1/2*FCGV["EL"]/FCGV["SW"],
     gc186 -> (FCGV["EL"]*Sin[aDM])/(2*FCGV["SW"]),
     gc192 -> -FCGV["EL"]^2,
     gc193 -> (FCGV["EL"]^2*v*Cos[aDM])/(2*FCGV["SW"]^2),
     gc195 -> -1/2*(FCGV["EL"]^2*v*Sin[aDM])/FCGV["SW"]^2,
     gc198 -> (FCGV["CW"]*FCGV["EL"])/FCGV["SW"],
     gc199 -> FCGV["EL"]^2/FCGV["SW"]^2,
     gc202 -> (FCGV["EL"]*(FCGV["CW"]^2 + FCGV["SW"]^2))/(2*FCGV["CW"]*FCGV["SW"]),
     gc203 -> -1/2*(FCGV["EL"]*(FCGV["CW"]^2 + FCGV["SW"]^2)*Cos[aDM])/(FCGV["CW"]*FCGV["SW"]),
     gc204 -> -1/2*(FCGV["CW"]*FCGV["EL"])/FCGV["SW"] + (FCGV["EL"]*FCGV["SW"])/(2*FCGV["CW"]),
     gc205 -> -1/2*(FCGV["CW"]*FCGV["EL"])/FCGV["SW"] + (FCGV["EL"]*FCGV["SW"])/(2*FCGV["CW"]),
     gc206 -> (FCGV["EL"]*(FCGV["CW"]^2 + FCGV["SW"]^2)*Sin[aDM])/(2*FCGV["CW"]*FCGV["SW"]),
     gc210 -> -1/2*(FCGV["EL"]^2*v)/FCGV["CW"],
     gc216 -> -1/2*(FCGV["EL"]^2*v)/FCGV["CW"],
     gc219 -> (FCGV["CW"]*FCGV["EL"]^2)/FCGV["SW"],
     gc225 -> (FCGV["EL"]^2*(FCGV["CW"]^2 + FCGV["SW"]^2)^2*v*Cos[aDM])/(2*FCGV["CW"]^2*FCGV["SW"]^2),
     gc227 -> -1/2*(FCGV["EL"]^2*(FCGV["CW"]^2 + FCGV["SW"]^2)^2*v*Sin[aDM])/(FCGV["CW"]^2*FCGV["SW"]^2),
     gc230 -> -((FCGV["CW"]^2*FCGV["EL"]^2)/FCGV["SW"]^2),
     gc231 -> -1/3*FCGV["EL"],
     gc232 -> -1/3*FCGV["EL"],
     gc233 -> -1/3*FCGV["EL"],
     gc234 -> -FCGV["EL"],
     gc235 -> -FCGV["EL"],
     gc236 -> -FCGV["EL"],
     gc237 -> (2*FCGV["EL"])/3,
     gc238 -> (2*FCGV["EL"])/3,
     gc239 -> (2*FCGV["EL"])/3,
     gc240 -> FCGV["EL"]/(Sqrt[2]*FCGV["SW"]),
     gc241 -> FCGV["EL"]/(Sqrt[2]*FCGV["SW"]),
     gc242 -> FCGV["EL"]/(Sqrt[2]*FCGV["SW"]),
     gc243 -> (CKM2x3*FCGV["EL"])/(Sqrt[2]*FCGV["SW"]),
     gc244 -> (CKM2x1*FCGV["EL"])/(Sqrt[2]*FCGV["SW"]),
     gc245 -> (CKM2x2*FCGV["EL"])/(Sqrt[2]*FCGV["SW"]),
     gc246 -> (CKM3x3*FCGV["EL"])/(Sqrt[2]*FCGV["SW"]),
     gc247 -> (CKM3x1*FCGV["EL"])/(Sqrt[2]*FCGV["SW"]),
     gc248 -> (CKM3x2*FCGV["EL"])/(Sqrt[2]*FCGV["SW"]),
     gc249 -> (CKM1x3*FCGV["EL"])/(Sqrt[2]*FCGV["SW"]),
     gc250 -> (CKM1x1*FCGV["EL"])/(Sqrt[2]*FCGV["SW"]),
     gc251 -> (CKM1x2*FCGV["EL"])/(Sqrt[2]*FCGV["SW"]),
     gc252 -> FCGV["EL"]/(Sqrt[2]*FCGV["SW"]),
     gc253 -> FCGV["EL"]/(Sqrt[2]*FCGV["SW"]),
     gc254 -> FCGV["EL"]/(Sqrt[2]*FCGV["SW"]),
     gc255 -> (FCGV["EL"]*Conjugate[CKM2x3])/(Sqrt[2]*FCGV["SW"]),
     gc256 -> (FCGV["EL"]*Conjugate[CKM3x3])/(Sqrt[2]*FCGV["SW"]),
     gc257 -> (FCGV["EL"]*Conjugate[CKM1x3])/(Sqrt[2]*FCGV["SW"]),
     gc258 -> (FCGV["EL"]*Conjugate[CKM2x1])/(Sqrt[2]*FCGV["SW"]),
     gc259 -> (FCGV["EL"]*Conjugate[CKM3x1])/(Sqrt[2]*FCGV["SW"]),
     gc260 -> (FCGV["EL"]*Conjugate[CKM1x1])/(Sqrt[2]*FCGV["SW"]),
     gc261 -> (FCGV["EL"]*Conjugate[CKM2x2])/(Sqrt[2]*FCGV["SW"]),
     gc262 -> (FCGV["EL"]*Conjugate[CKM3x2])/(Sqrt[2]*FCGV["SW"]),
     gc263 -> (FCGV["EL"]*Conjugate[CKM1x2])/(Sqrt[2]*FCGV["SW"]),
     gc264L -> -1/6*(FCGV["EL"]*(3*FCGV["CW"]^2 + FCGV["SW"]^2))/(FCGV["CW"]*FCGV["SW"]),
     gc264R -> (FCGV["EL"]*FCGV["SW"])/(3*FCGV["CW"]),
     gc265L -> -1/6*(FCGV["EL"]*(3*FCGV["CW"]^2 + FCGV["SW"]^2))/(FCGV["CW"]*FCGV["SW"]),
     gc265R -> (FCGV["EL"]*FCGV["SW"])/(3*FCGV["CW"]),
     gc266L -> -1/6*(FCGV["EL"]*(3*FCGV["CW"]^2 + FCGV["SW"]^2))/(FCGV["CW"]*FCGV["SW"]),
     gc266R -> (FCGV["EL"]*FCGV["SW"])/(3*FCGV["CW"]),
     gc267L -> -1/2*(FCGV["EL"]*(FCGV["CW"]^2 - FCGV["SW"]^2))/(FCGV["CW"]*FCGV["SW"]),
     gc267R -> (FCGV["EL"]*FCGV["SW"])/FCGV["CW"],
     gc268L -> -1/2*(FCGV["EL"]*(FCGV["CW"]^2 - FCGV["SW"]^2))/(FCGV["CW"]*FCGV["SW"]),
     gc268R -> (FCGV["EL"]*FCGV["SW"])/FCGV["CW"],
     gc269L -> -1/2*(FCGV["EL"]*(FCGV["CW"]^2 - FCGV["SW"]^2))/(FCGV["CW"]*FCGV["SW"]),
     gc269R -> (FCGV["EL"]*FCGV["SW"])/FCGV["CW"],
     gc270L -> (FCGV["CW"]*FCGV["EL"])/(2*FCGV["SW"]) - (FCGV["EL"]*FCGV["SW"])/(6*FCGV["CW"]),
     gc270R -> (-2*FCGV["EL"]*FCGV["SW"])/(3*FCGV["CW"]),
     gc271L -> (FCGV["CW"]*FCGV["EL"])/(2*FCGV["SW"]) - (FCGV["EL"]*FCGV["SW"])/(6*FCGV["CW"]),
     gc271R -> (-2*FCGV["EL"]*FCGV["SW"])/(3*FCGV["CW"]),
     gc272L -> (FCGV["CW"]*FCGV["EL"])/(2*FCGV["SW"]) - (FCGV["EL"]*FCGV["SW"])/(6*FCGV["CW"]),
     gc272R -> (-2*FCGV["EL"]*FCGV["SW"])/(3*FCGV["CW"]),
     gc273 -> (FCGV["EL"]*(FCGV["CW"]^2 + FCGV["SW"]^2))/(2*FCGV["CW"]*FCGV["SW"]),
     gc274 -> (FCGV["EL"]*(FCGV["CW"]^2 + FCGV["SW"]^2))/(2*FCGV["CW"]*FCGV["SW"]),
     gc275 -> (FCGV["EL"]*(FCGV["CW"]^2 + FCGV["SW"]^2))/(2*FCGV["CW"]*FCGV["SW"])};

