(* Patched for use with FeynCalc *)
(* * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * *)
(*                                                                             *)
(*         This file has been automatically generated by FeynRules.            *)
(*                                                                             *)
(* * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * *)


FR$ModelInformation={
  ModelName->"InertDoublet",
  Authors -> {"Andreas Goudelis, Bjoern Herrmann, Oscal Stal"},
  Version -> "1.0",
  Date -> "04. 10. 2013",
  Institutions -> {"LAPTh-Annecy, Oscar Klein Center-Stockholm"},
  Emails -> {"andreas.goudelis@lapth.cnrs.fr"}};

FR$ClassesTranslation={ve -> F[1], vm -> F[2], vt -> F[3], e -> F[4], m -> F[5], ta -> F[6], u -> F[7], c -> F[8], t -> F[9], d -> F[10], s -> F[11], b -> F[12], A -> V[1], Z -> V[2], W -> V[3], G -> V[4], ghA -> U[1], ghZ -> U[2], ghWp -> U[3], ghWm -> U[4], ghG -> U[5], h -> S[1], G0 -> S[2], Gch -> S[3], H0 -> S[4], A0 -> S[5], Hch -> S[6]};

FR$InteractionOrderPerturbativeExpansion={{HIG, 0}, {QCD, 0}, {QED, 0}};

FR$GoldstoneList={S[2], S[3]};

(*     Declared indices    *)

IndexRange[ Index[Generation] ] = Range[ 3 ]

IndexRange[ Index[Colour] ] = NoUnfold[ Range[ 3 ] ]

IndexRange[ Index[Gluon] ] = NoUnfold[ Range[ 8 ] ]

IndexRange[ Index[SU2W] ] = Range[ 3 ]

(*     Declared particles    *)

M$ClassesDescription = {
F[1] == {
    SelfConjugate -> False,
    PropagatorType -> Straight,
    PropagatorArrow -> Forward,
    Mass -> Mnue,
    Indices -> {},
    PropagatorLabel -> "ve" },

F[2] == {
    SelfConjugate -> False,
    PropagatorType -> Straight,
    PropagatorArrow -> Forward,
    Mass -> Mnum,
    Indices -> {},
    PropagatorLabel -> "vm" },

F[3] == {
    SelfConjugate -> False,
    PropagatorType -> Straight,
    PropagatorArrow -> Forward,
    Mass -> Mnut,
    Indices -> {},
    PropagatorLabel -> "vt" },

F[4] == {
    SelfConjugate -> False,
    QuantumNumbers -> {-Q},
    PropagatorType -> Straight,
    PropagatorArrow -> Forward,
    Mass -> Me,
    Indices -> {},
    PropagatorLabel -> "e" },

F[5] == {
    SelfConjugate -> False,
    QuantumNumbers -> {-Q},
    PropagatorType -> Straight,
    PropagatorArrow -> Forward,
    Mass -> FCGV["MM"],
    Indices -> {},
    PropagatorLabel -> "m" },

F[6] == {
    SelfConjugate -> False,
    QuantumNumbers -> {-Q},
    PropagatorType -> Straight,
    PropagatorArrow -> Forward,
    Mass -> MTA,
    Indices -> {},
    PropagatorLabel -> "ta" },

F[7] == {
    SelfConjugate -> False,
    QuantumNumbers -> {(2*Q)/3},
    PropagatorType -> Straight,
    PropagatorArrow -> Forward,
    Mass -> FCGV["MU"],
    Indices -> {Index[Colour]},
    PropagatorLabel -> "u" },

F[8] == {
    SelfConjugate -> False,
    QuantumNumbers -> {(2*Q)/3},
    PropagatorType -> Straight,
    PropagatorArrow -> Forward,
    Mass -> FCGV["MC"],
    Indices -> {Index[Colour]},
    PropagatorLabel -> "c" },

F[9] == {
    SelfConjugate -> False,
    QuantumNumbers -> {(2*Q)/3},
    PropagatorType -> Straight,
    PropagatorArrow -> Forward,
    Mass -> FCGV["MT"],
    Indices -> {Index[Colour]},
    PropagatorLabel -> "t" },

F[10] == {
    SelfConjugate -> False,
    QuantumNumbers -> {-1/3*Q},
    PropagatorType -> Straight,
    PropagatorArrow -> Forward,
    Mass -> FCGV["MD"],
    Indices -> {Index[Colour]},
    PropagatorLabel -> "d" },

F[11] == {
    SelfConjugate -> False,
    QuantumNumbers -> {-1/3*Q},
    PropagatorType -> Straight,
    PropagatorArrow -> Forward,
    Mass -> FCGV["MS"],
    Indices -> {Index[Colour]},
    PropagatorLabel -> "s" },

F[12] == {
    SelfConjugate -> False,
    QuantumNumbers -> {-1/3*Q},
    PropagatorType -> Straight,
    PropagatorArrow -> Forward,
    Mass -> FCGV["MB"],
    Indices -> {Index[Colour]},
    PropagatorLabel -> "b" },

V[1] == {
    SelfConjugate -> True,
    PropagatorType -> Sine,
    PropagatorArrow -> None,
    Mass -> 0,
    Indices -> {},
    PropagatorLabel -> "A" },

V[2] == {
    SelfConjugate -> True,
    PropagatorType -> Sine,
    PropagatorArrow -> None,
    Mass -> FCGV["MZ"],
    Indices -> {},
    PropagatorLabel -> "Z" },

V[3] == {
    SelfConjugate -> False,
    QuantumNumbers -> {Q},
    PropagatorType -> Sine,
    PropagatorArrow -> Forward,
    Mass -> FCGV["MW"],
    Indices -> {},
    PropagatorLabel -> "W" },

V[4] == {
    SelfConjugate -> True,
    PropagatorType -> Cycles,
    PropagatorArrow -> None,
    Mass -> 0,
    Indices -> {Index[Gluon]},
    PropagatorLabel -> "G" },

U[1] == {
    SelfConjugate -> False,
    QuantumNumbers -> {GhostNumber},
    PropagatorType -> GhostDash,
    PropagatorArrow -> Forward,
    Mass -> 0,
    Indices -> {},
    PropagatorLabel -> "ghA" },

U[2] == {
    SelfConjugate -> False,
    QuantumNumbers -> {GhostNumber},
    PropagatorType -> GhostDash,
    PropagatorArrow -> Forward,
    Mass -> FCGV["MZ"],
    Indices -> {},
    PropagatorLabel -> "ghZ" },

U[3] == {
    SelfConjugate -> False,
    QuantumNumbers -> {Q, GhostNumber},
    PropagatorType -> GhostDash,
    PropagatorArrow -> Forward,
    Mass -> FCGV["MW"],
    Indices -> {},
    PropagatorLabel -> "ghWp" },

U[4] == {
    SelfConjugate -> False,
    QuantumNumbers -> {-Q, GhostNumber},
    PropagatorType -> GhostDash,
    PropagatorArrow -> Forward,
    Mass -> FCGV["MW"],
    Indices -> {},
    PropagatorLabel -> "ghWm" },

U[5] == {
    SelfConjugate -> False,
    QuantumNumbers -> {GhostNumber},
    PropagatorType -> GhostDash,
    PropagatorArrow -> Forward,
    Mass -> 0,
    Indices -> {Index[Gluon]},
    PropagatorLabel -> "ghG" },

S[1] == {
    SelfConjugate -> True,
    PropagatorType -> ScalarDash,
    PropagatorArrow -> None,
    Mass -> mh,
    Indices -> {},
    PropagatorLabel -> "h" },

S[2] == {
    SelfConjugate -> True,
    PropagatorType -> ScalarDash,
    PropagatorArrow -> None,
    Mass -> FCGV["MZ"],
    Indices -> {},
    PropagatorLabel -> "G0" },

S[3] == {
    SelfConjugate -> False,
    PropagatorType -> ScalarDash,
    PropagatorArrow -> None,
    QuantumNumbers -> {Q},
    Mass -> FCGV["MW"],
    Indices -> {},
    PropagatorLabel -> "Gch" },

S[4] == {
    SelfConjugate -> True,
    PropagatorType -> ScalarDash,
    PropagatorArrow -> None,
    Mass -> MH0,
    Indices -> {},
    PropagatorLabel -> "H0" },

S[5] == {
    SelfConjugate -> True,
    PropagatorType -> ScalarDash,
    PropagatorArrow -> None,
    Mass -> MA0,
    Indices -> {},
    PropagatorLabel -> "A0" },

S[6] == {
    SelfConjugate -> False,
    QuantumNumbers -> {Q},
    PropagatorType -> ScalarDash,
    PropagatorArrow -> Forward,
    Mass -> MHch,
    Indices -> {},
    PropagatorLabel -> "Hch" }
}


(*        Definitions       *)


Mnue[ ___ ] := Mnue;
Mnum[ ___ ] := Mnum;
Mnut[ ___ ] := Mnut;
Me[ ___ ] := Me;
FCGV["MM"][ ___ ] := FCGV["MM"];
MTA[ ___ ] := MTA;
FCGV["MU"][ ___ ] := FCGV["MU"];
FCGV["MC"][ ___ ] := FCGV["MC"];
FCGV["MT"][ ___ ] := FCGV["MT"];
FCGV["MD"][ ___ ] := FCGV["MD"];
FCGV["MS"][ ___ ] := FCGV["MS"];
FCGV["MB"][ ___ ] := FCGV["MB"];
FCGV["MZ"][ ___ ] := FCGV["MZ"];
FCGV["MW"][ ___ ] := FCGV["MW"];
mh[ ___ ] := mh;
MH0[ ___ ] := MH0;
MA0[ ___ ] := MA0;
MHch[ ___ ] := MHch;


TheLabel[ F[7, {__}] ] := TheLabel[F[7]];
TheLabel[ F[8, {__}] ] := TheLabel[F[8]];
TheLabel[ F[9, {__}] ] := TheLabel[F[9]];
TheLabel[ F[10, {__}] ] := TheLabel[F[10]];
TheLabel[ F[11, {__}] ] := TheLabel[F[11]];
TheLabel[ F[12, {__}] ] := TheLabel[F[12]];
TheLabel[ V[4, {__}] ] := TheLabel[V[4]];
TheLabel[ U[5, {__}] ] := TheLabel[U[5]];


(*      Couplings (calculated by FeynRules)      *)

M$CouplingMatrices = {

C[ S[2] , S[2] , S[2] , S[2] ] == {{(-6*I)*lam, 0}},

C[ S[2] , S[2] , S[3] , -S[3] ] == {{(-2*I)*lam, 0}},

C[ S[3] , S[3] , -S[3] , -S[3] ] == {{(-4*I)*lam, 0}},

C[ S[2] , S[2] , S[1] , S[1] ] == {{(-2*I)*lam, 0}},

C[ S[3] , -S[3] , S[1] , S[1] ] == {{(-2*I)*lam, 0}},

C[ S[1] , S[1] , S[1] , S[1] ] == {{(-6*I)*lam, 0}},

C[ S[5] , S[5] , S[5] , S[5] ] == {{(-6*I)*lam2, 0}},

C[ S[5] , S[5] , S[4] , S[4] ] == {{(-2*I)*lam2, 0}},

C[ S[4] , S[4] , S[4] , S[4] ] == {{(-6*I)*lam2, 0}},

C[ S[5] , S[5] , S[6] , -S[6] ] == {{(-2*I)*lam2, 0}},

C[ S[4] , S[4] , S[6] , -S[6] ] == {{(-2*I)*lam2, 0}},

C[ S[6] , S[6] , -S[6] , -S[6] ] == {{(-4*I)*lam2, 0}},

C[ S[5] , S[5] , S[2] , S[2] ] == {{(-I)*(lam3 + lam4 + lam5), 0}},

C[ S[5] , S[5] , S[3] , -S[3] ] == {{(-I)*lam3, 0}},

C[ S[5] , S[5] , S[1] , S[1] ] == {{(-I)*(lam3 + lam4 - lam5), 0}},

C[ S[2] , S[2] , S[4] , S[4] ] == {{(-I)*(lam3 + lam4 - lam5), 0}},

C[ S[3] , -S[3] , S[4] , S[4] ] == {{(-I)*lam3, 0}},

C[ S[1] , S[1] , S[4] , S[4] ] == {{(-I)*(lam3 + lam4 + lam5), 0}},

C[ S[2] , S[2] , S[6] , -S[6] ] == {{(-I)*lam3, 0}},

C[ S[3] , -S[3] , S[6] , -S[6] ] == {{(-I)*(lam3 + lam4), 0}},

C[ S[1] , S[1] , S[6] , -S[6] ] == {{(-I)*lam3, 0}},

C[ S[5] , S[2] , -S[3] , S[6] ] == {{(-1/2*I)*(lam4 + lam5), 0}},

C[ S[5] , -S[3] , S[1] , S[6] ] == {{(-lam4 + lam5)/2, 0}},

C[ S[2] , -S[3] , S[4] , S[6] ] == {{(lam4 - lam5)/2, 0}},

C[ -S[3] , S[1] , S[4] , S[6] ] == {{(-1/2*I)*(lam4 + lam5), 0}},

C[ S[5] , S[2] , S[3] , -S[6] ] == {{(-1/2*I)*(lam4 + lam5), 0}},

C[ S[5] , S[3] , S[1] , -S[6] ] == {{(lam4 - lam5)/2, 0}},

C[ S[2] , S[3] , S[4] , -S[6] ] == {{(-lam4 + lam5)/2, 0}},

C[ S[3] , S[1] , S[4] , -S[6] ] == {{(-1/2*I)*(lam4 + lam5), 0}},

C[ S[5] , S[2] , S[1] , S[4] ] == {{(-I)*lam5, 0}},

C[ -S[3] , -S[3] , S[6] , S[6] ] == {{(-2*I)*lam5, 0}},

C[ S[3] , S[3] , -S[6] , -S[6] ] == {{(-2*I)*lam5, 0}},

C[ S[2] , S[2] , S[1] ] == {{(-2*I)*lam*v, 0}},

C[ S[3] , -S[3] , S[1] ] == {{(-2*I)*lam*v, 0}},

C[ S[1] , S[1] , S[1] ] == {{(-6*I)*lam*v, 0}},

C[ S[5] , S[5] , S[1] ] == {{(-I)*(lam3 + lam4 - lam5)*v, 0}},

C[ S[1] , S[4] , S[4] ] == {{(-I)*(lam3 + lam4 + lam5)*v, 0}},

C[ S[1] , S[6] , -S[6] ] == {{(-I)*lam3*v, 0}},

C[ S[5] , -S[3] , S[6] ] == {{-1/2*((lam4 - lam5)*v), 0}},

C[ -S[3] , S[4] , S[6] ] == {{(-1/2*I)*(lam4 + lam5)*v, 0}},

C[ S[5] , S[3] , -S[6] ] == {{((lam4 - lam5)*v)/2, 0}},

C[ S[3] , S[4] , -S[6] ] == {{(-1/2*I)*(lam4 + lam5)*v, 0}},

C[ S[5] , S[2] , S[4] ] == {{(-I)*lam5*v, 0}},

C[ S[3] , -S[3] , V[1] , V[1] ] == {{(2*I)*FCGV["EL"]^2, 0}},

C[ S[6] , -S[6] , V[1] , V[1] ] == {{(2*I)*FCGV["EL"]^2, 0}},

C[ S[3] , -S[3] , V[1] ] == {{(-I)*gc46, 0}, {I*gc46, 0}},

C[ S[6] , -S[6] , V[1] ] == {{(-I)*gc47, 0}, {I*gc47, 0}},

C[ S[1] , V[4, {e1x2}] , V[4, {e2x2}] ] == {{(-I)*gc48*IndexDelta[e1x2, e2x2], 0}, {I*gc48*IndexDelta[e1x2, e2x2], 0}, {0, 0}},

C[ -U[1] , U[4] , V[3] ] == {{I*gc49, 0}, {I*gc49, 0}, {0, 0}},

C[ -U[1] , U[3] , -V[3] ] == {{I*gc50, 0}, {I*gc50, 0}, {0, 0}},

C[ -S[3] , -U[4] , U[1] ] == {{((-1/2*I)*FCGV["EL"]^2*v)/FCGV["SW"], 0}},

C[ -U[4] , U[1] , -V[3] ] == {{I*gc52, 0}, {I*gc52, 0}, {0, 0}},

C[ S[2] , -U[4] , U[4] ] == {{-1/4*(FCGV["EL"]^2*v)/FCGV["SW"]^2, 0}},

C[ S[1] , -U[4] , U[4] ] == {{((-1/4*I)*FCGV["EL"]^2*v)/FCGV["SW"]^2, 0}},

C[ -U[4] , U[4] , V[1] ] == {{I*gc55, 0}, {I*gc55, 0}, {0, 0}},

C[ -U[4] , U[4] , V[2] ] == {{I*gc56, 0}, {I*gc56, 0}, {0, 0}},

C[ -S[3] , -U[4] , U[2] ] == {{((-1/4*I)*FCGV["EL"]^2*(FCGV["CW"] - FCGV["SW"])*(FCGV["CW"] + FCGV["SW"])*v)/(FCGV["CW"]*FCGV["SW"]^2), 0}},

C[ -U[4] , U[2] , -V[3] ] == {{I*gc58, 0}, {I*gc58, 0}, {0, 0}},

C[ S[3] , -U[3] , U[1] ] == {{((-1/2*I)*FCGV["EL"]^2*v)/FCGV["SW"], 0}},

C[ -U[3] , U[1] , V[3] ] == {{I*gc60, 0}, {I*gc60, 0}, {0, 0}},

C[ S[2] , -U[3] , U[3] ] == {{(FCGV["EL"]^2*v)/(4*FCGV["SW"]^2), 0}},

C[ S[1] , -U[3] , U[3] ] == {{((-1/4*I)*FCGV["EL"]^2*v)/FCGV["SW"]^2, 0}},

C[ -U[3] , U[3] , V[1] ] == {{I*gc63, 0}, {I*gc63, 0}, {0, 0}},

C[ -U[3] , U[3] , V[2] ] == {{I*gc64, 0}, {I*gc64, 0}, {0, 0}},

C[ S[3] , -U[3] , U[2] ] == {{((-1/4*I)*FCGV["EL"]^2*(FCGV["CW"] - FCGV["SW"])*(FCGV["CW"] + FCGV["SW"])*v)/(FCGV["CW"]*FCGV["SW"]^2), 0}},

C[ -U[3] , U[2] , V[3] ] == {{I*gc66, 0}, {I*gc66, 0}, {0, 0}},

C[ S[3] , -U[2] , U[4] ] == {{((I/4)*FCGV["EL"]^2*(FCGV["CW"]^2 + FCGV["SW"]^2)*v)/(FCGV["CW"]*FCGV["SW"]^2), 0}},

C[ -U[2] , U[4] , V[3] ] == {{I*gc68, 0}, {I*gc68, 0}, {0, 0}},

C[ -S[3] , -U[2] , U[3] ] == {{((I/4)*FCGV["EL"]^2*(FCGV["CW"]^2 + FCGV["SW"]^2)*v)/(FCGV["CW"]*FCGV["SW"]^2), 0}},

C[ -U[2] , U[3] , -V[3] ] == {{I*gc70, 0}, {I*gc70, 0}, {0, 0}},

C[ S[1] , -U[2] , U[2] ] == {{((-1/4*I)*FCGV["EL"]^2*(FCGV["CW"]^2 + FCGV["SW"]^2)^2*v)/(FCGV["CW"]^2*FCGV["SW"]^2), 0}},

C[ -U[5, {e1x1}] , U[5, {e2x1}] , V[4, {e3x2}] ] == {{gc72*FASUNF[e3x2, e1x1, e2x1], 0}, {gc72*FASUNF[e3x2, e1x1, e2x1], 0}, {0, 0}},

C[ V[4, {e1x2}] , V[4, {e2x2}] , V[4, {e3x2}] ] == {{-(gc73*FASUNF[e1x2, e2x2, e3x2]), 0}, {gc73*FASUNF[e1x2, e2x2, e3x2], 0}, {gc73*FASUNF[e1x2, e2x2, e3x2], 0}, {-(gc73*FASUNF[e1x2, e2x2, e3x2]), 0}, {-(gc73*FASUNF[e1x2, e2x2, e3x2]), 0}, {gc73*FASUNF[e1x2, e2x2, e3x2], 0}},

C[ V[4, {e1x2}] , V[4, {e2x2}] , V[4, {e3x2}] , V[4, {e4x2}] ] == {{(-I)*gc74*(FASUNF[e1x2, e2x2, e3x2, e4x2] + FASUNF[e1x2, e3x2, e2x2, e4x2]), 0}, {I*gc74*(FASUNF[e1x2, e2x2, e3x2, e4x2] - FASUNF[e1x2, e4x2, e2x2, e3x2]), 0}, {I*gc74*(FASUNF[e1x2, e3x2, e2x2, e4x2] + FASUNF[e1x2, e4x2, e2x2, e3x2]), 0}},

C[ S[1] , V[4, {e1x2}] , V[4, {e2x2}] , V[4, {e3x2}] ] == {{-(gc75*FASUNF[e1x2, e2x2, e3x2]), 0}, {gc75*FASUNF[e1x2, e2x2, e3x2], 0}, {gc75*FASUNF[e1x2, e2x2, e3x2], 0}, {-(gc75*FASUNF[e1x2, e2x2, e3x2]), 0}, {-(gc75*FASUNF[e1x2, e2x2, e3x2]), 0}, {gc75*FASUNF[e1x2, e2x2, e3x2], 0}},

C[ S[1] , V[4, {e1x2}] , V[4, {e2x2}] , V[4, {e3x2}] , V[4, {e4x2}] ] == {{(-I)*gc76*(FASUNF[e1x2, e2x2, e3x2, e4x2] + FASUNF[e1x2, e3x2, e2x2, e4x2]), 0}, {I*gc76*(FASUNF[e1x2, e2x2, e3x2, e4x2] - FASUNF[e1x2, e4x2, e2x2, e3x2]), 0}, {I*gc76*(FASUNF[e1x2, e3x2, e2x2, e4x2] + FASUNF[e1x2, e4x2, e2x2, e3x2]), 0}},

C[ -F[12, {e1x2}] , F[12, {e2x2}] , S[2] ] == {{gc77L*IndexDelta[e1x2, e2x2], 0}, {gc77R*IndexDelta[e1x2, e2x2], 0}},

C[ -F[12, {e1x2}] , F[12, {e2x2}] , S[1] ] == {{I*gc78*IndexDelta[e1x2, e2x2], 0}, {I*gc78*IndexDelta[e1x2, e2x2], 0}},

C[ -F[10, {e1x2}] , F[10, {e2x2}] , S[2] ] == {{gc79L*IndexDelta[e1x2, e2x2], 0}, {gc79R*IndexDelta[e1x2, e2x2], 0}},

C[ -F[10, {e1x2}] , F[10, {e2x2}] , S[1] ] == {{I*gc80*IndexDelta[e1x2, e2x2], 0}, {I*gc80*IndexDelta[e1x2, e2x2], 0}},

C[ -F[11, {e1x2}] , F[11, {e2x2}] , S[2] ] == {{gc81L*IndexDelta[e1x2, e2x2], 0}, {gc81R*IndexDelta[e1x2, e2x2], 0}},

C[ -F[11, {e1x2}] , F[11, {e2x2}] , S[1] ] == {{I*gc82*IndexDelta[e1x2, e2x2], 0}, {I*gc82*IndexDelta[e1x2, e2x2], 0}},

C[ -F[12, {e1x2}] , F[8, {e2x2}] , -S[3] ] == {{I*gc83L*IndexDelta[e1x2, e2x2], 0}, {I*gc83R*IndexDelta[e1x2, e2x2], 0}},

C[ -F[12, {e1x2}] , F[9, {e2x2}] , -S[3] ] == {{I*gc84L*IndexDelta[e1x2, e2x2], 0}, {I*gc84R*IndexDelta[e1x2, e2x2], 0}},

C[ -F[12, {e1x2}] , F[7, {e2x2}] , -S[3] ] == {{I*gc85L*IndexDelta[e1x2, e2x2], 0}, {I*gc85R*IndexDelta[e1x2, e2x2], 0}},

C[ -F[10, {e1x2}] , F[8, {e2x2}] , -S[3] ] == {{I*gc86L*IndexDelta[e1x2, e2x2], 0}, {I*gc86R*IndexDelta[e1x2, e2x2], 0}},

C[ -F[10, {e1x2}] , F[9, {e2x2}] , -S[3] ] == {{I*gc87L*IndexDelta[e1x2, e2x2], 0}, {I*gc87R*IndexDelta[e1x2, e2x2], 0}},

C[ -F[10, {e1x2}] , F[7, {e2x2}] , -S[3] ] == {{I*gc88L*IndexDelta[e1x2, e2x2], 0}, {I*gc88R*IndexDelta[e1x2, e2x2], 0}},

C[ -F[11, {e1x2}] , F[8, {e2x2}] , -S[3] ] == {{I*gc89L*IndexDelta[e1x2, e2x2], 0}, {I*gc89R*IndexDelta[e1x2, e2x2], 0}},

C[ -F[11, {e1x2}] , F[9, {e2x2}] , -S[3] ] == {{I*gc90L*IndexDelta[e1x2, e2x2], 0}, {I*gc90R*IndexDelta[e1x2, e2x2], 0}},

C[ -F[11, {e1x2}] , F[7, {e2x2}] , -S[3] ] == {{I*gc91L*IndexDelta[e1x2, e2x2], 0}, {I*gc91R*IndexDelta[e1x2, e2x2], 0}},

C[ -F[4] , F[4] , S[2] ] == {{gc92L, 0}, {gc92R, 0}},

C[ -F[4] , F[4] , S[1] ] == {{I*gc93, 0}, {I*gc93, 0}},

C[ -F[5] , F[5] , S[2] ] == {{gc94L, 0}, {gc94R, 0}},

C[ -F[5] , F[5] , S[1] ] == {{I*gc95, 0}, {I*gc95, 0}},

C[ -F[6] , F[6] , S[2] ] == {{gc96L, 0}, {gc96R, 0}},

C[ -F[6] , F[6] , S[1] ] == {{I*gc97, 0}, {I*gc97, 0}},

C[ -F[4] , F[1] , -S[3] ] == {{I*gc98, 0}, {0, 0}},

C[ -F[5] , F[2] , -S[3] ] == {{I*gc99, 0}, {0, 0}},

C[ -F[6] , F[3] , -S[3] ] == {{I*gc100, 0}, {0, 0}},

C[ -F[8, {e1x2}] , F[12, {e2x2}] , S[3] ] == {{I*gc101L*IndexDelta[e1x2, e2x2], 0}, {I*gc101R*IndexDelta[e1x2, e2x2], 0}},

C[ -F[8, {e1x2}] , F[10, {e2x2}] , S[3] ] == {{I*gc102L*IndexDelta[e1x2, e2x2], 0}, {I*gc102R*IndexDelta[e1x2, e2x2], 0}},

C[ -F[8, {e1x2}] , F[11, {e2x2}] , S[3] ] == {{I*gc103L*IndexDelta[e1x2, e2x2], 0}, {I*gc103R*IndexDelta[e1x2, e2x2], 0}},

C[ -F[9, {e1x2}] , F[12, {e2x2}] , S[3] ] == {{I*gc104L*IndexDelta[e1x2, e2x2], 0}, {I*gc104R*IndexDelta[e1x2, e2x2], 0}},

C[ -F[9, {e1x2}] , F[10, {e2x2}] , S[3] ] == {{I*gc105L*IndexDelta[e1x2, e2x2], 0}, {I*gc105R*IndexDelta[e1x2, e2x2], 0}},

C[ -F[9, {e1x2}] , F[11, {e2x2}] , S[3] ] == {{I*gc106L*IndexDelta[e1x2, e2x2], 0}, {I*gc106R*IndexDelta[e1x2, e2x2], 0}},

C[ -F[7, {e1x2}] , F[12, {e2x2}] , S[3] ] == {{I*gc107L*IndexDelta[e1x2, e2x2], 0}, {I*gc107R*IndexDelta[e1x2, e2x2], 0}},

C[ -F[7, {e1x2}] , F[10, {e2x2}] , S[3] ] == {{I*gc108L*IndexDelta[e1x2, e2x2], 0}, {I*gc108R*IndexDelta[e1x2, e2x2], 0}},

C[ -F[7, {e1x2}] , F[11, {e2x2}] , S[3] ] == {{I*gc109L*IndexDelta[e1x2, e2x2], 0}, {I*gc109R*IndexDelta[e1x2, e2x2], 0}},

C[ -F[8, {e1x2}] , F[8, {e2x2}] , S[2] ] == {{gc110L*IndexDelta[e1x2, e2x2], 0}, {gc110R*IndexDelta[e1x2, e2x2], 0}},

C[ -F[8, {e1x2}] , F[8, {e2x2}] , S[1] ] == {{I*gc111*IndexDelta[e1x2, e2x2], 0}, {I*gc111*IndexDelta[e1x2, e2x2], 0}},

C[ -F[9, {e1x2}] , F[9, {e2x2}] , S[2] ] == {{gc112L*IndexDelta[e1x2, e2x2], 0}, {gc112R*IndexDelta[e1x2, e2x2], 0}},

C[ -F[9, {e1x2}] , F[9, {e2x2}] , S[1] ] == {{I*gc113*IndexDelta[e1x2, e2x2], 0}, {I*gc113*IndexDelta[e1x2, e2x2], 0}},

C[ -F[7, {e1x2}] , F[7, {e2x2}] , S[2] ] == {{gc114L*IndexDelta[e1x2, e2x2], 0}, {gc114R*IndexDelta[e1x2, e2x2], 0}},

C[ -F[7, {e1x2}] , F[7, {e2x2}] , S[1] ] == {{I*gc115*IndexDelta[e1x2, e2x2], 0}, {I*gc115*IndexDelta[e1x2, e2x2], 0}},

C[ -F[1] , F[4] , S[3] ] == {{0, 0}, {I*gc116R, 0}},

C[ -F[2] , F[5] , S[3] ] == {{0, 0}, {I*gc117R, 0}},

C[ -F[3] , F[6] , S[3] ] == {{0, 0}, {I*gc118R, 0}},

C[ -F[12, {e1x2}] , F[12, {e2x2}] , V[4, {e3x2}] ] == {{I*gc119*FASUNT[e3x2, e1x2, e2x2], 0}, {I*gc119*FASUNT[e3x2, e1x2, e2x2], 0}},

C[ -F[10, {e1x2}] , F[10, {e2x2}] , V[4, {e3x2}] ] == {{I*gc120*FASUNT[e3x2, e1x2, e2x2], 0}, {I*gc120*FASUNT[e3x2, e1x2, e2x2], 0}},

C[ -F[11, {e1x2}] , F[11, {e2x2}] , V[4, {e3x2}] ] == {{I*gc121*FASUNT[e3x2, e1x2, e2x2], 0}, {I*gc121*FASUNT[e3x2, e1x2, e2x2], 0}},

C[ -F[8, {e1x2}] , F[8, {e2x2}] , V[4, {e3x2}] ] == {{I*gc122*FASUNT[e3x2, e1x2, e2x2], 0}, {I*gc122*FASUNT[e3x2, e1x2, e2x2], 0}},

C[ -F[9, {e1x2}] , F[9, {e2x2}] , V[4, {e3x2}] ] == {{I*gc123*FASUNT[e3x2, e1x2, e2x2], 0}, {I*gc123*FASUNT[e3x2, e1x2, e2x2], 0}},

C[ -F[7, {e1x2}] , F[7, {e2x2}] , V[4, {e3x2}] ] == {{I*gc124*FASUNT[e3x2, e1x2, e2x2], 0}, {I*gc124*FASUNT[e3x2, e1x2, e2x2], 0}},

C[ S[2] , -S[3] , V[1] , V[3] ] == {{-1/2*FCGV["EL"]^2/FCGV["SW"], 0}},

C[ -S[3] , S[1] , V[1] , V[3] ] == {{((I/2)*FCGV["EL"]^2)/FCGV["SW"], 0}},

C[ S[5] , -S[6] , V[1] , V[3] ] == {{-1/2*FCGV["EL"]^2/FCGV["SW"], 0}},

C[ S[4] , -S[6] , V[1] , V[3] ] == {{((I/2)*FCGV["EL"]^2)/FCGV["SW"], 0}},

C[ -S[3] , V[1] , V[3] ] == {{0, 0}, {0, 0}, {I*gc129, 0}},

C[ S[5] , -S[6] , V[3] ] == {{-gc130, 0}, {gc130, 0}},

C[ S[2] , -S[3] , V[3] ] == {{-gc131, 0}, {gc131, 0}},

C[ -S[3] , S[1] , V[3] ] == {{(-I)*gc132, 0}, {I*gc132, 0}},

C[ S[4] , -S[6] , V[3] ] == {{(-I)*gc133, 0}, {I*gc133, 0}},

C[ V[1] , V[3] , -V[3] ] == {{(-I)*gc134, 0}, {I*gc134, 0}, {I*gc134, 0}, {(-I)*gc134, 0}, {(-I)*gc134, 0}, {I*gc134, 0}},

C[ S[2] , S[3] , V[1] , -V[3] ] == {{FCGV["EL"]^2/(2*FCGV["SW"]), 0}},

C[ S[3] , S[1] , V[1] , -V[3] ] == {{((I/2)*FCGV["EL"]^2)/FCGV["SW"], 0}},

C[ S[5] , S[6] , V[1] , -V[3] ] == {{FCGV["EL"]^2/(2*FCGV["SW"]), 0}},

C[ S[4] , S[6] , V[1] , -V[3] ] == {{((I/2)*FCGV["EL"]^2)/FCGV["SW"], 0}},

C[ S[3] , V[1] , -V[3] ] == {{0, 0}, {0, 0}, {I*gc139, 0}},

C[ S[5] , S[6] , -V[3] ] == {{-gc140, 0}, {gc140, 0}},

C[ S[2] , S[3] , -V[3] ] == {{-gc141, 0}, {gc141, 0}},

C[ S[3] , S[1] , -V[3] ] == {{(-I)*gc142, 0}, {I*gc142, 0}},

C[ S[4] , S[6] , -V[3] ] == {{(-I)*gc143, 0}, {I*gc143, 0}},

C[ S[5] , S[5] , V[3] , -V[3] ] == {{((I/2)*FCGV["EL"]^2)/FCGV["SW"]^2, 0}},

C[ S[2] , S[2] , V[3] , -V[3] ] == {{((I/2)*FCGV["EL"]^2)/FCGV["SW"]^2, 0}},

C[ S[3] , -S[3] , V[3] , -V[3] ] == {{((I/2)*FCGV["EL"]^2)/FCGV["SW"]^2, 0}},

C[ S[1] , S[1] , V[3] , -V[3] ] == {{((I/2)*FCGV["EL"]^2)/FCGV["SW"]^2, 0}},

C[ S[4] , S[4] , V[3] , -V[3] ] == {{((I/2)*FCGV["EL"]^2)/FCGV["SW"]^2, 0}},

C[ S[6] , -S[6] , V[3] , -V[3] ] == {{((I/2)*FCGV["EL"]^2)/FCGV["SW"]^2, 0}},

C[ S[1] , V[3] , -V[3] ] == {{0, 0}, {0, 0}, {I*gc150, 0}},

C[ V[1] , V[1] , V[3] , -V[3] ] == {{(-I)*gc151, 0}, {(-I)*gc151, 0}, {(2*I)*gc151, 0}},

C[ V[3] , -V[3] , V[2] ] == {{(-I)*gc152, 0}, {I*gc152, 0}, {I*gc152, 0}, {(-I)*gc152, 0}, {(-I)*gc152, 0}, {I*gc152, 0}},

C[ V[3] , V[3] , -V[3] , -V[3] ] == {{(-I)*gc153, 0}, {(-I)*gc153, 0}, {(2*I)*gc153, 0}},

C[ S[3] , -S[3] , V[1] , V[2] ] == {{(I*FCGV["EL"]^2*(FCGV["CW"] - FCGV["SW"])*(FCGV["CW"] + FCGV["SW"]))/(FCGV["CW"]*FCGV["SW"]), 0}},

C[ S[6] , -S[6] , V[1] , V[2] ] == {{(I*FCGV["EL"]^2*(FCGV["CW"] - FCGV["SW"])*(FCGV["CW"] + FCGV["SW"]))/(FCGV["CW"]*FCGV["SW"]), 0}},

C[ S[5] , S[4] , V[2] ] == {{-gc156, 0}, {gc156, 0}},

C[ S[2] , S[1] , V[2] ] == {{-gc157, 0}, {gc157, 0}},

C[ S[3] , -S[3] , V[2] ] == {{(-I)*gc158, 0}, {I*gc158, 0}},

C[ S[6] , -S[6] , V[2] ] == {{(-I)*gc159, 0}, {I*gc159, 0}},

C[ S[2] , -S[3] , V[3] , V[2] ] == {{FCGV["EL"]^2/(2*FCGV["CW"]), 0}},

C[ -S[3] , S[1] , V[3] , V[2] ] == {{((-1/2*I)*FCGV["EL"]^2)/FCGV["CW"], 0}},

C[ S[5] , -S[6] , V[3] , V[2] ] == {{FCGV["EL"]^2/(2*FCGV["CW"]), 0}},

C[ S[4] , -S[6] , V[3] , V[2] ] == {{((-1/2*I)*FCGV["EL"]^2)/FCGV["CW"], 0}},

C[ -S[3] , V[3] , V[2] ] == {{0, 0}, {0, 0}, {I*gc164, 0}},

C[ S[2] , S[3] , -V[3] , V[2] ] == {{-1/2*FCGV["EL"]^2/FCGV["CW"], 0}},

C[ S[3] , S[1] , -V[3] , V[2] ] == {{((-1/2*I)*FCGV["EL"]^2)/FCGV["CW"], 0}},

C[ S[5] , S[6] , -V[3] , V[2] ] == {{-1/2*FCGV["EL"]^2/FCGV["CW"], 0}},

C[ S[4] , S[6] , -V[3] , V[2] ] == {{((-1/2*I)*FCGV["EL"]^2)/FCGV["CW"], 0}},

C[ S[3] , -V[3] , V[2] ] == {{0, 0}, {0, 0}, {I*gc169, 0}},

C[ V[1] , V[3] , -V[3] , V[2] ] == {{(-2*I)*gc170, 0}, {I*gc170, 0}, {I*gc170, 0}},

C[ S[5] , S[5] , V[2] , V[2] ] == {{((I/2)*FCGV["EL"]^2*(FCGV["CW"]^2 + FCGV["SW"]^2)^2)/(FCGV["CW"]^2*FCGV["SW"]^2), 0}},

C[ S[2] , S[2] , V[2] , V[2] ] == {{((I/2)*FCGV["EL"]^2*(FCGV["CW"]^2 + FCGV["SW"]^2)^2)/(FCGV["CW"]^2*FCGV["SW"]^2), 0}},

C[ S[3] , -S[3] , V[2] , V[2] ] == {{((I/2)*FCGV["EL"]^2*(FCGV["CW"] - FCGV["SW"])^2*(FCGV["CW"] + FCGV["SW"])^2)/(FCGV["CW"]^2*FCGV["SW"]^2), 0}},

C[ S[1] , S[1] , V[2] , V[2] ] == {{((I/2)*FCGV["EL"]^2*(FCGV["CW"]^2 + FCGV["SW"]^2)^2)/(FCGV["CW"]^2*FCGV["SW"]^2), 0}},

C[ S[4] , S[4] , V[2] , V[2] ] == {{((I/2)*FCGV["EL"]^2*(FCGV["CW"]^2 + FCGV["SW"]^2)^2)/(FCGV["CW"]^2*FCGV["SW"]^2), 0}},

C[ S[6] , -S[6] , V[2] , V[2] ] == {{((I/2)*FCGV["EL"]^2*(FCGV["CW"] - FCGV["SW"])^2*(FCGV["CW"] + FCGV["SW"])^2)/(FCGV["CW"]^2*FCGV["SW"]^2), 0}},

C[ S[1] , V[2] , V[2] ] == {{0, 0}, {0, 0}, {I*gc177, 0}},

C[ V[3] , -V[3] , V[2] , V[2] ] == {{(-I)*gc178, 0}, {(-I)*gc178, 0}, {(2*I)*gc178, 0}},

C[ -F[12, {e1x2}] , F[12, {e2x2}] , V[1] ] == {{I*gc179*IndexDelta[e1x2, e2x2], 0}, {I*gc179*IndexDelta[e1x2, e2x2], 0}},

C[ -F[10, {e1x2}] , F[10, {e2x2}] , V[1] ] == {{I*gc180*IndexDelta[e1x2, e2x2], 0}, {I*gc180*IndexDelta[e1x2, e2x2], 0}},

C[ -F[11, {e1x2}] , F[11, {e2x2}] , V[1] ] == {{I*gc181*IndexDelta[e1x2, e2x2], 0}, {I*gc181*IndexDelta[e1x2, e2x2], 0}},

C[ -F[4] , F[4] , V[1] ] == {{I*gc182, 0}, {I*gc182, 0}},

C[ -F[5] , F[5] , V[1] ] == {{I*gc183, 0}, {I*gc183, 0}},

C[ -F[6] , F[6] , V[1] ] == {{I*gc184, 0}, {I*gc184, 0}},

C[ -F[8, {e1x2}] , F[8, {e2x2}] , V[1] ] == {{I*gc185*IndexDelta[e1x2, e2x2], 0}, {I*gc185*IndexDelta[e1x2, e2x2], 0}},

C[ -F[9, {e1x2}] , F[9, {e2x2}] , V[1] ] == {{I*gc186*IndexDelta[e1x2, e2x2], 0}, {I*gc186*IndexDelta[e1x2, e2x2], 0}},

C[ -F[7, {e1x2}] , F[7, {e2x2}] , V[1] ] == {{I*gc187*IndexDelta[e1x2, e2x2], 0}, {I*gc187*IndexDelta[e1x2, e2x2], 0}},

C[ -F[1] , F[4] , V[3] ] == {{I*gc188, 0}, {0, 0}},

C[ -F[2] , F[5] , V[3] ] == {{I*gc189, 0}, {0, 0}},

C[ -F[3] , F[6] , V[3] ] == {{I*gc190, 0}, {0, 0}},

C[ -F[8, {e1x2}] , F[12, {e2x2}] , V[3] ] == {{I*gc191*IndexDelta[e1x2, e2x2], 0}, {0, 0}},

C[ -F[8, {e1x2}] , F[10, {e2x2}] , V[3] ] == {{I*gc192*IndexDelta[e1x2, e2x2], 0}, {0, 0}},

C[ -F[8, {e1x2}] , F[11, {e2x2}] , V[3] ] == {{I*gc193*IndexDelta[e1x2, e2x2], 0}, {0, 0}},

C[ -F[9, {e1x2}] , F[12, {e2x2}] , V[3] ] == {{I*gc194*IndexDelta[e1x2, e2x2], 0}, {0, 0}},

C[ -F[9, {e1x2}] , F[10, {e2x2}] , V[3] ] == {{I*gc195*IndexDelta[e1x2, e2x2], 0}, {0, 0}},

C[ -F[9, {e1x2}] , F[11, {e2x2}] , V[3] ] == {{I*gc196*IndexDelta[e1x2, e2x2], 0}, {0, 0}},

C[ -F[7, {e1x2}] , F[12, {e2x2}] , V[3] ] == {{I*gc197*IndexDelta[e1x2, e2x2], 0}, {0, 0}},

C[ -F[7, {e1x2}] , F[10, {e2x2}] , V[3] ] == {{I*gc198*IndexDelta[e1x2, e2x2], 0}, {0, 0}},

C[ -F[7, {e1x2}] , F[11, {e2x2}] , V[3] ] == {{I*gc199*IndexDelta[e1x2, e2x2], 0}, {0, 0}},

C[ -F[4] , F[1] , -V[3] ] == {{I*gc200, 0}, {0, 0}},

C[ -F[5] , F[2] , -V[3] ] == {{I*gc201, 0}, {0, 0}},

C[ -F[6] , F[3] , -V[3] ] == {{I*gc202, 0}, {0, 0}},

C[ -F[12, {e1x2}] , F[8, {e2x2}] , -V[3] ] == {{I*gc203*IndexDelta[e1x2, e2x2], 0}, {0, 0}},

C[ -F[12, {e1x2}] , F[9, {e2x2}] , -V[3] ] == {{I*gc204*IndexDelta[e1x2, e2x2], 0}, {0, 0}},

C[ -F[12, {e1x2}] , F[7, {e2x2}] , -V[3] ] == {{I*gc205*IndexDelta[e1x2, e2x2], 0}, {0, 0}},

C[ -F[10, {e1x2}] , F[8, {e2x2}] , -V[3] ] == {{I*gc206*IndexDelta[e1x2, e2x2], 0}, {0, 0}},

C[ -F[10, {e1x2}] , F[9, {e2x2}] , -V[3] ] == {{I*gc207*IndexDelta[e1x2, e2x2], 0}, {0, 0}},

C[ -F[10, {e1x2}] , F[7, {e2x2}] , -V[3] ] == {{I*gc208*IndexDelta[e1x2, e2x2], 0}, {0, 0}},

C[ -F[11, {e1x2}] , F[8, {e2x2}] , -V[3] ] == {{I*gc209*IndexDelta[e1x2, e2x2], 0}, {0, 0}},

C[ -F[11, {e1x2}] , F[9, {e2x2}] , -V[3] ] == {{I*gc210*IndexDelta[e1x2, e2x2], 0}, {0, 0}},

C[ -F[11, {e1x2}] , F[7, {e2x2}] , -V[3] ] == {{I*gc211*IndexDelta[e1x2, e2x2], 0}, {0, 0}},

C[ -F[12, {e1x2}] , F[12, {e2x2}] , V[2] ] == {{I*gc212L*IndexDelta[e1x2, e2x2], 0}, {I*gc212R*IndexDelta[e1x2, e2x2], 0}},

C[ -F[10, {e1x2}] , F[10, {e2x2}] , V[2] ] == {{I*gc213L*IndexDelta[e1x2, e2x2], 0}, {I*gc213R*IndexDelta[e1x2, e2x2], 0}},

C[ -F[11, {e1x2}] , F[11, {e2x2}] , V[2] ] == {{I*gc214L*IndexDelta[e1x2, e2x2], 0}, {I*gc214R*IndexDelta[e1x2, e2x2], 0}},

C[ -F[4] , F[4] , V[2] ] == {{I*gc215L, 0}, {I*gc215R, 0}},

C[ -F[5] , F[5] , V[2] ] == {{I*gc216L, 0}, {I*gc216R, 0}},

C[ -F[6] , F[6] , V[2] ] == {{I*gc217L, 0}, {I*gc217R, 0}},

C[ -F[8, {e1x2}] , F[8, {e2x2}] , V[2] ] == {{I*gc218L*IndexDelta[e1x2, e2x2], 0}, {I*gc218R*IndexDelta[e1x2, e2x2], 0}},

C[ -F[9, {e1x2}] , F[9, {e2x2}] , V[2] ] == {{I*gc219L*IndexDelta[e1x2, e2x2], 0}, {I*gc219R*IndexDelta[e1x2, e2x2], 0}},

C[ -F[7, {e1x2}] , F[7, {e2x2}] , V[2] ] == {{I*gc220L*IndexDelta[e1x2, e2x2], 0}, {I*gc220R*IndexDelta[e1x2, e2x2], 0}},

C[ -F[1] , F[1] , V[2] ] == {{I*gc221, 0}, {0, 0}},

C[ -F[2] , F[2] , V[2] ] == {{I*gc222, 0}, {0, 0}},

C[ -F[3] , F[3] , V[2] ] == {{I*gc223, 0}, {0, 0}}

}

(* * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * *)

(* Parameter replacement lists (These lists were created by FeynRules) *)

(* FA Couplings *)

M$FACouplings = {
     gc46 -> -FCGV["EL"],
     gc47 -> -FCGV["EL"],
     gc48 -> GH,
     gc49 -> FCGV["EL"],
     gc50 -> -FCGV["EL"],
     gc52 -> FCGV["EL"],
     gc55 -> -FCGV["EL"],
     gc56 -> -((FCGV["CW"]*FCGV["EL"])/FCGV["SW"]),
     gc58 -> (FCGV["CW"]*FCGV["EL"])/FCGV["SW"],
     gc60 -> -FCGV["EL"],
     gc63 -> FCGV["EL"],
     gc64 -> (FCGV["CW"]*FCGV["EL"])/FCGV["SW"],
     gc66 -> -((FCGV["CW"]*FCGV["EL"])/FCGV["SW"]),
     gc68 -> (FCGV["CW"]*FCGV["EL"])/FCGV["SW"],
     gc70 -> -((FCGV["CW"]*FCGV["EL"])/FCGV["SW"]),
     gc72 -> gstr,
     gc73 -> -gstr,
     gc74 -> -gstr^2,
     gc75 -> -(GH*gstr),
     gc76 -> -(GH*gstr^2),
     gc77L -> -(FCGV["MB"]/v),
     gc77R -> FCGV["MB"]/v,
     gc78 -> -(FCGV["MB"]/v),
     gc79L -> -(FCGV["MD"]/v),
     gc79R -> FCGV["MD"]/v,
     gc80 -> -(FCGV["MD"]/v),
     gc81L -> -(FCGV["MS"]/v),
     gc81R -> FCGV["MS"]/v,
     gc82 -> -(FCGV["MS"]/v),
     gc83L -> -((Sqrt[2]*FCGV["MS"]*Conjugate[CKM2x3])/v),
     gc83R -> (Sqrt[2]*FCGV["MT"]*Conjugate[CKM2x3])/v,
     gc84L -> -((Sqrt[2]*FCGV["MB"]*Conjugate[CKM3x3])/v),
     gc84R -> (Sqrt[2]*FCGV["MT"]*Conjugate[CKM3x3])/v,
     gc85L -> -((Sqrt[2]*FCGV["MD"]*Conjugate[CKM1x3])/v),
     gc85R -> (Sqrt[2]*FCGV["MT"]*Conjugate[CKM1x3])/v,
     gc86L -> -((Sqrt[2]*FCGV["MS"]*Conjugate[CKM2x1])/v),
     gc86R -> (Sqrt[2]*FCGV["MU"]*Conjugate[CKM2x1])/v,
     gc87L -> -((Sqrt[2]*FCGV["MB"]*Conjugate[CKM3x1])/v),
     gc87R -> (Sqrt[2]*FCGV["MU"]*Conjugate[CKM3x1])/v,
     gc88L -> -((Sqrt[2]*FCGV["MD"]*Conjugate[CKM1x1])/v),
     gc88R -> (Sqrt[2]*FCGV["MU"]*Conjugate[CKM1x1])/v,
     gc89L -> -((Sqrt[2]*FCGV["MS"]*Conjugate[CKM2x2])/v),
     gc89R -> (Sqrt[2]*FCGV["MC"]*Conjugate[CKM2x2])/v,
     gc90L -> -((Sqrt[2]*FCGV["MB"]*Conjugate[CKM3x2])/v),
     gc90R -> (Sqrt[2]*FCGV["MC"]*Conjugate[CKM3x2])/v,
     gc91L -> -((Sqrt[2]*FCGV["MD"]*Conjugate[CKM1x2])/v),
     gc91R -> (Sqrt[2]*FCGV["MC"]*Conjugate[CKM1x2])/v,
     gc92L -> -(Me/v),
     gc92R -> Me/v,
     gc93 -> -(Me/v),
     gc94L -> -(FCGV["MM"]/v),
     gc94R -> FCGV["MM"]/v,
     gc95 -> -(FCGV["MM"]/v),
     gc96L -> -(MTA/v),
     gc96R -> MTA/v,
     gc97 -> -(MTA/v),
     gc98 -> -((Sqrt[2]*Me)/v),
     gc99 -> -((Sqrt[2]*FCGV["MM"])/v),
     gc100 -> -((Sqrt[2]*MTA)/v),
     gc101L -> (Sqrt[2]*CKM2x3*FCGV["MT"])/v,
     gc101R -> -((Sqrt[2]*CKM2x3*FCGV["MS"])/v),
     gc102L -> (Sqrt[2]*CKM2x1*FCGV["MU"])/v,
     gc102R -> -((Sqrt[2]*CKM2x1*FCGV["MS"])/v),
     gc103L -> (Sqrt[2]*CKM2x2*FCGV["MC"])/v,
     gc103R -> -((Sqrt[2]*CKM2x2*FCGV["MS"])/v),
     gc104L -> (Sqrt[2]*CKM3x3*FCGV["MT"])/v,
     gc104R -> -((Sqrt[2]*CKM3x3*FCGV["MB"])/v),
     gc105L -> (Sqrt[2]*CKM3x1*FCGV["MU"])/v,
     gc105R -> -((Sqrt[2]*CKM3x1*FCGV["MB"])/v),
     gc106L -> (Sqrt[2]*CKM3x2*FCGV["MC"])/v,
     gc106R -> -((Sqrt[2]*CKM3x2*FCGV["MB"])/v),
     gc107L -> (Sqrt[2]*CKM1x3*FCGV["MT"])/v,
     gc107R -> -((Sqrt[2]*CKM1x3*FCGV["MD"])/v),
     gc108L -> (Sqrt[2]*CKM1x1*FCGV["MU"])/v,
     gc108R -> -((Sqrt[2]*CKM1x1*FCGV["MD"])/v),
     gc109L -> (Sqrt[2]*CKM1x2*FCGV["MC"])/v,
     gc109R -> -((Sqrt[2]*CKM1x2*FCGV["MD"])/v),
     gc110L -> FCGV["MC"]/v,
     gc110R -> -(FCGV["MC"]/v),
     gc111 -> -(FCGV["MC"]/v),
     gc112L -> FCGV["MT"]/v,
     gc112R -> -(FCGV["MT"]/v),
     gc113 -> -(FCGV["MT"]/v),
     gc114L -> FCGV["MU"]/v,
     gc114R -> -(FCGV["MU"]/v),
     gc115 -> -(FCGV["MU"]/v),
     gc116R -> -((Sqrt[2]*Me)/v),
     gc117R -> -((Sqrt[2]*FCGV["MM"])/v),
     gc118R -> -((Sqrt[2]*MTA)/v),
     gc119 -> gstr,
     gc120 -> gstr,
     gc121 -> gstr,
     gc122 -> gstr,
     gc123 -> gstr,
     gc124 -> gstr,
     gc129 -> (FCGV["EL"]^2*v)/(2*FCGV["SW"]),
     gc130 -> FCGV["EL"]/(2*FCGV["SW"]),
     gc131 -> FCGV["EL"]/(2*FCGV["SW"]),
     gc132 -> FCGV["EL"]/(2*FCGV["SW"]),
     gc133 -> -1/2*FCGV["EL"]/FCGV["SW"],
     gc134 -> FCGV["EL"],
     gc139 -> (FCGV["EL"]^2*v)/(2*FCGV["SW"]),
     gc140 -> FCGV["EL"]/(2*FCGV["SW"]),
     gc141 -> FCGV["EL"]/(2*FCGV["SW"]),
     gc142 -> -1/2*FCGV["EL"]/FCGV["SW"],
     gc143 -> FCGV["EL"]/(2*FCGV["SW"]),
     gc150 -> (FCGV["EL"]^2*v)/(2*FCGV["SW"]^2),
     gc151 -> -FCGV["EL"]^2,
     gc152 -> (FCGV["CW"]*FCGV["EL"])/FCGV["SW"],
     gc153 -> FCGV["EL"]^2/FCGV["SW"]^2,
     gc156 -> -1/2*(FCGV["EL"]*(FCGV["CW"]^2 + FCGV["SW"]^2))/(FCGV["CW"]*FCGV["SW"]),
     gc157 -> -1/2*(FCGV["EL"]*(FCGV["CW"]^2 + FCGV["SW"]^2))/(FCGV["CW"]*FCGV["SW"]),
     gc158 -> -1/2*(FCGV["CW"]*FCGV["EL"])/FCGV["SW"] + (FCGV["EL"]*FCGV["SW"])/(2*FCGV["CW"]),
     gc159 -> -1/2*(FCGV["CW"]*FCGV["EL"])/FCGV["SW"] + (FCGV["EL"]*FCGV["SW"])/(2*FCGV["CW"]),
     gc164 -> -1/2*(FCGV["EL"]^2*v)/FCGV["CW"],
     gc169 -> -1/2*(FCGV["EL"]^2*v)/FCGV["CW"],
     gc170 -> (FCGV["CW"]*FCGV["EL"]^2)/FCGV["SW"],
     gc177 -> (FCGV["EL"]^2*(FCGV["CW"]^2 + FCGV["SW"]^2)^2*v)/(2*FCGV["CW"]^2*FCGV["SW"]^2),
     gc178 -> -((FCGV["CW"]^2*FCGV["EL"]^2)/FCGV["SW"]^2),
     gc179 -> -1/3*FCGV["EL"],
     gc180 -> -1/3*FCGV["EL"],
     gc181 -> -1/3*FCGV["EL"],
     gc182 -> -FCGV["EL"],
     gc183 -> -FCGV["EL"],
     gc184 -> -FCGV["EL"],
     gc185 -> (2*FCGV["EL"])/3,
     gc186 -> (2*FCGV["EL"])/3,
     gc187 -> (2*FCGV["EL"])/3,
     gc188 -> FCGV["EL"]/(Sqrt[2]*FCGV["SW"]),
     gc189 -> FCGV["EL"]/(Sqrt[2]*FCGV["SW"]),
     gc190 -> FCGV["EL"]/(Sqrt[2]*FCGV["SW"]),
     gc191 -> (CKM2x3*FCGV["EL"])/(Sqrt[2]*FCGV["SW"]),
     gc192 -> (CKM2x1*FCGV["EL"])/(Sqrt[2]*FCGV["SW"]),
     gc193 -> (CKM2x2*FCGV["EL"])/(Sqrt[2]*FCGV["SW"]),
     gc194 -> (CKM3x3*FCGV["EL"])/(Sqrt[2]*FCGV["SW"]),
     gc195 -> (CKM3x1*FCGV["EL"])/(Sqrt[2]*FCGV["SW"]),
     gc196 -> (CKM3x2*FCGV["EL"])/(Sqrt[2]*FCGV["SW"]),
     gc197 -> (CKM1x3*FCGV["EL"])/(Sqrt[2]*FCGV["SW"]),
     gc198 -> (CKM1x1*FCGV["EL"])/(Sqrt[2]*FCGV["SW"]),
     gc199 -> (CKM1x2*FCGV["EL"])/(Sqrt[2]*FCGV["SW"]),
     gc200 -> FCGV["EL"]/(Sqrt[2]*FCGV["SW"]),
     gc201 -> FCGV["EL"]/(Sqrt[2]*FCGV["SW"]),
     gc202 -> FCGV["EL"]/(Sqrt[2]*FCGV["SW"]),
     gc203 -> (FCGV["EL"]*Conjugate[CKM2x3])/(Sqrt[2]*FCGV["SW"]),
     gc204 -> (FCGV["EL"]*Conjugate[CKM3x3])/(Sqrt[2]*FCGV["SW"]),
     gc205 -> (FCGV["EL"]*Conjugate[CKM1x3])/(Sqrt[2]*FCGV["SW"]),
     gc206 -> (FCGV["EL"]*Conjugate[CKM2x1])/(Sqrt[2]*FCGV["SW"]),
     gc207 -> (FCGV["EL"]*Conjugate[CKM3x1])/(Sqrt[2]*FCGV["SW"]),
     gc208 -> (FCGV["EL"]*Conjugate[CKM1x1])/(Sqrt[2]*FCGV["SW"]),
     gc209 -> (FCGV["EL"]*Conjugate[CKM2x2])/(Sqrt[2]*FCGV["SW"]),
     gc210 -> (FCGV["EL"]*Conjugate[CKM3x2])/(Sqrt[2]*FCGV["SW"]),
     gc211 -> (FCGV["EL"]*Conjugate[CKM1x2])/(Sqrt[2]*FCGV["SW"]),
     gc212L -> -1/6*(FCGV["EL"]*(3*FCGV["CW"]^2 + FCGV["SW"]^2))/(FCGV["CW"]*FCGV["SW"]),
     gc212R -> (FCGV["EL"]*FCGV["SW"])/(3*FCGV["CW"]),
     gc213L -> -1/6*(FCGV["EL"]*(3*FCGV["CW"]^2 + FCGV["SW"]^2))/(FCGV["CW"]*FCGV["SW"]),
     gc213R -> (FCGV["EL"]*FCGV["SW"])/(3*FCGV["CW"]),
     gc214L -> -1/6*(FCGV["EL"]*(3*FCGV["CW"]^2 + FCGV["SW"]^2))/(FCGV["CW"]*FCGV["SW"]),
     gc214R -> (FCGV["EL"]*FCGV["SW"])/(3*FCGV["CW"]),
     gc215L -> -1/2*(FCGV["EL"]*(FCGV["CW"]^2 - FCGV["SW"]^2))/(FCGV["CW"]*FCGV["SW"]),
     gc215R -> (FCGV["EL"]*FCGV["SW"])/FCGV["CW"],
     gc216L -> -1/2*(FCGV["EL"]*(FCGV["CW"]^2 - FCGV["SW"]^2))/(FCGV["CW"]*FCGV["SW"]),
     gc216R -> (FCGV["EL"]*FCGV["SW"])/FCGV["CW"],
     gc217L -> -1/2*(FCGV["EL"]*(FCGV["CW"]^2 - FCGV["SW"]^2))/(FCGV["CW"]*FCGV["SW"]),
     gc217R -> (FCGV["EL"]*FCGV["SW"])/FCGV["CW"],
     gc218L -> (FCGV["CW"]*FCGV["EL"])/(2*FCGV["SW"]) - (FCGV["EL"]*FCGV["SW"])/(6*FCGV["CW"]),
     gc218R -> (-2*FCGV["EL"]*FCGV["SW"])/(3*FCGV["CW"]),
     gc219L -> (FCGV["CW"]*FCGV["EL"])/(2*FCGV["SW"]) - (FCGV["EL"]*FCGV["SW"])/(6*FCGV["CW"]),
     gc219R -> (-2*FCGV["EL"]*FCGV["SW"])/(3*FCGV["CW"]),
     gc220L -> (FCGV["CW"]*FCGV["EL"])/(2*FCGV["SW"]) - (FCGV["EL"]*FCGV["SW"])/(6*FCGV["CW"]),
     gc220R -> (-2*FCGV["EL"]*FCGV["SW"])/(3*FCGV["CW"]),
     gc221 -> (FCGV["EL"]*(FCGV["CW"]^2 + FCGV["SW"]^2))/(2*FCGV["CW"]*FCGV["SW"]),
     gc222 -> (FCGV["EL"]*(FCGV["CW"]^2 + FCGV["SW"]^2))/(2*FCGV["CW"]*FCGV["SW"]),
     gc223 -> (FCGV["EL"]*(FCGV["CW"]^2 + FCGV["SW"]^2))/(2*FCGV["CW"]*FCGV["SW"])};

