///////////////////CODE GENERATED VIA MATHEMATICA///////////////////

#include <cmath>
#include <complex>

namespace DT {
namespace PAR {
std::complex<double> I(0., 1.);
std::complex<double> We1 = 0;
std::complex<double> We2 = 0;
std::complex<double> We3 = 0;
std::complex<double> Wd1 = 0;
std::complex<double> Wd2 = 0;
std::complex<double> Wd3 = 0;
std::complex<double> Wu1 = 0;
std::complex<double> Wu2 = 0;
std::complex<double> Wu3 = 1.51;
std::complex<double> Maux = 1;
std::complex<double> sqrt2 = 1.41421;
std::complex<double> Pi = 3.14159;
std::complex<double> Q = 100;
std::complex<double> alfSMZ = 0.1172;
std::complex<double> aS = 0.119;
std::complex<double> aEWinv = 137.036;
std::complex<double> Gf = 0.0000116639;
std::complex<double> rd;
std::complex<double> Msd[6];
std::complex<double> Msu[6];
std::complex<double> Msv[3];
std::complex<double> Mse[5];
std::complex<double> Mh[6];
std::complex<double> MHm2;
std::complex<double> MZ = 91.187600000000003;
std::complex<double> Mgo;
std::complex<double> MN[5];
std::complex<double> MC[2];
std::complex<double> Me[3];
std::complex<double> Md[3];
std::complex<double> Mu[3];
std::complex<double> Yd[3][3];
std::complex<double> Td[3][3];
std::complex<double> Ye[3][3];
std::complex<double> Te[3][3];
std::complex<double> lam;
std::complex<double> Tlam;
std::complex<double> kap;
std::complex<double> Tk;
std::complex<double> Yu[3][3];
std::complex<double> Tu[3][3];
std::complex<double> eta;
std::complex<double> etaS;
std::complex<double> PhiUL;
std::complex<double> PhiUR;
std::complex<double> vS;
std::complex<double> pG;
std::complex<double> ZD[6][6];
std::complex<double> ZU[6][6];
std::complex<double> ZV[3][3];
std::complex<double> ZE[6][6];
std::complex<double> ZH[6][6];
std::complex<double> ZP[2][2];
std::complex<double> ZN[5][5];
std::complex<double> UM[2][2];
std::complex<double> UP[2][2];
std::complex<double> ZEL[3][4];
std::complex<double> ZER[3][3];
std::complex<double> ZDL[3][3];
std::complex<double> ZDR[3][3];
std::complex<double> ZUL[3][3];
std::complex<double> ZUR[3][3];
std::complex<double> TBeta;
std::complex<double> HPP1;
std::complex<double> HGG1;
std::complex<double> HPP2;
std::complex<double> HGG2;
std::complex<double> HPP3;
std::complex<double> HGG3;
std::complex<double> HPP4;
std::complex<double> HGG4;
std::complex<double> HPP5;
std::complex<double> HGG5;
std::complex<double> HPP6;
std::complex<double> HGG6;
std::complex<double> QCDok;
std::complex<double> g3;
std::complex<double> el;
std::complex<double> MWm;
std::complex<double> TW;
std::complex<double> STW;
std::complex<double> CTW;
std::complex<double> TTW;
std::complex<double> g1;
std::complex<double> g2;
std::complex<double> v;
std::complex<double> vd;
std::complex<double> vu;

std::complex<double> coup1[6];
std::complex<double> coup2[6];
std::complex<double> coup3[6];
std::complex<double> coup4[5];
std::complex<double> coup5[5];
std::complex<double> coup6[6];
std::complex<double> coup7;
std::complex<double> coup8;
std::complex<double> coup9;
std::complex<double> coup10[5];
std::complex<double> coup11[5];
std::complex<double> coup12[6];
std::complex<double> coup13;
std::complex<double> coup14[5];
std::complex<double> coup15[5];
std::complex<double> coup16[6];
std::complex<double> coup17;
std::complex<double> coup18[5];
std::complex<double> coup19[5];
std::complex<double> coup20[6];
std::complex<double> coup21;
std::complex<double> coup22[5];
std::complex<double> coup23[5];
std::complex<double> coup24[6];
std::complex<double> coup25[6];
std::complex<double> coup26;
std::complex<double> coup27[6];
std::complex<double> coup28;
std::complex<double> coup29[6];
std::complex<double> coup30;
std::complex<double> coup31[6];
std::complex<double> coup32[6];
std::complex<double> coup33;
std::complex<double> coup34[6];
std::complex<double> coup35;
std::complex<double> coup36[6];
std::complex<double> coup37[6];
std::complex<double> coup38;
std::complex<double> coup39[6];
std::complex<double> coup40[6];
std::complex<double> coup41;
std::complex<double> coup42[2];
std::complex<double> coup43[2];
std::complex<double> coup44[2];
std::complex<double> coup45[2];
std::complex<double> coup46[6];
std::complex<double> coup47;
std::complex<double> coup48[2];
std::complex<double> coup49[2];
std::complex<double> coup50[6];
std::complex<double> coup51;
std::complex<double> coup52[2];
std::complex<double> coup53[2];
std::complex<double> coup54[6];
std::complex<double> coup55;
std::complex<double> coup56;
std::complex<double> coup57[5];
std::complex<double> coup58[5];
std::complex<double> coup59[5];
std::complex<double> coup60[5];
std::complex<double> coup61[6];
std::complex<double> coup62;
std::complex<double> coup63[6];
std::complex<double> coup64;
std::complex<double> coup65[6];
std::complex<double> coup66;
std::complex<double> coup67[6];
std::complex<double> coup68;
std::complex<double> coup69[6];
std::complex<double> coup70;
std::complex<double> coup71[2];
std::complex<double> coup72[2];
std::complex<double> coup73[2];
std::complex<double> coup74[2];
std::complex<double> coup75[6];
std::complex<double> coup76;
std::complex<double> coup77[6];
std::complex<double> coup78[6];
std::complex<double> coup79[2];
std::complex<double> coup80[2];
std::complex<double> coup81[2];
std::complex<double> coup82[2];
std::complex<double> coup83;
std::complex<double> coup84[3];
std::complex<double> coup85[3];
std::complex<double> coup86[3];
std::complex<double> coup87[3];
std::complex<double> coup88[3];
std::complex<double> coup89[3];
std::complex<double> coup90[6];
std::complex<double> coup91[6];
std::complex<double> coup92;
std::complex<double> coup93;
std::complex<double> coup94[6];
std::complex<double> coup95[6];
std::complex<double> coup96[6];
std::complex<double> coup97[6];
std::complex<double> coup98[6];
std::complex<double> coup99[6];
std::complex<double> coup100[6];
std::complex<double> coup101[6];
std::complex<double> coup102[6];
std::complex<double> coup103[6];
std::complex<double> coup104[6];
std::complex<double> coup105[6];
std::complex<double> coup106[6];
std::complex<double> coup107[6];
std::complex<double> coup108[6];
std::complex<double> coup109[6];
std::complex<double> coup110[6];
std::complex<double> coup111[6];
std::complex<double> coup112;
std::complex<double> coup113;
std::complex<double> coup114[6];
std::complex<double> coup115[6];
std::complex<double> coup116[6];
std::complex<double> coup117[6];
std::complex<double> coup118[6];
std::complex<double> coup119[6];
std::complex<double> coup120[6];
std::complex<double> coup121[6];
std::complex<double> coup122[6];
std::complex<double> coup123[6];
std::complex<double> coup124[6];
std::complex<double> coup125[6];
std::complex<double> coup126[6];
std::complex<double> coup127[6];
std::complex<double> coup128[6];
std::complex<double> coup129[6];
std::complex<double> coup130[6];
std::complex<double> coup131[6];
std::complex<double> coup132;
std::complex<double> coup133;
std::complex<double> coup134[6];
std::complex<double> coup135[6];
std::complex<double> coup136[6];
std::complex<double> coup137[6];
std::complex<double> coup138[6];
std::complex<double> coup139[6];
std::complex<double> coup140[6];
std::complex<double> coup141[6];
std::complex<double> coup142[6];
std::complex<double> coup143[6];
std::complex<double> coup144[6];
std::complex<double> coup145[6];
std::complex<double> coup146[6];
std::complex<double> coup147[6];
std::complex<double> coup148[6];
std::complex<double> coup149[6];

}  // namespace PAR
}  // namespace DT
