///////////////////CODE GENERATED VIA MATHEMATICA///////////////////

#include <cmath>
#include <complex>

namespace DT {
namespace PAR {
std::complex<double> I(0., 1.);
std::complex<double> We1 = 0;
std::complex<double> We2 = 0;
std::complex<double> We3 = 0;
std::complex<double> Wd1 = 0;
std::complex<double> Wd2 = 0;
std::complex<double> Wd3 = 0;
std::complex<double> Wu1 = 0;
std::complex<double> Wu2 = 0;
std::complex<double> Wu3 = 1.51;
std::complex<double> Maux = 1;
std::complex<double> sqrt2 = 1.41421;
std::complex<double> Pi = 3.14159;
std::complex<double> Q = 100;
std::complex<double> alfSMZ = 0.1172;
std::complex<double> aS = 0.119;
std::complex<double> aEWinv = 137.036;
std::complex<double> Gf = 0.0000116639;
std::complex<double> rd;
std::complex<double> Msd[6];
std::complex<double> Msu[6];
std::complex<double> Msv[3];
std::complex<double> Mse[5];
std::complex<double> Mh[6];
std::complex<double> MHm2;
std::complex<double> MZ = 91.187600000000003;
std::complex<double> Mgo;
std::complex<double> MN[5];
std::complex<double> MC[2];
std::complex<double> Me[3];
std::complex<double> Md[3];
std::complex<double> Mu[3];
std::complex<double> Yd[3][3];
std::complex<double> Td[3][3];
std::complex<double> Ye[3][3];
std::complex<double> Te[3][3];
std::complex<double> lam;
std::complex<double> Tlam;
std::complex<double> kap;
std::complex<double> Tk;
std::complex<double> Yu[3][3];
std::complex<double> Tu[3][3];
std::complex<double> eta;
std::complex<double> etaS;
std::complex<double> PhiUL;
std::complex<double> PhiUR;
std::complex<double> vS;
std::complex<double> pG;
std::complex<double> ZD[6][6];
std::complex<double> ZU[6][6];
std::complex<double> ZV[3][3];
std::complex<double> ZE[6][6];
std::complex<double> ZH[6][6];
std::complex<double> ZP[2][2];
std::complex<double> ZN[5][5];
std::complex<double> UM[2][2];
std::complex<double> UP[2][2];
std::complex<double> ZEL[3][4];
std::complex<double> ZER[3][3];
std::complex<double> ZDL[3][3];
std::complex<double> ZDR[3][3];
std::complex<double> ZUL[3][3];
std::complex<double> ZUR[3][3];
std::complex<double> TBeta;
std::complex<double> HPP1;
std::complex<double> HGG1;
std::complex<double> HPP2;
std::complex<double> HGG2;
std::complex<double> HPP3;
std::complex<double> HGG3;
std::complex<double> HPP4;
std::complex<double> HGG4;
std::complex<double> HPP5;
std::complex<double> HGG5;
std::complex<double> HPP6;
std::complex<double> HGG6;
std::complex<double> QCDok;
std::complex<double> g3;
std::complex<double> el;
std::complex<double> MWm;
std::complex<double> TW;
std::complex<double> STW;
std::complex<double> CTW;
std::complex<double> TTW;
std::complex<double> g1;
std::complex<double> g2;
std::complex<double> v;
std::complex<double> vd;
std::complex<double> vu;

std::complex<double> coup1[6];
std::complex<double> coup2[6];
std::complex<double> coup3[6];
std::complex<double> coup4[5];
std::complex<double> coup5[5];
std::complex<double> coup6[6];
std::complex<double> coup7;
std::complex<double> coup8;
std::complex<double> coup9;
std::complex<double> coup10[5];
std::complex<double> coup11[5];
}  // namespace PAR
}  // namespace DT
