///////////////////CODE GENERATED VIA MATHEMATICA///////////////////


#include "../../model.hpp"

double DT::chi0S0Hvm(const double &cos_t, const double &s){
	double t = (s* (MH*MH) +  (Mchi0*Mchi0)*(s +  (MH*MH)) + s* (MS0*MS0) -  (MH*MH)* (MS0*MS0) + cos_t*s*sqrt( (( (MH*MH) - s)*( (MH*MH) - s))/s)*sqrt(( (Mchi0*Mchi0*Mchi0*Mchi0) - 2* (Mchi0*Mchi0)*(s +  (MS0*MS0)) +  (( (MS0*MS0) - s)*( (MS0*MS0) - s)))/s) -  (s*s))/(2.*s);
	double u = -s - t + Mchi0*Mchi0 + MS0*MS0 + MH*MH + 0*0;
	return (4*(-u +  (Mchi0*Mchi0))* (token6*token6)* (token7*token7)* (token8*token8)* (token9*token9))/(3.* (token10*token10)* (( (MS0*MS0) - u)*( (MS0*MS0) - u)));
}
double DT::chi0S0Zvm(const double &cos_t, const double &s){
	double t = (s* (MS0*MS0) + s* (MZ*MZ) -  (MS0*MS0)* (MZ*MZ) +  (Mchi0*Mchi0)*(s +  (MZ*MZ)) + cos_t*s*sqrt(( (Mchi0*Mchi0*Mchi0*Mchi0) - 2* (Mchi0*Mchi0)*(s +  (MS0*MS0)) +  (( (MS0*MS0) - s)*( (MS0*MS0) - s)))/s)*sqrt( (( (MZ*MZ) - s)*( (MZ*MZ) - s))/s) -  (s*s))/(2.*s);
	double u = -s - t + Mchi0*Mchi0 + MS0*MS0 + MZ*MZ + 0*0;
	return (4*((-t +  (Mchi0*Mchi0))*(t*u + s* (Mchi0*Mchi0) - (s + t + u)* (MS0*MS0) +  (MS0*MS0*MS0*MS0)) + (t*(-s + t + u - 2* (MS0*MS0)) +  (Mchi0*Mchi0)*(s - 5*t - u + 6* (MS0*MS0)))* (MZ*MZ) - (t +  (Mchi0*Mchi0) - 2* (MS0*MS0))* (MZ*MZ*MZ*MZ))* (token11*token11)* (token19*token19)* (token59*token59)* (token6*token6))/(3.* (MZ*MZ)* (( (Mchi0*Mchi0) - t)*( (Mchi0*Mchi0) - t))* (token10*token10)* (token17*token17)* (token18*token18)* (token4*token4)) + (16*(2*s*(-t +  (Mchi0*Mchi0))* (MZ*MZ) + 2*(s + t + u - 2* (Mchi0*Mchi0))* (MZ*MZ*MZ*MZ) - 2* (MZ*MZ*MZ*MZ*MZ*MZ) + (-u +  (Mchi0*Mchi0))* (s*s))* (token11*token11)* (token3*token3)* (token59*token59)* (token6*token6))/(3.* (MZ*MZ)* (s*s)* (token10*token10)* (token17*token17)* (token18*token18)* (token4*token4)) - (8*token19*token3* (token11*token11)* (token59*token59)* (token6*token6)*(-4*(t +  (Mchi0*Mchi0) -  (MS0*MS0))* (MZ*MZ*MZ*MZ) +  (MZ*MZ)*(s*(t + u) - 4*(t + u)*(-t +  (MS0*MS0)) + 2* (Mchi0*Mchi0)*(s - 4*t + 4* (MS0*MS0)) -  (s*s)) + s*( (Mchi0*Mchi0)*(s + t + u - 2* (MS0*MS0)) + (-s + t + u)* (MS0*MS0) +  (s*s) -  (t*t) -  (u*u))))/(3.*s*(-t +  (Mchi0*Mchi0))* (MZ*MZ)* (token10*token10)* (token17*token17)* (token18*token18)* (token4*token4));
}
double DT::chi0S0Wmu(const double &cos_t, const double &s){
	double t = (s* (MMU*MMU) + s* (MS0*MS0) +  (MMU*MMU)* (MS0*MS0) + s* (MW*MW) -  (MS0*MS0)* (MW*MW) +  (Mchi0*Mchi0)*(s -  (MMU*MMU) +  (MW*MW)) + cos_t*s*sqrt(( (Mchi0*Mchi0*Mchi0*Mchi0) - 2* (Mchi0*Mchi0)*(s +  (MS0*MS0)) +  (( (MS0*MS0) - s)*( (MS0*MS0) - s)))/s)*sqrt(( (MMU*MMU*MMU*MMU) - 2* (MMU*MMU)*(s +  (MW*MW)) +  (( (MW*MW) - s)*( (MW*MW) - s)))/s) -  (s*s))/(2.*s);
	double u = -s - t + Mchi0*Mchi0 + MS0*MS0 + MW*MW + MMU*MMU;
	return (8*((-s +  (MMU*MMU))*(s*u - (s + t + u)* (MMU*MMU) +  (Mchi0*Mchi0)*(-s + 2* (MMU*MMU)) +  (MMU*MMU*MMU*MMU)) + (-2*s*t - (s + t + u)* (MMU*MMU) + 2* (Mchi0*Mchi0)*(s +  (MMU*MMU)) + 2* (MMU*MMU*MMU*MMU))* (MW*MW) + (2*(s + t + u) - 4* (Mchi0*Mchi0) -  (MMU*MMU))* (MW*MW*MW*MW) - 2* (MW*MW*MW*MW*MW*MW))* (token1*token1)* (token11*token11)* (token6*token6))/( (MW*MW)* (s*s)* (token18*token18)* (token4*token4)) - (2*((-t +  (Mchi0*Mchi0))*(-(t*u) - (s + u)* (MMU*MMU) +  (MchiM*MchiM)*(-s +  (MMU*MMU)) +  (MMU*MMU*MMU*MMU) + s* (MS0*MS0) + t* (MS0*MS0) + u* (MS0*MS0) -  (MS0*MS0*MS0*MS0)) + (-((s + t - u)* (MchiM*MchiM)) - t*(-s + t + u + 2* (MMU*MMU) - 2* (MS0*MS0)) + 6*Mchi0*MchiM*(t +  (MMU*MMU) -  (MS0*MS0)))* (MW*MW) + (t +  (MchiM*MchiM) + 2* (MMU*MMU) - 2* (MS0*MS0))* (MW*MW*MW*MW))* (token11*token11)* (token19*token19)* (token6*token6))/( (MW*MW)* (( (MchiM*MchiM) - t)*( (MchiM*MchiM) - t))* (token18*token18)* (token4*token4)) + (4*token1*token19* (token11*token11)* (token6*token6)*((s - t - u)* (MMU*MMU*MMU*MMU) + s*t* (MS0*MS0) + s*u* (MS0*MS0) + s*t* (MW*MW) + s*u* (MW*MW) + 4*t*u* (MW*MW) - 4*t* (MS0*MS0)* (MW*MW) - 4*u* (MS0*MS0)* (MW*MW) - 4*t* (MW*MW*MW*MW) + 4* (MS0*MS0)* (MW*MW*MW*MW) +  (Mchi0*Mchi0)*(s*t + s*u +  (MMU*MMU)*(s - t - 3*u + 4* (MS0*MS0)) - 8*t* (MW*MW) +  (MS0*MS0)*(-2*s + 8* (MW*MW)) -  (s*s)) -  (MS0*MS0)* (s*s) -  (MW*MW)* (s*s) + 2*Mchi0*MchiM*( (MMU*MMU*MMU*MMU) + s* (MW*MW) +  (MMU*MMU)*(-2*s +  (MW*MW)) - 2* (MW*MW*MW*MW) +  (s*s)) +  (s*s*s) - s* (t*t) + 4* (MW*MW)* (t*t) - s* (u*u) +  (MMU*MMU)*(s*t + s*u + 2*t*u - (3*s + 5*t + u)* (MW*MW) +  (MS0*MS0)*(s - 3*t - u + 8* (MW*MW)) - 2* (s*s) +  (t*t) +  (u*u))))/(s*(-t +  (MchiM*MchiM))* (MW*MW)* (token18*token18)* (token4*token4));
}
