///////////////////CODE GENERATED VIA MATHEMATICA///////////////////


#pragma once

#include <cmath>

namespace DT{
	extern double aEWM1;
	extern double Gf;
	extern double aS;
	extern double ymdo;
	extern double ymup;
	extern double yms;
	extern double ymc;
	extern double ymb;
	extern double ymt;
	extern double yme;
	extern double ymm;
	extern double ymtau;
	extern double cabi;
	extern double MW;
	extern double svev;
	extern double alpha;
	extern double MA1;
	extern double MS1;
	extern double MH;
	extern double GG;
	extern double MZ;
	extern double Me;
	extern double MMU;
	extern double MTA;
	extern double MU;
	extern double MC;
	extern double MT;
	extern double MD;
	extern double MS;
	extern double MB;
	extern double WZ;
	extern double WW;
	extern double WT;
	extern double WH;
	extern double WS1;
	extern double WA1;
	extern double E;
	extern double Pi;
	extern double aEW;
	extern double sw2;
	extern double EE;
	extern double cw;
	extern double sw;
	extern double gw;
	extern double g1;
	extern double vev;
	extern double delta2;
	extern double lam;
	extern double muH;
	extern double ye;
	extern double ym;
	extern double ytau;
	extern double yup;
	extern double yc;
	extern double yt;
	extern double ydo;
	extern double ys;
	extern double yb;
	extern double CKM1x1;
	extern double CKM1x2;
	extern double CKM1x3;
	extern double CKM2x1;
	extern double CKM2x2;
	extern double CKM2x3;
	extern double CKM3x1;
	extern double CKM3x2;
	extern double CKM3x3;
	extern double d2;
	extern double b1;
	extern double b2;
	extern double I1a11;
	extern double I1a12;
	extern double I1a13;
	extern double I1a21;
	extern double I1a22;
	extern double I1a23;
	extern double I1a31;
	extern double I1a32;
	extern double I1a33;
	extern double I2a11;
	extern double I2a12;
	extern double I2a13;
	extern double I2a21;
	extern double I2a22;
	extern double I2a23;
	extern double I2a31;
	extern double I2a32;
	extern double I2a33;
	extern double I3a11;
	extern double I3a12;
	extern double I3a13;
	extern double I3a21;
	extern double I3a22;
	extern double I3a23;
	extern double I3a31;
	extern double I3a32;
	extern double I3a33;
	extern double I4a11;
	extern double I4a12;
	extern double I4a13;
	extern double I4a21;
	extern double I4a22;
	extern double I4a23;
	extern double I4a31;
	extern double I4a32;
	extern double I4a33;
	extern double token1;
	extern double token2;
	extern double token3;
	extern double token4;
	extern double token5;
	extern double token6;
	extern double token7;
	extern double token8;
	extern double token9;
	extern double token10;
	extern double token11;
	extern double token12;
	extern double token13;
	extern double token14;
	extern double token15;
	extern double token16;
	extern double token17;
	extern double token18;
	extern double token19;
	extern double token20;
	extern double token21;
	extern double token22;
	extern double token23;
	extern double token24;
	extern double token25;
	extern double token26;
	extern double token27;
	extern double token28;
	extern double token29;
	extern double token30;
	extern double token31;
	extern double token32;
	extern double token33;
	extern double token34;
	extern double token35;
	extern double token36;
	extern double token37;
	extern double token38;
	extern double token39;
	extern double token40;
	extern double EL;
	extern double ee;
	extern double gs;
	extern double G;
	extern double FAGS;

	double A1A1HH(const double &cos_t, const double &s);
	double A1A1HS1(const double &cos_t, const double &s);
	double A1A1S1S1(const double &cos_t, const double &s);
	double A1A1ZZ(const double &cos_t, const double &s);
	double A1A1wW(const double &cos_t, const double &s);
	double A1A1Ee(const double &cos_t, const double &s);
	double A1A1MUmu(const double &cos_t, const double &s);
	double A1A1TAta(const double &cos_t, const double &s);
	double A1A1Uu(const double &cos_t, const double &s);
	double A1A1Cc(const double &cos_t, const double &s);
	double A1A1Tt(const double &cos_t, const double &s);
	double A1A1Dd(const double &cos_t, const double &s);
	double A1A1Ss(const double &cos_t, const double &s);
	double A1A1Bb(const double &cos_t, const double &s);
	double A1A1HHfl(const double &cos_t, const double &s);
	double A1A1HS1fl(const double &cos_t, const double &s);
	double A1A1S1S1fl(const double &cos_t, const double &s);
	double A1A1ZZfl(const double &cos_t, const double &s);
	double A1A1wWfl(const double &cos_t, const double &s);
	double A1A1Eefl(const double &cos_t, const double &s);
	double A1A1MUmufl(const double &cos_t, const double &s);
	double A1A1TAtafl(const double &cos_t, const double &s);
	double A1A1Uufl(const double &cos_t, const double &s);
	double A1A1Ccfl(const double &cos_t, const double &s);
	double A1A1Ttfl(const double &cos_t, const double &s);
	double A1A1Ddfl(const double &cos_t, const double &s);
	double A1A1Ssfl(const double &cos_t, const double &s);
	double A1A1Bbfl(const double &cos_t, const double &s);
	double A1A1(const double &cos_t, const double &s);
	double wHHH();
	double wHHS1();
	double wHS1S1();
	double wHA1A1();
	double wHZZ();
	double wHwW();
	double wHEe();
	double wHMUmu();
	double wHTAta();
	double wHUu();
	double wHCc();
	double wHTt();
	double wHDd();
	double wHSs();
	double wHBb();
	double wS1HH();
	double wS1HS1();
	double wS1S1S1();
	double wS1A1A1();
	double wS1ZZ();
	double wS1wW();
	double wS1Ee();
	double wS1MUmu();
	double wS1TAta();
	double wS1Uu();
	double wS1Cc();
	double wS1Tt();
	double wS1Dd();
	double wS1Ss();
	double wS1Bb();
	double wwH(const double QCDaS);
	double wwS1(const double QCDaS);
}
