///////////////////CODE GENERATED VIA MATHEMATICA///////////////////

#pragma once

#include <cmath>
#include <complex>

namespace DT
{
	namespace PAR
	{
		extern double aEWM1;
		extern double Gf;
		extern double aS;
		extern double ymdo;
		extern double ymup;
		extern double yms;
		extern double ymc;
		extern double ymb;
		extern double ymt;
		extern double yme;
		extern double ymm;
		extern double ymtau;
		extern double cabi;
		extern double MW;
		extern double svev;
		extern double alpha;
		extern double MA1;
		extern double MS1;
		extern double MH;
		extern double GG;
		extern double MZ;
		extern double Me;
		extern double MMU;
		extern double MTA;
		extern double MU;
		extern double MC;
		extern double MT;
		extern double MD;
		extern double MS;
		extern double MB;
		extern double WZ;
		extern double WW;
		extern double WT;
		extern double WH;
		extern double WS1;
		extern double WA1;
		extern double E;
		extern double Pi;
		extern double aEW;
		extern double sw2;
		extern double EE;
		extern double cw;
		extern double sw;
		extern double gw;
		extern double g1;
		extern double vev;
		extern double delta2;
		extern double lam;
		extern double muH;
		extern double ye;
		extern double ym;
		extern double ytau;
		extern double yup;
		extern double yc;
		extern double yt;
		extern double ydo;
		extern double ys;
		extern double yb;
		extern double CKM1x1;
		extern double CKM1x2;
		extern double CKM1x3;
		extern double CKM2x1;
		extern double CKM2x2;
		extern double CKM2x3;
		extern double CKM3x1;
		extern double CKM3x2;
		extern double CKM3x3;
		extern double d2;
		extern double b1;
		extern double b2;
		extern double I1a11;
		extern double I1a12;
		extern double I1a13;
		extern double I1a21;
		extern double I1a22;
		extern double I1a23;
		extern double I1a31;
		extern double I1a32;
		extern double I1a33;
		extern double I2a11;
		extern double I2a12;
		extern double I2a13;
		extern double I2a21;
		extern double I2a22;
		extern double I2a23;
		extern double I2a31;
		extern double I2a32;
		extern double I2a33;
		extern double I3a11;
		extern double I3a12;
		extern double I3a13;
		extern double I3a21;
		extern double I3a22;
		extern double I3a23;
		extern double I3a31;
		extern double I3a32;
		extern double I3a33;
		extern double I4a11;
		extern double I4a12;
		extern double I4a13;
		extern double I4a21;
		extern double I4a22;
		extern double I4a23;
		extern double I4a31;
		extern double I4a32;
		extern double I4a33;
		extern double token1;
		extern double token2;
		extern double token3;
		extern double token4;
		extern double token5;
		extern double token6;
		extern double token7;
		extern double token8;
		extern double token9;
		extern double token10;
		extern double token11;
		extern double token12;
		extern double token13;
		extern double token14;
		extern double token15;
		extern double token16;
		extern double token17;
		extern double token18;
		extern double token19;
		extern double token20;
		extern double token21;
		extern double token22;
		extern double token23;
		extern double token24;
		extern double token25;
		extern double token26;
		extern double token27;
		extern double token28;
		extern double token29;
		extern double token30;
		extern double token31;
		extern double token32;
		extern double token33;
		extern double token34;
		extern double token35;
		extern double token36;
		extern double token37;
		extern double token38;
		extern double token39;

		extern std::complex<double> token40;
		extern std::complex<double> token41;
		extern std::complex<double> token42;
		extern std::complex<double> token43;
		extern std::complex<double> token44;
		extern std::complex<double> token45;
		extern std::complex<double> token46;
		extern std::complex<double> token47;
		extern std::complex<double> token48;
		extern std::complex<double> token49;
		extern std::complex<double> token50;
		extern std::complex<double> token51;
		extern std::complex<double> token52;
		extern std::complex<double> token53;
		extern std::complex<double> token54;
		extern std::complex<double> token55;
		extern std::complex<double> token56;
		extern std::complex<double> token57;
		extern std::complex<double> token58;
		extern std::complex<double> token59;
		extern std::complex<double> token60;
		extern std::complex<double> token61;
		extern std::complex<double> token62;
		extern std::complex<double> token63;
		extern std::complex<double> token64;
		extern std::complex<double> token65;
		extern std::complex<double> token66;
		extern std::complex<double> token67;
		extern std::complex<double> token68;
		extern std::complex<double> token69;
		extern std::complex<double> token70;
		extern std::complex<double> token71;
		extern std::complex<double> token72;
		extern std::complex<double> token73;
		extern std::complex<double> token74;
		extern std::complex<double> token75;
		extern std::complex<double> token76;
		extern std::complex<double> token77;
		extern std::complex<double> token78;
		extern std::complex<double> token79;
		extern std::complex<double> token80;
		extern std::complex<double> token81;
		extern std::complex<double> token82;
		extern std::complex<double> token83;
		extern std::complex<double> token84;
		extern std::complex<double> token85;
		extern std::complex<double> token86;
		extern std::complex<double> token87;
		extern std::complex<double> token88;
		extern std::complex<double> token89;
		extern std::complex<double> token90;
		extern std::complex<double> token91;
		extern std::complex<double> token92;
		extern std::complex<double> token93;
		extern std::complex<double> token94;
		extern std::complex<double> token95;
		extern std::complex<double> token96;
		extern std::complex<double> token97;
		extern std::complex<double> token98;
		extern std::complex<double> token99;
		extern std::complex<double> token100;
		extern std::complex<double> token101;
		extern std::complex<double> token102;
		extern std::complex<double> token103;
		extern std::complex<double> token104;
		extern std::complex<double> token105;
		extern std::complex<double> token106;
		extern std::complex<double> token107;
		extern std::complex<double> token108;
		extern std::complex<double> token109;
		extern std::complex<double> token110;
		extern std::complex<double> token111;
		extern std::complex<double> token112;
		extern std::complex<double> token113;
		extern std::complex<double> token114;
		extern std::complex<double> token115;
		extern std::complex<double> token116;
		extern std::complex<double> token117;
		extern std::complex<double> token118;
		extern std::complex<double> token119;
		extern std::complex<double> token120;
		extern std::complex<double> token121;
		extern std::complex<double> token122;
		extern std::complex<double> token123;
		extern std::complex<double> token124;
		extern std::complex<double> token125;
		extern std::complex<double> token126;
		extern std::complex<double> token127;
		extern std::complex<double> token128;
		extern std::complex<double> token129;
		extern std::complex<double> token130;
		extern std::complex<double> token131;
		extern std::complex<double> token132;
		extern std::complex<double> token133;
		extern std::complex<double> token134;
		extern std::complex<double> token135;
		extern std::complex<double> token136;
		extern std::complex<double> token137;
		extern std::complex<double> token138;
		extern std::complex<double> token139;
		extern std::complex<double> token140;
		extern std::complex<double> token141;
		extern std::complex<double> token142;
		extern std::complex<double> token143;
		extern std::complex<double> token144;
		extern std::complex<double> token145;
		extern std::complex<double> token146;
		extern std::complex<double> token147;
		extern std::complex<double> token148;
		extern std::complex<double> token149;
		extern std::complex<double> token150;
		extern std::complex<double> token151;
		extern std::complex<double> token152;
		extern std::complex<double> token153;
		extern std::complex<double> token154;
		extern std::complex<double> token155;
		extern std::complex<double> token156;
		extern std::complex<double> token157;
		extern std::complex<double> token158;
		extern std::complex<double> token159;
		extern std::complex<double> token160;
		extern std::complex<double> token161;
		extern std::complex<double> token162;
		extern std::complex<double> token163;
		extern std::complex<double> token164;
		extern std::complex<double> token165;
		extern std::complex<double> token166;
		extern std::complex<double> token167;
		extern std::complex<double> token168;
		extern std::complex<double> token169;
		extern std::complex<double> token170;
		extern std::complex<double> token171;
		extern std::complex<double> token172;
		extern std::complex<double> token173;
		extern std::complex<double> token174;
		extern std::complex<double> token175;
		extern std::complex<double> token176;
		extern std::complex<double> token177;
		extern std::complex<double> token178;
		extern std::complex<double> token179;
		extern std::complex<double> token180;
		extern std::complex<double> token181;
		extern std::complex<double> token182;
		extern std::complex<double> token183;
		extern std::complex<double> token184;
		extern std::complex<double> token185;
		extern std::complex<double> token186;
		extern std::complex<double> token187;
		extern std::complex<double> token188;
		extern std::complex<double> token189;
		extern std::complex<double> token190;
		extern std::complex<double> token191;
		extern std::complex<double> token192;
		extern std::complex<double> token193;
		extern std::complex<double> token194;
		extern std::complex<double> token195;
		extern std::complex<double> token196;
		extern std::complex<double> token197;
		extern std::complex<double> token198;
		extern std::complex<double> token199;
		extern std::complex<double> token200;
		extern std::complex<double> token201;
		extern std::complex<double> token202;
		extern std::complex<double> token203;
		extern std::complex<double> token204;
		extern std::complex<double> token205;
		extern std::complex<double> token206;
		extern std::complex<double> token207;
		extern std::complex<double> token208;
		extern std::complex<double> token209;
		extern std::complex<double> token210;
		extern std::complex<double> token211;
		extern std::complex<double> token212;
		extern std::complex<double> token213;
		extern std::complex<double> token214;
		extern std::complex<double> token215;
		extern std::complex<double> token216;
		extern std::complex<double> token217;
		extern std::complex<double> token218;
		extern std::complex<double> token219;
		extern std::complex<double> token220;
		extern std::complex<double> token221;
		extern std::complex<double> token222;
		extern std::complex<double> token223;
		extern std::complex<double> token224;
		extern std::complex<double> token225;
		extern std::complex<double> token226;
		extern std::complex<double> token227;
		extern std::complex<double> token228;
		extern std::complex<double> token229;
		extern std::complex<double> token230;
		extern std::complex<double> token231;
		extern std::complex<double> token232;
		extern std::complex<double> token233;
		extern std::complex<double> token234;
		extern std::complex<double> token235;
		extern std::complex<double> token236;
		extern std::complex<double> token237;
		extern std::complex<double> token238;
		extern std::complex<double> token239;
		extern std::complex<double> token240;
		extern std::complex<double> token241;
		extern std::complex<double> token242;
		extern std::complex<double> token243;
		extern std::complex<double> token244;
		extern std::complex<double> token245;
		extern std::complex<double> token246;
		extern std::complex<double> token247;
		extern std::complex<double> token248;
		extern std::complex<double> token249;
		extern std::complex<double> token250;
		extern std::complex<double> token251;
		extern std::complex<double> token252;
		extern std::complex<double> token253;
		extern std::complex<double> token254;
		extern std::complex<double> token255;
		extern std::complex<double> token256;
		extern std::complex<double> token257;
		extern std::complex<double> token258;
		extern std::complex<double> token259;
		extern std::complex<double> token260;
		extern std::complex<double> token261;
		extern std::complex<double> token262;
		extern std::complex<double> token263;
		extern std::complex<double> token264;
		extern std::complex<double> token265;
		extern std::complex<double> token266;
		extern std::complex<double> token267;
		extern std::complex<double> token268;
		extern std::complex<double> token269;
		extern std::complex<double> token270;
		extern std::complex<double> token271;
		extern std::complex<double> token272;
		extern std::complex<double> token273;
		extern std::complex<double> token274;
		extern std::complex<double> token275;
		extern std::complex<double> token276;
		extern std::complex<double> token277;
		extern std::complex<double> token278;
		extern std::complex<double> token279;
		extern std::complex<double> token280;
		extern std::complex<double> token281;
		extern std::complex<double> token282;
		extern std::complex<double> token283;
		extern std::complex<double> token284;
		extern std::complex<double> token285;
		extern std::complex<double> token286;
		extern std::complex<double> token287;
		extern std::complex<double> token288;
		extern std::complex<double> token289;
		extern std::complex<double> token290;
		extern std::complex<double> token291;
		extern std::complex<double> token292;
		extern std::complex<double> token293;
		extern std::complex<double> token294;
		extern std::complex<double> token295;
		extern std::complex<double> token296;
		extern std::complex<double> token297;
		extern std::complex<double> token298;
		extern std::complex<double> token299;
		extern std::complex<double> token300;
		extern std::complex<double> token301;
		extern std::complex<double> token302;
		extern std::complex<double> token303;
		extern std::complex<double> token304;
		extern std::complex<double> token305;
		extern std::complex<double> token306;
		extern std::complex<double> token307;
		extern std::complex<double> token308;
		extern std::complex<double> token309;
		extern std::complex<double> token310;
		extern std::complex<double> token311;
		extern std::complex<double> token312;
		extern std::complex<double> token313;
		extern std::complex<double> token314;
		extern std::complex<double> token315;
		extern std::complex<double> token316;
		extern std::complex<double> token317;
		extern std::complex<double> token318;
		extern std::complex<double> token319;
		extern std::complex<double> token320;
		extern std::complex<double> token321;
		extern std::complex<double> token322;
		extern std::complex<double> token323;
		extern std::complex<double> token324;
		extern std::complex<double> token325;
		extern std::complex<double> token326;
		extern std::complex<double> token327;
		extern std::complex<double> token328;
		extern std::complex<double> token329;
		extern std::complex<double> token330;
		extern std::complex<double> token331;
		extern std::complex<double> token332;
		extern std::complex<double> token333;
		extern std::complex<double> token334;
		extern std::complex<double> token335;
		extern std::complex<double> token336;
		extern std::complex<double> token337;
		extern std::complex<double> token338;
		extern std::complex<double> token339;
		extern std::complex<double> token340;
		extern std::complex<double> token341;
		extern std::complex<double> token342;
		extern std::complex<double> token343;
		extern std::complex<double> token344;
		extern std::complex<double> token345;
		extern std::complex<double> token346;
		extern std::complex<double> token347;
		extern std::complex<double> token348;
		extern std::complex<double> token349;
		extern std::complex<double> token350;
		extern std::complex<double> token351;
		extern std::complex<double> token352;
		extern std::complex<double> token353;
		extern std::complex<double> token354;
		extern std::complex<double> token355;
		extern std::complex<double> token356;
		extern std::complex<double> token357;
		extern std::complex<double> token358;
		extern std::complex<double> token359;
		extern std::complex<double> token360;
		extern std::complex<double> token361;
		extern std::complex<double> token362;
		extern std::complex<double> token363;
		extern std::complex<double> token364;
		extern std::complex<double> token365;
		extern std::complex<double> token366;
		extern std::complex<double> token367;
		extern std::complex<double> token368;
		extern std::complex<double> token369;
		extern std::complex<double> token370;
		extern std::complex<double> token371;
		extern std::complex<double> token372;
		extern std::complex<double> token373;
		extern std::complex<double> token374;
		extern std::complex<double> token375;
		extern std::complex<double> token376;
		extern std::complex<double> token377;
		extern std::complex<double> token378;
		extern std::complex<double> token379;

		extern double EL;
		extern double ee;
		extern double gs;
		extern double G;
		extern double FAGS;
	}

	extern bool qcd;

	extern std::complex<double> CT_vev;
	extern std::complex<double> CT_Ze;
	extern std::complex<double> CT_Ze0;
	extern std::complex<double> CT_alpha;
	extern std::complex<double> CT_M_A1;
	extern std::complex<double> CT_M_b;
	extern std::complex<double> CT_M_t;
	extern std::complex<double> CT_M_W;
	extern std::complex<double> CT_M_Z;
	extern std::complex<double> CT_M_TAU;
	extern std::complex<double> CT_M_H;
	extern std::complex<double> CT_M_S1;
	extern std::complex<double> CT_svev;
	extern std::complex<double> CT_svev_OS_H;
	extern std::complex<double> CT_svev_OS_S1;
	extern std::complex<double> CT_svev_ZEM_H;
	extern std::complex<double> CT_svev_ZEM_S1;
	extern std::complex<double> CT_svev_ZEMPT_H;
	extern std::complex<double> CT_svev_ZEMPT_S1;
	extern std::complex<double> CT_WF_A1;
	extern std::complex<double> CT_WF_b_L;
	extern std::complex<double> CT_WF_b_R;
	extern std::complex<double> CT_WF_t_L;
	extern std::complex<double> CT_WF_t_R;
	extern std::complex<double> CT_WF_W;
	extern std::complex<double> CT_WF_ZZ;
	extern std::complex<double> CT_WF_ZA;
	extern std::complex<double> CT_WF_AZ;
	extern std::complex<double> CT_WF_AA;
	extern std::complex<double> CT_WF_TAU_L;
	extern std::complex<double> CT_WF_TAU_R;
	extern std::complex<double> CT_WF_HH;
	extern std::complex<double> CT_WF_HS1;
	extern std::complex<double> CT_WF_S1H;
	extern std::complex<double> CT_WF_S1S1;

	double A1A1HH(const double &cos_t, const double &s);
	double A1A1HS1(const double &cos_t, const double &s);
	double A1A1S1S1(const double &cos_t, const double &s);
	double A1A1ZZ(const double &cos_t, const double &s);
	double A1A1wW(const double &cos_t, const double &s);
	double A1A1Ee(const double &cos_t, const double &s);
	double A1A1MUmu(const double &cos_t, const double &s);
	double A1A1TAta(const double &cos_t, const double &s);
	double A1A1Uu(const double &cos_t, const double &s);
	double A1A1Cc(const double &cos_t, const double &s);
	double A1A1Tt(const double &cos_t, const double &s);
	double A1A1Dd(const double &cos_t, const double &s);
	double A1A1Ss(const double &cos_t, const double &s);
	double A1A1Bb(const double &cos_t, const double &s);
	double A1A1HHfl(const double &cos_t, const double &s);
	double A1A1HS1fl(const double &cos_t, const double &s);
	double A1A1S1S1fl(const double &cos_t, const double &s);
	double A1A1ZZfl(const double &cos_t, const double &s);
	double A1A1wWfl(const double &cos_t, const double &s);
	double A1A1Eefl(const double &cos_t, const double &s);
	double A1A1MUmufl(const double &cos_t, const double &s);
	double A1A1TAtafl(const double &cos_t, const double &s);
	double A1A1Uufl(const double &cos_t, const double &s);
	double A1A1Ccfl(const double &cos_t, const double &s);
	double A1A1Ttfl(const double &cos_t, const double &s);
	double A1A1Ddfl(const double &cos_t, const double &s);
	double A1A1Ssfl(const double &cos_t, const double &s);
	double A1A1Bbfl(const double &cos_t, const double &s);
	double wHHH();
	double wHHS1();
	double wHS1S1();
	double wHA1A1();
	double wHZZ();
	double wHwW();
	double wHEe();
	double wHMUmu();
	double wHTAta();
	double wHUu();
	double wHCc();
	double wHTt();
	double wHDd();
	double wHSs();
	double wHBb();
	double wS1HH();
	double wS1HS1();
	double wS1S1S1();
	double wS1A1A1();
	double wS1ZZ();
	double wS1wW();
	double wS1Ee();
	double wS1MUmu();
	double wS1TAta();
	double wS1Uu();
	double wS1Cc();
	double wS1Tt();
	double wS1Dd();
	double wS1Ss();
	double wS1Bb();
	double wwH(const double QCDaS);
	double wwS1(const double QCDaS);

	std::complex<double> A1A1HHTree(const double &cos_t, const double &s);
	std::complex<double> A1A1HH1Loop(const double &cos_t, const double &s);
	std::complex<double> A1A1HHCT(const double &cos_t, const double &s);
	double A1A1HHNLO(const double &cos_t, const double &s);

	std::complex<double> A1A1S1S1Tree(const double &cos_t, const double &s);
	std::complex<double> A1A1S1S11Loop(const double &cos_t, const double &s);
	std::complex<double> A1A1S1S1CT(const double &cos_t, const double &s);
	double A1A1S1S1NLO(const double &cos_t, const double &s);

	std::complex<double> A1A1HS1Tree(const double &cos_t, const double &s);
	std::complex<double> A1A1HS11Loop(const double &cos_t, const double &s);
	std::complex<double> A1A1HS1CT(const double &cos_t, const double &s);
	double A1A1HS1NLO(const double &cos_t, const double &s);

	std::complex<double> A1A1wWTree(const double &cos_t, const double &s);
	std::complex<double> A1A1wWTreeConj(const double &cos_t, const double &s);
	std::complex<double> A1A1wW1Loop(const double &cos_t, const double &s);
	std::complex<double> A1A1wWSoft(const double &cos_t, const double &s);
	std::complex<double> A1A1wWCT(const double &cos_t, const double &s);
	double A1A1wWNLO(const double &cos_t, const double &s);

	std::complex<double> A1A1ZZTree(const double &cos_t, const double &s);
	std::complex<double> A1A1ZZTreeConj(const double &cos_t, const double &s);
	std::complex<double> A1A1ZZ1Loop(const double &cos_t, const double &s);
	std::complex<double> A1A1ZZCT(const double &cos_t, const double &s);
	double A1A1ZZNLO(const double &cos_t, const double &s);

	std::complex<double> A1A1TAtaTree(const double &cos_t, const double &s);
	std::complex<double> A1A1TAtaTreeConj(const double &cos_t, const double &s);
	std::complex<double> A1A1TAta1Loop(const double &cos_t, const double &s);
	std::complex<double> A1A1TAtaCT(const double &cos_t, const double &s);
	std::complex<double> A1A1TAtaSoft(const double &cos_t, const double &s);
	double A1A1TAtaNLO(const double &cos_t, const double &s);

	std::complex<double> A1A1TtTree(const double &cos_t, const double &s);
	std::complex<double> A1A1TtTreeConj(const double &cos_t, const double &s);
	std::complex<double> A1A1Tt1Loop(const double &cos_t, const double &s);
	std::complex<double> A1A1TtCT(const double &cos_t, const double &s);
	std::complex<double> A1A1TtSoft(const double &cos_t, const double &s);
	double A1A1TtNLO(const double &cos_t, const double &s);

	std::complex<double> A1A1BbTree(const double &cos_t, const double &s);
	std::complex<double> A1A1BbTreeConj(const double &cos_t, const double &s);
	std::complex<double> A1A1Bb1Loop(const double &cos_t, const double &s);
	std::complex<double> A1A1BbCT(const double &cos_t, const double &s);
	std::complex<double> A1A1BbSoft(const double &cos_t, const double &s);
	double A1A1BbNLO(const double &cos_t, const double &s);

	double A1A1HHNLOfl(const double &cos_t, const double &s);
	double A1A1HS1NLOfl(const double &cos_t, const double &s);
	double A1A1S1S1NLOfl(const double &cos_t, const double &s);
	double A1A1ZZNLOfl(const double &cos_t, const double &s);
	double A1A1wWNLOfl(const double &cos_t, const double &s);
	double A1A1TAtaNLOfl(const double &cos_t, const double &s);
	double A1A1TtNLOfl(const double &cos_t, const double &s);
	double A1A1BbNLOfl(const double &cos_t, const double &s);
}
