#pragma once

#include <cmath>

namespace DT
{

    extern double aEWM1;
    extern double Gf;
    extern double aS;
    extern double ymdo;
    extern double ymup;
    extern double yms;
    extern double ymc;
    extern double ymb;
    extern double ymt;
    extern double yme;
    extern double ymm;
    extern double ymtau;
    extern double cabi;
    extern double MW;
    extern double svev;
    extern double alpha;
    extern double MA1;
    extern double MS1;
    extern double MH;
    extern double GG;
    extern double MZ;
    extern double Me;
    extern double MMU;
    extern double MTA;
    extern double MU;
    extern double MC;
    extern double MT;
    extern double MD;
    extern double MS;
    extern double MB;
    extern double WZ;
    extern double WW;
    extern double WT;
    extern double WH;
    extern double WS1;
    extern double WA1;
    extern double E;
    extern double Pi;
    extern double aEW;
    extern double sw2;
    extern double EE;
    extern double cw;
    extern double sw;
    extern double gw;
    extern double g1;
    extern double vev;
    extern double delta2;
    extern double lam;
    extern double muH;
    extern double ye;
    extern double ym;
    extern double ytau;
    extern double yup;
    extern double yc;
    extern double yt;
    extern double ydo;
    extern double ys;
    extern double yb;
    extern double CKM1x1;
    extern double CKM1x2;
    extern double CKM1x3;
    extern double CKM2x1;
    extern double CKM2x2;
    extern double CKM2x3;
    extern double CKM3x1;
    extern double CKM3x2;
    extern double CKM3x3;
    extern double d2;
    extern double b1;
    extern double b2;
    extern double I1a11;
    extern double I1a12;
    extern double I1a13;
    extern double I1a21;
    extern double I1a22;
    extern double I1a23;
    extern double I1a31;
    extern double I1a32;
    extern double I1a33;
    extern double I2a11;
    extern double I2a12;
    extern double I2a13;
    extern double I2a21;
    extern double I2a22;
    extern double I2a23;
    extern double I2a31;
    extern double I2a32;
    extern double I2a33;
    extern double I3a11;
    extern double I3a12;
    extern double I3a13;
    extern double I3a21;
    extern double I3a22;
    extern double I3a23;
    extern double I3a31;
    extern double I3a32;
    extern double I3a33;
    extern double I4a11;
    extern double I4a12;
    extern double I4a13;
    extern double I4a21;
    extern double I4a22;
    extern double I4a23;
    extern double I4a31;
    extern double I4a32;
    extern double I4a33;
    extern double gc16;
    extern double gc17;
    extern double gc18;
    extern double gc20;
    extern double gc23;
    extern double gc24;
    extern double gc26;
    extern double gc28;
    extern double gc31;
    extern double gc32;
    extern double gc34;
    extern double gc36;
    extern double gc38;
    extern double gc40;
    extern double gc41;
    extern double gc42;
    extern double gc43L;
    extern double gc43R;
    extern double gc44L;
    extern double gc44R;
    extern double gc45L;
    extern double gc45R;
    extern double gc46L;
    extern double gc46R;
    extern double gc47L;
    extern double gc47R;
    extern double gc48L;
    extern double gc48R;
    extern double gc49L;
    extern double gc49R;
    extern double gc50L;
    extern double gc50R;
    extern double gc51L;
    extern double gc51R;
    extern double gc52L;
    extern double gc52R;
    extern double gc53L;
    extern double gc53R;
    extern double gc54L;
    extern double gc54R;
    extern double gc55;
    extern double gc56;
    extern double gc57;
    extern double gc58;
    extern double gc59;
    extern double gc60;
    extern double gc61L;
    extern double gc61R;
    extern double gc62L;
    extern double gc62R;
    extern double gc63L;
    extern double gc63R;
    extern double gc64;
    extern double gc65;
    extern double gc66;
    extern double gc67L;
    extern double gc67R;
    extern double gc68L;
    extern double gc68R;
    extern double gc69L;
    extern double gc69R;
    extern double gc70L;
    extern double gc70R;
    extern double gc71L;
    extern double gc71R;
    extern double gc72L;
    extern double gc72R;
    extern double gc73L;
    extern double gc73R;
    extern double gc74L;
    extern double gc74R;
    extern double gc75L;
    extern double gc75R;
    extern double gc76L;
    extern double gc76R;
    extern double gc77L;
    extern double gc77R;
    extern double gc78L;
    extern double gc78R;
    extern double gc79;
    extern double gc80;
    extern double gc81;
    extern double gc95;
    extern double gc96;
    extern double gc97;
    extern double gc98;
    extern double gc99;
    extern double gc100;
    extern double gc101;
    extern double gc102;
    extern double gc103;
    extern double gc113;
    extern double gc114;
    extern double gc115;
    extern double gc117;
    extern double gc121;
    extern double gc122;
    extern double gc124;
    extern double gc127;
    extern double gc133;
    extern double gc134;
    extern double gc135R;
    extern double gc136R;
    extern double gc137R;
    extern double gc139;
    extern double gc140;
    extern double gc141;
    extern double gc150;
    extern double gc158;
    extern double gc159;
    extern double gc160;
    extern double gc161;
    extern double gc162;
    extern double gc163;
    extern double gc164;
    extern double gc165;
    extern double gc166;
    extern double gc167;
    extern double gc168;
    extern double gc169;
    extern double gc170;
    extern double gc171;
    extern double gc172;
    extern double gc173;
    extern double gc174;
    extern double gc175;
    extern double gc176;
    extern double gc177;
    extern double gc178;
    extern double gc179;
    extern double gc180;
    extern double gc181;
    extern double gc182;
    extern double gc183;
    extern double gc184;
    extern double gc185;
    extern double gc186;
    extern double gc187;
    extern double gc188;
    extern double gc189;
    extern double gc190;
    extern double gc191;
    extern double gc192;
    extern double gc193;
    extern double gc194;
    extern double gc195;
    extern double gc196;
    extern double gc197;
    extern double gc198L;
    extern double gc198R;
    extern double gc199L;
    extern double gc199R;
    extern double gc200L;
    extern double gc200R;
    extern double gc201L;
    extern double gc201R;
    extern double gc202L;
    extern double gc202R;
    extern double gc203L;
    extern double gc203R;
    extern double gc204;
    extern double gc205;
    extern double gc206;
    extern double gc207L;
    extern double gc207R;
    extern double gc208L;
    extern double gc208R;
    extern double gc209L;
    extern double gc209R;
    extern double EL;
    extern double ee;
    extern double gs;
    extern double G;
    extern double FAGS;

    double A1A1HH(const double cos_t, const double s);
    double A1A1HS1(const double cos_t, const double s);
    double A1A1S1S1(const double cos_t, const double s);
    double A1A1ZZ(const double cos_t, const double s);
    double A1A1wW(const double cos_t, const double s);
    double A1A1Ee(const double cos_t, const double s);
    double A1A1MUmu(const double cos_t, const double s);
    double A1A1TAta(const double cos_t, const double s);
    double A1A1Uu(const double cos_t, const double s);
    double A1A1Cc(const double cos_t, const double s);
    double A1A1Tt(const double cos_t, const double s);
    double A1A1Dd(const double cos_t, const double s);
    double A1A1Ss(const double cos_t, const double s);
    double A1A1Bb(const double cos_t, const double s);
    double A1A1HHfl(const double cos_t, const double s);
    double A1A1HS1fl(const double cos_t, const double s);
    double A1A1S1S1fl(const double cos_t, const double s);
    double A1A1ZZfl(const double cos_t, const double s);
    double A1A1wWfl(const double cos_t, const double s);
    double A1A1Eefl(const double cos_t, const double s);
    double A1A1MUmufl(const double cos_t, const double s);
    double A1A1TAtafl(const double cos_t, const double s);
    double A1A1Uufl(const double cos_t, const double s);
    double A1A1Ccfl(const double cos_t, const double s);
    double A1A1Ttfl(const double cos_t, const double s);
    double A1A1Ddfl(const double cos_t, const double s);
    double A1A1Ssfl(const double cos_t, const double s);
    double A1A1Bbfl(const double cos_t, const double s);
    double A1A1(const double cos_t, const double s);
    double wHHH();
    double wHHS1();
    double wHS1S1();
    double wHA1A1();
    double wHZZ();
    double wHwW();
    double wHEe();
    double wHMUmu();
    double wHTAta();
    double wHUu();
    double wHCc();
    double wHTt();
    double wHDd();
    double wHSs();
    double wHBb();
    double wS1HH();
    double wS1HS1();
    double wS1S1S1();
    double wS1A1A1();
    double wS1ZZ();
    double wS1wW();
    double wS1Ee();
    double wS1MUmu();
    double wS1TAta();
    double wS1Uu();
    double wS1Cc();
    double wS1Tt();
    double wS1Dd();
    double wS1Ss();
    double wS1Bb();
    double wwH();
    double wwS1();
} // namespace DT