///////////////////CODE GENERATED VIA MATHEMATICA///////////////////


#include "general_model.hpp"
#include "../model.hpp"

namespace DT{
	void ModelInfo::init()
	{
		DSmasses["H3"]=&MH3;
		DSmasses["A0"]=&MA0;
		DSmasses["Hch"]=&MHch;
		DSmasses["HCH"]=&MHch;
		DSdof["H3"]=1;
		DSdof["A0"]=1;
		DSdof["Hch"]=1;
		DSdof["HCH"]=1;
		neutraldsmasses.push_back(&MH3);
		neutraldsmasses.push_back(&MA0);
		denstructures.push_back(&MZ);
		denstructures.push_back(&WZ);
		denstructures.push_back(&MW);
		denstructures.push_back(&WW);
		denstructures.push_back(&MH1);
		denstructures.push_back(&WH1);
		denstructures.push_back(&MH2);
		denstructures.push_back(&WH2);
		N_widths = 4;
	}


	void AnnihilationAmps::init()
	{
		ADDCHANNEL("H3,H3,H1,H1",H3H3H1H1, H3H3H1H1fl)
		ADDCHANNEL("H3,H3,H1,H2",H3H3H1H2, H3H3H1H2fl)
		ADDCHANNEL("H3,H3,H2,H2",H3H3H2H2, H3H3H2H2fl)
		ADDCHANNEL("H3,H3,Z,Z",H3H3ZZ, H3H3ZZfl)
		ADDCHANNEL("H3,H3,w,W",H3H3wW, H3H3wWfl)
		ADDCHANNEL("H3,H3,G,G",H3H3GG, H3H3GGfl)
		ADDCHANNEL("H3,H3,E,e",H3H3Ee, H3H3Eefl)
		ADDCHANNEL("H3,H3,M,m",H3H3Mm, H3H3Mmfl)
		ADDCHANNEL("H3,H3,TA,ta",H3H3TAta, H3H3TAtafl)
		ADDCHANNEL("H3,H3,U,u",H3H3Uu, H3H3Uufl)
		ADDCHANNEL("H3,H3,C,c",H3H3Cc, H3H3Ccfl)
		ADDCHANNEL("H3,H3,T,t",H3H3Tt, H3H3Ttfl)
		ADDCHANNEL("H3,H3,D,d",H3H3Dd, H3H3Ddfl)
		ADDCHANNEL("H3,H3,S,s",H3H3Ss, H3H3Ssfl)
		ADDCHANNEL("H3,H3,B,b",H3H3Bb, H3H3Bbfl)
		ADDCHANNEL("H3,A0,H1,Z",H3A0H1Z, H3A0H1Zfl)
		ADDCHANNEL("H3,A0,H2,Z",H3A0H2Z, H3A0H2Zfl)
		ADDCHANNEL("H3,A0,w,W",H3A0wW, H3A0wWfl)
		ADDCHANNEL("H3,A0,VE,ve",H3A0VEve, H3A0VEvefl)
		ADDCHANNEL("H3,A0,VM,vm",H3A0VMvm, H3A0VMvmfl)
		ADDCHANNEL("H3,A0,VT,vt",H3A0VTvt, H3A0VTvtfl)
		ADDCHANNEL("H3,A0,E,e",H3A0Ee, H3A0Eefl)
		ADDCHANNEL("H3,A0,M,m",H3A0Mm, H3A0Mmfl)
		ADDCHANNEL("H3,A0,TA,ta",H3A0TAta, H3A0TAtafl)
		ADDCHANNEL("H3,A0,U,u",H3A0Uu, H3A0Uufl)
		ADDCHANNEL("H3,A0,C,c",H3A0Cc, H3A0Ccfl)
		ADDCHANNEL("H3,A0,T,t",H3A0Tt, H3A0Ttfl)
		ADDCHANNEL("H3,A0,D,d",H3A0Dd, H3A0Ddfl)
		ADDCHANNEL("H3,A0,S,s",H3A0Ss, H3A0Ssfl)
		ADDCHANNEL("H3,A0,B,b",H3A0Bb, H3A0Bbfl)
		ADDCHANNEL("H3,Hch,H1,W",H3HchH1W, H3HchH1Wfl)
		ADDCHANNEL("H3,Hch,H2,W",H3HchH2W, H3HchH2Wfl)
		ADDCHANNEL("H3,Hch,A,W",H3HchAW, H3HchAWfl)
		ADDCHANNEL("H3,Hch,Z,W",H3HchZW, H3HchZWfl)
		ADDCHANNEL("H3,Hch,ve,E",H3HchveE, H3HchveEfl)
		ADDCHANNEL("H3,Hch,vm,M",H3HchvmM, H3HchvmMfl)
		ADDCHANNEL("H3,Hch,vt,TA",H3HchvtTA, H3HchvtTAfl)
		ADDCHANNEL("H3,Hch,u,D",H3HchuD, H3HchuDfl)
		ADDCHANNEL("H3,Hch,u,S",H3HchuS, H3HchuSfl)
		ADDCHANNEL("H3,Hch,u,B",H3HchuB, H3HchuBfl)
		ADDCHANNEL("H3,Hch,c,D",H3HchcD, H3HchcDfl)
		ADDCHANNEL("H3,Hch,c,S",H3HchcS, H3HchcSfl)
		ADDCHANNEL("H3,Hch,c,B",H3HchcB, H3HchcBfl)
		ADDCHANNEL("H3,Hch,t,D",H3HchtD, H3HchtDfl)
		ADDCHANNEL("H3,Hch,t,S",H3HchtS, H3HchtSfl)
		ADDCHANNEL("H3,Hch,t,B",H3HchtB, H3HchtBfl)
		ADDCHANNEL("A0,A0,H1,H1",A0A0H1H1, A0A0H1H1fl)
		ADDCHANNEL("A0,A0,H1,H2",A0A0H1H2, A0A0H1H2fl)
		ADDCHANNEL("A0,A0,H2,H2",A0A0H2H2, A0A0H2H2fl)
		ADDCHANNEL("A0,A0,Z,Z",A0A0ZZ, A0A0ZZfl)
		ADDCHANNEL("A0,A0,w,W",A0A0wW, A0A0wWfl)
		ADDCHANNEL("A0,A0,G,G",A0A0GG, A0A0GGfl)
		ADDCHANNEL("A0,A0,E,e",A0A0Ee, A0A0Eefl)
		ADDCHANNEL("A0,A0,M,m",A0A0Mm, A0A0Mmfl)
		ADDCHANNEL("A0,A0,TA,ta",A0A0TAta, A0A0TAtafl)
		ADDCHANNEL("A0,A0,U,u",A0A0Uu, A0A0Uufl)
		ADDCHANNEL("A0,A0,C,c",A0A0Cc, A0A0Ccfl)
		ADDCHANNEL("A0,A0,T,t",A0A0Tt, A0A0Ttfl)
		ADDCHANNEL("A0,A0,D,d",A0A0Dd, A0A0Ddfl)
		ADDCHANNEL("A0,A0,S,s",A0A0Ss, A0A0Ssfl)
		ADDCHANNEL("A0,A0,B,b",A0A0Bb, A0A0Bbfl)
		ADDCHANNEL("A0,Hch,H1,W",A0HchH1W, A0HchH1Wfl)
		ADDCHANNEL("A0,Hch,H2,W",A0HchH2W, A0HchH2Wfl)
		ADDCHANNEL("A0,Hch,A,W",A0HchAW, A0HchAWfl)
		ADDCHANNEL("A0,Hch,Z,W",A0HchZW, A0HchZWfl)
		ADDCHANNEL("A0,Hch,ve,E",A0HchveE, A0HchveEfl)
		ADDCHANNEL("A0,Hch,vm,M",A0HchvmM, A0HchvmMfl)
		ADDCHANNEL("A0,Hch,vt,TA",A0HchvtTA, A0HchvtTAfl)
		ADDCHANNEL("A0,Hch,u,D",A0HchuD, A0HchuDfl)
		ADDCHANNEL("A0,Hch,u,S",A0HchuS, A0HchuSfl)
		ADDCHANNEL("A0,Hch,u,B",A0HchuB, A0HchuBfl)
		ADDCHANNEL("A0,Hch,c,D",A0HchcD, A0HchcDfl)
		ADDCHANNEL("A0,Hch,c,S",A0HchcS, A0HchcSfl)
		ADDCHANNEL("A0,Hch,c,B",A0HchcB, A0HchcBfl)
		ADDCHANNEL("A0,Hch,t,D",A0HchtD, A0HchtDfl)
		ADDCHANNEL("A0,Hch,t,S",A0HchtS, A0HchtSfl)
		ADDCHANNEL("A0,Hch,t,B",A0HchtB, A0HchtBfl)
		ADDCHANNEL("Hch,Hch,W,W",HchHchWW, HchHchWWfl)
		ADDCHANNEL("Hch,HCH,H1,H1",HchHCHH1H1, HchHCHH1H1fl)
		ADDCHANNEL("Hch,HCH,H1,H2",HchHCHH1H2, HchHCHH1H2fl)
		ADDCHANNEL("Hch,HCH,H2,H2",HchHCHH2H2, HchHCHH2H2fl)
		ADDCHANNEL("Hch,HCH,H1,A",HchHCHH1A, HchHCHH1Afl)
		ADDCHANNEL("Hch,HCH,H1,Z",HchHCHH1Z, HchHCHH1Zfl)
		ADDCHANNEL("Hch,HCH,H2,A",HchHCHH2A, HchHCHH2Afl)
		ADDCHANNEL("Hch,HCH,H2,Z",HchHCHH2Z, HchHCHH2Zfl)
		ADDCHANNEL("Hch,HCH,A,A",HchHCHAA, HchHCHAAfl)
		ADDCHANNEL("Hch,HCH,A,Z",HchHCHAZ, HchHCHAZfl)
		ADDCHANNEL("Hch,HCH,Z,Z",HchHCHZZ, HchHCHZZfl)
		ADDCHANNEL("Hch,HCH,w,W",HchHCHwW, HchHCHwWfl)
		ADDCHANNEL("Hch,HCH,G,G",HchHCHGG, HchHCHGGfl)
		ADDCHANNEL("Hch,HCH,VE,ve",HchHCHVEve, HchHCHVEvefl)
		ADDCHANNEL("Hch,HCH,VM,vm",HchHCHVMvm, HchHCHVMvmfl)
		ADDCHANNEL("Hch,HCH,VT,vt",HchHCHVTvt, HchHCHVTvtfl)
		ADDCHANNEL("Hch,HCH,E,e",HchHCHEe, HchHCHEefl)
		ADDCHANNEL("Hch,HCH,M,m",HchHCHMm, HchHCHMmfl)
		ADDCHANNEL("Hch,HCH,TA,ta",HchHCHTAta, HchHCHTAtafl)
		ADDCHANNEL("Hch,HCH,U,u",HchHCHUu, HchHCHUufl)
		ADDCHANNEL("Hch,HCH,C,c",HchHCHCc, HchHCHCcfl)
		ADDCHANNEL("Hch,HCH,T,t",HchHCHTt, HchHCHTtfl)
		ADDCHANNEL("Hch,HCH,D,d",HchHCHDd, HchHCHDdfl)
		ADDCHANNEL("Hch,HCH,S,s",HchHCHSs, HchHCHSsfl)
		ADDCHANNEL("Hch,HCH,B,b",HchHCHBb, HchHCHBbfl)
	}
}
