///////////////////CODE GENERATED VIA MATHEMATICA///////////////////


#include "general_model.hpp"
#include "../model.hpp"

namespace DT{
	void Model::init()
	{
		particles["H3"]=&MH3;
		particles["A0"]=&MA0;
		particles["Hch"]=&MHch;
		particles["HCH"]=&MHch;
		dsmasses.push_back(&MH3);
		dsmasses.push_back(&MA0);
		dsmasses.push_back(&MHch);
		dsmasses.push_back(&MHch);
		neutraldsmasses.push_back(&MH3);
		neutraldsmasses.push_back(&MA0);
		ADDCHANNEL(H3H3H1H1, H3H3H1H1fl, MH3, MH3, MH1, MH1)
		ADDCHANNEL(H3H3H1H2, H3H3H1H2fl, MH3, MH3, MH1, MH2)
		ADDCHANNEL(H3H3H2H2, H3H3H2H2fl, MH3, MH3, MH2, MH2)
		ADDCHANNEL(H3H3ZZ, H3H3ZZfl, MH3, MH3, MZ, MZ)
		ADDCHANNEL(H3H3wW, H3H3wWfl, MH3, MH3, MW, MW)
		ADDCHANNEL(H3H3Ee, H3H3Eefl, MH3, MH3, Me, Me)
		ADDCHANNEL(H3H3Mm, H3H3Mmfl, MH3, MH3, MM, MM)
		ADDCHANNEL(H3H3TAta, H3H3TAtafl, MH3, MH3, MTA, MTA)
		ADDCHANNEL(H3H3Uu, H3H3Uufl, MH3, MH3, MU, MU)
		ADDCHANNEL(H3H3Cc, H3H3Ccfl, MH3, MH3, MC, MC)
		ADDCHANNEL(H3H3Tt, H3H3Ttfl, MH3, MH3, MT, MT)
		ADDCHANNEL(H3H3Dd, H3H3Ddfl, MH3, MH3, MD, MD)
		ADDCHANNEL(H3H3Ss, H3H3Ssfl, MH3, MH3, MS, MS)
		ADDCHANNEL(H3H3Bb, H3H3Bbfl, MH3, MH3, MB, MB)
		ADDCHANNEL(H3A0H1Z, H3A0H1Zfl, MH3, MA0, MH1, MZ)
		ADDCHANNEL(H3A0H2Z, H3A0H2Zfl, MH3, MA0, MH2, MZ)
		ADDCHANNEL(H3A0wW, H3A0wWfl, MH3, MA0, MW, MW)
		ADDCHANNEL(H3A0VEve, H3A0VEvefl, MH3, MA0, Mnue, Mnue)
		ADDCHANNEL(H3A0VMvm, H3A0VMvmfl, MH3, MA0, Mnum, Mnum)
		ADDCHANNEL(H3A0VTvt, H3A0VTvtfl, MH3, MA0, Mnut, Mnut)
		ADDCHANNEL(H3A0Ee, H3A0Eefl, MH3, MA0, Me, Me)
		ADDCHANNEL(H3A0Mm, H3A0Mmfl, MH3, MA0, MM, MM)
		ADDCHANNEL(H3A0TAta, H3A0TAtafl, MH3, MA0, MTA, MTA)
		ADDCHANNEL(H3A0Uu, H3A0Uufl, MH3, MA0, MU, MU)
		ADDCHANNEL(H3A0Cc, H3A0Ccfl, MH3, MA0, MC, MC)
		ADDCHANNEL(H3A0Tt, H3A0Ttfl, MH3, MA0, MT, MT)
		ADDCHANNEL(H3A0Dd, H3A0Ddfl, MH3, MA0, MD, MD)
		ADDCHANNEL(H3A0Ss, H3A0Ssfl, MH3, MA0, MS, MS)
		ADDCHANNEL(H3A0Bb, H3A0Bbfl, MH3, MA0, MB, MB)
		ADDCHANNEL(H3HchH1W, H3HchH1Wfl, MH3, MHch, MH1, MW)
		ADDCHANNEL(H3HchH2W, H3HchH2Wfl, MH3, MHch, MH2, MW)
		ADDCHANNEL(H3HchAW, H3HchAWfl, MH3, MHch, ZERO, MW)
		ADDCHANNEL(H3HchZW, H3HchZWfl, MH3, MHch, MZ, MW)
		ADDCHANNEL(H3HchveE, H3HchveEfl, MH3, MHch, Mnue, Me)
		ADDCHANNEL(H3HchvmM, H3HchvmMfl, MH3, MHch, Mnum, MM)
		ADDCHANNEL(H3HchvtTA, H3HchvtTAfl, MH3, MHch, Mnut, MTA)
		ADDCHANNEL(H3HchuD, H3HchuDfl, MH3, MHch, MU, MD)
		ADDCHANNEL(H3HchuS, H3HchuSfl, MH3, MHch, MU, MS)
		ADDCHANNEL(H3HchuB, H3HchuBfl, MH3, MHch, MU, MB)
		ADDCHANNEL(H3HchcD, H3HchcDfl, MH3, MHch, MC, MD)
		ADDCHANNEL(H3HchcS, H3HchcSfl, MH3, MHch, MC, MS)
		ADDCHANNEL(H3HchcB, H3HchcBfl, MH3, MHch, MC, MB)
		ADDCHANNEL(H3HchtD, H3HchtDfl, MH3, MHch, MT, MD)
		ADDCHANNEL(H3HchtS, H3HchtSfl, MH3, MHch, MT, MS)
		ADDCHANNEL(H3HchtB, H3HchtBfl, MH3, MHch, MT, MB)
		ADDCHANNEL(A0A0H1H1, A0A0H1H1fl, MA0, MA0, MH1, MH1)
		ADDCHANNEL(A0A0H1H2, A0A0H1H2fl, MA0, MA0, MH1, MH2)
		ADDCHANNEL(A0A0H2H2, A0A0H2H2fl, MA0, MA0, MH2, MH2)
		ADDCHANNEL(A0A0ZZ, A0A0ZZfl, MA0, MA0, MZ, MZ)
		ADDCHANNEL(A0A0wW, A0A0wWfl, MA0, MA0, MW, MW)
		ADDCHANNEL(A0A0Ee, A0A0Eefl, MA0, MA0, Me, Me)
		ADDCHANNEL(A0A0Mm, A0A0Mmfl, MA0, MA0, MM, MM)
		ADDCHANNEL(A0A0TAta, A0A0TAtafl, MA0, MA0, MTA, MTA)
		ADDCHANNEL(A0A0Uu, A0A0Uufl, MA0, MA0, MU, MU)
		ADDCHANNEL(A0A0Cc, A0A0Ccfl, MA0, MA0, MC, MC)
		ADDCHANNEL(A0A0Tt, A0A0Ttfl, MA0, MA0, MT, MT)
		ADDCHANNEL(A0A0Dd, A0A0Ddfl, MA0, MA0, MD, MD)
		ADDCHANNEL(A0A0Ss, A0A0Ssfl, MA0, MA0, MS, MS)
		ADDCHANNEL(A0A0Bb, A0A0Bbfl, MA0, MA0, MB, MB)
		ADDCHANNEL(A0HchH1W, A0HchH1Wfl, MA0, MHch, MH1, MW)
		ADDCHANNEL(A0HchH2W, A0HchH2Wfl, MA0, MHch, MH2, MW)
		ADDCHANNEL(A0HchAW, A0HchAWfl, MA0, MHch, ZERO, MW)
		ADDCHANNEL(A0HchZW, A0HchZWfl, MA0, MHch, MZ, MW)
		ADDCHANNEL(A0HchveE, A0HchveEfl, MA0, MHch, Mnue, Me)
		ADDCHANNEL(A0HchvmM, A0HchvmMfl, MA0, MHch, Mnum, MM)
		ADDCHANNEL(A0HchvtTA, A0HchvtTAfl, MA0, MHch, Mnut, MTA)
		ADDCHANNEL(A0HchuD, A0HchuDfl, MA0, MHch, MU, MD)
		ADDCHANNEL(A0HchuS, A0HchuSfl, MA0, MHch, MU, MS)
		ADDCHANNEL(A0HchuB, A0HchuBfl, MA0, MHch, MU, MB)
		ADDCHANNEL(A0HchcD, A0HchcDfl, MA0, MHch, MC, MD)
		ADDCHANNEL(A0HchcS, A0HchcSfl, MA0, MHch, MC, MS)
		ADDCHANNEL(A0HchcB, A0HchcBfl, MA0, MHch, MC, MB)
		ADDCHANNEL(A0HchtD, A0HchtDfl, MA0, MHch, MT, MD)
		ADDCHANNEL(A0HchtS, A0HchtSfl, MA0, MHch, MT, MS)
		ADDCHANNEL(A0HchtB, A0HchtBfl, MA0, MHch, MT, MB)
		ADDCHANNEL(HchHchWW, HchHchWWfl, MHch, MHch, MW, MW)
		ADDCHANNEL(HchHCHH1H1, HchHCHH1H1fl, MHch, MHch, MH1, MH1)
		ADDCHANNEL(HchHCHH1H2, HchHCHH1H2fl, MHch, MHch, MH1, MH2)
		ADDCHANNEL(HchHCHH2H2, HchHCHH2H2fl, MHch, MHch, MH2, MH2)
		ADDCHANNEL(HchHCHH1A, HchHCHH1Afl, MHch, MHch, MH1, ZERO)
		ADDCHANNEL(HchHCHH1Z, HchHCHH1Zfl, MHch, MHch, MH1, MZ)
		ADDCHANNEL(HchHCHH2A, HchHCHH2Afl, MHch, MHch, MH2, ZERO)
		ADDCHANNEL(HchHCHH2Z, HchHCHH2Zfl, MHch, MHch, MH2, MZ)
		ADDCHANNEL(HchHCHAA, HchHCHAAfl, MHch, MHch, ZERO, ZERO)
		ADDCHANNEL(HchHCHAZ, HchHCHAZfl, MHch, MHch, ZERO, MZ)
		ADDCHANNEL(HchHCHZZ, HchHCHZZfl, MHch, MHch, MZ, MZ)
		ADDCHANNEL(HchHCHwW, HchHCHwWfl, MHch, MHch, MW, MW)
		ADDCHANNEL(HchHCHVEve, HchHCHVEvefl, MHch, MHch, Mnue, Mnue)
		ADDCHANNEL(HchHCHVMvm, HchHCHVMvmfl, MHch, MHch, Mnum, Mnum)
		ADDCHANNEL(HchHCHVTvt, HchHCHVTvtfl, MHch, MHch, Mnut, Mnut)
		ADDCHANNEL(HchHCHEe, HchHCHEefl, MHch, MHch, Me, Me)
		ADDCHANNEL(HchHCHMm, HchHCHMmfl, MHch, MHch, MM, MM)
		ADDCHANNEL(HchHCHTAta, HchHCHTAtafl, MHch, MHch, MTA, MTA)
		ADDCHANNEL(HchHCHUu, HchHCHUufl, MHch, MHch, MU, MU)
		ADDCHANNEL(HchHCHCc, HchHCHCcfl, MHch, MHch, MC, MC)
		ADDCHANNEL(HchHCHTt, HchHCHTtfl, MHch, MHch, MT, MT)
		ADDCHANNEL(HchHCHDd, HchHCHDdfl, MHch, MHch, MD, MD)
		ADDCHANNEL(HchHCHSs, HchHCHSsfl, MHch, MHch, MS, MS)
		ADDCHANNEL(HchHCHBb, HchHCHBbfl, MHch, MHch, MB, MB)
		denstructures.push_back(&MZ);
		denstructures.push_back(&WZ);
		denstructures.push_back(&MW);
		denstructures.push_back(&WW);
		denstructures.push_back(&MH1);
		denstructures.push_back(&WH1);
		denstructures.push_back(&MH2);
		denstructures.push_back(&WH2);
		N_widths = 4;
	}
}
