///////////////////CODE GENERATED VIA MATHEMATICA///////////////////


#include "general_model.hpp"
#include "../model.hpp"

namespace DT{
	void ModelInfo::init()
	{
		DSmasses["A1"]=&MA1;
		DSdof["A1"]=1;
		neutraldsmasses.push_back(&MA1);
		ADDCHANNELINFO(A1A1HH, MA1, MA1, MH, MH)
		ADDCHANNELINFO(A1A1HS1, MA1, MA1, MH, MS1)
		ADDCHANNELINFO(A1A1S1S1, MA1, MA1, MS1, MS1)
		ADDCHANNELINFO(A1A1ZZ, MA1, MA1, MZ, MZ)
		ADDCHANNELINFO(A1A1wW, MA1, MA1, MW, MW)
		ADDCHANNELINFO(A1A1Ee, MA1, MA1, Me, Me)
		ADDCHANNELINFO(A1A1MUmu, MA1, MA1, MMU, MMU)
		ADDCHANNELINFO(A1A1TAta, MA1, MA1, MTA, MTA)
		ADDCHANNELINFO(A1A1Uu, MA1, MA1, MU, MU)
		ADDCHANNELINFO(A1A1Cc, MA1, MA1, MC, MC)
		ADDCHANNELINFO(A1A1Tt, MA1, MA1, MT, MT)
		ADDCHANNELINFO(A1A1Dd, MA1, MA1, MD, MD)
		ADDCHANNELINFO(A1A1Ss, MA1, MA1, MS, MS)
		ADDCHANNELINFO(A1A1Bb, MA1, MA1, MB, MB)
		denstructures.push_back(&MH);
		denstructures.push_back(&WH);
		denstructures.push_back(&MS1);
		denstructures.push_back(&WS1);
		N_widths = 2;
	}


	void AnnihilationAmps::init()
	{
		ADDCHANNEL(A1A1HH, A1A1HHfl)
		ADDCHANNEL(A1A1HS1, A1A1HS1fl)
		ADDCHANNEL(A1A1S1S1, A1A1S1S1fl)
		ADDCHANNEL(A1A1ZZ, A1A1ZZfl)
		ADDCHANNEL(A1A1wW, A1A1wWfl)
		ADDCHANNEL(A1A1Ee, A1A1Eefl)
		ADDCHANNEL(A1A1MUmu, A1A1MUmufl)
		ADDCHANNEL(A1A1TAta, A1A1TAtafl)
		ADDCHANNEL(A1A1Uu, A1A1Uufl)
		ADDCHANNEL(A1A1Cc, A1A1Ccfl)
		ADDCHANNEL(A1A1Tt, A1A1Ttfl)
		ADDCHANNEL(A1A1Dd, A1A1Ddfl)
		ADDCHANNEL(A1A1Ss, A1A1Ssfl)
		ADDCHANNEL(A1A1Bb, A1A1Bbfl)
	}
}
