#!/bin/bash

args=$#

case $args in
	1)
		cd FR_modfiles/CH_modfiles/
		if [[ -f vars1.mdl ]]; then
			cd -
			file_name=$1
			math -script mathematica/gen_init.m $1
		else
			echo "The model has not been implemented yet. Run the following code to load the model:"
			echo "./gen_amps [path/to/feynrules-current] [modelname.fr] [Name of Lagrangian]"
		fi
		;;
	3)
		math -script mathematica/FR_to_CH_FA.m $1 $2 $3
		math -script mathematica/amp2cpp.m
		;;
	*)	
		echo "Not the right amount of arguments given."
		echo "Either:"
		echo "./gen_amps [mydata.csv]"
		echo "Or:"
		echo "./gen_amps [path/to/feynrules-current] [modelname.fr] [Name of Lagrangian]"
		;;
esac
