///////////////////CODE GENERATED VIA MATHEMATICA///////////////////


#pragma once

#include <cmath>

namespace DT{
	extern double MZ;
	extern double aEWM1;
	extern double Gf;
	extern double aS;
	extern double mHsm;
	extern double mHc;
	extern double alph1;
	extern double alph2;
	extern double alph3;
	extern double mH1;
	extern double mH2;
	extern double m22sq;
	extern double mssq;
	extern double L2;
	extern double L6;
	extern double L8;
	extern double MC;
	extern double MB;
	extern double MT;
	extern double GG;
	extern double Mnue;
	extern double Mnum;
	extern double Mnut;
	extern double Me;
	extern double MM;
	extern double MTA;
	extern double MU;
	extern double MD;
	extern double MS;
	extern double WT;
	extern double WZ;
	extern double WW;
	extern double WHsm;
	extern double WH1;
	extern double WH2;
	extern double WH3;
	extern double WHc;
	extern double E;
	extern double Pi;
	extern double MW;
	extern double EE;
	extern double CW2;
	extern double SW2;
	extern double CW;
	extern double SW;
	extern double g1;
	extern double g2;
	extern double v;
	extern double RR1x1;
	extern double RR1x2;
	extern double RR1x3;
	extern double RR2x1;
	extern double RR2x2;
	extern double RR2x3;
	extern double RR3x1;
	extern double RR3x2;
	extern double RR3x3;
	extern double mH3;
	extern double m11sq;
	extern double L1;
	extern double L3;
	extern double L4;
	extern double L5;
	extern double L7;
	extern double Treal;
	extern double Timag;
	extern double CKM1x1;
	extern double CKM1x2;
	extern double CKM1x3;
	extern double CKM2x1;
	extern double CKM2x2;
	extern double CKM2x3;
	extern double CKM3x1;
	extern double CKM3x2;
	extern double CKM3x3;
	extern double gc19;
	extern double gc20;
	extern double gc21;
	extern double gc22;
	extern double gc24;
	extern double gc27;
	extern double gc28;
	extern double gc30;
	extern double gc32;
	extern double gc35;
	extern double gc36;
	extern double gc38;
	extern double gc40;
	extern double gc42;
	extern double gc44;
	extern double gc45;
	extern double gc46;
	extern double gc47L;
	extern double gc47R;
	extern double gc48;
	extern double gc49L;
	extern double gc49R;
	extern double gc50;
	extern double gc51L;
	extern double gc51R;
	extern double gc52;
	extern double gc53L;
	extern double gc53R;
	extern double gc54L;
	extern double gc54R;
	extern double gc55L;
	extern double gc55R;
	extern double gc56L;
	extern double gc56R;
	extern double gc57L;
	extern double gc57R;
	extern double gc58L;
	extern double gc58R;
	extern double gc59L;
	extern double gc59R;
	extern double gc60L;
	extern double gc60R;
	extern double gc61L;
	extern double gc61R;
	extern double gc62L;
	extern double gc62R;
	extern double gc63;
	extern double gc64L;
	extern double gc64R;
	extern double gc65;
	extern double gc66L;
	extern double gc66R;
	extern double gc67;
	extern double gc68;
	extern double gc69;
	extern double gc70;
	extern double gc71L;
	extern double gc71R;
	extern double gc72L;
	extern double gc72R;
	extern double gc73L;
	extern double gc73R;
	extern double gc74L;
	extern double gc74R;
	extern double gc75L;
	extern double gc75R;
	extern double gc76L;
	extern double gc76R;
	extern double gc77L;
	extern double gc77R;
	extern double gc78L;
	extern double gc78R;
	extern double gc79L;
	extern double gc79R;
	extern double gc80L;
	extern double gc80R;
	extern double gc81;
	extern double gc82L;
	extern double gc82R;
	extern double gc83;
	extern double gc84L;
	extern double gc84R;
	extern double gc85;
	extern double gc86R;
	extern double gc87R;
	extern double gc88R;
	extern double gc164;
	extern double gc165;
	extern double gc166;
	extern double gc167;
	extern double gc168;
	extern double gc169;
	extern double gc173;
	extern double gc174;
	extern double gc175;
	extern double gc177;
	extern double gc179;
	extern double gc181;
	extern double gc185;
	extern double gc186;
	extern double gc188;
	extern double gc190;
	extern double gc192;
	extern double gc198;
	extern double gc205;
	extern double gc206;
	extern double gc209;
	extern double gc210;
	extern double gc211;
	extern double gc212;
	extern double gc213;
	extern double gc214;
	extern double gc227;
	extern double gc239;
	extern double gc240;
	extern double gc241;
	extern double gc242;
	extern double gc243;
	extern double gc244;
	extern double gc245;
	extern double gc246;
	extern double gc247;
	extern double gc248;
	extern double gc249;
	extern double gc250;
	extern double gc251;
	extern double gc252;
	extern double gc253;
	extern double gc254;
	extern double gc255;
	extern double gc256;
	extern double gc257;
	extern double gc258;
	extern double gc259;
	extern double gc260;
	extern double gc261;
	extern double gc262;
	extern double gc263;
	extern double gc264;
	extern double gc265;
	extern double gc266;
	extern double gc267;
	extern double gc268;
	extern double gc269;
	extern double gc270;
	extern double gc271;
	extern double gc272;
	extern double gc273L;
	extern double gc273R;
	extern double gc274L;
	extern double gc274R;
	extern double gc275L;
	extern double gc275R;
	extern double gc276L;
	extern double gc276R;
	extern double gc277L;
	extern double gc277R;
	extern double gc278L;
	extern double gc278R;
	extern double gc279L;
	extern double gc279R;
	extern double gc280L;
	extern double gc280R;
	extern double gc281L;
	extern double gc281R;
	extern double gc282;
	extern double gc283;
	extern double gc284;
	extern double EL;
	extern double ee;
	extern double gs;
	extern double G;
	extern double FAGS;

	double H1H1hh(const double &cos_t, const double &s);
	double H1H1hZ(const double &cos_t, const double &s);
	double H1H1ZZ(const double &cos_t, const double &s);
	double H1H1wW(const double &cos_t, const double &s);
	double H1H1Ee(const double &cos_t, const double &s);
	double H1H1Mm(const double &cos_t, const double &s);
	double H1H1TAta(const double &cos_t, const double &s);
	double H1H1Uu(const double &cos_t, const double &s);
	double H1H1Cc(const double &cos_t, const double &s);
	double H1H1Tt(const double &cos_t, const double &s);
	double H1H1Dd(const double &cos_t, const double &s);
	double H1H1Ss(const double &cos_t, const double &s);
	double H1H1Bb(const double &cos_t, const double &s);
	double H1H2hh(const double &cos_t, const double &s);
	double H1H2hZ(const double &cos_t, const double &s);
	double H1H2ZZ(const double &cos_t, const double &s);
	double H1H2wW(const double &cos_t, const double &s);
	double H1H2VEve(const double &cos_t, const double &s);
	double H1H2VMvm(const double &cos_t, const double &s);
	double H1H2VTvt(const double &cos_t, const double &s);
	double H1H2Ee(const double &cos_t, const double &s);
	double H1H2Mm(const double &cos_t, const double &s);
	double H1H2TAta(const double &cos_t, const double &s);
	double H1H2Uu(const double &cos_t, const double &s);
	double H1H2Cc(const double &cos_t, const double &s);
	double H1H2Tt(const double &cos_t, const double &s);
	double H1H2Dd(const double &cos_t, const double &s);
	double H1H2Ss(const double &cos_t, const double &s);
	double H1H2Bb(const double &cos_t, const double &s);
	double H1H3hh(const double &cos_t, const double &s);
	double H1H3hZ(const double &cos_t, const double &s);
	double H1H3ZZ(const double &cos_t, const double &s);
	double H1H3wW(const double &cos_t, const double &s);
	double H1H3VEve(const double &cos_t, const double &s);
	double H1H3VMvm(const double &cos_t, const double &s);
	double H1H3VTvt(const double &cos_t, const double &s);
	double H1H3Ee(const double &cos_t, const double &s);
	double H1H3Mm(const double &cos_t, const double &s);
	double H1H3TAta(const double &cos_t, const double &s);
	double H1H3Uu(const double &cos_t, const double &s);
	double H1H3Cc(const double &cos_t, const double &s);
	double H1H3Tt(const double &cos_t, const double &s);
	double H1H3Dd(const double &cos_t, const double &s);
	double H1H3Ss(const double &cos_t, const double &s);
	double H1H3Bb(const double &cos_t, const double &s);
	double H1HchW(const double &cos_t, const double &s);
	double H1HcAW(const double &cos_t, const double &s);
	double H1HcZW(const double &cos_t, const double &s);
	double H1HcveE(const double &cos_t, const double &s);
	double H1HcvmM(const double &cos_t, const double &s);
	double H1HcvtTA(const double &cos_t, const double &s);
	double H1HcuD(const double &cos_t, const double &s);
	double H1HcuS(const double &cos_t, const double &s);
	double H1HcuB(const double &cos_t, const double &s);
	double H1HccD(const double &cos_t, const double &s);
	double H1HccS(const double &cos_t, const double &s);
	double H1HccB(const double &cos_t, const double &s);
	double H1HctD(const double &cos_t, const double &s);
	double H1HctS(const double &cos_t, const double &s);
	double H1HctB(const double &cos_t, const double &s);
	double H2H2hh(const double &cos_t, const double &s);
	double H2H2hZ(const double &cos_t, const double &s);
	double H2H2ZZ(const double &cos_t, const double &s);
	double H2H2wW(const double &cos_t, const double &s);
	double H2H2Ee(const double &cos_t, const double &s);
	double H2H2Mm(const double &cos_t, const double &s);
	double H2H2TAta(const double &cos_t, const double &s);
	double H2H2Uu(const double &cos_t, const double &s);
	double H2H2Cc(const double &cos_t, const double &s);
	double H2H2Tt(const double &cos_t, const double &s);
	double H2H2Dd(const double &cos_t, const double &s);
	double H2H2Ss(const double &cos_t, const double &s);
	double H2H2Bb(const double &cos_t, const double &s);
	double H2H3hh(const double &cos_t, const double &s);
	double H2H3hZ(const double &cos_t, const double &s);
	double H2H3ZZ(const double &cos_t, const double &s);
	double H2H3wW(const double &cos_t, const double &s);
	double H2H3VEve(const double &cos_t, const double &s);
	double H2H3VMvm(const double &cos_t, const double &s);
	double H2H3VTvt(const double &cos_t, const double &s);
	double H2H3Ee(const double &cos_t, const double &s);
	double H2H3Mm(const double &cos_t, const double &s);
	double H2H3TAta(const double &cos_t, const double &s);
	double H2H3Uu(const double &cos_t, const double &s);
	double H2H3Cc(const double &cos_t, const double &s);
	double H2H3Tt(const double &cos_t, const double &s);
	double H2H3Dd(const double &cos_t, const double &s);
	double H2H3Ss(const double &cos_t, const double &s);
	double H2H3Bb(const double &cos_t, const double &s);
	double H2HchW(const double &cos_t, const double &s);
	double H2HcAW(const double &cos_t, const double &s);
	double H2HcZW(const double &cos_t, const double &s);
	double H2HcveE(const double &cos_t, const double &s);
	double H2HcvmM(const double &cos_t, const double &s);
	double H2HcvtTA(const double &cos_t, const double &s);
	double H2HcuD(const double &cos_t, const double &s);
	double H2HcuS(const double &cos_t, const double &s);
	double H2HcuB(const double &cos_t, const double &s);
	double H2HccD(const double &cos_t, const double &s);
	double H2HccS(const double &cos_t, const double &s);
	double H2HccB(const double &cos_t, const double &s);
	double H2HctD(const double &cos_t, const double &s);
	double H2HctS(const double &cos_t, const double &s);
	double H2HctB(const double &cos_t, const double &s);
	double H3H3hh(const double &cos_t, const double &s);
	double H3H3hZ(const double &cos_t, const double &s);
	double H3H3ZZ(const double &cos_t, const double &s);
	double H3H3wW(const double &cos_t, const double &s);
	double H3H3Ee(const double &cos_t, const double &s);
	double H3H3Mm(const double &cos_t, const double &s);
	double H3H3TAta(const double &cos_t, const double &s);
	double H3H3Uu(const double &cos_t, const double &s);
	double H3H3Cc(const double &cos_t, const double &s);
	double H3H3Tt(const double &cos_t, const double &s);
	double H3H3Dd(const double &cos_t, const double &s);
	double H3H3Ss(const double &cos_t, const double &s);
	double H3H3Bb(const double &cos_t, const double &s);
	double H3HchW(const double &cos_t, const double &s);
	double H3HcAW(const double &cos_t, const double &s);
	double H3HcZW(const double &cos_t, const double &s);
	double H3HcveE(const double &cos_t, const double &s);
	double H3HcvmM(const double &cos_t, const double &s);
	double H3HcvtTA(const double &cos_t, const double &s);
	double H3HcuD(const double &cos_t, const double &s);
	double H3HcuS(const double &cos_t, const double &s);
	double H3HcuB(const double &cos_t, const double &s);
	double H3HccD(const double &cos_t, const double &s);
	double H3HccS(const double &cos_t, const double &s);
	double H3HccB(const double &cos_t, const double &s);
	double H3HctD(const double &cos_t, const double &s);
	double H3HctS(const double &cos_t, const double &s);
	double H3HctB(const double &cos_t, const double &s);
	double HcHcWW(const double &cos_t, const double &s);
	double HcHChh(const double &cos_t, const double &s);
	double HcHChA(const double &cos_t, const double &s);
	double HcHChZ(const double &cos_t, const double &s);
	double HcHCAA(const double &cos_t, const double &s);
	double HcHCAZ(const double &cos_t, const double &s);
	double HcHCZZ(const double &cos_t, const double &s);
	double HcHCwW(const double &cos_t, const double &s);
	double HcHCVEve(const double &cos_t, const double &s);
	double HcHCVMvm(const double &cos_t, const double &s);
	double HcHCVTvt(const double &cos_t, const double &s);
	double HcHCEe(const double &cos_t, const double &s);
	double HcHCMm(const double &cos_t, const double &s);
	double HcHCTAta(const double &cos_t, const double &s);
	double HcHCUu(const double &cos_t, const double &s);
	double HcHCCc(const double &cos_t, const double &s);
	double HcHCTt(const double &cos_t, const double &s);
	double HcHCDd(const double &cos_t, const double &s);
	double HcHCSs(const double &cos_t, const double &s);
	double HcHCBb(const double &cos_t, const double &s);
	double H1H1hhfl(const double &cos_t, const double &s);
	double H1H1hZfl(const double &cos_t, const double &s);
	double H1H1ZZfl(const double &cos_t, const double &s);
	double H1H1wWfl(const double &cos_t, const double &s);
	double H1H1Eefl(const double &cos_t, const double &s);
	double H1H1Mmfl(const double &cos_t, const double &s);
	double H1H1TAtafl(const double &cos_t, const double &s);
	double H1H1Uufl(const double &cos_t, const double &s);
	double H1H1Ccfl(const double &cos_t, const double &s);
	double H1H1Ttfl(const double &cos_t, const double &s);
	double H1H1Ddfl(const double &cos_t, const double &s);
	double H1H1Ssfl(const double &cos_t, const double &s);
	double H1H1Bbfl(const double &cos_t, const double &s);
	double H1H2hhfl(const double &cos_t, const double &s);
	double H1H2hZfl(const double &cos_t, const double &s);
	double H1H2ZZfl(const double &cos_t, const double &s);
	double H1H2wWfl(const double &cos_t, const double &s);
	double H1H2VEvefl(const double &cos_t, const double &s);
	double H1H2VMvmfl(const double &cos_t, const double &s);
	double H1H2VTvtfl(const double &cos_t, const double &s);
	double H1H2Eefl(const double &cos_t, const double &s);
	double H1H2Mmfl(const double &cos_t, const double &s);
	double H1H2TAtafl(const double &cos_t, const double &s);
	double H1H2Uufl(const double &cos_t, const double &s);
	double H1H2Ccfl(const double &cos_t, const double &s);
	double H1H2Ttfl(const double &cos_t, const double &s);
	double H1H2Ddfl(const double &cos_t, const double &s);
	double H1H2Ssfl(const double &cos_t, const double &s);
	double H1H2Bbfl(const double &cos_t, const double &s);
	double H1H3hhfl(const double &cos_t, const double &s);
	double H1H3hZfl(const double &cos_t, const double &s);
	double H1H3ZZfl(const double &cos_t, const double &s);
	double H1H3wWfl(const double &cos_t, const double &s);
	double H1H3VEvefl(const double &cos_t, const double &s);
	double H1H3VMvmfl(const double &cos_t, const double &s);
	double H1H3VTvtfl(const double &cos_t, const double &s);
	double H1H3Eefl(const double &cos_t, const double &s);
	double H1H3Mmfl(const double &cos_t, const double &s);
	double H1H3TAtafl(const double &cos_t, const double &s);
	double H1H3Uufl(const double &cos_t, const double &s);
	double H1H3Ccfl(const double &cos_t, const double &s);
	double H1H3Ttfl(const double &cos_t, const double &s);
	double H1H3Ddfl(const double &cos_t, const double &s);
	double H1H3Ssfl(const double &cos_t, const double &s);
	double H1H3Bbfl(const double &cos_t, const double &s);
	double H1HchWfl(const double &cos_t, const double &s);
	double H1HcAWfl(const double &cos_t, const double &s);
	double H1HcZWfl(const double &cos_t, const double &s);
	double H1HcveEfl(const double &cos_t, const double &s);
	double H1HcvmMfl(const double &cos_t, const double &s);
	double H1HcvtTAfl(const double &cos_t, const double &s);
	double H1HcuDfl(const double &cos_t, const double &s);
	double H1HcuSfl(const double &cos_t, const double &s);
	double H1HcuBfl(const double &cos_t, const double &s);
	double H1HccDfl(const double &cos_t, const double &s);
	double H1HccSfl(const double &cos_t, const double &s);
	double H1HccBfl(const double &cos_t, const double &s);
	double H1HctDfl(const double &cos_t, const double &s);
	double H1HctSfl(const double &cos_t, const double &s);
	double H1HctBfl(const double &cos_t, const double &s);
	double H2H2hhfl(const double &cos_t, const double &s);
	double H2H2hZfl(const double &cos_t, const double &s);
	double H2H2ZZfl(const double &cos_t, const double &s);
	double H2H2wWfl(const double &cos_t, const double &s);
	double H2H2Eefl(const double &cos_t, const double &s);
	double H2H2Mmfl(const double &cos_t, const double &s);
	double H2H2TAtafl(const double &cos_t, const double &s);
	double H2H2Uufl(const double &cos_t, const double &s);
	double H2H2Ccfl(const double &cos_t, const double &s);
	double H2H2Ttfl(const double &cos_t, const double &s);
	double H2H2Ddfl(const double &cos_t, const double &s);
	double H2H2Ssfl(const double &cos_t, const double &s);
	double H2H2Bbfl(const double &cos_t, const double &s);
	double H2H3hhfl(const double &cos_t, const double &s);
	double H2H3hZfl(const double &cos_t, const double &s);
	double H2H3ZZfl(const double &cos_t, const double &s);
	double H2H3wWfl(const double &cos_t, const double &s);
	double H2H3VEvefl(const double &cos_t, const double &s);
	double H2H3VMvmfl(const double &cos_t, const double &s);
	double H2H3VTvtfl(const double &cos_t, const double &s);
	double H2H3Eefl(const double &cos_t, const double &s);
	double H2H3Mmfl(const double &cos_t, const double &s);
	double H2H3TAtafl(const double &cos_t, const double &s);
	double H2H3Uufl(const double &cos_t, const double &s);
	double H2H3Ccfl(const double &cos_t, const double &s);
	double H2H3Ttfl(const double &cos_t, const double &s);
	double H2H3Ddfl(const double &cos_t, const double &s);
	double H2H3Ssfl(const double &cos_t, const double &s);
	double H2H3Bbfl(const double &cos_t, const double &s);
	double H2HchWfl(const double &cos_t, const double &s);
	double H2HcAWfl(const double &cos_t, const double &s);
	double H2HcZWfl(const double &cos_t, const double &s);
	double H2HcveEfl(const double &cos_t, const double &s);
	double H2HcvmMfl(const double &cos_t, const double &s);
	double H2HcvtTAfl(const double &cos_t, const double &s);
	double H2HcuDfl(const double &cos_t, const double &s);
	double H2HcuSfl(const double &cos_t, const double &s);
	double H2HcuBfl(const double &cos_t, const double &s);
	double H2HccDfl(const double &cos_t, const double &s);
	double H2HccSfl(const double &cos_t, const double &s);
	double H2HccBfl(const double &cos_t, const double &s);
	double H2HctDfl(const double &cos_t, const double &s);
	double H2HctSfl(const double &cos_t, const double &s);
	double H2HctBfl(const double &cos_t, const double &s);
	double H3H3hhfl(const double &cos_t, const double &s);
	double H3H3hZfl(const double &cos_t, const double &s);
	double H3H3ZZfl(const double &cos_t, const double &s);
	double H3H3wWfl(const double &cos_t, const double &s);
	double H3H3Eefl(const double &cos_t, const double &s);
	double H3H3Mmfl(const double &cos_t, const double &s);
	double H3H3TAtafl(const double &cos_t, const double &s);
	double H3H3Uufl(const double &cos_t, const double &s);
	double H3H3Ccfl(const double &cos_t, const double &s);
	double H3H3Ttfl(const double &cos_t, const double &s);
	double H3H3Ddfl(const double &cos_t, const double &s);
	double H3H3Ssfl(const double &cos_t, const double &s);
	double H3H3Bbfl(const double &cos_t, const double &s);
	double H3HchWfl(const double &cos_t, const double &s);
	double H3HcAWfl(const double &cos_t, const double &s);
	double H3HcZWfl(const double &cos_t, const double &s);
	double H3HcveEfl(const double &cos_t, const double &s);
	double H3HcvmMfl(const double &cos_t, const double &s);
	double H3HcvtTAfl(const double &cos_t, const double &s);
	double H3HcuDfl(const double &cos_t, const double &s);
	double H3HcuSfl(const double &cos_t, const double &s);
	double H3HcuBfl(const double &cos_t, const double &s);
	double H3HccDfl(const double &cos_t, const double &s);
	double H3HccSfl(const double &cos_t, const double &s);
	double H3HccBfl(const double &cos_t, const double &s);
	double H3HctDfl(const double &cos_t, const double &s);
	double H3HctSfl(const double &cos_t, const double &s);
	double H3HctBfl(const double &cos_t, const double &s);
	double HcHcWWfl(const double &cos_t, const double &s);
	double HcHChhfl(const double &cos_t, const double &s);
	double HcHChAfl(const double &cos_t, const double &s);
	double HcHChZfl(const double &cos_t, const double &s);
	double HcHCAAfl(const double &cos_t, const double &s);
	double HcHCAZfl(const double &cos_t, const double &s);
	double HcHCZZfl(const double &cos_t, const double &s);
	double HcHCwWfl(const double &cos_t, const double &s);
	double HcHCVEvefl(const double &cos_t, const double &s);
	double HcHCVMvmfl(const double &cos_t, const double &s);
	double HcHCVTvtfl(const double &cos_t, const double &s);
	double HcHCEefl(const double &cos_t, const double &s);
	double HcHCMmfl(const double &cos_t, const double &s);
	double HcHCTAtafl(const double &cos_t, const double &s);
	double HcHCUufl(const double &cos_t, const double &s);
	double HcHCCcfl(const double &cos_t, const double &s);
	double HcHCTtfl(const double &cos_t, const double &s);
	double HcHCDdfl(const double &cos_t, const double &s);
	double HcHCSsfl(const double &cos_t, const double &s);
	double HcHCBbfl(const double &cos_t, const double &s);
	double H1H1(const double &cos_t, const double &s);
	double H1H2(const double &cos_t, const double &s);
	double H1H3(const double &cos_t, const double &s);
	double H1Hc(const double &cos_t, const double &s);
	double H2H2(const double &cos_t, const double &s);
	double H2H3(const double &cos_t, const double &s);
	double H2Hc(const double &cos_t, const double &s);
	double H3H3(const double &cos_t, const double &s);
	double H3Hc(const double &cos_t, const double &s);
	double HcHc(const double &cos_t, const double &s);
	double wZH1H2();
	double wZH1H3();
	double wZH2H3();
	double wZHCHc();
	double wZhZ();
	double wZwW();
	double wZVEve();
	double wZVMvm();
	double wZVTvt();
	double wZEe();
	double wZMm();
	double wZTAta();
	double wZUu();
	double wZCc();
	double wZTt();
	double wZDd();
	double wZSs();
	double wZBb();
	double wWH1Hc();
	double wWH2Hc();
	double wWH3Hc();
	double wWhW();
	double wWAW();
	double wWZW();
	double wWveE();
	double wWvmM();
	double wWvtTA();
	double wWuD();
	double wWuS();
	double wWuB();
	double wWcD();
	double wWcS();
	double wWcB();
	double wWtD();
	double wWtS();
	double wWtB();
	double whhh();
	double whH1H1();
	double whH1H2();
	double whH1H3();
	double whH2H2();
	double whH2H3();
	double whH3H3();
	double whHCHc();
	double whZZ();
	double whwW();
	double whEe();
	double whMm();
	double whTAta();
	double whUu();
	double whCc();
	double whTt();
	double whDd();
	double whSs();
	double whBb();
	double wwZ();
	double wwW();
	double wwh();
}
