///////////////////CODE GENERATED VIA MATHEMATICA///////////////////


#pragma once

#include <cmath>

namespace DT{
	extern double MZ;
	extern double aEWM1;
	extern double Gf;
	extern double aS;
	extern double mHsm;
	extern double mHc;
	extern double alph1;
	extern double alph2;
	extern double alph3;
	extern double mH1;
	extern double mH2;
	extern double m22sq;
	extern double mssq;
	extern double L2;
	extern double L6;
	extern double L8;
	extern double MC;
	extern double MB;
	extern double MT;
	extern double GG;
	extern double Mnue;
	extern double Mnum;
	extern double Mnut;
	extern double Me;
	extern double MM;
	extern double MTA;
	extern double MU;
	extern double MD;
	extern double MS;
	extern double WT;
	extern double WZ;
	extern double WW;
	extern double WHsm;
	extern double WH1;
	extern double WH2;
	extern double WH3;
	extern double WHc;
	extern double E;
	extern double Pi;
	extern double MW;
	extern double EE;
	extern double CW2;
	extern double SW2;
	extern double CW;
	extern double SW;
	extern double g1;
	extern double g2;
	extern double v;
	extern double RR1x1;
	extern double RR1x2;
	extern double RR1x3;
	extern double RR2x1;
	extern double RR2x2;
	extern double RR2x3;
	extern double RR3x1;
	extern double RR3x2;
	extern double RR3x3;
	extern double mH3;
	extern double m11sq;
	extern double L1;
	extern double L3;
	extern double L4;
	extern double L5;
	extern double L7;
	extern double Treal;
	extern double Timag;
	extern double CKM1x1;
	extern double CKM1x2;
	extern double CKM1x3;
	extern double CKM2x1;
	extern double CKM2x2;
	extern double CKM2x3;
	extern double CKM3x1;
	extern double CKM3x2;
	extern double CKM3x3;
	extern double gc19;
	extern double gc20;
	extern double gc21;
	extern double gc22;
	extern double gc24;
	extern double gc27;
	extern double gc28;
	extern double gc30;
	extern double gc32;
	extern double gc35;
	extern double gc36;
	extern double gc38;
	extern double gc40;
	extern double gc42;
	extern double gc44;
	extern double gc45;
	extern double gc46;
	extern double gc47L;
	extern double gc47R;
	extern double gc48;
	extern double gc49L;
	extern double gc49R;
	extern double gc50;
	extern double gc51L;
	extern double gc51R;
	extern double gc52;
	extern double gc53L;
	extern double gc53R;
	extern double gc54L;
	extern double gc54R;
	extern double gc55L;
	extern double gc55R;
	extern double gc56L;
	extern double gc56R;
	extern double gc57L;
	extern double gc57R;
	extern double gc58L;
	extern double gc58R;
	extern double gc59L;
	extern double gc59R;
	extern double gc60L;
	extern double gc60R;
	extern double gc61L;
	extern double gc61R;
	extern double gc62L;
	extern double gc62R;
	extern double gc63;
	extern double gc64L;
	extern double gc64R;
	extern double gc65;
	extern double gc66L;
	extern double gc66R;
	extern double gc67;
	extern double gc68;
	extern double gc69;
	extern double gc70;
	extern double gc71L;
	extern double gc71R;
	extern double gc72L;
	extern double gc72R;
	extern double gc73L;
	extern double gc73R;
	extern double gc74L;
	extern double gc74R;
	extern double gc75L;
	extern double gc75R;
	extern double gc76L;
	extern double gc76R;
	extern double gc77L;
	extern double gc77R;
	extern double gc78L;
	extern double gc78R;
	extern double gc79L;
	extern double gc79R;
	extern double gc80L;
	extern double gc80R;
	extern double gc81;
	extern double gc82L;
	extern double gc82R;
	extern double gc83;
	extern double gc84L;
	extern double gc84R;
	extern double gc85;
	extern double gc86R;
	extern double gc87R;
	extern double gc88R;
	extern double gc164;
	extern double gc165;
	extern double gc166;
	extern double gc167;
	extern double gc168;
	extern double gc169;
	extern double gc173;
	extern double gc174;
	extern double gc175;
	extern double gc177;
	extern double gc179;
	extern double gc181;
	extern double gc185;
	extern double gc186;
	extern double gc188;
	extern double gc190;
	extern double gc192;
	extern double gc198;
	extern double gc205;
	extern double gc206;
	extern double gc209;
	extern double gc210;
	extern double gc211;
	extern double gc212;
	extern double gc213;
	extern double gc214;
	extern double gc227;
	extern double gc239;
	extern double gc240;
	extern double gc241;
	extern double gc242;
	extern double gc243;
	extern double gc244;
	extern double gc245;
	extern double gc246;
	extern double gc247;
	extern double gc248;
	extern double gc249;
	extern double gc250;
	extern double gc251;
	extern double gc252;
	extern double gc253;
	extern double gc254;
	extern double gc255;
	extern double gc256;
	extern double gc257;
	extern double gc258;
	extern double gc259;
	extern double gc260;
	extern double gc261;
	extern double gc262;
	extern double gc263;
	extern double gc264;
	extern double gc265;
	extern double gc266;
	extern double gc267;
	extern double gc268;
	extern double gc269;
	extern double gc270;
	extern double gc271;
	extern double gc272;
	extern double gc273L;
	extern double gc273R;
	extern double gc274L;
	extern double gc274R;
	extern double gc275L;
	extern double gc275R;
	extern double gc276L;
	extern double gc276R;
	extern double gc277L;
	extern double gc277R;
	extern double gc278L;
	extern double gc278R;
	extern double gc279L;
	extern double gc279R;
	extern double gc280L;
	extern double gc280R;
	extern double gc281L;
	extern double gc281R;
	extern double gc282;
	extern double gc283;
	extern double gc284;
	extern double EL;
	extern double ee;
	extern double gs;
	extern double G;
	extern double FAGS;

	double H1H1hh(double cos_t, double s);
	double H1H1hZ(double cos_t, double s);
	double H1H1ZZ(double cos_t, double s);
	double H1H1wW(double cos_t, double s);
	double H1H1Ee(double cos_t, double s);
	double H1H1Mm(double cos_t, double s);
	double H1H1TAta(double cos_t, double s);
	double H1H1Uu(double cos_t, double s);
	double H1H1Cc(double cos_t, double s);
	double H1H1Tt(double cos_t, double s);
	double H1H1Dd(double cos_t, double s);
	double H1H1Ss(double cos_t, double s);
	double H1H1Bb(double cos_t, double s);
	double H1H2hh(double cos_t, double s);
	double H1H2hZ(double cos_t, double s);
	double H1H2ZZ(double cos_t, double s);
	double H1H2wW(double cos_t, double s);
	double H1H2VEve(double cos_t, double s);
	double H1H2VMvm(double cos_t, double s);
	double H1H2VTvt(double cos_t, double s);
	double H1H2Ee(double cos_t, double s);
	double H1H2Mm(double cos_t, double s);
	double H1H2TAta(double cos_t, double s);
	double H1H2Uu(double cos_t, double s);
	double H1H2Cc(double cos_t, double s);
	double H1H2Tt(double cos_t, double s);
	double H1H2Dd(double cos_t, double s);
	double H1H2Ss(double cos_t, double s);
	double H1H2Bb(double cos_t, double s);
	double H1H3hh(double cos_t, double s);
	double H1H3hZ(double cos_t, double s);
	double H1H3ZZ(double cos_t, double s);
	double H1H3wW(double cos_t, double s);
	double H1H3VEve(double cos_t, double s);
	double H1H3VMvm(double cos_t, double s);
	double H1H3VTvt(double cos_t, double s);
	double H1H3Ee(double cos_t, double s);
	double H1H3Mm(double cos_t, double s);
	double H1H3TAta(double cos_t, double s);
	double H1H3Uu(double cos_t, double s);
	double H1H3Cc(double cos_t, double s);
	double H1H3Tt(double cos_t, double s);
	double H1H3Dd(double cos_t, double s);
	double H1H3Ss(double cos_t, double s);
	double H1H3Bb(double cos_t, double s);
	double H1HchW(double cos_t, double s);
	double H1HcAW(double cos_t, double s);
	double H1HcZW(double cos_t, double s);
	double H1HcveE(double cos_t, double s);
	double H1HcvmM(double cos_t, double s);
	double H1HcvtTA(double cos_t, double s);
	double H1HcuD(double cos_t, double s);
	double H1HcuS(double cos_t, double s);
	double H1HcuB(double cos_t, double s);
	double H1HccD(double cos_t, double s);
	double H1HccS(double cos_t, double s);
	double H1HccB(double cos_t, double s);
	double H1HctD(double cos_t, double s);
	double H1HctS(double cos_t, double s);
	double H1HctB(double cos_t, double s);
	double H2H2hh(double cos_t, double s);
	double H2H2hZ(double cos_t, double s);
	double H2H2ZZ(double cos_t, double s);
	double H2H2wW(double cos_t, double s);
	double H2H2Ee(double cos_t, double s);
	double H2H2Mm(double cos_t, double s);
	double H2H2TAta(double cos_t, double s);
	double H2H2Uu(double cos_t, double s);
	double H2H2Cc(double cos_t, double s);
	double H2H2Tt(double cos_t, double s);
	double H2H2Dd(double cos_t, double s);
	double H2H2Ss(double cos_t, double s);
	double H2H2Bb(double cos_t, double s);
	double H2H3hh(double cos_t, double s);
	double H2H3hZ(double cos_t, double s);
	double H2H3ZZ(double cos_t, double s);
	double H2H3wW(double cos_t, double s);
	double H2H3VEve(double cos_t, double s);
	double H2H3VMvm(double cos_t, double s);
	double H2H3VTvt(double cos_t, double s);
	double H2H3Ee(double cos_t, double s);
	double H2H3Mm(double cos_t, double s);
	double H2H3TAta(double cos_t, double s);
	double H2H3Uu(double cos_t, double s);
	double H2H3Cc(double cos_t, double s);
	double H2H3Tt(double cos_t, double s);
	double H2H3Dd(double cos_t, double s);
	double H2H3Ss(double cos_t, double s);
	double H2H3Bb(double cos_t, double s);
	double H2HchW(double cos_t, double s);
	double H2HcAW(double cos_t, double s);
	double H2HcZW(double cos_t, double s);
	double H2HcveE(double cos_t, double s);
	double H2HcvmM(double cos_t, double s);
	double H2HcvtTA(double cos_t, double s);
	double H2HcuD(double cos_t, double s);
	double H2HcuS(double cos_t, double s);
	double H2HcuB(double cos_t, double s);
	double H2HccD(double cos_t, double s);
	double H2HccS(double cos_t, double s);
	double H2HccB(double cos_t, double s);
	double H2HctD(double cos_t, double s);
	double H2HctS(double cos_t, double s);
	double H2HctB(double cos_t, double s);
	double H3H3hh(double cos_t, double s);
	double H3H3hZ(double cos_t, double s);
	double H3H3ZZ(double cos_t, double s);
	double H3H3wW(double cos_t, double s);
	double H3H3Ee(double cos_t, double s);
	double H3H3Mm(double cos_t, double s);
	double H3H3TAta(double cos_t, double s);
	double H3H3Uu(double cos_t, double s);
	double H3H3Cc(double cos_t, double s);
	double H3H3Tt(double cos_t, double s);
	double H3H3Dd(double cos_t, double s);
	double H3H3Ss(double cos_t, double s);
	double H3H3Bb(double cos_t, double s);
	double H3HchW(double cos_t, double s);
	double H3HcAW(double cos_t, double s);
	double H3HcZW(double cos_t, double s);
	double H3HcveE(double cos_t, double s);
	double H3HcvmM(double cos_t, double s);
	double H3HcvtTA(double cos_t, double s);
	double H3HcuD(double cos_t, double s);
	double H3HcuS(double cos_t, double s);
	double H3HcuB(double cos_t, double s);
	double H3HccD(double cos_t, double s);
	double H3HccS(double cos_t, double s);
	double H3HccB(double cos_t, double s);
	double H3HctD(double cos_t, double s);
	double H3HctS(double cos_t, double s);
	double H3HctB(double cos_t, double s);
	double HcHcWW(double cos_t, double s);
	double HcHChh(double cos_t, double s);
	double HcHChA(double cos_t, double s);
	double HcHChZ(double cos_t, double s);
	double HcHCAA(double cos_t, double s);
	double HcHCAZ(double cos_t, double s);
	double HcHCZZ(double cos_t, double s);
	double HcHCwW(double cos_t, double s);
	double HcHCVEve(double cos_t, double s);
	double HcHCVMvm(double cos_t, double s);
	double HcHCVTvt(double cos_t, double s);
	double HcHCEe(double cos_t, double s);
	double HcHCMm(double cos_t, double s);
	double HcHCTAta(double cos_t, double s);
	double HcHCUu(double cos_t, double s);
	double HcHCCc(double cos_t, double s);
	double HcHCTt(double cos_t, double s);
	double HcHCDd(double cos_t, double s);
	double HcHCSs(double cos_t, double s);
	double HcHCBb(double cos_t, double s);
	double H1H1hhfl(double cos_t, double s);
	double H1H1hZfl(double cos_t, double s);
	double H1H1ZZfl(double cos_t, double s);
	double H1H1wWfl(double cos_t, double s);
	double H1H1Eefl(double cos_t, double s);
	double H1H1Mmfl(double cos_t, double s);
	double H1H1TAtafl(double cos_t, double s);
	double H1H1Uufl(double cos_t, double s);
	double H1H1Ccfl(double cos_t, double s);
	double H1H1Ttfl(double cos_t, double s);
	double H1H1Ddfl(double cos_t, double s);
	double H1H1Ssfl(double cos_t, double s);
	double H1H1Bbfl(double cos_t, double s);
	double H1H2hhfl(double cos_t, double s);
	double H1H2hZfl(double cos_t, double s);
	double H1H2ZZfl(double cos_t, double s);
	double H1H2wWfl(double cos_t, double s);
	double H1H2VEvefl(double cos_t, double s);
	double H1H2VMvmfl(double cos_t, double s);
	double H1H2VTvtfl(double cos_t, double s);
	double H1H2Eefl(double cos_t, double s);
	double H1H2Mmfl(double cos_t, double s);
	double H1H2TAtafl(double cos_t, double s);
	double H1H2Uufl(double cos_t, double s);
	double H1H2Ccfl(double cos_t, double s);
	double H1H2Ttfl(double cos_t, double s);
	double H1H2Ddfl(double cos_t, double s);
	double H1H2Ssfl(double cos_t, double s);
	double H1H2Bbfl(double cos_t, double s);
	double H1H3hhfl(double cos_t, double s);
	double H1H3hZfl(double cos_t, double s);
	double H1H3ZZfl(double cos_t, double s);
	double H1H3wWfl(double cos_t, double s);
	double H1H3VEvefl(double cos_t, double s);
	double H1H3VMvmfl(double cos_t, double s);
	double H1H3VTvtfl(double cos_t, double s);
	double H1H3Eefl(double cos_t, double s);
	double H1H3Mmfl(double cos_t, double s);
	double H1H3TAtafl(double cos_t, double s);
	double H1H3Uufl(double cos_t, double s);
	double H1H3Ccfl(double cos_t, double s);
	double H1H3Ttfl(double cos_t, double s);
	double H1H3Ddfl(double cos_t, double s);
	double H1H3Ssfl(double cos_t, double s);
	double H1H3Bbfl(double cos_t, double s);
	double H1HchWfl(double cos_t, double s);
	double H1HcAWfl(double cos_t, double s);
	double H1HcZWfl(double cos_t, double s);
	double H1HcveEfl(double cos_t, double s);
	double H1HcvmMfl(double cos_t, double s);
	double H1HcvtTAfl(double cos_t, double s);
	double H1HcuDfl(double cos_t, double s);
	double H1HcuSfl(double cos_t, double s);
	double H1HcuBfl(double cos_t, double s);
	double H1HccDfl(double cos_t, double s);
	double H1HccSfl(double cos_t, double s);
	double H1HccBfl(double cos_t, double s);
	double H1HctDfl(double cos_t, double s);
	double H1HctSfl(double cos_t, double s);
	double H1HctBfl(double cos_t, double s);
	double H2H2hhfl(double cos_t, double s);
	double H2H2hZfl(double cos_t, double s);
	double H2H2ZZfl(double cos_t, double s);
	double H2H2wWfl(double cos_t, double s);
	double H2H2Eefl(double cos_t, double s);
	double H2H2Mmfl(double cos_t, double s);
	double H2H2TAtafl(double cos_t, double s);
	double H2H2Uufl(double cos_t, double s);
	double H2H2Ccfl(double cos_t, double s);
	double H2H2Ttfl(double cos_t, double s);
	double H2H2Ddfl(double cos_t, double s);
	double H2H2Ssfl(double cos_t, double s);
	double H2H2Bbfl(double cos_t, double s);
	double H2H3hhfl(double cos_t, double s);
	double H2H3hZfl(double cos_t, double s);
	double H2H3ZZfl(double cos_t, double s);
	double H2H3wWfl(double cos_t, double s);
	double H2H3VEvefl(double cos_t, double s);
	double H2H3VMvmfl(double cos_t, double s);
	double H2H3VTvtfl(double cos_t, double s);
	double H2H3Eefl(double cos_t, double s);
	double H2H3Mmfl(double cos_t, double s);
	double H2H3TAtafl(double cos_t, double s);
	double H2H3Uufl(double cos_t, double s);
	double H2H3Ccfl(double cos_t, double s);
	double H2H3Ttfl(double cos_t, double s);
	double H2H3Ddfl(double cos_t, double s);
	double H2H3Ssfl(double cos_t, double s);
	double H2H3Bbfl(double cos_t, double s);
	double H2HchWfl(double cos_t, double s);
	double H2HcAWfl(double cos_t, double s);
	double H2HcZWfl(double cos_t, double s);
	double H2HcveEfl(double cos_t, double s);
	double H2HcvmMfl(double cos_t, double s);
	double H2HcvtTAfl(double cos_t, double s);
	double H2HcuDfl(double cos_t, double s);
	double H2HcuSfl(double cos_t, double s);
	double H2HcuBfl(double cos_t, double s);
	double H2HccDfl(double cos_t, double s);
	double H2HccSfl(double cos_t, double s);
	double H2HccBfl(double cos_t, double s);
	double H2HctDfl(double cos_t, double s);
	double H2HctSfl(double cos_t, double s);
	double H2HctBfl(double cos_t, double s);
	double H3H3hhfl(double cos_t, double s);
	double H3H3hZfl(double cos_t, double s);
	double H3H3ZZfl(double cos_t, double s);
	double H3H3wWfl(double cos_t, double s);
	double H3H3Eefl(double cos_t, double s);
	double H3H3Mmfl(double cos_t, double s);
	double H3H3TAtafl(double cos_t, double s);
	double H3H3Uufl(double cos_t, double s);
	double H3H3Ccfl(double cos_t, double s);
	double H3H3Ttfl(double cos_t, double s);
	double H3H3Ddfl(double cos_t, double s);
	double H3H3Ssfl(double cos_t, double s);
	double H3H3Bbfl(double cos_t, double s);
	double H3HchWfl(double cos_t, double s);
	double H3HcAWfl(double cos_t, double s);
	double H3HcZWfl(double cos_t, double s);
	double H3HcveEfl(double cos_t, double s);
	double H3HcvmMfl(double cos_t, double s);
	double H3HcvtTAfl(double cos_t, double s);
	double H3HcuDfl(double cos_t, double s);
	double H3HcuSfl(double cos_t, double s);
	double H3HcuBfl(double cos_t, double s);
	double H3HccDfl(double cos_t, double s);
	double H3HccSfl(double cos_t, double s);
	double H3HccBfl(double cos_t, double s);
	double H3HctDfl(double cos_t, double s);
	double H3HctSfl(double cos_t, double s);
	double H3HctBfl(double cos_t, double s);
	double HcHcWWfl(double cos_t, double s);
	double HcHChhfl(double cos_t, double s);
	double HcHChAfl(double cos_t, double s);
	double HcHChZfl(double cos_t, double s);
	double HcHCAAfl(double cos_t, double s);
	double HcHCAZfl(double cos_t, double s);
	double HcHCZZfl(double cos_t, double s);
	double HcHCwWfl(double cos_t, double s);
	double HcHCVEvefl(double cos_t, double s);
	double HcHCVMvmfl(double cos_t, double s);
	double HcHCVTvtfl(double cos_t, double s);
	double HcHCEefl(double cos_t, double s);
	double HcHCMmfl(double cos_t, double s);
	double HcHCTAtafl(double cos_t, double s);
	double HcHCUufl(double cos_t, double s);
	double HcHCCcfl(double cos_t, double s);
	double HcHCTtfl(double cos_t, double s);
	double HcHCDdfl(double cos_t, double s);
	double HcHCSsfl(double cos_t, double s);
	double HcHCBbfl(double cos_t, double s);
	double H1H1(double cos_t, double s);
	double H1H2(double cos_t, double s);
	double H1H3(double cos_t, double s);
	double H1Hc(double cos_t, double s);
	double H2H2(double cos_t, double s);
	double H2H3(double cos_t, double s);
	double H2Hc(double cos_t, double s);
	double H3H3(double cos_t, double s);
	double H3Hc(double cos_t, double s);
	double HcHc(double cos_t, double s);
	double wZH1H2();
	double wZH1H3();
	double wZH2H3();
	double wZHCHc();
	double wZhZ();
	double wZwW();
	double wZVEve();
	double wZVMvm();
	double wZVTvt();
	double wZEe();
	double wZMm();
	double wZTAta();
	double wZUu();
	double wZCc();
	double wZTt();
	double wZDd();
	double wZSs();
	double wZBb();
	double wWH1Hc();
	double wWH2Hc();
	double wWH3Hc();
	double wWhW();
	double wWAW();
	double wWZW();
	double wWveE();
	double wWvmM();
	double wWvtTA();
	double wWuD();
	double wWuS();
	double wWuB();
	double wWcD();
	double wWcS();
	double wWcB();
	double wWtD();
	double wWtS();
	double wWtB();
	double whhh();
	double whH1H1();
	double whH1H2();
	double whH1H3();
	double whH2H2();
	double whH2H3();
	double whH3H3();
	double whHCHc();
	double whZZ();
	double whwW();
	double whEe();
	double whMm();
	double whTAta();
	double whUu();
	double whCc();
	double whTt();
	double whDd();
	double whSs();
	double whBb();
	double wwZ();
	double wwW();
	double wwh();
}
