///////////////////CODE GENERATED VIA MATHEMATICA///////////////////


#pragma once

#include <cmath>

namespace DT{
namespace PAR{
	extern double aEWM1;
	extern double Gf;
	extern double aS;
	extern double ymdo;
	extern double ymup;
	extern double yms;
	extern double ymc;
	extern double ymb;
	extern double ymt;
	extern double yme;
	extern double ymm;
	extern double ymtau;
	extern double s12;
	extern double s23;
	extern double s13;
	extern double Mchi;
	extern double lamHS;
	extern double lamPQ;
	extern double lamPL;
	extern double lamPLprime;
	extern double lamHPQ;
	extern double lamHPL;
	extern double lamPQPL;
	extern double lamPQPLprime;
	extern double ymsD;
	extern double ymbD;
	extern double ymmD;
	extern double GG;
	extern double MZ;
	extern double Me;
	extern double MMU;
	extern double MTA;
	extern double MU;
	extern double MC;
	extern double MT;
	extern double MD;
	extern double MS;
	extern double MB;
	extern double MH;
	extern double MS0;
	extern double MA0;
	extern double MphiQ;
	extern double WZ;
	extern double WW;
	extern double WT;
	extern double WH;
	extern double WchiM;
	extern double Wchi0;
	extern double WS0;
	extern double WA0;
	extern double WphiQ;
	extern double E;
	extern double Pi;
	extern double Mox118x0;
	extern double aEW;
	extern double MW;
	extern double sw2;
	extern double EE;
	extern double cw;
	extern double sw;
	extern double gw;
	extern double g1;
	extern double vev;
	extern double ye;
	extern double ym;
	extern double ytau;
	extern double yup;
	extern double yc;
	extern double yt;
	extern double ydo;
	extern double ys;
	extern double yb;
	extern double c12;
	extern double c23;
	extern double c13;
	extern double CKM1x1;
	extern double CKM1x2;
	extern double CKM1x3;
	extern double CKM2x1;
	extern double CKM2x2;
	extern double CKM2x3;
	extern double CKM3x1;
	extern double CKM3x2;
	extern double CKM3x3;
	extern double lamH;
	extern double muH;
	extern double MchiM;
	extern double Mchi0;
	extern double muPQ;
	extern double muPL;
	extern double lamHPLprime;
	extern double muPLprime;
	extern double token1;
	extern double token2;
	extern double token3;
	extern double token4;
	extern double token5;
	extern double token6;
	extern double token7;
	extern double token8;
	extern double token9;
	extern double token10;
	extern double token11;
	extern double token12;
	extern double token13;
	extern double token14;
	extern double token15;
	extern double token16;
	extern double token17;
	extern double token18;
	extern double token19;
	extern double token20;
	extern double token21;
	extern double token22;
	extern double token23;
	extern double token24;
	extern double token25;
	extern double token26;
	extern double token27;
	extern double token28;
	extern double token29;
	extern double token30;
	extern double token31;
	extern double token32;
	extern double token33;
	extern double token34;
	extern double token35;
	extern double token36;
	extern double token37;
	extern double token38;
	extern double token39;
	extern double token40;
	extern double token41;
	extern double token42;
	extern double token43;
	extern double token44;
	extern double token45;
	extern double token46;
	extern double token47;
	extern double token48;
	extern double token49;
	extern double token50;
	extern double token51;
	extern double token52;
	extern double token53;
	extern double token54;
	extern double token55;
	extern double token56;
	extern double token57;
	extern double token58;
	extern double token59;
	extern double token60;
	extern double token61;
	extern double token62;
	extern double token63;
	extern double token64;
	extern double token65;
	extern double token66;
	extern double token67;
	extern double token68;
	extern double token69;
	extern double token70;
	extern double token71;
	extern double token72;
	extern double token73;
	extern double token74;
	extern double token75;
	extern double token76;
	extern double token77;
	extern double token78;
	extern double token79;
	extern double token80;
	extern double token81;
	extern double token82;
	extern double token83;
	extern double token84;
	extern double token85;
	extern double token86;
	extern double token87;
	extern double token88;
	extern double token89;
	extern double token90;
	extern double token91;
	extern double token92;
	extern double token93;
	extern double token94;
	extern double token95;
	extern double token96;
	extern double token97;
	extern double token98;
	extern double token99;
	extern double EL;
	extern double ee;
	extern double gs;
	extern double G;
	extern double FAGS;
}
	double chiMchiMmumu(const double &cos_t, const double &s);
	double chiMCHIMHZ(const double &cos_t, const double &s);
	double chiMCHIMAA(const double &cos_t, const double &s);
	double chiMCHIMAZ(const double &cos_t, const double &s);
	double chiMCHIMZZ(const double &cos_t, const double &s);
	double chiMCHIMwW(const double &cos_t, const double &s);
	double chiMCHIMVEve(const double &cos_t, const double &s);
	double chiMCHIMVMvm(const double &cos_t, const double &s);
	double chiMCHIMVTvt(const double &cos_t, const double &s);
	double chiMCHIMEe(const double &cos_t, const double &s);
	double chiMCHIMMUmu(const double &cos_t, const double &s);
	double chiMCHIMTAta(const double &cos_t, const double &s);
	double chiMCHIMUu(const double &cos_t, const double &s);
	double chiMCHIMCc(const double &cos_t, const double &s);
	double chiMCHIMTt(const double &cos_t, const double &s);
	double chiMCHIMDd(const double &cos_t, const double &s);
	double chiMCHIMSs(const double &cos_t, const double &s);
	double chiMCHIMSb(const double &cos_t, const double &s);
	double chiMCHIMsB(const double &cos_t, const double &s);
	double chiMCHIMBb(const double &cos_t, const double &s);
	double chiMchi0vmmu(const double &cos_t, const double &s);
	double chiMCHI0Hw(const double &cos_t, const double &s);
	double chiMCHI0Aw(const double &cos_t, const double &s);
	double chiMCHI0Zw(const double &cos_t, const double &s);
	double chiMCHI0VEe(const double &cos_t, const double &s);
	double chiMCHI0VMmu(const double &cos_t, const double &s);
	double chiMCHI0VTta(const double &cos_t, const double &s);
	double chiMCHI0Ud(const double &cos_t, const double &s);
	double chiMCHI0Us(const double &cos_t, const double &s);
	double chiMCHI0Ub(const double &cos_t, const double &s);
	double chiMCHI0Cd(const double &cos_t, const double &s);
	double chiMCHI0Cs(const double &cos_t, const double &s);
	double chiMCHI0Cb(const double &cos_t, const double &s);
	double chiMCHI0Td(const double &cos_t, const double &s);
	double chiMCHI0Ts(const double &cos_t, const double &s);
	double chiMCHI0Tb(const double &cos_t, const double &s);
	double chiMS0Hmu(const double &cos_t, const double &s);
	double chiMS0Amu(const double &cos_t, const double &s);
	double chiMS0Zmu(const double &cos_t, const double &s);
	double chiMS0wvm(const double &cos_t, const double &s);
	double chiMA0Hmu(const double &cos_t, const double &s);
	double chiMA0Amu(const double &cos_t, const double &s);
	double chiMA0Zmu(const double &cos_t, const double &s);
	double chiMA0wvm(const double &cos_t, const double &s);
	double chiMpQHs(const double &cos_t, const double &s);
	double chiMpQHb(const double &cos_t, const double &s);
	double chiMpQAs(const double &cos_t, const double &s);
	double chiMpQAb(const double &cos_t, const double &s);
	double chiMpQZs(const double &cos_t, const double &s);
	double chiMpQZb(const double &cos_t, const double &s);
	double chiMpQwu(const double &cos_t, const double &s);
	double chiMpQwc(const double &cos_t, const double &s);
	double chiMpQwt(const double &cos_t, const double &s);
	double chiMpQGs(const double &cos_t, const double &s);
	double chiMpQGb(const double &cos_t, const double &s);
	double chi0chi0vmvm(const double &cos_t, const double &s);
	double chi0CHI0HZ(const double &cos_t, const double &s);
	double chi0CHI0ZZ(const double &cos_t, const double &s);
	double chi0CHI0wW(const double &cos_t, const double &s);
	double chi0CHI0VEve(const double &cos_t, const double &s);
	double chi0CHI0VMvm(const double &cos_t, const double &s);
	double chi0CHI0VTvt(const double &cos_t, const double &s);
	double chi0CHI0Ee(const double &cos_t, const double &s);
	double chi0CHI0MUmu(const double &cos_t, const double &s);
	double chi0CHI0TAta(const double &cos_t, const double &s);
	double chi0CHI0Uu(const double &cos_t, const double &s);
	double chi0CHI0Uc(const double &cos_t, const double &s);
	double chi0CHI0Ut(const double &cos_t, const double &s);
	double chi0CHI0uC(const double &cos_t, const double &s);
	double chi0CHI0uT(const double &cos_t, const double &s);
	double chi0CHI0Cc(const double &cos_t, const double &s);
	double chi0CHI0Ct(const double &cos_t, const double &s);
	double chi0CHI0cT(const double &cos_t, const double &s);
	double chi0CHI0Tt(const double &cos_t, const double &s);
	double chi0CHI0Dd(const double &cos_t, const double &s);
	double chi0CHI0Ss(const double &cos_t, const double &s);
	double chi0CHI0Bb(const double &cos_t, const double &s);
	double chi0S0Hvm(const double &cos_t, const double &s);
	double chi0S0Zvm(const double &cos_t, const double &s);
	double chi0S0Wmu(const double &cos_t, const double &s);
	double chi0A0Hvm(const double &cos_t, const double &s);
	double chi0A0Zvm(const double &cos_t, const double &s);
	double chi0A0Wmu(const double &cos_t, const double &s);
	double chi0pQHu(const double &cos_t, const double &s);
	double chi0pQHc(const double &cos_t, const double &s);
	double chi0pQHt(const double &cos_t, const double &s);
	double chi0pQAu(const double &cos_t, const double &s);
	double chi0pQAc(const double &cos_t, const double &s);
	double chi0pQAt(const double &cos_t, const double &s);
	double chi0pQZu(const double &cos_t, const double &s);
	double chi0pQZc(const double &cos_t, const double &s);
	double chi0pQZt(const double &cos_t, const double &s);
	double chi0pQWd(const double &cos_t, const double &s);
	double chi0pQWs(const double &cos_t, const double &s);
	double chi0pQWb(const double &cos_t, const double &s);
	double chi0pQGu(const double &cos_t, const double &s);
	double chi0pQGc(const double &cos_t, const double &s);
	double chi0pQGt(const double &cos_t, const double &s);
	double S0S0HH(const double &cos_t, const double &s);
	double S0S0ZZ(const double &cos_t, const double &s);
	double S0S0wW(const double &cos_t, const double &s);
	double S0S0VMvm(const double &cos_t, const double &s);
	double S0S0Ee(const double &cos_t, const double &s);
	double S0S0MUmu(const double &cos_t, const double &s);
	double S0S0TAta(const double &cos_t, const double &s);
	double S0S0Uu(const double &cos_t, const double &s);
	double S0S0Cc(const double &cos_t, const double &s);
	double S0S0Tt(const double &cos_t, const double &s);
	double S0S0Dd(const double &cos_t, const double &s);
	double S0S0Ss(const double &cos_t, const double &s);
	double S0S0Bb(const double &cos_t, const double &s);
	double S0A0VMvm(const double &cos_t, const double &s);
	double S0A0MUmu(const double &cos_t, const double &s);
	double S0pQVMu(const double &cos_t, const double &s);
	double S0pQVMc(const double &cos_t, const double &s);
	double S0pQVMt(const double &cos_t, const double &s);
	double S0pQMUs(const double &cos_t, const double &s);
	double S0pQMUb(const double &cos_t, const double &s);
	double A0A0HH(const double &cos_t, const double &s);
	double A0A0ZZ(const double &cos_t, const double &s);
	double A0A0wW(const double &cos_t, const double &s);
	double A0A0VMvm(const double &cos_t, const double &s);
	double A0A0Ee(const double &cos_t, const double &s);
	double A0A0MUmu(const double &cos_t, const double &s);
	double A0A0TAta(const double &cos_t, const double &s);
	double A0A0Uu(const double &cos_t, const double &s);
	double A0A0Cc(const double &cos_t, const double &s);
	double A0A0Tt(const double &cos_t, const double &s);
	double A0A0Dd(const double &cos_t, const double &s);
	double A0A0Ss(const double &cos_t, const double &s);
	double A0A0Bb(const double &cos_t, const double &s);
	double A0pQVMu(const double &cos_t, const double &s);
	double A0pQVMc(const double &cos_t, const double &s);
	double A0pQVMt(const double &cos_t, const double &s);
	double A0pQMUs(const double &cos_t, const double &s);
	double A0pQMUb(const double &cos_t, const double &s);
	double pQPQHH(const double &cos_t, const double &s);
	double pQPQHA(const double &cos_t, const double &s);
	double pQPQHZ(const double &cos_t, const double &s);
	double pQPQHG(const double &cos_t, const double &s);
	double pQPQAA(const double &cos_t, const double &s);
	double pQPQAZ(const double &cos_t, const double &s);
	double pQPQAG(const double &cos_t, const double &s);
	double pQPQZZ(const double &cos_t, const double &s);
	double pQPQZG(const double &cos_t, const double &s);
	double pQPQwW(const double &cos_t, const double &s);
	double pQPQGG(const double &cos_t, const double &s);
	double pQPQVEve(const double &cos_t, const double &s);
	double pQPQVMvm(const double &cos_t, const double &s);
	double pQPQVTvt(const double &cos_t, const double &s);
	double pQPQEe(const double &cos_t, const double &s);
	double pQPQMUmu(const double &cos_t, const double &s);
	double pQPQTAta(const double &cos_t, const double &s);
	double pQPQUu(const double &cos_t, const double &s);
	double pQPQUc(const double &cos_t, const double &s);
	double pQPQUt(const double &cos_t, const double &s);
	double pQPQuC(const double &cos_t, const double &s);
	double pQPQuT(const double &cos_t, const double &s);
	double pQPQCc(const double &cos_t, const double &s);
	double pQPQCt(const double &cos_t, const double &s);
	double pQPQcT(const double &cos_t, const double &s);
	double pQPQTt(const double &cos_t, const double &s);
	double pQPQDd(const double &cos_t, const double &s);
	double pQPQSs(const double &cos_t, const double &s);
	double pQPQSb(const double &cos_t, const double &s);
	double pQPQsB(const double &cos_t, const double &s);
	double pQPQBb(const double &cos_t, const double &s);
	double chiMchiMmumufl(const double &cos_t, const double &s);
	double chiMCHIMHZfl(const double &cos_t, const double &s);
	double chiMCHIMAAfl(const double &cos_t, const double &s);
	double chiMCHIMAZfl(const double &cos_t, const double &s);
	double chiMCHIMZZfl(const double &cos_t, const double &s);
	double chiMCHIMwWfl(const double &cos_t, const double &s);
	double chiMCHIMVEvefl(const double &cos_t, const double &s);
	double chiMCHIMVMvmfl(const double &cos_t, const double &s);
	double chiMCHIMVTvtfl(const double &cos_t, const double &s);
	double chiMCHIMEefl(const double &cos_t, const double &s);
	double chiMCHIMMUmufl(const double &cos_t, const double &s);
	double chiMCHIMTAtafl(const double &cos_t, const double &s);
	double chiMCHIMUufl(const double &cos_t, const double &s);
	double chiMCHIMCcfl(const double &cos_t, const double &s);
	double chiMCHIMTtfl(const double &cos_t, const double &s);
	double chiMCHIMDdfl(const double &cos_t, const double &s);
	double chiMCHIMSsfl(const double &cos_t, const double &s);
	double chiMCHIMSbfl(const double &cos_t, const double &s);
	double chiMCHIMsBfl(const double &cos_t, const double &s);
	double chiMCHIMBbfl(const double &cos_t, const double &s);
	double chiMchi0vmmufl(const double &cos_t, const double &s);
	double chiMCHI0Hwfl(const double &cos_t, const double &s);
	double chiMCHI0Awfl(const double &cos_t, const double &s);
	double chiMCHI0Zwfl(const double &cos_t, const double &s);
	double chiMCHI0VEefl(const double &cos_t, const double &s);
	double chiMCHI0VMmufl(const double &cos_t, const double &s);
	double chiMCHI0VTtafl(const double &cos_t, const double &s);
	double chiMCHI0Udfl(const double &cos_t, const double &s);
	double chiMCHI0Usfl(const double &cos_t, const double &s);
	double chiMCHI0Ubfl(const double &cos_t, const double &s);
	double chiMCHI0Cdfl(const double &cos_t, const double &s);
	double chiMCHI0Csfl(const double &cos_t, const double &s);
	double chiMCHI0Cbfl(const double &cos_t, const double &s);
	double chiMCHI0Tdfl(const double &cos_t, const double &s);
	double chiMCHI0Tsfl(const double &cos_t, const double &s);
	double chiMCHI0Tbfl(const double &cos_t, const double &s);
	double chiMS0Hmufl(const double &cos_t, const double &s);
	double chiMS0Amufl(const double &cos_t, const double &s);
	double chiMS0Zmufl(const double &cos_t, const double &s);
	double chiMS0wvmfl(const double &cos_t, const double &s);
	double chiMA0Hmufl(const double &cos_t, const double &s);
	double chiMA0Amufl(const double &cos_t, const double &s);
	double chiMA0Zmufl(const double &cos_t, const double &s);
	double chiMA0wvmfl(const double &cos_t, const double &s);
	double chiMpQHsfl(const double &cos_t, const double &s);
	double chiMpQHbfl(const double &cos_t, const double &s);
	double chiMpQAsfl(const double &cos_t, const double &s);
	double chiMpQAbfl(const double &cos_t, const double &s);
	double chiMpQZsfl(const double &cos_t, const double &s);
	double chiMpQZbfl(const double &cos_t, const double &s);
	double chiMpQwufl(const double &cos_t, const double &s);
	double chiMpQwcfl(const double &cos_t, const double &s);
	double chiMpQwtfl(const double &cos_t, const double &s);
	double chiMpQGsfl(const double &cos_t, const double &s);
	double chiMpQGbfl(const double &cos_t, const double &s);
	double chi0chi0vmvmfl(const double &cos_t, const double &s);
	double chi0CHI0HZfl(const double &cos_t, const double &s);
	double chi0CHI0ZZfl(const double &cos_t, const double &s);
	double chi0CHI0wWfl(const double &cos_t, const double &s);
	double chi0CHI0VEvefl(const double &cos_t, const double &s);
	double chi0CHI0VMvmfl(const double &cos_t, const double &s);
	double chi0CHI0VTvtfl(const double &cos_t, const double &s);
	double chi0CHI0Eefl(const double &cos_t, const double &s);
	double chi0CHI0MUmufl(const double &cos_t, const double &s);
	double chi0CHI0TAtafl(const double &cos_t, const double &s);
	double chi0CHI0Uufl(const double &cos_t, const double &s);
	double chi0CHI0Ucfl(const double &cos_t, const double &s);
	double chi0CHI0Utfl(const double &cos_t, const double &s);
	double chi0CHI0uCfl(const double &cos_t, const double &s);
	double chi0CHI0uTfl(const double &cos_t, const double &s);
	double chi0CHI0Ccfl(const double &cos_t, const double &s);
	double chi0CHI0Ctfl(const double &cos_t, const double &s);
	double chi0CHI0cTfl(const double &cos_t, const double &s);
	double chi0CHI0Ttfl(const double &cos_t, const double &s);
	double chi0CHI0Ddfl(const double &cos_t, const double &s);
	double chi0CHI0Ssfl(const double &cos_t, const double &s);
	double chi0CHI0Bbfl(const double &cos_t, const double &s);
	double chi0S0Hvmfl(const double &cos_t, const double &s);
	double chi0S0Zvmfl(const double &cos_t, const double &s);
	double chi0S0Wmufl(const double &cos_t, const double &s);
	double chi0A0Hvmfl(const double &cos_t, const double &s);
	double chi0A0Zvmfl(const double &cos_t, const double &s);
	double chi0A0Wmufl(const double &cos_t, const double &s);
	double chi0pQHufl(const double &cos_t, const double &s);
	double chi0pQHcfl(const double &cos_t, const double &s);
	double chi0pQHtfl(const double &cos_t, const double &s);
	double chi0pQAufl(const double &cos_t, const double &s);
	double chi0pQAcfl(const double &cos_t, const double &s);
	double chi0pQAtfl(const double &cos_t, const double &s);
	double chi0pQZufl(const double &cos_t, const double &s);
	double chi0pQZcfl(const double &cos_t, const double &s);
	double chi0pQZtfl(const double &cos_t, const double &s);
	double chi0pQWdfl(const double &cos_t, const double &s);
	double chi0pQWsfl(const double &cos_t, const double &s);
	double chi0pQWbfl(const double &cos_t, const double &s);
	double chi0pQGufl(const double &cos_t, const double &s);
	double chi0pQGcfl(const double &cos_t, const double &s);
	double chi0pQGtfl(const double &cos_t, const double &s);
	double S0S0HHfl(const double &cos_t, const double &s);
	double S0S0ZZfl(const double &cos_t, const double &s);
	double S0S0wWfl(const double &cos_t, const double &s);
	double S0S0VMvmfl(const double &cos_t, const double &s);
	double S0S0Eefl(const double &cos_t, const double &s);
	double S0S0MUmufl(const double &cos_t, const double &s);
	double S0S0TAtafl(const double &cos_t, const double &s);
	double S0S0Uufl(const double &cos_t, const double &s);
	double S0S0Ccfl(const double &cos_t, const double &s);
	double S0S0Ttfl(const double &cos_t, const double &s);
	double S0S0Ddfl(const double &cos_t, const double &s);
	double S0S0Ssfl(const double &cos_t, const double &s);
	double S0S0Bbfl(const double &cos_t, const double &s);
	double S0A0VMvmfl(const double &cos_t, const double &s);
	double S0A0MUmufl(const double &cos_t, const double &s);
	double S0pQVMufl(const double &cos_t, const double &s);
	double S0pQVMcfl(const double &cos_t, const double &s);
	double S0pQVMtfl(const double &cos_t, const double &s);
	double S0pQMUsfl(const double &cos_t, const double &s);
	double S0pQMUbfl(const double &cos_t, const double &s);
	double A0A0HHfl(const double &cos_t, const double &s);
	double A0A0ZZfl(const double &cos_t, const double &s);
	double A0A0wWfl(const double &cos_t, const double &s);
	double A0A0VMvmfl(const double &cos_t, const double &s);
	double A0A0Eefl(const double &cos_t, const double &s);
	double A0A0MUmufl(const double &cos_t, const double &s);
	double A0A0TAtafl(const double &cos_t, const double &s);
	double A0A0Uufl(const double &cos_t, const double &s);
	double A0A0Ccfl(const double &cos_t, const double &s);
	double A0A0Ttfl(const double &cos_t, const double &s);
	double A0A0Ddfl(const double &cos_t, const double &s);
	double A0A0Ssfl(const double &cos_t, const double &s);
	double A0A0Bbfl(const double &cos_t, const double &s);
	double A0pQVMufl(const double &cos_t, const double &s);
	double A0pQVMcfl(const double &cos_t, const double &s);
	double A0pQVMtfl(const double &cos_t, const double &s);
	double A0pQMUsfl(const double &cos_t, const double &s);
	double A0pQMUbfl(const double &cos_t, const double &s);
	double pQPQHHfl(const double &cos_t, const double &s);
	double pQPQHAfl(const double &cos_t, const double &s);
	double pQPQHZfl(const double &cos_t, const double &s);
	double pQPQHGfl(const double &cos_t, const double &s);
	double pQPQAAfl(const double &cos_t, const double &s);
	double pQPQAZfl(const double &cos_t, const double &s);
	double pQPQAGfl(const double &cos_t, const double &s);
	double pQPQZZfl(const double &cos_t, const double &s);
	double pQPQZGfl(const double &cos_t, const double &s);
	double pQPQwWfl(const double &cos_t, const double &s);
	double pQPQGGfl(const double &cos_t, const double &s);
	double pQPQVEvefl(const double &cos_t, const double &s);
	double pQPQVMvmfl(const double &cos_t, const double &s);
	double pQPQVTvtfl(const double &cos_t, const double &s);
	double pQPQEefl(const double &cos_t, const double &s);
	double pQPQMUmufl(const double &cos_t, const double &s);
	double pQPQTAtafl(const double &cos_t, const double &s);
	double pQPQUufl(const double &cos_t, const double &s);
	double pQPQUcfl(const double &cos_t, const double &s);
	double pQPQUtfl(const double &cos_t, const double &s);
	double pQPQuCfl(const double &cos_t, const double &s);
	double pQPQuTfl(const double &cos_t, const double &s);
	double pQPQCcfl(const double &cos_t, const double &s);
	double pQPQCtfl(const double &cos_t, const double &s);
	double pQPQcTfl(const double &cos_t, const double &s);
	double pQPQTtfl(const double &cos_t, const double &s);
	double pQPQDdfl(const double &cos_t, const double &s);
	double pQPQSsfl(const double &cos_t, const double &s);
	double pQPQSbfl(const double &cos_t, const double &s);
	double pQPQsBfl(const double &cos_t, const double &s);
	double pQPQBbfl(const double &cos_t, const double &s);
	double wtHt();
	double wtpQchi0();
	double wtAt();
	double wtZt();
	double wtWd();
	double wtWs();
	double wtWb();
	double wtGt();
	double wHHH();
	double wHS0S0();
	double wHA0A0();
	double wHPQpQ();
	double wHZZ();
	double wHwW();
	double wHEe();
	double wHMUmu();
	double wHTAta();
	double wHUu();
	double wHCc();
	double wHTt();
	double wHDd();
	double wHSs();
	double wHBb();
	double wwt(const double QCDaS);
	double wwH(const double QCDaS);
}
