(* Patched for use with FeynCalc *)
(* * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * *)
(*                                                                             *)
(*         This file has been automatically generated by FeynRules.            *)
(*                                                                             *)
(* * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * *)


FR$ModelInformation={
  ModelName->"bdm5_lamhs",
  Authors -> {"N. Christensen", "C. Duhr", "B. Fuks"},
  Version -> "1.4.6",
  Date -> "15. 04. 2014",
  Institutions -> {"Michigan State University", "Universite catholique de Louvain (CP3)", "IPHC Strasbourg / University of Strasbourg"},
  Emails -> {"neil@pa.msu.edu", "claude.duhr@uclouvain.be", "benjamin.fuks@cnrs.in2p3.fr"},
  URLs -> "http://feynrules.phys.ucl.ac.be/view/Main/StandardModel"};

FR$ClassesTranslation={A -> V[1], Z -> V[2], W -> V[3], G -> V[4], ghA -> U[1], ghZ -> U[2], ghWp -> U[3], ghWm -> U[4], ghG -> U[5], ve -> F[1], vm -> F[2], vt -> F[3], e -> F[4], mu -> F[5], ta -> F[6], u -> F[7], c -> F[8], t -> F[9], d -> F[10], s -> F[11], b -> F[12], H -> S[1], G0 -> S[2], GP -> S[3], chiM -> F[13], chi0 -> F[14], S0 -> S[4], A0 -> S[5], pQ -> S[6]};

FR$InteractionOrderPerturbativeExpansion={{QCD, 0}, {QED, 0}};

FR$GoldstoneList={S[2], S[3]};

(*     Declared indices    *)

IndexRange[ Index[Gluon] ] = NoUnfold[ Range[ 8 ] ]

IndexRange[ Index[SU2W] ] = Range[ 3 ]

IndexRange[ Index[Generation] ] = Range[ 3 ]

IndexRange[ Index[Colour] ] = NoUnfold[ Range[ 3 ] ]

IndexRange[ Index[SU2D] ] = Range[ 2 ]

(*     Declared particles    *)

M$ClassesDescription = {
V[1] == {
    SelfConjugate -> True,
    PropagatorType -> Sine,
    PropagatorArrow -> None,
    Mass -> 0,
    Indices -> {},
    PropagatorLabel -> "A" },

V[2] == {
    SelfConjugate -> True,
    PropagatorType -> Sine,
    PropagatorArrow -> None,
    Mass -> FCGV["MZ"],
    Indices -> {},
    PropagatorLabel -> "Z" },

V[3] == {
    SelfConjugate -> False,
    QuantumNumbers -> {Q},
    PropagatorType -> Sine,
    PropagatorArrow -> Forward,
    Mass -> FCGV["MW"],
    Indices -> {},
    PropagatorLabel -> "W" },

V[4] == {
    SelfConjugate -> True,
    PropagatorType -> Cycles,
    PropagatorArrow -> None,
    Mass -> 0,
    Indices -> {Index[Gluon]},
    PropagatorLabel -> "G" },

U[1] == {
    SelfConjugate -> False,
    QuantumNumbers -> {GhostNumber},
    PropagatorType -> GhostDash,
    PropagatorArrow -> Forward,
    Mass -> 0,
    Indices -> {},
    PropagatorLabel -> "ghA" },

U[2] == {
    SelfConjugate -> False,
    QuantumNumbers -> {GhostNumber},
    PropagatorType -> GhostDash,
    PropagatorArrow -> Forward,
    Mass -> FCGV["MZ"],
    Indices -> {},
    PropagatorLabel -> "ghZ" },

U[3] == {
    SelfConjugate -> False,
    QuantumNumbers -> {GhostNumber, Q},
    PropagatorType -> GhostDash,
    PropagatorArrow -> Forward,
    Mass -> FCGV["MW"],
    Indices -> {},
    PropagatorLabel -> "ghWp" },

U[4] == {
    SelfConjugate -> False,
    QuantumNumbers -> {GhostNumber, -Q},
    PropagatorType -> GhostDash,
    PropagatorArrow -> Forward,
    Mass -> FCGV["MW"],
    Indices -> {},
    PropagatorLabel -> "ghWm" },

U[5] == {
    SelfConjugate -> False,
    QuantumNumbers -> {GhostNumber},
    PropagatorType -> GhostDash,
    PropagatorArrow -> Forward,
    Mass -> 0,
    Indices -> {Index[Gluon]},
    PropagatorLabel -> "ghG" },

F[1] == {
    SelfConjugate -> False,
    QuantumNumbers -> {LeptonNumber},
    PropagatorType -> Straight,
    PropagatorArrow -> Forward,
    Mass -> 0,
    Indices -> {},
    PropagatorLabel -> "ve" },

F[2] == {
    SelfConjugate -> False,
    QuantumNumbers -> {LeptonNumber},
    PropagatorType -> Straight,
    PropagatorArrow -> Forward,
    Mass -> 0,
    Indices -> {},
    PropagatorLabel -> "vm" },

F[3] == {
    SelfConjugate -> False,
    QuantumNumbers -> {LeptonNumber},
    PropagatorType -> Straight,
    PropagatorArrow -> Forward,
    Mass -> 0,
    Indices -> {},
    PropagatorLabel -> "vt" },

F[4] == {
    SelfConjugate -> False,
    QuantumNumbers -> {-Q, LeptonNumber},
    PropagatorType -> Straight,
    PropagatorArrow -> Forward,
    Mass -> Me,
    Indices -> {},
    PropagatorLabel -> "e" },

F[5] == {
    SelfConjugate -> False,
    QuantumNumbers -> {-Q, LeptonNumber},
    PropagatorType -> Straight,
    PropagatorArrow -> Forward,
    Mass -> MMU,
    Indices -> {},
    PropagatorLabel -> "mu" },

F[6] == {
    SelfConjugate -> False,
    QuantumNumbers -> {-Q, LeptonNumber},
    PropagatorType -> Straight,
    PropagatorArrow -> Forward,
    Mass -> MTA,
    Indices -> {},
    PropagatorLabel -> "ta" },

F[7] == {
    SelfConjugate -> False,
    QuantumNumbers -> {(2*Q)/3},
    PropagatorType -> Straight,
    PropagatorArrow -> Forward,
    Mass -> FCGV["MU"],
    Indices -> {Index[Colour]},
    PropagatorLabel -> "u" },

F[8] == {
    SelfConjugate -> False,
    QuantumNumbers -> {(2*Q)/3},
    PropagatorType -> Straight,
    PropagatorArrow -> Forward,
    Mass -> FCGV["MC"],
    Indices -> {Index[Colour]},
    PropagatorLabel -> "c" },

F[9] == {
    SelfConjugate -> False,
    QuantumNumbers -> {(2*Q)/3},
    PropagatorType -> Straight,
    PropagatorArrow -> Forward,
    Mass -> FCGV["MT"],
    Indices -> {Index[Colour]},
    PropagatorLabel -> "t" },

F[10] == {
    SelfConjugate -> False,
    QuantumNumbers -> {-1/3*Q},
    PropagatorType -> Straight,
    PropagatorArrow -> Forward,
    Mass -> FCGV["MD"],
    Indices -> {Index[Colour]},
    PropagatorLabel -> "d" },

F[11] == {
    SelfConjugate -> False,
    QuantumNumbers -> {-1/3*Q},
    PropagatorType -> Straight,
    PropagatorArrow -> Forward,
    Mass -> FCGV["MS"],
    Indices -> {Index[Colour]},
    PropagatorLabel -> "s" },

F[12] == {
    SelfConjugate -> False,
    QuantumNumbers -> {-1/3*Q},
    PropagatorType -> Straight,
    PropagatorArrow -> Forward,
    Mass -> FCGV["MB"],
    Indices -> {Index[Colour]},
    PropagatorLabel -> "b" },

S[1] == {
    SelfConjugate -> True,
    PropagatorType -> ScalarDash,
    PropagatorArrow -> None,
    Mass -> FCGV["MH"],
    Indices -> {},
    PropagatorLabel -> "H" },

S[2] == {
    SelfConjugate -> True,
    PropagatorType -> ScalarDash,
    PropagatorArrow -> None,
    Mass -> FCGV["MZ"],
    Indices -> {},
    PropagatorLabel -> "G0" },

S[3] == {
    SelfConjugate -> False,
    QuantumNumbers -> {Q},
    PropagatorType -> ScalarDash,
    PropagatorArrow -> None,
    Mass -> FCGV["MW"],
    Indices -> {},
    PropagatorLabel -> "GP" },

F[13] == {
    SelfConjugate -> False,
    QuantumNumbers -> {-Q},
    PropagatorType -> Straight,
    PropagatorArrow -> Forward,
    Mass -> MchiM,
    Indices -> {},
    PropagatorLabel -> "chiM" },

F[14] == {
    SelfConjugate -> False,
    QuantumNumbers -> {0},
    PropagatorType -> Straight,
    PropagatorArrow -> None,
    Mass -> Mchi0,
    Indices -> {},
    PropagatorLabel -> "chi0" },

S[4] == {
    SelfConjugate -> True,
    PropagatorType -> ScalarDash,
    PropagatorArrow -> None,
    Mass -> MS0,
    Indices -> {},
    PropagatorLabel -> "S0" },

S[5] == {
    SelfConjugate -> True,
    PropagatorType -> ScalarDash,
    PropagatorArrow -> None,
    Mass -> MA0,
    Indices -> {},
    PropagatorLabel -> "A0" },

S[6] == {
    SelfConjugate -> False,
    QuantumNumbers -> {(2*Q)/3},
    PropagatorType -> ScalarDash,
    PropagatorArrow -> None,
    Mass -> MphiQ,
    Indices -> {Index[Colour]},
    PropagatorLabel -> "pQ" }
}


(*        Definitions       *)

FAGaugeXi[ V[1] ] = FAGaugeXi[A];
FAGaugeXi[ V[2] ] = FAGaugeXi[Z];
FAGaugeXi[ V[3] ] = FAGaugeXi[W];
FAGaugeXi[ V[4] ] = FAGaugeXi[G];
FAGaugeXi[ U[1] ] = FAGaugeXi[A];
FAGaugeXi[ U[2] ] = FAGaugeXi[Z];
FAGaugeXi[ U[3] ] = FAGaugeXi[W];
FAGaugeXi[ U[4] ] = FAGaugeXi[W];
FAGaugeXi[ U[5] ] = FAGaugeXi[G];
FAGaugeXi[ S[1] ] = 1;
FAGaugeXi[ S[2] ] = FAGaugeXi[Z];
FAGaugeXi[ S[3] ] = FAGaugeXi[W];
FAGaugeXi[ F[13] ] = FAGaugeXi[F[21]];
FAGaugeXi[ F[14] ] = FAGaugeXi[F[22]];
FAGaugeXi[ S[4] ] = FAGaugeXi[S[21]];
FAGaugeXi[ S[5] ] = FAGaugeXi[S[22]];
FAGaugeXi[ S[6] ] = FAGaugeXi[S[24]];

FCGV["MZ"][ ___ ] := FCGV["MZ"];
FCGV["MW"][ ___ ] := FCGV["MW"];
Me[ ___ ] := Me;
MMU[ ___ ] := MMU;
MTA[ ___ ] := MTA;
FCGV["MU"][ ___ ] := FCGV["MU"];
FCGV["MC"][ ___ ] := FCGV["MC"];
FCGV["MT"][ ___ ] := FCGV["MT"];
FCGV["MD"][ ___ ] := FCGV["MD"];
FCGV["MS"][ ___ ] := FCGV["MS"];
FCGV["MB"][ ___ ] := FCGV["MB"];
FCGV["MH"][ ___ ] := FCGV["MH"];
MchiM[ ___ ] := MchiM;
Mchi0[ ___ ] := Mchi0;
MS0[ ___ ] := MS0;
MA0[ ___ ] := MA0;
MphiQ[ ___ ] := MphiQ;


TheLabel[ V[4, {__}] ] := TheLabel[V[4]];
TheLabel[ U[5, {__}] ] := TheLabel[U[5]];
TheLabel[ F[7, {__}] ] := TheLabel[F[7]];
TheLabel[ F[8, {__}] ] := TheLabel[F[8]];
TheLabel[ F[9, {__}] ] := TheLabel[F[9]];
TheLabel[ F[10, {__}] ] := TheLabel[F[10]];
TheLabel[ F[11, {__}] ] := TheLabel[F[11]];
TheLabel[ F[12, {__}] ] := TheLabel[F[12]];
TheLabel[ S[6, {__}] ] := TheLabel[S[6]];


(*      Couplings (calculated by FeynRules)      *)

M$CouplingMatrices = {

C[ S[2] , S[2] , S[2] , S[2] ] == {{(-6*I)*lamH, 0}},

C[ S[2] , S[2] , S[3] , -S[3] ] == {{(-2*I)*lamH, 0}},

C[ S[3] , S[3] , -S[3] , -S[3] ] == {{(-4*I)*lamH, 0}},

C[ S[2] , S[2] , S[1] , S[1] ] == {{(-2*I)*lamH, 0}},

C[ S[3] , -S[3] , S[1] , S[1] ] == {{(-2*I)*lamH, 0}},

C[ S[1] , S[1] , S[1] , S[1] ] == {{(-6*I)*lamH, 0}},

C[ S[5] , S[5] , S[2] , S[2] ] == {{(-I)*(lamHPL - lamHPLprime), 0}},

C[ S[5] , S[5] , S[3] , -S[3] ] == {{(-I)*(lamHPL - lamHPLprime), 0}},

C[ S[5] , S[5] , S[1] , S[1] ] == {{(-I)*(lamHPL - lamHPLprime), 0}},

C[ S[5] , S[5] , S[5] , S[5] ] == {{(-6*I)*(lamPL + lamPLprime), 0}},

C[ S[2] , S[2] , S[4] , S[4] ] == {{(-I)*(lamHPL + lamHPLprime), 0}},

C[ S[3] , -S[3] , S[4] , S[4] ] == {{(-I)*(lamHPL + lamHPLprime), 0}},

C[ S[1] , S[1] , S[4] , S[4] ] == {{(-I)*(lamHPL + lamHPLprime), 0}},

C[ S[5] , S[5] , S[4] , S[4] ] == {{(-2*I)*(lamPL - lamPLprime), 0}},

C[ S[4] , S[4] , S[4] , S[4] ] == {{(-6*I)*(lamPL + lamPLprime), 0}},

C[ S[2] , S[2] , S[1] ] == {{(-2*I)*lamH*vev, 0}},

C[ S[3] , -S[3] , S[1] ] == {{(-2*I)*lamH*vev, 0}},

C[ S[1] , S[1] , S[1] ] == {{(-6*I)*lamH*vev, 0}},

C[ S[5] , S[5] , S[1] ] == {{(-I)*(lamHPL - lamHPLprime)*vev, 0}},

C[ S[1] , S[4] , S[4] ] == {{(-I)*(lamHPL + lamHPLprime)*vev, 0}},

C[ S[3] , -S[3] , V[1] , V[1] ] == {{(2*I)*FCGV["EL"]^2, 0}},

C[ S[3] , -S[3] , V[1] ] == {{(-I)*gc22, 0}, {I*gc22, 0}},

C[ -U[1] , U[4] , V[3] ] == {{I*gc23, 0}, {I*gc23, 0}, {0, 0}},

C[ -U[1] , U[3] , -V[3] ] == {{I*gc24, 0}, {I*gc24, 0}, {0, 0}},

C[ -S[3] , -U[4] , U[1] ] == {{(FCGV["EL"]^2*vev)/(2*sw), 0}},

C[ -U[4] , U[1] , -V[3] ] == {{I*gc26, 0}, {I*gc26, 0}, {0, 0}},

C[ S[2] , -U[4] , U[4] ] == {{-1/4*(FCGV["EL"]^2*vev)/sw^2, 0}},

C[ S[1] , -U[4] , U[4] ] == {{((-1/4*I)*FCGV["EL"]^2*vev)/sw^2, 0}},

C[ -U[4] , U[4] , V[1] ] == {{I*gc29, 0}, {I*gc29, 0}, {0, 0}},

C[ -U[4] , U[4] , V[2] ] == {{I*gc30, 0}, {I*gc30, 0}, {0, 0}},

C[ -S[3] , -U[4] , U[2] ] == {{(FCGV["EL"]^2*(cw - sw)*(cw + sw)*vev)/(4*cw*sw^2), 0}},

C[ -U[4] , U[2] , -V[3] ] == {{I*gc32, 0}, {I*gc32, 0}, {0, 0}},

C[ S[3] , -U[3] , U[1] ] == {{-1/2*(FCGV["EL"]^2*vev)/sw, 0}},

C[ -U[3] , U[1] , V[3] ] == {{I*gc34, 0}, {I*gc34, 0}, {0, 0}},

C[ S[2] , -U[3] , U[3] ] == {{(FCGV["EL"]^2*vev)/(4*sw^2), 0}},

C[ S[1] , -U[3] , U[3] ] == {{((-1/4*I)*FCGV["EL"]^2*vev)/sw^2, 0}},

C[ -U[3] , U[3] , V[1] ] == {{I*gc37, 0}, {I*gc37, 0}, {0, 0}},

C[ -U[3] , U[3] , V[2] ] == {{I*gc38, 0}, {I*gc38, 0}, {0, 0}},

C[ S[3] , -U[3] , U[2] ] == {{-1/4*(FCGV["EL"]^2*(cw - sw)*(cw + sw)*vev)/(cw*sw^2), 0}},

C[ -U[3] , U[2] , V[3] ] == {{I*gc40, 0}, {I*gc40, 0}, {0, 0}},

C[ S[3] , -U[2] , U[4] ] == {{(FCGV["EL"]^2*(cw^2 + sw^2)*vev)/(4*cw*sw^2), 0}},

C[ -U[2] , U[4] , V[3] ] == {{I*gc42, 0}, {I*gc42, 0}, {0, 0}},

C[ -S[3] , -U[2] , U[3] ] == {{-1/4*(FCGV["EL"]^2*(cw^2 + sw^2)*vev)/(cw*sw^2), 0}},

C[ -U[2] , U[3] , -V[3] ] == {{I*gc44, 0}, {I*gc44, 0}, {0, 0}},

C[ S[1] , -U[2] , U[2] ] == {{((-1/4*I)*FCGV["EL"]^2*(cw^2 + sw^2)^2*vev)/(cw^2*sw^2), 0}},

C[ -U[5, {e1x1}] , U[5, {e2x1}] , V[4, {e3x2}] ] == {{gc46*FASUNF[e3x2, e1x1, e2x1], 0}, {gc46*FASUNF[e3x2, e1x1, e2x1], 0}, {0, 0}},

C[ V[4, {e1x2}] , V[4, {e2x2}] , V[4, {e3x2}] ] == {{-(gc47*FASUNF[e1x2, e2x2, e3x2]), 0}, {gc47*FASUNF[e1x2, e2x2, e3x2], 0}, {gc47*FASUNF[e1x2, e2x2, e3x2], 0}, {-(gc47*FASUNF[e1x2, e2x2, e3x2]), 0}, {-(gc47*FASUNF[e1x2, e2x2, e3x2]), 0}, {gc47*FASUNF[e1x2, e2x2, e3x2], 0}},

C[ V[4, {e1x2}] , V[4, {e2x2}] , V[4, {e3x2}] , V[4, {e4x2}] ] == {{(-I)*gc48*(FASUNF[e1x2, e2x2, e3x2, e4x2] + FASUNF[e1x2, e3x2, e2x2, e4x2]), 0}, {I*gc48*(FASUNF[e1x2, e2x2, e3x2, e4x2] - FASUNF[e1x2, e4x2, e2x2, e3x2]), 0}, {I*gc48*(FASUNF[e1x2, e3x2, e2x2, e4x2] + FASUNF[e1x2, e4x2, e2x2, e3x2]), 0}},

C[ -F[13] , F[13] , V[1] ] == {{I*gc49, 0}, {I*gc49, 0}},

C[ S[6, {e2x1}] , -S[6, {e3x1}] , V[1] ] == {{(-I)*gc50*IndexDelta[e2x1, e3x1], 0}, {I*gc50*IndexDelta[e2x1, e3x1], 0}},

C[ S[2] , S[2] , S[6, {e3x1}] , -S[6, {e4x1}] ] == {{(-I)*lamHPQ*IndexDelta[e3x1, e4x1], 0}},

C[ S[3] , -S[3] , S[6, {e3x1}] , -S[6, {e4x1}] ] == {{(-I)*lamHPQ*IndexDelta[e3x1, e4x1], 0}},

C[ S[1] , S[1] , S[6, {e3x1}] , -S[6, {e4x1}] ] == {{(-I)*lamHPQ*IndexDelta[e3x1, e4x1], 0}},

C[ S[5] , S[5] , S[6, {e3x1}] , -S[6, {e4x1}] ] == {{(-I)*(lamPQPL - lamPQPLprime)*IndexDelta[e3x1, e4x1], 0}},

C[ S[6, {e1x1}] , -S[6, {e2x1}] , S[4] , S[4] ] == {{(-I)*(lamPQPL + lamPQPLprime)*IndexDelta[e1x1, e2x1], 0}},

C[ S[1] , S[6, {e2x1}] , -S[6, {e3x1}] ] == {{(-I)*lamHPQ*vev*IndexDelta[e2x1, e3x1], 0}},

C[ S[6, {e3x1}] , -S[6, {e4x1}] , V[1] , V[1] ] == {{((8*I)/9)*FCGV["EL"]^2*IndexDelta[e3x1, e4x1], 0}},

C[ S[6, {e1x1}] , S[6, {e2x1}] , -S[6, {e3x1}] , -S[6, {e4x1}] ] == {{(-2*I)*lamPQ*(IndexDelta[e1x1, e4x1]*IndexDelta[e2x1, e3x1] + IndexDelta[e1x1, e3x1]*IndexDelta[e2x1, e4x1]), 0}},

C[ -F[12, {e1x2}] , F[8, {e2x2}] , -S[3] ] == {{gc59L*IndexDelta[e1x2, e2x2], 0}, {gc59R*IndexDelta[e1x2, e2x2], 0}},

C[ -F[12, {e1x2}] , F[9, {e2x2}] , -S[3] ] == {{gc60L*IndexDelta[e1x2, e2x2], 0}, {gc60R*IndexDelta[e1x2, e2x2], 0}},

C[ -F[12, {e1x2}] , F[7, {e2x2}] , -S[3] ] == {{gc61L*IndexDelta[e1x2, e2x2], 0}, {gc61R*IndexDelta[e1x2, e2x2], 0}},

C[ -F[10, {e1x2}] , F[8, {e2x2}] , -S[3] ] == {{gc62L*IndexDelta[e1x2, e2x2], 0}, {gc62R*IndexDelta[e1x2, e2x2], 0}},

C[ -F[10, {e1x2}] , F[9, {e2x2}] , -S[3] ] == {{gc63L*IndexDelta[e1x2, e2x2], 0}, {gc63R*IndexDelta[e1x2, e2x2], 0}},

C[ -F[10, {e1x2}] , F[7, {e2x2}] , -S[3] ] == {{gc64L*IndexDelta[e1x2, e2x2], 0}, {gc64R*IndexDelta[e1x2, e2x2], 0}},

C[ -F[11, {e1x2}] , F[8, {e2x2}] , -S[3] ] == {{gc65L*IndexDelta[e1x2, e2x2], 0}, {gc65R*IndexDelta[e1x2, e2x2], 0}},

C[ -F[11, {e1x2}] , F[9, {e2x2}] , -S[3] ] == {{gc66L*IndexDelta[e1x2, e2x2], 0}, {gc66R*IndexDelta[e1x2, e2x2], 0}},

C[ -F[11, {e1x2}] , F[7, {e2x2}] , -S[3] ] == {{gc67L*IndexDelta[e1x2, e2x2], 0}, {gc67R*IndexDelta[e1x2, e2x2], 0}},

C[ -F[12, {e1x2}] , F[12, {e2x2}] , S[2] ] == {{gc68L*IndexDelta[e1x2, e2x2], 0}, {gc68R*IndexDelta[e1x2, e2x2], 0}},

C[ -F[10, {e1x2}] , F[10, {e2x2}] , S[2] ] == {{gc69L*IndexDelta[e1x2, e2x2], 0}, {gc69R*IndexDelta[e1x2, e2x2], 0}},

C[ -F[11, {e1x2}] , F[11, {e2x2}] , S[2] ] == {{gc70L*IndexDelta[e1x2, e2x2], 0}, {gc70R*IndexDelta[e1x2, e2x2], 0}},

C[ -F[12, {e1x2}] , F[12, {e2x2}] , S[1] ] == {{I*gc71*IndexDelta[e1x2, e2x2], 0}, {I*gc71*IndexDelta[e1x2, e2x2], 0}},

C[ -F[10, {e1x2}] , F[10, {e2x2}] , S[1] ] == {{I*gc72*IndexDelta[e1x2, e2x2], 0}, {I*gc72*IndexDelta[e1x2, e2x2], 0}},

C[ -F[11, {e1x2}] , F[11, {e2x2}] , S[1] ] == {{I*gc73*IndexDelta[e1x2, e2x2], 0}, {I*gc73*IndexDelta[e1x2, e2x2], 0}},

C[ -F[4] , F[1] , -S[3] ] == {{gc74, 0}, {0, 0}},

C[ -F[5] , F[2] , -S[3] ] == {{gc75, 0}, {0, 0}},

C[ -F[6] , F[3] , -S[3] ] == {{gc76, 0}, {0, 0}},

C[ -F[4] , F[4] , S[2] ] == {{gc77L, 0}, {gc77R, 0}},

C[ -F[5] , F[5] , S[2] ] == {{gc78L, 0}, {gc78R, 0}},

C[ -F[6] , F[6] , S[2] ] == {{gc79L, 0}, {gc79R, 0}},

C[ -F[4] , F[4] , S[1] ] == {{I*gc80, 0}, {I*gc80, 0}},

C[ -F[5] , F[5] , S[1] ] == {{I*gc81, 0}, {I*gc81, 0}},

C[ -F[6] , F[6] , S[1] ] == {{I*gc82, 0}, {I*gc82, 0}},

C[ -F[8, {e1x2}] , F[12, {e2x2}] , S[3] ] == {{gc83L*IndexDelta[e1x2, e2x2], 0}, {gc83R*IndexDelta[e1x2, e2x2], 0}},

C[ -F[8, {e1x2}] , F[10, {e2x2}] , S[3] ] == {{gc84L*IndexDelta[e1x2, e2x2], 0}, {gc84R*IndexDelta[e1x2, e2x2], 0}},

C[ -F[8, {e1x2}] , F[11, {e2x2}] , S[3] ] == {{gc85L*IndexDelta[e1x2, e2x2], 0}, {gc85R*IndexDelta[e1x2, e2x2], 0}},

C[ -F[9, {e1x2}] , F[12, {e2x2}] , S[3] ] == {{gc86L*IndexDelta[e1x2, e2x2], 0}, {gc86R*IndexDelta[e1x2, e2x2], 0}},

C[ -F[9, {e1x2}] , F[10, {e2x2}] , S[3] ] == {{gc87L*IndexDelta[e1x2, e2x2], 0}, {gc87R*IndexDelta[e1x2, e2x2], 0}},

C[ -F[9, {e1x2}] , F[11, {e2x2}] , S[3] ] == {{gc88L*IndexDelta[e1x2, e2x2], 0}, {gc88R*IndexDelta[e1x2, e2x2], 0}},

C[ -F[7, {e1x2}] , F[12, {e2x2}] , S[3] ] == {{gc89L*IndexDelta[e1x2, e2x2], 0}, {gc89R*IndexDelta[e1x2, e2x2], 0}},

C[ -F[7, {e1x2}] , F[10, {e2x2}] , S[3] ] == {{gc90L*IndexDelta[e1x2, e2x2], 0}, {gc90R*IndexDelta[e1x2, e2x2], 0}},

C[ -F[7, {e1x2}] , F[11, {e2x2}] , S[3] ] == {{gc91L*IndexDelta[e1x2, e2x2], 0}, {gc91R*IndexDelta[e1x2, e2x2], 0}},

C[ -F[8, {e1x2}] , F[8, {e2x2}] , S[2] ] == {{gc92L*IndexDelta[e1x2, e2x2], 0}, {gc92R*IndexDelta[e1x2, e2x2], 0}},

C[ -F[9, {e1x2}] , F[9, {e2x2}] , S[2] ] == {{gc93L*IndexDelta[e1x2, e2x2], 0}, {gc93R*IndexDelta[e1x2, e2x2], 0}},

C[ -F[7, {e1x2}] , F[7, {e2x2}] , S[2] ] == {{gc94L*IndexDelta[e1x2, e2x2], 0}, {gc94R*IndexDelta[e1x2, e2x2], 0}},

C[ -F[8, {e1x2}] , F[8, {e2x2}] , S[1] ] == {{I*gc95*IndexDelta[e1x2, e2x2], 0}, {I*gc95*IndexDelta[e1x2, e2x2], 0}},

C[ -F[9, {e1x2}] , F[9, {e2x2}] , S[1] ] == {{I*gc96*IndexDelta[e1x2, e2x2], 0}, {I*gc96*IndexDelta[e1x2, e2x2], 0}},

C[ -F[7, {e1x2}] , F[7, {e2x2}] , S[1] ] == {{I*gc97*IndexDelta[e1x2, e2x2], 0}, {I*gc97*IndexDelta[e1x2, e2x2], 0}},

C[ -F[14] , F[8, {e2x2}] , -S[6, {e3x1}] ] == {{I*gc98*IndexDelta[e2x2, e3x1], 0}, {0, 0}},

C[ -F[14] , F[9, {e2x2}] , -S[6, {e3x1}] ] == {{I*gc99*IndexDelta[e2x2, e3x1], 0}, {0, 0}},

C[ -F[14] , F[7, {e2x2}] , -S[6, {e3x1}] ] == {{I*gc100*IndexDelta[e2x2, e3x1], 0}, {0, 0}},

C[ -F[13] , F[12, {e2x2}] , -S[6, {e3x1}] ] == {{I*gc101*IndexDelta[e2x2, e3x1], 0}, {0, 0}},

C[ -F[13] , F[11, {e2x2}] , -S[6, {e3x1}] ] == {{I*gc102*IndexDelta[e2x2, e3x1], 0}, {0, 0}},

C[ -F[14] , F[2] , S[5] ] == {{gc103, 0}, {0, 0}},

C[ -F[14] , F[2] , S[4] ] == {{I*gc104, 0}, {0, 0}},

C[ -F[13] , F[5] , S[5] ] == {{gc105, 0}, {0, 0}},

C[ -F[13] , F[5] , S[4] ] == {{I*gc106, 0}, {0, 0}},

C[ -F[8, {e1x2}] , F[14] , S[6, {e3x1}] ] == {{0, 0}, {I*gc107R*IndexDelta[e1x2, e3x1], 0}},

C[ -F[9, {e1x2}] , F[14] , S[6, {e3x1}] ] == {{0, 0}, {I*gc108R*IndexDelta[e1x2, e3x1], 0}},

C[ -F[7, {e1x2}] , F[14] , S[6, {e3x1}] ] == {{0, 0}, {I*gc109R*IndexDelta[e1x2, e3x1], 0}},

C[ -F[12, {e1x2}] , F[13] , S[6, {e3x1}] ] == {{0, 0}, {I*gc110R*IndexDelta[e1x2, e3x1], 0}},

C[ -F[11, {e1x2}] , F[13] , S[6, {e3x1}] ] == {{0, 0}, {I*gc111R*IndexDelta[e1x2, e3x1], 0}},

C[ -F[2] , F[14] , S[5] ] == {{0, 0}, {gc112R, 0}},

C[ -F[2] , F[14] , S[4] ] == {{0, 0}, {I*gc113R, 0}},

C[ -F[5] , F[13] , S[5] ] == {{0, 0}, {gc114R, 0}},

C[ -F[5] , F[13] , S[4] ] == {{0, 0}, {I*gc115R, 0}},

C[ S[6, {e2x1}] , -S[6, {e3x1}] , V[4, {e1x2}] ] == {{(-I)*gc116*FASUNT[e1x2, e3x1, e2x1], 0}, {I*gc116*FASUNT[e1x2, e3x1, e2x1], 0}},

C[ S[6, {e3x1}] , -S[6, {e4x1}] , V[1] , V[4, {e2x2}] ] == {{((4*I)/3)*FCGV["EL"]*FAGS*FASUNT[e2x2, e4x1, e3x1], 0}},

C[ S[6, {e3x1}] , -S[6, {e4x1}] , V[4, {e1x2}] , V[4, {e2x2}] ] == {{I*FAGS^2*(FASUNT[e1x2, e2x2, e4x1, e3x1] + FASUNT[e2x2, e1x2, e4x1, e3x1]), 0}},

C[ S[2] , -S[3] , V[1] , V[3] ] == {{((-1/2*I)*FCGV["EL"]^2)/sw, 0}},

C[ -S[3] , S[1] , V[1] , V[3] ] == {{-1/2*FCGV["EL"]^2/sw, 0}},

C[ -S[3] , V[1] , V[3] ] == {{-1/2*(FCGV["EL"]^2*vev)/sw, 0}},

C[ S[2] , -S[3] , V[3] ] == {{(-I)*gc122, 0}, {I*gc122, 0}},

C[ -S[3] , S[1] , V[3] ] == {{-gc123, 0}, {gc123, 0}},

C[ V[1] , V[3] , -V[3] ] == {{(-I)*gc124, 0}, {I*gc124, 0}, {I*gc124, 0}, {(-I)*gc124, 0}, {(-I)*gc124, 0}, {I*gc124, 0}},

C[ -F[14] , F[13] , V[3] ] == {{I*gc125, 0}, {I*gc125, 0}},

C[ S[2] , S[3] , V[1] , -V[3] ] == {{((-1/2*I)*FCGV["EL"]^2)/sw, 0}},

C[ S[3] , S[1] , V[1] , -V[3] ] == {{FCGV["EL"]^2/(2*sw), 0}},

C[ S[3] , V[1] , -V[3] ] == {{(FCGV["EL"]^2*vev)/(2*sw), 0}},

C[ S[2] , S[3] , -V[3] ] == {{(-I)*gc129, 0}, {I*gc129, 0}},

C[ S[3] , S[1] , -V[3] ] == {{-gc130, 0}, {gc130, 0}},

C[ -F[13] , F[14] , -V[3] ] == {{I*gc131, 0}, {I*gc131, 0}},

C[ S[2] , S[2] , V[3] , -V[3] ] == {{((I/2)*FCGV["EL"]^2)/sw^2, 0}},

C[ S[3] , -S[3] , V[3] , -V[3] ] == {{((I/2)*FCGV["EL"]^2)/sw^2, 0}},

C[ S[1] , S[1] , V[3] , -V[3] ] == {{((I/2)*FCGV["EL"]^2)/sw^2, 0}},

C[ S[1] , V[3] , -V[3] ] == {{((I/2)*FCGV["EL"]^2*vev)/sw^2, 0}},

C[ V[1] , V[1] , V[3] , -V[3] ] == {{(-I)*gc136, 0}, {(-I)*gc136, 0}, {(2*I)*gc136, 0}},

C[ V[3] , -V[3] , V[2] ] == {{(-I)*gc137, 0}, {I*gc137, 0}, {I*gc137, 0}, {(-I)*gc137, 0}, {(-I)*gc137, 0}, {I*gc137, 0}},

C[ V[3] , V[3] , -V[3] , -V[3] ] == {{(-I)*gc138, 0}, {(-I)*gc138, 0}, {(2*I)*gc138, 0}},

C[ -F[1] , F[4] , S[3] ] == {{0, 0}, {gc139R, 0}},

C[ -F[2] , F[5] , S[3] ] == {{0, 0}, {gc140R, 0}},

C[ -F[3] , F[6] , S[3] ] == {{0, 0}, {gc141R, 0}},

C[ S[3] , -S[3] , V[1] , V[2] ] == {{(I*FCGV["EL"]^2*(cw - sw)*(cw + sw))/(cw*sw), 0}},

C[ S[2] , S[1] , V[2] ] == {{-gc143, 0}, {gc143, 0}},

C[ S[3] , -S[3] , V[2] ] == {{(-I)*gc144, 0}, {I*gc144, 0}},

C[ -F[14] , F[14] , V[2] ] == {{I*gc145, 0}, {I*gc145, 0}},

C[ -F[13] , F[13] , V[2] ] == {{I*gc146, 0}, {I*gc146, 0}},

C[ S[6, {e1x1}] , -S[6, {e2x1}] , V[2] ] == {{(-I)*gc147*IndexDelta[e1x1, e2x1], 0}, {I*gc147*IndexDelta[e1x1, e2x1], 0}},

C[ S[6, {e2x1}] , -S[6, {e3x1}] , V[1] , V[2] ] == {{(((-8*I)/9)*FCGV["EL"]^2*sw*IndexDelta[e2x1, e3x1])/cw, 0}},

C[ S[6, {e2x1}] , -S[6, {e3x1}] , V[4, {e1x2}] , V[2] ] == {{(((-4*I)/3)*FCGV["EL"]*FAGS*sw*FASUNT[e1x2, e3x1, e2x1])/cw, 0}},

C[ S[2] , -S[3] , V[3] , V[2] ] == {{((I/2)*FCGV["EL"]^2)/cw, 0}},

C[ -S[3] , S[1] , V[3] , V[2] ] == {{FCGV["EL"]^2/(2*cw), 0}},

C[ -S[3] , V[3] , V[2] ] == {{(FCGV["EL"]^2*vev)/(2*cw), 0}},

C[ S[2] , S[3] , -V[3] , V[2] ] == {{((I/2)*FCGV["EL"]^2)/cw, 0}},

C[ S[3] , S[1] , -V[3] , V[2] ] == {{-1/2*FCGV["EL"]^2/cw, 0}},

C[ S[3] , -V[3] , V[2] ] == {{-1/2*(FCGV["EL"]^2*vev)/cw, 0}},

C[ V[1] , V[3] , -V[3] , V[2] ] == {{(-2*I)*gc156, 0}, {I*gc156, 0}, {I*gc156, 0}},

C[ S[2] , S[2] , V[2] , V[2] ] == {{((I/2)*FCGV["EL"]^2*(cw^2 + sw^2)^2)/(cw^2*sw^2), 0}},

C[ S[3] , -S[3] , V[2] , V[2] ] == {{((I/2)*FCGV["EL"]^2*(cw - sw)^2*(cw + sw)^2)/(cw^2*sw^2), 0}},

C[ S[1] , S[1] , V[2] , V[2] ] == {{((I/2)*FCGV["EL"]^2*(cw^2 + sw^2)^2)/(cw^2*sw^2), 0}},

C[ S[1] , V[2] , V[2] ] == {{((I/2)*FCGV["EL"]^2*(cw^2 + sw^2)^2*vev)/(cw^2*sw^2), 0}},

C[ S[6, {e1x1}] , -S[6, {e2x1}] , V[2] , V[2] ] == {{(((8*I)/9)*FCGV["EL"]^2*sw^2*IndexDelta[e1x1, e2x1])/cw^2, 0}},

C[ V[3] , -V[3] , V[2] , V[2] ] == {{(-I)*gc162, 0}, {(-I)*gc162, 0}, {(2*I)*gc162, 0}},

C[ -F[4] , F[4] , V[1] ] == {{I*gc163, 0}, {I*gc163, 0}},

C[ -F[5] , F[5] , V[1] ] == {{I*gc164, 0}, {I*gc164, 0}},

C[ -F[6] , F[6] , V[1] ] == {{I*gc165, 0}, {I*gc165, 0}},

C[ -F[8, {e1x2}] , F[8, {e2x2}] , V[1] ] == {{I*gc166*IndexDelta[e1x2, e2x2], 0}, {I*gc166*IndexDelta[e1x2, e2x2], 0}},

C[ -F[9, {e1x2}] , F[9, {e2x2}] , V[1] ] == {{I*gc167*IndexDelta[e1x2, e2x2], 0}, {I*gc167*IndexDelta[e1x2, e2x2], 0}},

C[ -F[7, {e1x2}] , F[7, {e2x2}] , V[1] ] == {{I*gc168*IndexDelta[e1x2, e2x2], 0}, {I*gc168*IndexDelta[e1x2, e2x2], 0}},

C[ -F[12, {e1x2}] , F[12, {e2x2}] , V[1] ] == {{I*gc169*IndexDelta[e1x2, e2x2], 0}, {I*gc169*IndexDelta[e1x2, e2x2], 0}},

C[ -F[10, {e1x2}] , F[10, {e2x2}] , V[1] ] == {{I*gc170*IndexDelta[e1x2, e2x2], 0}, {I*gc170*IndexDelta[e1x2, e2x2], 0}},

C[ -F[11, {e1x2}] , F[11, {e2x2}] , V[1] ] == {{I*gc171*IndexDelta[e1x2, e2x2], 0}, {I*gc171*IndexDelta[e1x2, e2x2], 0}},

C[ -F[8, {e1x2}] , F[8, {e2x2}] , V[4, {e3x2}] ] == {{I*gc172*FASUNT[e3x2, e1x2, e2x2], 0}, {I*gc172*FASUNT[e3x2, e1x2, e2x2], 0}},

C[ -F[9, {e1x2}] , F[9, {e2x2}] , V[4, {e3x2}] ] == {{I*gc173*FASUNT[e3x2, e1x2, e2x2], 0}, {I*gc173*FASUNT[e3x2, e1x2, e2x2], 0}},

C[ -F[7, {e1x2}] , F[7, {e2x2}] , V[4, {e3x2}] ] == {{I*gc174*FASUNT[e3x2, e1x2, e2x2], 0}, {I*gc174*FASUNT[e3x2, e1x2, e2x2], 0}},

C[ -F[12, {e1x2}] , F[12, {e2x2}] , V[4, {e3x2}] ] == {{I*gc175*FASUNT[e3x2, e1x2, e2x2], 0}, {I*gc175*FASUNT[e3x2, e1x2, e2x2], 0}},

C[ -F[10, {e1x2}] , F[10, {e2x2}] , V[4, {e3x2}] ] == {{I*gc176*FASUNT[e3x2, e1x2, e2x2], 0}, {I*gc176*FASUNT[e3x2, e1x2, e2x2], 0}},

C[ -F[11, {e1x2}] , F[11, {e2x2}] , V[4, {e3x2}] ] == {{I*gc177*FASUNT[e3x2, e1x2, e2x2], 0}, {I*gc177*FASUNT[e3x2, e1x2, e2x2], 0}},

C[ -F[8, {e1x2}] , F[12, {e2x2}] , V[3] ] == {{I*gc178*IndexDelta[e1x2, e2x2], 0}, {0, 0}},

C[ -F[8, {e1x2}] , F[10, {e2x2}] , V[3] ] == {{I*gc179*IndexDelta[e1x2, e2x2], 0}, {0, 0}},

C[ -F[8, {e1x2}] , F[11, {e2x2}] , V[3] ] == {{I*gc180*IndexDelta[e1x2, e2x2], 0}, {0, 0}},

C[ -F[9, {e1x2}] , F[12, {e2x2}] , V[3] ] == {{I*gc181*IndexDelta[e1x2, e2x2], 0}, {0, 0}},

C[ -F[9, {e1x2}] , F[10, {e2x2}] , V[3] ] == {{I*gc182*IndexDelta[e1x2, e2x2], 0}, {0, 0}},

C[ -F[9, {e1x2}] , F[11, {e2x2}] , V[3] ] == {{I*gc183*IndexDelta[e1x2, e2x2], 0}, {0, 0}},

C[ -F[7, {e1x2}] , F[12, {e2x2}] , V[3] ] == {{I*gc184*IndexDelta[e1x2, e2x2], 0}, {0, 0}},

C[ -F[7, {e1x2}] , F[10, {e2x2}] , V[3] ] == {{I*gc185*IndexDelta[e1x2, e2x2], 0}, {0, 0}},

C[ -F[7, {e1x2}] , F[11, {e2x2}] , V[3] ] == {{I*gc186*IndexDelta[e1x2, e2x2], 0}, {0, 0}},

C[ -F[12, {e1x2}] , F[8, {e2x2}] , -V[3] ] == {{I*gc187*IndexDelta[e1x2, e2x2], 0}, {0, 0}},

C[ -F[12, {e1x2}] , F[9, {e2x2}] , -V[3] ] == {{I*gc188*IndexDelta[e1x2, e2x2], 0}, {0, 0}},

C[ -F[12, {e1x2}] , F[7, {e2x2}] , -V[3] ] == {{I*gc189*IndexDelta[e1x2, e2x2], 0}, {0, 0}},

C[ -F[10, {e1x2}] , F[8, {e2x2}] , -V[3] ] == {{I*gc190*IndexDelta[e1x2, e2x2], 0}, {0, 0}},

C[ -F[10, {e1x2}] , F[9, {e2x2}] , -V[3] ] == {{I*gc191*IndexDelta[e1x2, e2x2], 0}, {0, 0}},

C[ -F[10, {e1x2}] , F[7, {e2x2}] , -V[3] ] == {{I*gc192*IndexDelta[e1x2, e2x2], 0}, {0, 0}},

C[ -F[11, {e1x2}] , F[8, {e2x2}] , -V[3] ] == {{I*gc193*IndexDelta[e1x2, e2x2], 0}, {0, 0}},

C[ -F[11, {e1x2}] , F[9, {e2x2}] , -V[3] ] == {{I*gc194*IndexDelta[e1x2, e2x2], 0}, {0, 0}},

C[ -F[11, {e1x2}] , F[7, {e2x2}] , -V[3] ] == {{I*gc195*IndexDelta[e1x2, e2x2], 0}, {0, 0}},

C[ -F[1] , F[4] , V[3] ] == {{I*gc196, 0}, {0, 0}},

C[ -F[2] , F[5] , V[3] ] == {{I*gc197, 0}, {0, 0}},

C[ -F[3] , F[6] , V[3] ] == {{I*gc198, 0}, {0, 0}},

C[ -F[4] , F[1] , -V[3] ] == {{I*gc199, 0}, {0, 0}},

C[ -F[5] , F[2] , -V[3] ] == {{I*gc200, 0}, {0, 0}},

C[ -F[6] , F[3] , -V[3] ] == {{I*gc201, 0}, {0, 0}},

C[ -F[8, {e1x2}] , F[8, {e2x2}] , V[2] ] == {{I*gc202L*IndexDelta[e1x2, e2x2], 0}, {I*gc202R*IndexDelta[e1x2, e2x2], 0}},

C[ -F[9, {e1x2}] , F[9, {e2x2}] , V[2] ] == {{I*gc203L*IndexDelta[e1x2, e2x2], 0}, {I*gc203R*IndexDelta[e1x2, e2x2], 0}},

C[ -F[7, {e1x2}] , F[7, {e2x2}] , V[2] ] == {{I*gc204L*IndexDelta[e1x2, e2x2], 0}, {I*gc204R*IndexDelta[e1x2, e2x2], 0}},

C[ -F[12, {e1x2}] , F[12, {e2x2}] , V[2] ] == {{I*gc205L*IndexDelta[e1x2, e2x2], 0}, {I*gc205R*IndexDelta[e1x2, e2x2], 0}},

C[ -F[10, {e1x2}] , F[10, {e2x2}] , V[2] ] == {{I*gc206L*IndexDelta[e1x2, e2x2], 0}, {I*gc206R*IndexDelta[e1x2, e2x2], 0}},

C[ -F[11, {e1x2}] , F[11, {e2x2}] , V[2] ] == {{I*gc207L*IndexDelta[e1x2, e2x2], 0}, {I*gc207R*IndexDelta[e1x2, e2x2], 0}},

C[ -F[1] , F[1] , V[2] ] == {{I*gc208, 0}, {0, 0}},

C[ -F[2] , F[2] , V[2] ] == {{I*gc209, 0}, {0, 0}},

C[ -F[3] , F[3] , V[2] ] == {{I*gc210, 0}, {0, 0}},

C[ -F[4] , F[4] , V[2] ] == {{I*gc211L, 0}, {I*gc211R, 0}},

C[ -F[5] , F[5] , V[2] ] == {{I*gc212L, 0}, {I*gc212R, 0}},

C[ -F[6] , F[6] , V[2] ] == {{I*gc213L, 0}, {I*gc213R, 0}}

}

(* * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * *)

(* Parameter replacement lists (These lists were created by FeynRules) *)

(* FA Couplings *)

M$FACouplings = {
     gc22 -> -FCGV["EL"],
     gc23 -> FCGV["EL"],
     gc24 -> -FCGV["EL"],
     gc26 -> FCGV["EL"],
     gc29 -> -FCGV["EL"],
     gc30 -> -((cw*FCGV["EL"])/sw),
     gc32 -> (cw*FCGV["EL"])/sw,
     gc34 -> -FCGV["EL"],
     gc37 -> FCGV["EL"],
     gc38 -> (cw*FCGV["EL"])/sw,
     gc40 -> -((cw*FCGV["EL"])/sw),
     gc42 -> (cw*FCGV["EL"])/sw,
     gc44 -> -((cw*FCGV["EL"])/sw),
     gc46 -> FAGS,
     gc47 -> -FAGS,
     gc48 -> -FAGS^2,
     gc49 -> -FCGV["EL"],
     gc50 -> (-2*FCGV["EL"])/3,
     gc59L -> CKM2x3*yb,
     gc59R -> -(CKM2x3*yc),
     gc60L -> CKM3x3*yb,
     gc60R -> -(CKM3x3*yt),
     gc61L -> CKM1x3*yb,
     gc61R -> -(CKM1x3*yup),
     gc62L -> CKM2x1*ydo,
     gc62R -> -(CKM2x1*yc),
     gc63L -> CKM3x1*ydo,
     gc63R -> -(CKM3x1*yt),
     gc64L -> CKM1x1*ydo,
     gc64R -> -(CKM1x1*yup),
     gc65L -> CKM2x2*ys,
     gc65R -> -(CKM2x2*yc),
     gc66L -> CKM3x2*ys,
     gc66R -> -(CKM3x2*yt),
     gc67L -> CKM1x2*ys,
     gc67R -> -(CKM1x2*yup),
     gc68L -> -(yb/Sqrt[2]),
     gc68R -> yb/Sqrt[2],
     gc69L -> -(ydo/Sqrt[2]),
     gc69R -> ydo/Sqrt[2],
     gc70L -> -(ys/Sqrt[2]),
     gc70R -> ys/Sqrt[2],
     gc71 -> -(yb/Sqrt[2]),
     gc72 -> -(ydo/Sqrt[2]),
     gc73 -> -(ys/Sqrt[2]),
     gc74 -> ye,
     gc75 -> ym,
     gc76 -> ytau,
     gc77L -> -(ye/Sqrt[2]),
     gc77R -> ye/Sqrt[2],
     gc78L -> -(ym/Sqrt[2]),
     gc78R -> ym/Sqrt[2],
     gc79L -> -(ytau/Sqrt[2]),
     gc79R -> ytau/Sqrt[2],
     gc80 -> -(ye/Sqrt[2]),
     gc81 -> -(ym/Sqrt[2]),
     gc82 -> -(ytau/Sqrt[2]),
     gc83L -> CKM2x3*yc,
     gc83R -> -(CKM2x3*yb),
     gc84L -> CKM2x1*yc,
     gc84R -> -(CKM2x1*ydo),
     gc85L -> CKM2x2*yc,
     gc85R -> -(CKM2x2*ys),
     gc86L -> CKM3x3*yt,
     gc86R -> -(CKM3x3*yb),
     gc87L -> CKM3x1*yt,
     gc87R -> -(CKM3x1*ydo),
     gc88L -> CKM3x2*yt,
     gc88R -> -(CKM3x2*ys),
     gc89L -> CKM1x3*yup,
     gc89R -> -(CKM1x3*yb),
     gc90L -> CKM1x1*yup,
     gc90R -> -(CKM1x1*ydo),
     gc91L -> CKM1x2*yup,
     gc91R -> -(CKM1x2*ys),
     gc92L -> yc/Sqrt[2],
     gc92R -> -(yc/Sqrt[2]),
     gc93L -> yt/Sqrt[2],
     gc93R -> -(yt/Sqrt[2]),
     gc94L -> yup/Sqrt[2],
     gc94R -> -(yup/Sqrt[2]),
     gc95 -> -(yc/Sqrt[2]),
     gc96 -> -(yt/Sqrt[2]),
     gc97 -> -(yup/Sqrt[2]),
     gc98 -> CKM2x3*ymbD + CKM2x2*ymsD,
     gc99 -> CKM3x3*ymbD + CKM3x2*ymsD,
     gc100 -> CKM1x3*ymbD + CKM1x2*ymsD,
     gc101 -> ymbD,
     gc102 -> ymsD,
     gc103 -> ymmD/Sqrt[2],
     gc104 -> ymmD/Sqrt[2],
     gc105 -> ymmD/Sqrt[2],
     gc106 -> ymmD/Sqrt[2],
     gc107R -> CKM2x3*ymbD + CKM2x2*ymsD,
     gc108R -> CKM3x3*ymbD + CKM3x2*ymsD,
     gc109R -> CKM1x3*ymbD + CKM1x2*ymsD,
     gc110R -> ymbD,
     gc111R -> ymsD,
     gc112R -> -(ymmD/Sqrt[2]),
     gc113R -> ymmD/Sqrt[2],
     gc114R -> -(ymmD/Sqrt[2]),
     gc115R -> ymmD/Sqrt[2],
     gc116 -> -FAGS,
     gc122 -> FCGV["EL"]/(2*sw),
     gc123 -> -1/2*FCGV["EL"]/sw,
     gc124 -> FCGV["EL"],
     gc125 -> FCGV["EL"]/(Sqrt[2]*sw),
     gc129 -> -1/2*FCGV["EL"]/sw,
     gc130 -> -1/2*FCGV["EL"]/sw,
     gc131 -> FCGV["EL"]/(Sqrt[2]*sw),
     gc136 -> -FCGV["EL"]^2,
     gc137 -> (cw*FCGV["EL"])/sw,
     gc138 -> FCGV["EL"]^2/sw^2,
     gc139R -> -ye,
     gc140R -> -ym,
     gc141R -> -ytau,
     gc143 -> -1/2*(FCGV["EL"]*(cw^2 + sw^2))/(cw*sw),
     gc144 -> -1/2*(cw*FCGV["EL"])/sw + (FCGV["EL"]*sw)/(2*cw),
     gc145 -> (FCGV["EL"]*(cw^2 + sw^2))/(2*cw*sw),
     gc146 -> -1/2*(FCGV["EL"]*(cw^2 - sw^2))/(cw*sw),
     gc147 -> (2*FCGV["EL"]*sw)/(3*cw),
     gc156 -> (cw*FCGV["EL"]^2)/sw,
     gc162 -> -((cw^2*FCGV["EL"]^2)/sw^2),
     gc163 -> -FCGV["EL"],
     gc164 -> -FCGV["EL"],
     gc165 -> -FCGV["EL"],
     gc166 -> (2*FCGV["EL"])/3,
     gc167 -> (2*FCGV["EL"])/3,
     gc168 -> (2*FCGV["EL"])/3,
     gc169 -> -1/3*FCGV["EL"],
     gc170 -> -1/3*FCGV["EL"],
     gc171 -> -1/3*FCGV["EL"],
     gc172 -> FAGS,
     gc173 -> FAGS,
     gc174 -> FAGS,
     gc175 -> FAGS,
     gc176 -> FAGS,
     gc177 -> FAGS,
     gc178 -> (CKM2x3*FCGV["EL"])/(Sqrt[2]*sw),
     gc179 -> (CKM2x1*FCGV["EL"])/(Sqrt[2]*sw),
     gc180 -> (CKM2x2*FCGV["EL"])/(Sqrt[2]*sw),
     gc181 -> (CKM3x3*FCGV["EL"])/(Sqrt[2]*sw),
     gc182 -> (CKM3x1*FCGV["EL"])/(Sqrt[2]*sw),
     gc183 -> (CKM3x2*FCGV["EL"])/(Sqrt[2]*sw),
     gc184 -> (CKM1x3*FCGV["EL"])/(Sqrt[2]*sw),
     gc185 -> (CKM1x1*FCGV["EL"])/(Sqrt[2]*sw),
     gc186 -> (CKM1x2*FCGV["EL"])/(Sqrt[2]*sw),
     gc187 -> (CKM2x3*FCGV["EL"])/(Sqrt[2]*sw),
     gc188 -> (CKM3x3*FCGV["EL"])/(Sqrt[2]*sw),
     gc189 -> (CKM1x3*FCGV["EL"])/(Sqrt[2]*sw),
     gc190 -> (CKM2x1*FCGV["EL"])/(Sqrt[2]*sw),
     gc191 -> (CKM3x1*FCGV["EL"])/(Sqrt[2]*sw),
     gc192 -> (CKM1x1*FCGV["EL"])/(Sqrt[2]*sw),
     gc193 -> (CKM2x2*FCGV["EL"])/(Sqrt[2]*sw),
     gc194 -> (CKM3x2*FCGV["EL"])/(Sqrt[2]*sw),
     gc195 -> (CKM1x2*FCGV["EL"])/(Sqrt[2]*sw),
     gc196 -> FCGV["EL"]/(Sqrt[2]*sw),
     gc197 -> FCGV["EL"]/(Sqrt[2]*sw),
     gc198 -> FCGV["EL"]/(Sqrt[2]*sw),
     gc199 -> FCGV["EL"]/(Sqrt[2]*sw),
     gc200 -> FCGV["EL"]/(Sqrt[2]*sw),
     gc201 -> FCGV["EL"]/(Sqrt[2]*sw),
     gc202L -> (cw*FCGV["EL"])/(2*sw) - (FCGV["EL"]*sw)/(6*cw),
     gc202R -> (-2*FCGV["EL"]*sw)/(3*cw),
     gc203L -> (cw*FCGV["EL"])/(2*sw) - (FCGV["EL"]*sw)/(6*cw),
     gc203R -> (-2*FCGV["EL"]*sw)/(3*cw),
     gc204L -> (cw*FCGV["EL"])/(2*sw) - (FCGV["EL"]*sw)/(6*cw),
     gc204R -> (-2*FCGV["EL"]*sw)/(3*cw),
     gc205L -> -1/6*(FCGV["EL"]*(3*cw^2 + sw^2))/(cw*sw),
     gc205R -> (FCGV["EL"]*sw)/(3*cw),
     gc206L -> -1/6*(FCGV["EL"]*(3*cw^2 + sw^2))/(cw*sw),
     gc206R -> (FCGV["EL"]*sw)/(3*cw),
     gc207L -> -1/6*(FCGV["EL"]*(3*cw^2 + sw^2))/(cw*sw),
     gc207R -> (FCGV["EL"]*sw)/(3*cw),
     gc208 -> (FCGV["EL"]*(cw^2 + sw^2))/(2*cw*sw),
     gc209 -> (FCGV["EL"]*(cw^2 + sw^2))/(2*cw*sw),
     gc210 -> (FCGV["EL"]*(cw^2 + sw^2))/(2*cw*sw),
     gc211L -> -1/2*(FCGV["EL"]*(cw^2 - sw^2))/(cw*sw),
     gc211R -> (FCGV["EL"]*sw)/cw,
     gc212L -> -1/2*(FCGV["EL"]*(cw^2 - sw^2))/(cw*sw),
     gc212R -> (FCGV["EL"]*sw)/cw,
     gc213L -> -1/2*(FCGV["EL"]*(cw^2 - sw^2))/(cw*sw),
     gc213R -> (FCGV["EL"]*sw)/cw};

