(* Patched for use with FeynCalc *)
(* * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * *)
(*                                                                             *)
(*         This file has been automatically generated by FeynRules.            *)
(*                                                                             *)
(* * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * *)


FR$ModelInformation={
  ModelName->"N2HDM_CPVDM",
  Authors -> {"Jonas Wittbrodt"},
  Version -> "1.0"};

FR$ClassesTranslation={ve -> F[1], vm -> F[2], vt -> F[3], e -> F[4], m -> F[5], ta -> F[6], u -> F[7], c -> F[8], t -> F[9], d -> F[10], s -> F[11], b -> F[12], A -> V[1], Z -> V[2], W -> V[3], G -> V[4], ghA -> U[1], ghZ -> U[2], ghWp -> U[3], ghWm -> U[4], ghG -> U[5], h -> S[1], G0 -> S[2], Gch -> S[3], H1 -> S[4], H2 -> S[5], H3 -> S[6], Hc -> S[7]};

FR$InteractionOrderPerturbativeExpansion={{QCD, 0}, {QED, 0}};

FR$GoldstoneList={S[2], S[3]};

(*     Declared indices    *)

IndexRange[ Index[Generation] ] = Range[ 3 ]

IndexRange[ Index[Colour] ] = NoUnfold[ Range[ 3 ] ]

IndexRange[ Index[Gluon] ] = NoUnfold[ Range[ 8 ] ]

IndexRange[ Index[SU2W] ] = Range[ 3 ]

IndexRange[ Index[DarkHiggs] ] = Range[ 3 ]

(*     Declared particles    *)

M$ClassesDescription = {
F[1] == {
    SelfConjugate -> False,
    PropagatorType -> Straight,
    PropagatorArrow -> Forward,
    Mass -> Mnue,
    Indices -> {},
    PropagatorLabel -> "ve" },

F[2] == {
    SelfConjugate -> False,
    PropagatorType -> Straight,
    PropagatorArrow -> Forward,
    Mass -> Mnum,
    Indices -> {},
    PropagatorLabel -> "vm" },

F[3] == {
    SelfConjugate -> False,
    PropagatorType -> Straight,
    PropagatorArrow -> Forward,
    Mass -> Mnut,
    Indices -> {},
    PropagatorLabel -> "vt" },

F[4] == {
    SelfConjugate -> False,
    QuantumNumbers -> {-Q},
    PropagatorType -> Straight,
    PropagatorArrow -> Forward,
    Mass -> Me,
    Indices -> {},
    PropagatorLabel -> "e" },

F[5] == {
    SelfConjugate -> False,
    QuantumNumbers -> {-Q},
    PropagatorType -> Straight,
    PropagatorArrow -> Forward,
    Mass -> FCGV["MM"],
    Indices -> {},
    PropagatorLabel -> "m" },

F[6] == {
    SelfConjugate -> False,
    QuantumNumbers -> {-Q},
    PropagatorType -> Straight,
    PropagatorArrow -> Forward,
    Mass -> MTA,
    Indices -> {},
    PropagatorLabel -> "ta" },

F[7] == {
    SelfConjugate -> False,
    QuantumNumbers -> {(2*Q)/3},
    PropagatorType -> Straight,
    PropagatorArrow -> Forward,
    Mass -> FCGV["MU"],
    Indices -> {Index[Colour]},
    PropagatorLabel -> "u" },

F[8] == {
    SelfConjugate -> False,
    QuantumNumbers -> {(2*Q)/3},
    PropagatorType -> Straight,
    PropagatorArrow -> Forward,
    Mass -> FCGV["MC"],
    Indices -> {Index[Colour]},
    PropagatorLabel -> "c" },

F[9] == {
    SelfConjugate -> False,
    QuantumNumbers -> {(2*Q)/3},
    PropagatorType -> Straight,
    PropagatorArrow -> Forward,
    Mass -> FCGV["MT"],
    Indices -> {Index[Colour]},
    PropagatorLabel -> "t" },

F[10] == {
    SelfConjugate -> False,
    QuantumNumbers -> {-1/3*Q},
    PropagatorType -> Straight,
    PropagatorArrow -> Forward,
    Mass -> FCGV["MD"],
    Indices -> {Index[Colour]},
    PropagatorLabel -> "d" },

F[11] == {
    SelfConjugate -> False,
    QuantumNumbers -> {-1/3*Q},
    PropagatorType -> Straight,
    PropagatorArrow -> Forward,
    Mass -> FCGV["MS"],
    Indices -> {Index[Colour]},
    PropagatorLabel -> "s" },

F[12] == {
    SelfConjugate -> False,
    QuantumNumbers -> {-1/3*Q},
    PropagatorType -> Straight,
    PropagatorArrow -> Forward,
    Mass -> FCGV["MB"],
    Indices -> {Index[Colour]},
    PropagatorLabel -> "b" },

V[1] == {
    SelfConjugate -> True,
    PropagatorType -> Sine,
    PropagatorArrow -> None,
    Mass -> 0,
    Indices -> {},
    PropagatorLabel -> "A" },

V[2] == {
    SelfConjugate -> True,
    PropagatorType -> Sine,
    PropagatorArrow -> None,
    Mass -> FCGV["MZ"],
    Indices -> {},
    PropagatorLabel -> "Z" },

V[3] == {
    SelfConjugate -> False,
    QuantumNumbers -> {Q},
    PropagatorType -> Sine,
    PropagatorArrow -> Forward,
    Mass -> FCGV["MW"],
    Indices -> {},
    PropagatorLabel -> "W" },

V[4] == {
    SelfConjugate -> True,
    PropagatorType -> Cycles,
    PropagatorArrow -> None,
    Mass -> 0,
    Indices -> {Index[Gluon]},
    PropagatorLabel -> "G" },

U[1] == {
    SelfConjugate -> False,
    QuantumNumbers -> {GhostNumber},
    PropagatorType -> GhostDash,
    PropagatorArrow -> Forward,
    Mass -> 0,
    Indices -> {},
    PropagatorLabel -> "ghA" },

U[2] == {
    SelfConjugate -> False,
    QuantumNumbers -> {GhostNumber},
    PropagatorType -> GhostDash,
    PropagatorArrow -> Forward,
    Mass -> FCGV["MZ"],
    Indices -> {},
    PropagatorLabel -> "ghZ" },

U[3] == {
    SelfConjugate -> False,
    QuantumNumbers -> {Q, GhostNumber},
    PropagatorType -> GhostDash,
    PropagatorArrow -> Forward,
    Mass -> FCGV["MW"],
    Indices -> {},
    PropagatorLabel -> "ghWp" },

U[4] == {
    SelfConjugate -> False,
    QuantumNumbers -> {-Q, GhostNumber},
    PropagatorType -> GhostDash,
    PropagatorArrow -> Forward,
    Mass -> FCGV["MW"],
    Indices -> {},
    PropagatorLabel -> "ghWm" },

U[5] == {
    SelfConjugate -> False,
    QuantumNumbers -> {GhostNumber},
    PropagatorType -> GhostDash,
    PropagatorArrow -> Forward,
    Mass -> 0,
    Indices -> {Index[Gluon]},
    PropagatorLabel -> "ghG" },

S[1] == {
    SelfConjugate -> True,
    PropagatorType -> ScalarDash,
    PropagatorArrow -> None,
    Mass -> mHsm,
    Indices -> {},
    PropagatorLabel -> "h" },

S[2] == {
    SelfConjugate -> True,
    PropagatorType -> ScalarDash,
    PropagatorArrow -> None,
    Mass -> FCGV["MZ"],
    Indices -> {},
    PropagatorLabel -> "G0" },

S[3] == {
    SelfConjugate -> False,
    PropagatorType -> ScalarDash,
    PropagatorArrow -> None,
    QuantumNumbers -> {Q},
    Mass -> FCGV["MW"],
    Indices -> {},
    PropagatorLabel -> "Gch" },

S[4] == {
    SelfConjugate -> True,
    PropagatorType -> ScalarDash,
    PropagatorArrow -> None,
    Mass -> mH1,
    Indices -> {},
    PropagatorLabel -> "H1" },

S[5] == {
    SelfConjugate -> True,
    PropagatorType -> ScalarDash,
    PropagatorArrow -> None,
    Mass -> mH2,
    Indices -> {},
    PropagatorLabel -> "H2" },

S[6] == {
    SelfConjugate -> True,
    PropagatorType -> ScalarDash,
    PropagatorArrow -> None,
    Mass -> mH3,
    Indices -> {},
    PropagatorLabel -> "H3" },

S[7] == {
    SelfConjugate -> False,
    QuantumNumbers -> {Q},
    PropagatorType -> ScalarDash,
    PropagatorArrow -> Forward,
    Mass -> mHc,
    Indices -> {},
    PropagatorLabel -> "Hc" }
}


(*        Definitions       *)

FAGaugeXi[ S[7] ] = FAGaugeXi[S[5]];

Mnue[ ___ ] := Mnue;
Mnum[ ___ ] := Mnum;
Mnut[ ___ ] := Mnut;
Me[ ___ ] := Me;
FCGV["MM"][ ___ ] := FCGV["MM"];
MTA[ ___ ] := MTA;
FCGV["MU"][ ___ ] := FCGV["MU"];
FCGV["MC"][ ___ ] := FCGV["MC"];
FCGV["MT"][ ___ ] := FCGV["MT"];
FCGV["MD"][ ___ ] := FCGV["MD"];
FCGV["MS"][ ___ ] := FCGV["MS"];
FCGV["MB"][ ___ ] := FCGV["MB"];
FCGV["MZ"][ ___ ] := FCGV["MZ"];
FCGV["MW"][ ___ ] := FCGV["MW"];
mHsm[ ___ ] := mHsm;
mH1[ ___ ] := mH1;
mH2[ ___ ] := mH2;
mH3[ ___ ] := mH3;
mHc[ ___ ] := mHc;


TheLabel[ F[7, {__}] ] := TheLabel[F[7]];
TheLabel[ F[8, {__}] ] := TheLabel[F[8]];
TheLabel[ F[9, {__}] ] := TheLabel[F[9]];
TheLabel[ F[10, {__}] ] := TheLabel[F[10]];
TheLabel[ F[11, {__}] ] := TheLabel[F[11]];
TheLabel[ F[12, {__}] ] := TheLabel[F[12]];
TheLabel[ V[4, {__}] ] := TheLabel[V[4]];
TheLabel[ U[5, {__}] ] := TheLabel[U[5]];


(*      Couplings (calculated by FeynRules)      *)

M$CouplingMatrices = {

C[ S[2] , S[2] , S[2] , S[2] ] == {{(-3*I)*L1, 0}},

C[ S[2] , S[2] , S[3] , -S[3] ] == {{(-I)*L1, 0}},

C[ S[3] , S[3] , -S[3] , -S[3] ] == {{(-2*I)*L1, 0}},

C[ S[2] , S[2] , S[1] , S[1] ] == {{(-I)*L1, 0}},

C[ S[3] , -S[3] , S[1] , S[1] ] == {{(-I)*L1, 0}},

C[ S[1] , S[1] , S[1] , S[1] ] == {{(-3*I)*L1, 0}},

C[ S[7] , S[7] , -S[7] , -S[7] ] == {{(-2*I)*L2, 0}},

C[ S[2] , S[2] , S[7] , -S[7] ] == {{(-I)*L3, 0}},

C[ S[3] , -S[3] , S[7] , -S[7] ] == {{(-I)*(L3 + L4), 0}},

C[ S[1] , S[1] , S[7] , -S[7] ] == {{(-I)*L3, 0}},

C[ -S[3] , -S[3] , S[7] , S[7] ] == {{(-2*I)*L5, 0}},

C[ S[3] , S[3] , -S[7] , -S[7] ] == {{(-2*I)*L5, 0}},

C[ S[2] , S[2] , S[1] ] == {{(-I)*L1*v, 0}},

C[ S[3] , -S[3] , S[1] ] == {{(-I)*L1*v, 0}},

C[ S[1] , S[1] , S[1] ] == {{(-3*I)*L1*v, 0}},

C[ S[1] , S[7] , -S[7] ] == {{(-I)*L3*v, 0}},

C[ S[3] , -S[3] , V[1] , V[1] ] == {{(2*I)*FCGV["EL"]^2, 0}},

C[ S[7] , -S[7] , V[1] , V[1] ] == {{(2*I)*FCGV["EL"]^2, 0}},

C[ S[3] , -S[3] , V[1] ] == {{(-I)*gc19, 0}, {I*gc19, 0}},

C[ S[7] , -S[7] , V[1] ] == {{(-I)*gc20, 0}, {I*gc20, 0}},

C[ -U[1] , U[4] , V[3] ] == {{I*gc21, 0}, {I*gc21, 0}, {0, 0}},

C[ -U[1] , U[3] , -V[3] ] == {{I*gc22, 0}, {I*gc22, 0}, {0, 0}},

C[ -S[3] , -U[4] , U[1] ] == {{((-1/2*I)*FCGV["EL"]^2*v)/FCGV["SW"], 0}},

C[ -U[4] , U[1] , -V[3] ] == {{I*gc24, 0}, {I*gc24, 0}, {0, 0}},

C[ S[2] , -U[4] , U[4] ] == {{-1/4*(FCGV["EL"]^2*v)/FCGV["SW"]^2, 0}},

C[ S[1] , -U[4] , U[4] ] == {{((-1/4*I)*FCGV["EL"]^2*v)/FCGV["SW"]^2, 0}},

C[ -U[4] , U[4] , V[1] ] == {{I*gc27, 0}, {I*gc27, 0}, {0, 0}},

C[ -U[4] , U[4] , V[2] ] == {{I*gc28, 0}, {I*gc28, 0}, {0, 0}},

C[ -S[3] , -U[4] , U[2] ] == {{((-1/4*I)*FCGV["EL"]^2*(FCGV["CW"] - FCGV["SW"])*(FCGV["CW"] + FCGV["SW"])*v)/(FCGV["CW"]*FCGV["SW"]^2), 0}},

C[ -U[4] , U[2] , -V[3] ] == {{I*gc30, 0}, {I*gc30, 0}, {0, 0}},

C[ S[3] , -U[3] , U[1] ] == {{((-1/2*I)*FCGV["EL"]^2*v)/FCGV["SW"], 0}},

C[ -U[3] , U[1] , V[3] ] == {{I*gc32, 0}, {I*gc32, 0}, {0, 0}},

C[ S[2] , -U[3] , U[3] ] == {{(FCGV["EL"]^2*v)/(4*FCGV["SW"]^2), 0}},

C[ S[1] , -U[3] , U[3] ] == {{((-1/4*I)*FCGV["EL"]^2*v)/FCGV["SW"]^2, 0}},

C[ -U[3] , U[3] , V[1] ] == {{I*gc35, 0}, {I*gc35, 0}, {0, 0}},

C[ -U[3] , U[3] , V[2] ] == {{I*gc36, 0}, {I*gc36, 0}, {0, 0}},

C[ S[3] , -U[3] , U[2] ] == {{((-1/4*I)*FCGV["EL"]^2*(FCGV["CW"] - FCGV["SW"])*(FCGV["CW"] + FCGV["SW"])*v)/(FCGV["CW"]*FCGV["SW"]^2), 0}},

C[ -U[3] , U[2] , V[3] ] == {{I*gc38, 0}, {I*gc38, 0}, {0, 0}},

C[ S[3] , -U[2] , U[4] ] == {{((I/4)*FCGV["EL"]^2*(FCGV["CW"]^2 + FCGV["SW"]^2)*v)/(FCGV["CW"]*FCGV["SW"]^2), 0}},

C[ -U[2] , U[4] , V[3] ] == {{I*gc40, 0}, {I*gc40, 0}, {0, 0}},

C[ -S[3] , -U[2] , U[3] ] == {{((I/4)*FCGV["EL"]^2*(FCGV["CW"]^2 + FCGV["SW"]^2)*v)/(FCGV["CW"]*FCGV["SW"]^2), 0}},

C[ -U[2] , U[3] , -V[3] ] == {{I*gc42, 0}, {I*gc42, 0}, {0, 0}},

C[ S[1] , -U[2] , U[2] ] == {{((-1/4*I)*FCGV["EL"]^2*(FCGV["CW"]^2 + FCGV["SW"]^2)^2*v)/(FCGV["CW"]^2*FCGV["SW"]^2), 0}},

C[ -U[5, {e1x1}] , U[5, {e2x1}] , V[4, {e3x2}] ] == {{gc44*FASUNF[e3x2, e1x1, e2x1], 0}, {gc44*FASUNF[e3x2, e1x1, e2x1], 0}, {0, 0}},

C[ V[4, {e1x2}] , V[4, {e2x2}] , V[4, {e3x2}] ] == {{-(gc45*FASUNF[e1x2, e2x2, e3x2]), 0}, {gc45*FASUNF[e1x2, e2x2, e3x2], 0}, {gc45*FASUNF[e1x2, e2x2, e3x2], 0}, {-(gc45*FASUNF[e1x2, e2x2, e3x2]), 0}, {-(gc45*FASUNF[e1x2, e2x2, e3x2]), 0}, {gc45*FASUNF[e1x2, e2x2, e3x2], 0}},

C[ V[4, {e1x2}] , V[4, {e2x2}] , V[4, {e3x2}] , V[4, {e4x2}] ] == {{(-I)*gc46*(FASUNF[e1x2, e2x2, e3x2, e4x2] + FASUNF[e1x2, e3x2, e2x2, e4x2]), 0}, {I*gc46*(FASUNF[e1x2, e2x2, e3x2, e4x2] - FASUNF[e1x2, e4x2, e2x2, e3x2]), 0}, {I*gc46*(FASUNF[e1x2, e3x2, e2x2, e4x2] + FASUNF[e1x2, e4x2, e2x2, e3x2]), 0}},

C[ -F[12, {e1x2}] , F[12, {e2x2}] , S[2] ] == {{gc47L*IndexDelta[e1x2, e2x2], 0}, {gc47R*IndexDelta[e1x2, e2x2], 0}},

C[ -F[12, {e1x2}] , F[12, {e2x2}] , S[1] ] == {{I*gc48*IndexDelta[e1x2, e2x2], 0}, {I*gc48*IndexDelta[e1x2, e2x2], 0}},

C[ -F[10, {e1x2}] , F[10, {e2x2}] , S[2] ] == {{gc49L*IndexDelta[e1x2, e2x2], 0}, {gc49R*IndexDelta[e1x2, e2x2], 0}},

C[ -F[10, {e1x2}] , F[10, {e2x2}] , S[1] ] == {{I*gc50*IndexDelta[e1x2, e2x2], 0}, {I*gc50*IndexDelta[e1x2, e2x2], 0}},

C[ -F[11, {e1x2}] , F[11, {e2x2}] , S[2] ] == {{gc51L*IndexDelta[e1x2, e2x2], 0}, {gc51R*IndexDelta[e1x2, e2x2], 0}},

C[ -F[11, {e1x2}] , F[11, {e2x2}] , S[1] ] == {{I*gc52*IndexDelta[e1x2, e2x2], 0}, {I*gc52*IndexDelta[e1x2, e2x2], 0}},

C[ -F[12, {e1x2}] , F[8, {e2x2}] , -S[3] ] == {{I*gc53L*IndexDelta[e1x2, e2x2], 0}, {I*gc53R*IndexDelta[e1x2, e2x2], 0}},

C[ -F[12, {e1x2}] , F[9, {e2x2}] , -S[3] ] == {{I*gc54L*IndexDelta[e1x2, e2x2], 0}, {I*gc54R*IndexDelta[e1x2, e2x2], 0}},

C[ -F[12, {e1x2}] , F[7, {e2x2}] , -S[3] ] == {{I*gc55L*IndexDelta[e1x2, e2x2], 0}, {I*gc55R*IndexDelta[e1x2, e2x2], 0}},

C[ -F[10, {e1x2}] , F[8, {e2x2}] , -S[3] ] == {{I*gc56L*IndexDelta[e1x2, e2x2], 0}, {I*gc56R*IndexDelta[e1x2, e2x2], 0}},

C[ -F[10, {e1x2}] , F[9, {e2x2}] , -S[3] ] == {{I*gc57L*IndexDelta[e1x2, e2x2], 0}, {I*gc57R*IndexDelta[e1x2, e2x2], 0}},

C[ -F[10, {e1x2}] , F[7, {e2x2}] , -S[3] ] == {{I*gc58L*IndexDelta[e1x2, e2x2], 0}, {I*gc58R*IndexDelta[e1x2, e2x2], 0}},

C[ -F[11, {e1x2}] , F[8, {e2x2}] , -S[3] ] == {{I*gc59L*IndexDelta[e1x2, e2x2], 0}, {I*gc59R*IndexDelta[e1x2, e2x2], 0}},

C[ -F[11, {e1x2}] , F[9, {e2x2}] , -S[3] ] == {{I*gc60L*IndexDelta[e1x2, e2x2], 0}, {I*gc60R*IndexDelta[e1x2, e2x2], 0}},

C[ -F[11, {e1x2}] , F[7, {e2x2}] , -S[3] ] == {{I*gc61L*IndexDelta[e1x2, e2x2], 0}, {I*gc61R*IndexDelta[e1x2, e2x2], 0}},

C[ -F[4] , F[4] , S[2] ] == {{gc62L, 0}, {gc62R, 0}},

C[ -F[4] , F[4] , S[1] ] == {{I*gc63, 0}, {I*gc63, 0}},

C[ -F[5] , F[5] , S[2] ] == {{gc64L, 0}, {gc64R, 0}},

C[ -F[5] , F[5] , S[1] ] == {{I*gc65, 0}, {I*gc65, 0}},

C[ -F[6] , F[6] , S[2] ] == {{gc66L, 0}, {gc66R, 0}},

C[ -F[6] , F[6] , S[1] ] == {{I*gc67, 0}, {I*gc67, 0}},

C[ -F[4] , F[1] , -S[3] ] == {{I*gc68, 0}, {0, 0}},

C[ -F[5] , F[2] , -S[3] ] == {{I*gc69, 0}, {0, 0}},

C[ -F[6] , F[3] , -S[3] ] == {{I*gc70, 0}, {0, 0}},

C[ -F[8, {e1x2}] , F[12, {e2x2}] , S[3] ] == {{I*gc71L*IndexDelta[e1x2, e2x2], 0}, {I*gc71R*IndexDelta[e1x2, e2x2], 0}},

C[ -F[8, {e1x2}] , F[10, {e2x2}] , S[3] ] == {{I*gc72L*IndexDelta[e1x2, e2x2], 0}, {I*gc72R*IndexDelta[e1x2, e2x2], 0}},

C[ -F[8, {e1x2}] , F[11, {e2x2}] , S[3] ] == {{I*gc73L*IndexDelta[e1x2, e2x2], 0}, {I*gc73R*IndexDelta[e1x2, e2x2], 0}},

C[ -F[9, {e1x2}] , F[12, {e2x2}] , S[3] ] == {{I*gc74L*IndexDelta[e1x2, e2x2], 0}, {I*gc74R*IndexDelta[e1x2, e2x2], 0}},

C[ -F[9, {e1x2}] , F[10, {e2x2}] , S[3] ] == {{I*gc75L*IndexDelta[e1x2, e2x2], 0}, {I*gc75R*IndexDelta[e1x2, e2x2], 0}},

C[ -F[9, {e1x2}] , F[11, {e2x2}] , S[3] ] == {{I*gc76L*IndexDelta[e1x2, e2x2], 0}, {I*gc76R*IndexDelta[e1x2, e2x2], 0}},

C[ -F[7, {e1x2}] , F[12, {e2x2}] , S[3] ] == {{I*gc77L*IndexDelta[e1x2, e2x2], 0}, {I*gc77R*IndexDelta[e1x2, e2x2], 0}},

C[ -F[7, {e1x2}] , F[10, {e2x2}] , S[3] ] == {{I*gc78L*IndexDelta[e1x2, e2x2], 0}, {I*gc78R*IndexDelta[e1x2, e2x2], 0}},

C[ -F[7, {e1x2}] , F[11, {e2x2}] , S[3] ] == {{I*gc79L*IndexDelta[e1x2, e2x2], 0}, {I*gc79R*IndexDelta[e1x2, e2x2], 0}},

C[ -F[8, {e1x2}] , F[8, {e2x2}] , S[2] ] == {{gc80L*IndexDelta[e1x2, e2x2], 0}, {gc80R*IndexDelta[e1x2, e2x2], 0}},

C[ -F[8, {e1x2}] , F[8, {e2x2}] , S[1] ] == {{I*gc81*IndexDelta[e1x2, e2x2], 0}, {I*gc81*IndexDelta[e1x2, e2x2], 0}},

C[ -F[9, {e1x2}] , F[9, {e2x2}] , S[2] ] == {{gc82L*IndexDelta[e1x2, e2x2], 0}, {gc82R*IndexDelta[e1x2, e2x2], 0}},

C[ -F[9, {e1x2}] , F[9, {e2x2}] , S[1] ] == {{I*gc83*IndexDelta[e1x2, e2x2], 0}, {I*gc83*IndexDelta[e1x2, e2x2], 0}},

C[ -F[7, {e1x2}] , F[7, {e2x2}] , S[2] ] == {{gc84L*IndexDelta[e1x2, e2x2], 0}, {gc84R*IndexDelta[e1x2, e2x2], 0}},

C[ -F[7, {e1x2}] , F[7, {e2x2}] , S[1] ] == {{I*gc85*IndexDelta[e1x2, e2x2], 0}, {I*gc85*IndexDelta[e1x2, e2x2], 0}},

C[ -F[1] , F[4] , S[3] ] == {{0, 0}, {I*gc86R, 0}},

C[ -F[2] , F[5] , S[3] ] == {{0, 0}, {I*gc87R, 0}},

C[ -F[3] , F[6] , S[3] ] == {{0, 0}, {I*gc88R, 0}},

C[ S[2] , -S[3] , S[4] , S[7] ] == {{(L4*(RR1x1 - I*RR1x2) - L5*(RR1x1 + I*RR1x2))/2, 0}},

C[ -S[3] , S[1] , S[4] , S[7] ] == {{((-I)*L4*RR1x1 - I*L5*RR1x1 - L4*RR1x2 + L5*RR1x2)/2, 0}},

C[ S[2] , S[3] , S[4] , -S[7] ] == {{(L5*(RR1x1 - I*RR1x2) - L4*(RR1x1 + I*RR1x2))/2, 0}},

C[ S[3] , S[1] , S[4] , -S[7] ] == {{((-I)*L4*RR1x1 - I*L5*RR1x1 + L4*RR1x2 - L5*RR1x2)/2, 0}},

C[ -S[3] , S[4] , S[7] ] == {{(-1/2*I)*(2*RR1x3*(I*Timag + Treal) + L4*(RR1x1 - I*RR1x2)*v + L5*(RR1x1 + I*RR1x2)*v), 0}},

C[ S[3] , S[4] , -S[7] ] == {{(-1/2*I)*(2*RR1x3*((-I)*Timag + Treal) + L5*(RR1x1 - I*RR1x2)*v + L4*(RR1x1 + I*RR1x2)*v), 0}},

C[ S[4] , S[4] , S[7] , -S[7] ] == {{(-I)*(L2*(RR1x1^2 + RR1x2^2) + L8*RR1x3^2), 0}},

C[ S[2] , S[2] , S[4] , S[4] ] == {{(-I)*(-(L5*RR1x1^2) + L5*RR1x2^2 + L3*(RR1x1^2 + RR1x2^2) + L4*(RR1x1^2 + RR1x2^2) + L7*RR1x3^2), 0}},

C[ S[3] , -S[3] , S[4] , S[4] ] == {{(-I)*(L3*(RR1x1^2 + RR1x2^2) + L7*RR1x3^2), 0}},

C[ S[1] , S[1] , S[4] , S[4] ] == {{(-I)*(L5*RR1x1^2 - L5*RR1x2^2 + L3*(RR1x1^2 + RR1x2^2) + L4*(RR1x1^2 + RR1x2^2) + L7*RR1x3^2), 0}},

C[ S[1] , S[4] , S[4] ] == {{(-I)*(-2*RR1x2*RR1x3*Timag + 2*RR1x1*RR1x3*Treal + (L3 + L4 + L5)*RR1x1^2*v + (L3 + L4 - L5)*RR1x2^2*v + L7*RR1x3^2*v), 0}},

C[ S[4] , S[4] , S[4] , S[4] ] == {{(-3*I)*(L2*(RR1x1^2 + RR1x2^2)^2 + 2*L8*(RR1x1^2 + RR1x2^2)*RR1x3^2 + L6*RR1x3^4), 0}},

C[ S[2] , S[1] , S[4] , S[4] ] == {{(-2*I)*L5*RR1x1*RR1x2, 0}},

C[ S[2] , S[4] , S[4] ] == {{(-2*I)*(RR1x1*RR1x3*Timag + RR1x2*RR1x3*Treal + L5*RR1x1*RR1x2*v), 0}},

C[ S[2] , -S[3] , S[5] , S[7] ] == {{(L4*(RR2x1 - I*RR2x2) - L5*(RR2x1 + I*RR2x2))/2, 0}},

C[ -S[3] , S[1] , S[5] , S[7] ] == {{((-I)*L4*RR2x1 - I*L5*RR2x1 - L4*RR2x2 + L5*RR2x2)/2, 0}},

C[ S[2] , S[3] , S[5] , -S[7] ] == {{(L5*(RR2x1 - I*RR2x2) - L4*(RR2x1 + I*RR2x2))/2, 0}},

C[ S[3] , S[1] , S[5] , -S[7] ] == {{((-I)*L4*RR2x1 - I*L5*RR2x1 + L4*RR2x2 - L5*RR2x2)/2, 0}},

C[ -S[3] , S[5] , S[7] ] == {{(-1/2*I)*(2*RR2x3*(I*Timag + Treal) + L4*(RR2x1 - I*RR2x2)*v + L5*(RR2x1 + I*RR2x2)*v), 0}},

C[ S[3] , S[5] , -S[7] ] == {{(-1/2*I)*(2*RR2x3*((-I)*Timag + Treal) + L5*(RR2x1 - I*RR2x2)*v + L4*(RR2x1 + I*RR2x2)*v), 0}},

C[ S[4] , S[5] , S[7] , -S[7] ] == {{(-I)*(L2*RR1x1*RR2x1 + L2*RR1x2*RR2x2 + L8*RR1x3*RR2x3), 0}},

C[ S[2] , S[2] , S[4] , S[5] ] == {{(-I)*(L3*RR1x1*RR2x1 + L4*RR1x1*RR2x1 - L5*RR1x1*RR2x1 + L3*RR1x2*RR2x2 + L4*RR1x2*RR2x2 + L5*RR1x2*RR2x2 + L7*RR1x3*RR2x3), 0}},

C[ S[3] , -S[3] , S[4] , S[5] ] == {{(-I)*(L3*RR1x1*RR2x1 + L3*RR1x2*RR2x2 + L7*RR1x3*RR2x3), 0}},

C[ S[1] , S[1] , S[4] , S[5] ] == {{(-I)*(L3*RR1x1*RR2x1 + L4*RR1x1*RR2x1 + L5*RR1x1*RR2x1 + L3*RR1x2*RR2x2 + L4*RR1x2*RR2x2 - L5*RR1x2*RR2x2 + L7*RR1x3*RR2x3), 0}},

C[ S[1] , S[4] , S[5] ] == {{(-I)*(-(RR1x2*RR2x3*Timag) + RR1x1*RR2x3*Treal + (L3 + L4 + L5)*RR1x1*RR2x1*v + (L3 + L4 - L5)*RR1x2*RR2x2*v + RR1x3*(-(RR2x2*Timag) + RR2x1*Treal + L7*RR2x3*v)), 0}},

C[ S[4] , S[4] , S[4] , S[5] ] == {{(-3*I)*(L2*(RR1x1^2 + RR1x2^2)*(RR1x1*RR2x1 + RR1x2*RR2x2) + L6*RR1x3^3*RR2x3 + L8*RR1x3*(RR1x1*RR1x3*RR2x1 + RR1x2*RR1x3*RR2x2 + RR1x1^2*RR2x3 + RR1x2^2*RR2x3)), 0}},

C[ S[2] , S[1] , S[4] , S[5] ] == {{(-I)*L5*(RR1x2*RR2x1 + RR1x1*RR2x2), 0}},

C[ S[2] , S[4] , S[5] ] == {{(-I)*(RR1x3*RR2x1*Timag + RR1x1*RR2x3*Timag + RR1x3*RR2x2*Treal + RR1x2*RR2x3*Treal + L5*RR1x2*RR2x1*v + L5*RR1x1*RR2x2*v), 0}},

C[ S[5] , S[5] , S[7] , -S[7] ] == {{(-I)*(L2*(RR2x1^2 + RR2x2^2) + L8*RR2x3^2), 0}},

C[ S[2] , S[2] , S[5] , S[5] ] == {{(-I)*(-(L5*RR2x1^2) + L5*RR2x2^2 + L3*(RR2x1^2 + RR2x2^2) + L4*(RR2x1^2 + RR2x2^2) + L7*RR2x3^2), 0}},

C[ S[3] , -S[3] , S[5] , S[5] ] == {{(-I)*(L3*(RR2x1^2 + RR2x2^2) + L7*RR2x3^2), 0}},

C[ S[1] , S[1] , S[5] , S[5] ] == {{(-I)*(L5*RR2x1^2 - L5*RR2x2^2 + L3*(RR2x1^2 + RR2x2^2) + L4*(RR2x1^2 + RR2x2^2) + L7*RR2x3^2), 0}},

C[ S[1] , S[5] , S[5] ] == {{(-I)*(-2*RR2x2*RR2x3*Timag + 2*RR2x1*RR2x3*Treal + (L3 + L4 + L5)*RR2x1^2*v + (L3 + L4 - L5)*RR2x2^2*v + L7*RR2x3^2*v), 0}},

C[ S[4] , S[4] , S[5] , S[5] ] == {{(-I)*(L2*(4*RR1x1*RR1x2*RR2x1*RR2x2 + RR1x1^2*(3*RR2x1^2 + RR2x2^2) + RR1x2^2*(RR2x1^2 + 3*RR2x2^2)) + 3*L6*RR1x3^2*RR2x3^2 + L8*(RR1x3^2*(RR2x1^2 + RR2x2^2) + 4*RR1x3*(RR1x1*RR2x1 + RR1x2*RR2x2)*RR2x3 + (RR1x1^2 + RR1x2^2)*RR2x3^2)), 0}},

C[ S[4] , S[5] , S[5] , S[5] ] == {{(-3*I)*(L2*(RR1x1*RR2x1 + RR1x2*RR2x2)*(RR2x1^2 + RR2x2^2) + L6*RR1x3*RR2x3^3 + L8*RR2x3*(RR1x3*RR2x1^2 + RR1x3*RR2x2^2 + RR1x1*RR2x1*RR2x3 + RR1x2*RR2x2*RR2x3)), 0}},

C[ S[5] , S[5] , S[5] , S[5] ] == {{(-3*I)*(L2*(RR2x1^2 + RR2x2^2)^2 + 2*L8*(RR2x1^2 + RR2x2^2)*RR2x3^2 + L6*RR2x3^4), 0}},

C[ S[2] , S[1] , S[5] , S[5] ] == {{(-2*I)*L5*RR2x1*RR2x2, 0}},

C[ S[2] , S[5] , S[5] ] == {{(-2*I)*(RR2x1*RR2x3*Timag + RR2x2*RR2x3*Treal + L5*RR2x1*RR2x2*v), 0}},

C[ S[2] , -S[3] , S[6] , S[7] ] == {{(L4*(RR3x1 - I*RR3x2) - L5*(RR3x1 + I*RR3x2))/2, 0}},

C[ -S[3] , S[1] , S[6] , S[7] ] == {{((-I)*L4*RR3x1 - I*L5*RR3x1 - L4*RR3x2 + L5*RR3x2)/2, 0}},

C[ S[2] , S[3] , S[6] , -S[7] ] == {{(L5*(RR3x1 - I*RR3x2) - L4*(RR3x1 + I*RR3x2))/2, 0}},

C[ S[3] , S[1] , S[6] , -S[7] ] == {{(-1/2*I)*(L4*RR3x1 + L5*RR3x1 + I*L4*RR3x2 - I*L5*RR3x2), 0}},

C[ -S[3] , S[6] , S[7] ] == {{(-1/2*I)*((2*I)*RR3x3*Timag + 2*RR3x3*Treal + L4*RR3x1*v + L5*RR3x1*v - I*L4*RR3x2*v + I*L5*RR3x2*v), 0}},

C[ S[3] , S[6] , -S[7] ] == {{(-1/2*I)*(2*RR3x3*((-I)*Timag + Treal) + L5*(RR3x1 - I*RR3x2)*v + L4*(RR3x1 + I*RR3x2)*v), 0}},

C[ S[4] , S[6] , S[7] , -S[7] ] == {{(-I)*(L2*RR1x1*RR3x1 + L2*RR1x2*RR3x2 + L8*RR1x3*RR3x3), 0}},

C[ S[2] , S[2] , S[4] , S[6] ] == {{(-I)*(L3*RR1x1*RR3x1 + L4*RR1x1*RR3x1 - L5*RR1x1*RR3x1 + L3*RR1x2*RR3x2 + L4*RR1x2*RR3x2 + L5*RR1x2*RR3x2 + L7*RR1x3*RR3x3), 0}},

C[ S[3] , -S[3] , S[4] , S[6] ] == {{(-I)*(L3*RR1x1*RR3x1 + L3*RR1x2*RR3x2 + L7*RR1x3*RR3x3), 0}},

C[ S[1] , S[1] , S[4] , S[6] ] == {{(-I)*(L3*RR1x1*RR3x1 + L4*RR1x1*RR3x1 + L5*RR1x1*RR3x1 + L3*RR1x2*RR3x2 + L4*RR1x2*RR3x2 - L5*RR1x2*RR3x2 + L7*RR1x3*RR3x3), 0}},

C[ S[1] , S[4] , S[6] ] == {{(-I)*(-(RR1x2*RR3x3*Timag) + RR1x1*RR3x3*Treal + (L3 + L4 + L5)*RR1x1*RR3x1*v + (L3 + L4 - L5)*RR1x2*RR3x2*v + RR1x3*(-(RR3x2*Timag) + RR3x1*Treal + L7*RR3x3*v)), 0}},

C[ S[4] , S[4] , S[4] , S[6] ] == {{(-3*I)*(L2*(RR1x1^2 + RR1x2^2)*(RR1x1*RR3x1 + RR1x2*RR3x2) + L6*RR1x3^3*RR3x3 + L8*RR1x3*(RR1x1*RR1x3*RR3x1 + RR1x2*RR1x3*RR3x2 + RR1x1^2*RR3x3 + RR1x2^2*RR3x3)), 0}},

C[ S[2] , S[1] , S[4] , S[6] ] == {{(-I)*L5*(RR1x2*RR3x1 + RR1x1*RR3x2), 0}},

C[ S[2] , S[4] , S[6] ] == {{(-I)*(RR1x3*RR3x1*Timag + RR1x1*RR3x3*Timag + RR1x3*RR3x2*Treal + RR1x2*RR3x3*Treal + L5*RR1x2*RR3x1*v + L5*RR1x1*RR3x2*v), 0}},

C[ S[5] , S[6] , S[7] , -S[7] ] == {{(-I)*(L2*RR2x1*RR3x1 + L2*RR2x2*RR3x2 + L8*RR2x3*RR3x3), 0}},

C[ S[2] , S[2] , S[5] , S[6] ] == {{(-I)*(L3*RR2x1*RR3x1 + L4*RR2x1*RR3x1 - L5*RR2x1*RR3x1 + L3*RR2x2*RR3x2 + L4*RR2x2*RR3x2 + L5*RR2x2*RR3x2 + L7*RR2x3*RR3x3), 0}},

C[ S[3] , -S[3] , S[5] , S[6] ] == {{(-I)*(L3*RR2x1*RR3x1 + L3*RR2x2*RR3x2 + L7*RR2x3*RR3x3), 0}},

C[ S[1] , S[1] , S[5] , S[6] ] == {{(-I)*(L3*RR2x1*RR3x1 + L4*RR2x1*RR3x1 + L5*RR2x1*RR3x1 + L3*RR2x2*RR3x2 + L4*RR2x2*RR3x2 - L5*RR2x2*RR3x2 + L7*RR2x3*RR3x3), 0}},

C[ S[1] , S[5] , S[6] ] == {{(-I)*(-(RR2x2*RR3x3*Timag) + RR2x1*RR3x3*Treal + (L3 + L4 + L5)*RR2x1*RR3x1*v + (L3 + L4 - L5)*RR2x2*RR3x2*v + RR2x3*(-(RR3x2*Timag) + RR3x1*Treal + L7*RR3x3*v)), 0}},

C[ S[4] , S[4] , S[5] , S[6] ] == {{(-I)*(L2*(2*RR1x1*RR1x2*(RR2x2*RR3x1 + RR2x1*RR3x2) + RR1x1^2*(3*RR2x1*RR3x1 + RR2x2*RR3x2) + RR1x2^2*(RR2x1*RR3x1 + 3*RR2x2*RR3x2)) + 3*L6*RR1x3^2*RR2x3*RR3x3 + L8*(RR1x3^2*(RR2x1*RR3x1 + RR2x2*RR3x2) + (RR1x1^2 + RR1x2^2)*RR2x3*RR3x3 + 2*RR1x3*(RR1x1*RR2x3*RR3x1 + RR1x2*RR2x3*RR3x2 + RR1x1*RR2x1*RR3x3 + RR1x2*RR2x2*RR3x3))), 0}},

C[ S[4] , S[5] , S[5] , S[6] ] == {{(-I)*(L2*(RR1x1*(3*RR2x1^2*RR3x1 + RR2x2^2*RR3x1 + 2*RR2x1*RR2x2*RR3x2) + RR1x2*(2*RR2x1*RR2x2*RR3x1 + RR2x1^2*RR3x2 + 3*RR2x2^2*RR3x2)) + 3*L6*RR1x3*RR2x3^2*RR3x3 + L8*RR2x3*(RR1x1*RR2x3*RR3x1 + RR1x2*RR2x3*RR3x2 + 2*RR1x1*RR2x1*RR3x3 + 2*RR1x2*RR2x2*RR3x3) + L8*RR1x3*(2*RR2x1*RR2x3*RR3x1 + RR2x1^2*RR3x3 + RR2x2*(2*RR2x3*RR3x2 + RR2x2*RR3x3))), 0}},

C[ S[5] , S[5] , S[5] , S[6] ] == {{(-3*I)*(L2*(RR2x1^2 + RR2x2^2)*(RR2x1*RR3x1 + RR2x2*RR3x2) + L6*RR2x3^3*RR3x3 + L8*RR2x3*(RR2x1*RR2x3*RR3x1 + RR2x2*RR2x3*RR3x2 + RR2x1^2*RR3x3 + RR2x2^2*RR3x3)), 0}},

C[ S[2] , S[1] , S[5] , S[6] ] == {{(-I)*L5*(RR2x2*RR3x1 + RR2x1*RR3x2), 0}},

C[ S[2] , S[5] , S[6] ] == {{(-I)*(RR2x3*RR3x1*Timag + RR2x1*RR3x3*Timag + RR2x3*RR3x2*Treal + RR2x2*RR3x3*Treal + L5*RR2x2*RR3x1*v + L5*RR2x1*RR3x2*v), 0}},

C[ S[6] , S[6] , S[7] , -S[7] ] == {{(-I)*(L2*(RR3x1^2 + RR3x2^2) + L8*RR3x3^2), 0}},

C[ S[2] , S[2] , S[6] , S[6] ] == {{(-I)*(-(L5*RR3x1^2) + L5*RR3x2^2 + L3*(RR3x1^2 + RR3x2^2) + L4*(RR3x1^2 + RR3x2^2) + L7*RR3x3^2), 0}},

C[ S[3] , -S[3] , S[6] , S[6] ] == {{(-I)*(L3*(RR3x1^2 + RR3x2^2) + L7*RR3x3^2), 0}},

C[ S[1] , S[1] , S[6] , S[6] ] == {{(-I)*(L5*RR3x1^2 - L5*RR3x2^2 + L3*(RR3x1^2 + RR3x2^2) + L4*(RR3x1^2 + RR3x2^2) + L7*RR3x3^2), 0}},

C[ S[1] , S[6] , S[6] ] == {{(-I)*(-2*RR3x2*RR3x3*Timag + 2*RR3x1*RR3x3*Treal + (L3 + L4 + L5)*RR3x1^2*v + (L3 + L4 - L5)*RR3x2^2*v + L7*RR3x3^2*v), 0}},

C[ S[4] , S[4] , S[6] , S[6] ] == {{(-I)*(L2*(4*RR1x1*RR1x2*RR3x1*RR3x2 + RR1x1^2*(3*RR3x1^2 + RR3x2^2) + RR1x2^2*(RR3x1^2 + 3*RR3x2^2)) + 3*L6*RR1x3^2*RR3x3^2 + L8*(RR1x3^2*(RR3x1^2 + RR3x2^2) + 4*RR1x3*(RR1x1*RR3x1 + RR1x2*RR3x2)*RR3x3 + (RR1x1^2 + RR1x2^2)*RR3x3^2)), 0}},

C[ S[4] , S[5] , S[6] , S[6] ] == {{(-I)*(L8*RR1x3*RR2x3*(RR3x1^2 + RR3x2^2) + L2*RR1x1*(2*RR2x2*RR3x1*RR3x2 + RR2x1*(3*RR3x1^2 + RR3x2^2)) + L2*RR1x2*(2*RR2x1*RR3x1*RR3x2 + RR2x2*(RR3x1^2 + 3*RR3x2^2)) + 2*L8*RR1x3*(RR2x1*RR3x1 + RR2x2*RR3x2)*RR3x3 + 3*L6*RR1x3*RR2x3*RR3x3^2 + L8*RR3x3*(2*RR1x1*RR2x3*RR3x1 + 2*RR1x2*RR2x3*RR3x2 + RR1x1*RR2x1*RR3x3 + RR1x2*RR2x2*RR3x3)), 0}},

C[ S[5] , S[5] , S[6] , S[6] ] == {{(-I)*(L2*(4*RR2x1*RR2x2*RR3x1*RR3x2 + RR2x1^2*(3*RR3x1^2 + RR3x2^2) + RR2x2^2*(RR3x1^2 + 3*RR3x2^2)) + 3*L6*RR2x3^2*RR3x3^2 + L8*(RR2x3^2*(RR3x1^2 + RR3x2^2) + 4*RR2x3*(RR2x1*RR3x1 + RR2x2*RR3x2)*RR3x3 + (RR2x1^2 + RR2x2^2)*RR3x3^2)), 0}},

C[ S[4] , S[6] , S[6] , S[6] ] == {{(-3*I)*(L2*(RR1x1*RR3x1 + RR1x2*RR3x2)*(RR3x1^2 + RR3x2^2) + L6*RR1x3*RR3x3^3 + L8*RR3x3*(RR1x3*RR3x1^2 + RR1x3*RR3x2^2 + RR1x1*RR3x1*RR3x3 + RR1x2*RR3x2*RR3x3)), 0}},

C[ S[5] , S[6] , S[6] , S[6] ] == {{(-3*I)*(L2*(RR2x1*RR3x1 + RR2x2*RR3x2)*(RR3x1^2 + RR3x2^2) + L6*RR2x3*RR3x3^3 + L8*RR3x3*(RR2x3*RR3x1^2 + RR2x3*RR3x2^2 + RR2x1*RR3x1*RR3x3 + RR2x2*RR3x2*RR3x3)), 0}},

C[ S[6] , S[6] , S[6] , S[6] ] == {{(-3*I)*(L2*(RR3x1^2 + RR3x2^2)^2 + 2*L8*(RR3x1^2 + RR3x2^2)*RR3x3^2 + L6*RR3x3^4), 0}},

C[ S[2] , S[1] , S[6] , S[6] ] == {{(-2*I)*L5*RR3x1*RR3x2, 0}},

C[ S[2] , S[6] , S[6] ] == {{(-2*I)*(RR3x1*RR3x3*Timag + RR3x2*RR3x3*Treal + L5*RR3x1*RR3x2*v), 0}},

C[ -F[12, {e1x2}] , F[12, {e2x2}] , V[4, {e3x2}] ] == {{I*gc164*FASUNT[e3x2, e1x2, e2x2], 0}, {I*gc164*FASUNT[e3x2, e1x2, e2x2], 0}},

C[ -F[10, {e1x2}] , F[10, {e2x2}] , V[4, {e3x2}] ] == {{I*gc165*FASUNT[e3x2, e1x2, e2x2], 0}, {I*gc165*FASUNT[e3x2, e1x2, e2x2], 0}},

C[ -F[11, {e1x2}] , F[11, {e2x2}] , V[4, {e3x2}] ] == {{I*gc166*FASUNT[e3x2, e1x2, e2x2], 0}, {I*gc166*FASUNT[e3x2, e1x2, e2x2], 0}},

C[ -F[8, {e1x2}] , F[8, {e2x2}] , V[4, {e3x2}] ] == {{I*gc167*FASUNT[e3x2, e1x2, e2x2], 0}, {I*gc167*FASUNT[e3x2, e1x2, e2x2], 0}},

C[ -F[9, {e1x2}] , F[9, {e2x2}] , V[4, {e3x2}] ] == {{I*gc168*FASUNT[e3x2, e1x2, e2x2], 0}, {I*gc168*FASUNT[e3x2, e1x2, e2x2], 0}},

C[ -F[7, {e1x2}] , F[7, {e2x2}] , V[4, {e3x2}] ] == {{I*gc169*FASUNT[e3x2, e1x2, e2x2], 0}, {I*gc169*FASUNT[e3x2, e1x2, e2x2], 0}},

C[ S[2] , -S[3] , V[1] , V[3] ] == {{-1/2*FCGV["EL"]^2/FCGV["SW"], 0}},

C[ -S[3] , S[1] , V[1] , V[3] ] == {{((I/2)*FCGV["EL"]^2)/FCGV["SW"], 0}},

C[ -S[3] , V[1] , V[3] ] == {{((I/2)*FCGV["EL"]^2*v)/FCGV["SW"], 0}},

C[ S[2] , -S[3] , V[3] ] == {{-gc173, 0}, {gc173, 0}},

C[ -S[3] , S[1] , V[3] ] == {{(-I)*gc174, 0}, {I*gc174, 0}},

C[ V[1] , V[3] , -V[3] ] == {{(-I)*gc175, 0}, {I*gc175, 0}, {I*gc175, 0}, {(-I)*gc175, 0}, {(-I)*gc175, 0}, {I*gc175, 0}},

C[ S[4] , -S[7] , V[1] , V[3] ] == {{((I/2)*FCGV["EL"]^2*(RR1x1 + I*RR1x2))/FCGV["SW"], 0}},

C[ S[4] , -S[7] , V[3] ] == {{I*gc177*(RR1x1 + I*RR1x2), 0}, {gc177*((-I)*RR1x1 + RR1x2), 0}},

C[ S[5] , -S[7] , V[1] , V[3] ] == {{((I/2)*FCGV["EL"]^2*(RR2x1 + I*RR2x2))/FCGV["SW"], 0}},

C[ S[5] , -S[7] , V[3] ] == {{I*gc179*(RR2x1 + I*RR2x2), 0}, {gc179*((-I)*RR2x1 + RR2x2), 0}},

C[ S[6] , -S[7] , V[1] , V[3] ] == {{((I/2)*FCGV["EL"]^2*(RR3x1 + I*RR3x2))/FCGV["SW"], 0}},

C[ S[6] , -S[7] , V[3] ] == {{I*gc181*(RR3x1 + I*RR3x2), 0}, {gc181*((-I)*RR3x1 + RR3x2), 0}},

C[ S[2] , S[3] , V[1] , -V[3] ] == {{FCGV["EL"]^2/(2*FCGV["SW"]), 0}},

C[ S[3] , S[1] , V[1] , -V[3] ] == {{((I/2)*FCGV["EL"]^2)/FCGV["SW"], 0}},

C[ S[3] , V[1] , -V[3] ] == {{((I/2)*FCGV["EL"]^2*v)/FCGV["SW"], 0}},

C[ S[2] , S[3] , -V[3] ] == {{-gc185, 0}, {gc185, 0}},

C[ S[3] , S[1] , -V[3] ] == {{(-I)*gc186, 0}, {I*gc186, 0}},

C[ S[4] , S[7] , V[1] , -V[3] ] == {{(FCGV["EL"]^2*(I*RR1x1 + RR1x2))/(2*FCGV["SW"]), 0}},

C[ S[4] , S[7] , -V[3] ] == {{-((gc188*(I*RR1x1 + RR1x2))/(RR1x1 + RR1x2)), 0}, {(gc188*(I*RR1x1 + RR1x2))/(RR1x1 + RR1x2), 0}},

C[ S[5] , S[7] , V[1] , -V[3] ] == {{(FCGV["EL"]^2*(I*RR2x1 + RR2x2))/(2*FCGV["SW"]), 0}},

C[ S[5] , S[7] , -V[3] ] == {{-((gc190*(I*RR2x1 + RR2x2))/(RR2x1 + RR2x2)), 0}, {(gc190*(I*RR2x1 + RR2x2))/(RR2x1 + RR2x2), 0}},

C[ S[6] , S[7] , V[1] , -V[3] ] == {{(FCGV["EL"]^2*(I*RR3x1 + RR3x2))/(2*FCGV["SW"]), 0}},

C[ S[6] , S[7] , -V[3] ] == {{-((gc192*(I*RR3x1 + RR3x2))/(RR3x1 + RR3x2)), 0}, {(gc192*(I*RR3x1 + RR3x2))/(RR3x1 + RR3x2), 0}},

C[ S[2] , S[2] , V[3] , -V[3] ] == {{((I/2)*FCGV["EL"]^2)/FCGV["SW"]^2, 0}},

C[ S[3] , -S[3] , V[3] , -V[3] ] == {{((I/2)*FCGV["EL"]^2)/FCGV["SW"]^2, 0}},

C[ S[1] , S[1] , V[3] , -V[3] ] == {{((I/2)*FCGV["EL"]^2)/FCGV["SW"]^2, 0}},

C[ S[7] , -S[7] , V[3] , -V[3] ] == {{((I/2)*FCGV["EL"]^2)/FCGV["SW"]^2, 0}},

C[ S[1] , V[3] , -V[3] ] == {{((I/2)*FCGV["EL"]^2*v)/FCGV["SW"]^2, 0}},

C[ V[1] , V[1] , V[3] , -V[3] ] == {{(-I)*gc198, 0}, {(-I)*gc198, 0}, {(2*I)*gc198, 0}},

C[ S[4] , S[4] , V[3] , -V[3] ] == {{((I/2)*FCGV["EL"]^2*(RR1x1^2 + RR1x2^2))/FCGV["SW"]^2, 0}},

C[ S[4] , S[5] , V[3] , -V[3] ] == {{((I/2)*FCGV["EL"]^2*(RR1x1*RR2x1 + RR1x2*RR2x2))/FCGV["SW"]^2, 0}},

C[ S[5] , S[5] , V[3] , -V[3] ] == {{((I/2)*FCGV["EL"]^2*(RR2x1^2 + RR2x2^2))/FCGV["SW"]^2, 0}},

C[ S[4] , S[6] , V[3] , -V[3] ] == {{((I/2)*FCGV["EL"]^2*(RR1x1*RR3x1 + RR1x2*RR3x2))/FCGV["SW"]^2, 0}},

C[ S[5] , S[6] , V[3] , -V[3] ] == {{((I/2)*FCGV["EL"]^2*(RR2x1*RR3x1 + RR2x2*RR3x2))/FCGV["SW"]^2, 0}},

C[ S[6] , S[6] , V[3] , -V[3] ] == {{((I/2)*FCGV["EL"]^2*(RR3x1^2 + RR3x2^2))/FCGV["SW"]^2, 0}},

C[ V[3] , -V[3] , V[2] ] == {{(-I)*gc205, 0}, {I*gc205, 0}, {I*gc205, 0}, {(-I)*gc205, 0}, {(-I)*gc205, 0}, {I*gc205, 0}},

C[ V[3] , V[3] , -V[3] , -V[3] ] == {{(-I)*gc206, 0}, {(-I)*gc206, 0}, {(2*I)*gc206, 0}},

C[ S[3] , -S[3] , V[1] , V[2] ] == {{(I*FCGV["EL"]^2*(FCGV["CW"] - FCGV["SW"])*(FCGV["CW"] + FCGV["SW"]))/(FCGV["CW"]*FCGV["SW"]), 0}},

C[ S[7] , -S[7] , V[1] , V[2] ] == {{(I*FCGV["EL"]^2*(FCGV["CW"] - FCGV["SW"])*(FCGV["CW"] + FCGV["SW"]))/(FCGV["CW"]*FCGV["SW"]), 0}},

C[ S[2] , S[1] , V[2] ] == {{-gc209, 0}, {gc209, 0}},

C[ S[3] , -S[3] , V[2] ] == {{(-I)*gc210, 0}, {I*gc210, 0}},

C[ S[7] , -S[7] , V[2] ] == {{(-I)*gc211, 0}, {I*gc211, 0}},

C[ S[4] , S[5] , V[2] ] == {{-gc212, 0}, {gc212, 0}},

C[ S[4] , S[6] , V[2] ] == {{-gc213, 0}, {gc213, 0}},

C[ S[5] , S[6] , V[2] ] == {{-gc214, 0}, {gc214, 0}},

C[ S[2] , -S[3] , V[3] , V[2] ] == {{FCGV["EL"]^2/(2*FCGV["CW"]), 0}},

C[ -S[3] , S[1] , V[3] , V[2] ] == {{((-1/2*I)*FCGV["EL"]^2)/FCGV["CW"], 0}},

C[ -S[3] , V[3] , V[2] ] == {{((-1/2*I)*FCGV["EL"]^2*v)/FCGV["CW"], 0}},

C[ S[4] , -S[7] , V[3] , V[2] ] == {{(FCGV["EL"]^2*((-I)*RR1x1 + RR1x2))/(2*FCGV["CW"]), 0}},

C[ S[5] , -S[7] , V[3] , V[2] ] == {{(FCGV["EL"]^2*((-I)*RR2x1 + RR2x2))/(2*FCGV["CW"]), 0}},

C[ S[6] , -S[7] , V[3] , V[2] ] == {{(FCGV["EL"]^2*((-I)*RR3x1 + RR3x2))/(2*FCGV["CW"]), 0}},

C[ S[2] , S[3] , -V[3] , V[2] ] == {{-1/2*FCGV["EL"]^2/FCGV["CW"], 0}},

C[ S[3] , S[1] , -V[3] , V[2] ] == {{((-1/2*I)*FCGV["EL"]^2)/FCGV["CW"], 0}},

C[ S[3] , -V[3] , V[2] ] == {{((-1/2*I)*FCGV["EL"]^2*v)/FCGV["CW"], 0}},

C[ S[4] , S[7] , -V[3] , V[2] ] == {{((-1/2*I)*FCGV["EL"]^2*(RR1x1 - I*RR1x2))/FCGV["CW"], 0}},

C[ S[5] , S[7] , -V[3] , V[2] ] == {{((-1/2*I)*FCGV["EL"]^2*(RR2x1 - I*RR2x2))/FCGV["CW"], 0}},

C[ S[6] , S[7] , -V[3] , V[2] ] == {{((-1/2*I)*FCGV["EL"]^2*(RR3x1 - I*RR3x2))/FCGV["CW"], 0}},

C[ V[1] , V[3] , -V[3] , V[2] ] == {{(-2*I)*gc227, 0}, {I*gc227, 0}, {I*gc227, 0}},

C[ S[2] , S[2] , V[2] , V[2] ] == {{((I/2)*FCGV["EL"]^2*(FCGV["CW"]^2 + FCGV["SW"]^2)^2)/(FCGV["CW"]^2*FCGV["SW"]^2), 0}},

C[ S[3] , -S[3] , V[2] , V[2] ] == {{((I/2)*FCGV["EL"]^2*(FCGV["CW"] - FCGV["SW"])^2*(FCGV["CW"] + FCGV["SW"])^2)/(FCGV["CW"]^2*FCGV["SW"]^2), 0}},

C[ S[1] , S[1] , V[2] , V[2] ] == {{((I/2)*FCGV["EL"]^2*(FCGV["CW"]^2 + FCGV["SW"]^2)^2)/(FCGV["CW"]^2*FCGV["SW"]^2), 0}},

C[ S[7] , -S[7] , V[2] , V[2] ] == {{((I/2)*FCGV["EL"]^2*(FCGV["CW"] - FCGV["SW"])^2*(FCGV["CW"] + FCGV["SW"])^2)/(FCGV["CW"]^2*FCGV["SW"]^2), 0}},

C[ S[1] , V[2] , V[2] ] == {{((I/2)*FCGV["EL"]^2*(FCGV["CW"]^2 + FCGV["SW"]^2)^2*v)/(FCGV["CW"]^2*FCGV["SW"]^2), 0}},

C[ S[4] , S[4] , V[2] , V[2] ] == {{((I/2)*FCGV["EL"]^2*(RR1x1^2 + RR1x2^2)*(FCGV["CW"]^2 + FCGV["SW"]^2)^2)/(FCGV["CW"]^2*FCGV["SW"]^2), 0}},

C[ S[4] , S[5] , V[2] , V[2] ] == {{((I/2)*FCGV["EL"]^2*(RR1x1*RR2x1 + RR1x2*RR2x2)*(FCGV["CW"]^2 + FCGV["SW"]^2)^2)/(FCGV["CW"]^2*FCGV["SW"]^2), 0}},

C[ S[5] , S[5] , V[2] , V[2] ] == {{((I/2)*FCGV["EL"]^2*(RR2x1^2 + RR2x2^2)*(FCGV["CW"]^2 + FCGV["SW"]^2)^2)/(FCGV["CW"]^2*FCGV["SW"]^2), 0}},

C[ S[4] , S[6] , V[2] , V[2] ] == {{((I/2)*FCGV["EL"]^2*(RR1x1*RR3x1 + RR1x2*RR3x2)*(FCGV["CW"]^2 + FCGV["SW"]^2)^2)/(FCGV["CW"]^2*FCGV["SW"]^2), 0}},

C[ S[5] , S[6] , V[2] , V[2] ] == {{((I/2)*FCGV["EL"]^2*(RR2x1*RR3x1 + RR2x2*RR3x2)*(FCGV["CW"]^2 + FCGV["SW"]^2)^2)/(FCGV["CW"]^2*FCGV["SW"]^2), 0}},

C[ S[6] , S[6] , V[2] , V[2] ] == {{((I/2)*FCGV["EL"]^2*(RR3x1^2 + RR3x2^2)*(FCGV["CW"]^2 + FCGV["SW"]^2)^2)/(FCGV["CW"]^2*FCGV["SW"]^2), 0}},

C[ V[3] , -V[3] , V[2] , V[2] ] == {{(-I)*gc239, 0}, {(-I)*gc239, 0}, {(2*I)*gc239, 0}},

C[ -F[12, {e1x2}] , F[12, {e2x2}] , V[1] ] == {{I*gc240*IndexDelta[e1x2, e2x2], 0}, {I*gc240*IndexDelta[e1x2, e2x2], 0}},

C[ -F[10, {e1x2}] , F[10, {e2x2}] , V[1] ] == {{I*gc241*IndexDelta[e1x2, e2x2], 0}, {I*gc241*IndexDelta[e1x2, e2x2], 0}},

C[ -F[11, {e1x2}] , F[11, {e2x2}] , V[1] ] == {{I*gc242*IndexDelta[e1x2, e2x2], 0}, {I*gc242*IndexDelta[e1x2, e2x2], 0}},

C[ -F[4] , F[4] , V[1] ] == {{I*gc243, 0}, {I*gc243, 0}},

C[ -F[5] , F[5] , V[1] ] == {{I*gc244, 0}, {I*gc244, 0}},

C[ -F[6] , F[6] , V[1] ] == {{I*gc245, 0}, {I*gc245, 0}},

C[ -F[8, {e1x2}] , F[8, {e2x2}] , V[1] ] == {{I*gc246*IndexDelta[e1x2, e2x2], 0}, {I*gc246*IndexDelta[e1x2, e2x2], 0}},

C[ -F[9, {e1x2}] , F[9, {e2x2}] , V[1] ] == {{I*gc247*IndexDelta[e1x2, e2x2], 0}, {I*gc247*IndexDelta[e1x2, e2x2], 0}},

C[ -F[7, {e1x2}] , F[7, {e2x2}] , V[1] ] == {{I*gc248*IndexDelta[e1x2, e2x2], 0}, {I*gc248*IndexDelta[e1x2, e2x2], 0}},

C[ -F[1] , F[4] , V[3] ] == {{I*gc249, 0}, {0, 0}},

C[ -F[2] , F[5] , V[3] ] == {{I*gc250, 0}, {0, 0}},

C[ -F[3] , F[6] , V[3] ] == {{I*gc251, 0}, {0, 0}},

C[ -F[8, {e1x2}] , F[12, {e2x2}] , V[3] ] == {{I*gc252*IndexDelta[e1x2, e2x2], 0}, {0, 0}},

C[ -F[8, {e1x2}] , F[10, {e2x2}] , V[3] ] == {{I*gc253*IndexDelta[e1x2, e2x2], 0}, {0, 0}},

C[ -F[8, {e1x2}] , F[11, {e2x2}] , V[3] ] == {{I*gc254*IndexDelta[e1x2, e2x2], 0}, {0, 0}},

C[ -F[9, {e1x2}] , F[12, {e2x2}] , V[3] ] == {{I*gc255*IndexDelta[e1x2, e2x2], 0}, {0, 0}},

C[ -F[9, {e1x2}] , F[10, {e2x2}] , V[3] ] == {{I*gc256*IndexDelta[e1x2, e2x2], 0}, {0, 0}},

C[ -F[9, {e1x2}] , F[11, {e2x2}] , V[3] ] == {{I*gc257*IndexDelta[e1x2, e2x2], 0}, {0, 0}},

C[ -F[7, {e1x2}] , F[12, {e2x2}] , V[3] ] == {{I*gc258*IndexDelta[e1x2, e2x2], 0}, {0, 0}},

C[ -F[7, {e1x2}] , F[10, {e2x2}] , V[3] ] == {{I*gc259*IndexDelta[e1x2, e2x2], 0}, {0, 0}},

C[ -F[7, {e1x2}] , F[11, {e2x2}] , V[3] ] == {{I*gc260*IndexDelta[e1x2, e2x2], 0}, {0, 0}},

C[ -F[4] , F[1] , -V[3] ] == {{I*gc261, 0}, {0, 0}},

C[ -F[5] , F[2] , -V[3] ] == {{I*gc262, 0}, {0, 0}},

C[ -F[6] , F[3] , -V[3] ] == {{I*gc263, 0}, {0, 0}},

C[ -F[12, {e1x2}] , F[8, {e2x2}] , -V[3] ] == {{I*gc264*IndexDelta[e1x2, e2x2], 0}, {0, 0}},

C[ -F[12, {e1x2}] , F[9, {e2x2}] , -V[3] ] == {{I*gc265*IndexDelta[e1x2, e2x2], 0}, {0, 0}},

C[ -F[12, {e1x2}] , F[7, {e2x2}] , -V[3] ] == {{I*gc266*IndexDelta[e1x2, e2x2], 0}, {0, 0}},

C[ -F[10, {e1x2}] , F[8, {e2x2}] , -V[3] ] == {{I*gc267*IndexDelta[e1x2, e2x2], 0}, {0, 0}},

C[ -F[10, {e1x2}] , F[9, {e2x2}] , -V[3] ] == {{I*gc268*IndexDelta[e1x2, e2x2], 0}, {0, 0}},

C[ -F[10, {e1x2}] , F[7, {e2x2}] , -V[3] ] == {{I*gc269*IndexDelta[e1x2, e2x2], 0}, {0, 0}},

C[ -F[11, {e1x2}] , F[8, {e2x2}] , -V[3] ] == {{I*gc270*IndexDelta[e1x2, e2x2], 0}, {0, 0}},

C[ -F[11, {e1x2}] , F[9, {e2x2}] , -V[3] ] == {{I*gc271*IndexDelta[e1x2, e2x2], 0}, {0, 0}},

C[ -F[11, {e1x2}] , F[7, {e2x2}] , -V[3] ] == {{I*gc272*IndexDelta[e1x2, e2x2], 0}, {0, 0}},

C[ -F[12, {e1x2}] , F[12, {e2x2}] , V[2] ] == {{I*gc273L*IndexDelta[e1x2, e2x2], 0}, {I*gc273R*IndexDelta[e1x2, e2x2], 0}},

C[ -F[10, {e1x2}] , F[10, {e2x2}] , V[2] ] == {{I*gc274L*IndexDelta[e1x2, e2x2], 0}, {I*gc274R*IndexDelta[e1x2, e2x2], 0}},

C[ -F[11, {e1x2}] , F[11, {e2x2}] , V[2] ] == {{I*gc275L*IndexDelta[e1x2, e2x2], 0}, {I*gc275R*IndexDelta[e1x2, e2x2], 0}},

C[ -F[4] , F[4] , V[2] ] == {{I*gc276L, 0}, {I*gc276R, 0}},

C[ -F[5] , F[5] , V[2] ] == {{I*gc277L, 0}, {I*gc277R, 0}},

C[ -F[6] , F[6] , V[2] ] == {{I*gc278L, 0}, {I*gc278R, 0}},

C[ -F[8, {e1x2}] , F[8, {e2x2}] , V[2] ] == {{I*gc279L*IndexDelta[e1x2, e2x2], 0}, {I*gc279R*IndexDelta[e1x2, e2x2], 0}},

C[ -F[9, {e1x2}] , F[9, {e2x2}] , V[2] ] == {{I*gc280L*IndexDelta[e1x2, e2x2], 0}, {I*gc280R*IndexDelta[e1x2, e2x2], 0}},

C[ -F[7, {e1x2}] , F[7, {e2x2}] , V[2] ] == {{I*gc281L*IndexDelta[e1x2, e2x2], 0}, {I*gc281R*IndexDelta[e1x2, e2x2], 0}},

C[ -F[1] , F[1] , V[2] ] == {{I*gc282, 0}, {0, 0}},

C[ -F[2] , F[2] , V[2] ] == {{I*gc283, 0}, {0, 0}},

C[ -F[3] , F[3] , V[2] ] == {{I*gc284, 0}, {0, 0}}

}

(* * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * *)

(* Parameter replacement lists (These lists were created by FeynRules) *)

(* FA Couplings *)

M$FACouplings = {
     gc19 -> -FCGV["EL"],
     gc20 -> -FCGV["EL"],
     gc21 -> FCGV["EL"],
     gc22 -> -FCGV["EL"],
     gc24 -> FCGV["EL"],
     gc27 -> -FCGV["EL"],
     gc28 -> -((FCGV["CW"]*FCGV["EL"])/FCGV["SW"]),
     gc30 -> (FCGV["CW"]*FCGV["EL"])/FCGV["SW"],
     gc32 -> -FCGV["EL"],
     gc35 -> FCGV["EL"],
     gc36 -> (FCGV["CW"]*FCGV["EL"])/FCGV["SW"],
     gc38 -> -((FCGV["CW"]*FCGV["EL"])/FCGV["SW"]),
     gc40 -> (FCGV["CW"]*FCGV["EL"])/FCGV["SW"],
     gc42 -> -((FCGV["CW"]*FCGV["EL"])/FCGV["SW"]),
     gc44 -> FAGS,
     gc45 -> -FAGS,
     gc46 -> -FAGS^2,
     gc47L -> -(FCGV["MB"]/v),
     gc47R -> FCGV["MB"]/v,
     gc48 -> -(FCGV["MB"]/v),
     gc49L -> -(FCGV["MD"]/v),
     gc49R -> FCGV["MD"]/v,
     gc50 -> -(FCGV["MD"]/v),
     gc51L -> -(FCGV["MS"]/v),
     gc51R -> FCGV["MS"]/v,
     gc52 -> -(FCGV["MS"]/v),
     gc53L -> -((Sqrt[2]*FCGV["MS"]*Conjugate[CKM2x3])/v),
     gc53R -> (Sqrt[2]*FCGV["MT"]*Conjugate[CKM2x3])/v,
     gc54L -> -((Sqrt[2]*FCGV["MB"]*Conjugate[CKM3x3])/v),
     gc54R -> (Sqrt[2]*FCGV["MT"]*Conjugate[CKM3x3])/v,
     gc55L -> -((Sqrt[2]*FCGV["MD"]*Conjugate[CKM1x3])/v),
     gc55R -> (Sqrt[2]*FCGV["MT"]*Conjugate[CKM1x3])/v,
     gc56L -> -((Sqrt[2]*FCGV["MS"]*Conjugate[CKM2x1])/v),
     gc56R -> (Sqrt[2]*FCGV["MU"]*Conjugate[CKM2x1])/v,
     gc57L -> -((Sqrt[2]*FCGV["MB"]*Conjugate[CKM3x1])/v),
     gc57R -> (Sqrt[2]*FCGV["MU"]*Conjugate[CKM3x1])/v,
     gc58L -> -((Sqrt[2]*FCGV["MD"]*Conjugate[CKM1x1])/v),
     gc58R -> (Sqrt[2]*FCGV["MU"]*Conjugate[CKM1x1])/v,
     gc59L -> -((Sqrt[2]*FCGV["MS"]*Conjugate[CKM2x2])/v),
     gc59R -> (Sqrt[2]*FCGV["MC"]*Conjugate[CKM2x2])/v,
     gc60L -> -((Sqrt[2]*FCGV["MB"]*Conjugate[CKM3x2])/v),
     gc60R -> (Sqrt[2]*FCGV["MC"]*Conjugate[CKM3x2])/v,
     gc61L -> -((Sqrt[2]*FCGV["MD"]*Conjugate[CKM1x2])/v),
     gc61R -> (Sqrt[2]*FCGV["MC"]*Conjugate[CKM1x2])/v,
     gc62L -> -(Me/v),
     gc62R -> Me/v,
     gc63 -> -(Me/v),
     gc64L -> -(FCGV["MM"]/v),
     gc64R -> FCGV["MM"]/v,
     gc65 -> -(FCGV["MM"]/v),
     gc66L -> -(MTA/v),
     gc66R -> MTA/v,
     gc67 -> -(MTA/v),
     gc68 -> -((Sqrt[2]*Me)/v),
     gc69 -> -((Sqrt[2]*FCGV["MM"])/v),
     gc70 -> -((Sqrt[2]*MTA)/v),
     gc71L -> (Sqrt[2]*CKM2x3*FCGV["MT"])/v,
     gc71R -> -((Sqrt[2]*CKM2x3*FCGV["MS"])/v),
     gc72L -> (Sqrt[2]*CKM2x1*FCGV["MU"])/v,
     gc72R -> -((Sqrt[2]*CKM2x1*FCGV["MS"])/v),
     gc73L -> (Sqrt[2]*CKM2x2*FCGV["MC"])/v,
     gc73R -> -((Sqrt[2]*CKM2x2*FCGV["MS"])/v),
     gc74L -> (Sqrt[2]*CKM3x3*FCGV["MT"])/v,
     gc74R -> -((Sqrt[2]*CKM3x3*FCGV["MB"])/v),
     gc75L -> (Sqrt[2]*CKM3x1*FCGV["MU"])/v,
     gc75R -> -((Sqrt[2]*CKM3x1*FCGV["MB"])/v),
     gc76L -> (Sqrt[2]*CKM3x2*FCGV["MC"])/v,
     gc76R -> -((Sqrt[2]*CKM3x2*FCGV["MB"])/v),
     gc77L -> (Sqrt[2]*CKM1x3*FCGV["MT"])/v,
     gc77R -> -((Sqrt[2]*CKM1x3*FCGV["MD"])/v),
     gc78L -> (Sqrt[2]*CKM1x1*FCGV["MU"])/v,
     gc78R -> -((Sqrt[2]*CKM1x1*FCGV["MD"])/v),
     gc79L -> (Sqrt[2]*CKM1x2*FCGV["MC"])/v,
     gc79R -> -((Sqrt[2]*CKM1x2*FCGV["MD"])/v),
     gc80L -> FCGV["MC"]/v,
     gc80R -> -(FCGV["MC"]/v),
     gc81 -> -(FCGV["MC"]/v),
     gc82L -> FCGV["MT"]/v,
     gc82R -> -(FCGV["MT"]/v),
     gc83 -> -(FCGV["MT"]/v),
     gc84L -> FCGV["MU"]/v,
     gc84R -> -(FCGV["MU"]/v),
     gc85 -> -(FCGV["MU"]/v),
     gc86R -> -((Sqrt[2]*Me)/v),
     gc87R -> -((Sqrt[2]*FCGV["MM"])/v),
     gc88R -> -((Sqrt[2]*MTA)/v),
     gc164 -> FAGS,
     gc165 -> FAGS,
     gc166 -> FAGS,
     gc167 -> FAGS,
     gc168 -> FAGS,
     gc169 -> FAGS,
     gc173 -> FCGV["EL"]/(2*FCGV["SW"]),
     gc174 -> FCGV["EL"]/(2*FCGV["SW"]),
     gc175 -> FCGV["EL"],
     gc177 -> FCGV["EL"]/(2*FCGV["SW"]),
     gc179 -> FCGV["EL"]/(2*FCGV["SW"]),
     gc181 -> FCGV["EL"]/(2*FCGV["SW"]),
     gc185 -> FCGV["EL"]/(2*FCGV["SW"]),
     gc186 -> -1/2*FCGV["EL"]/FCGV["SW"],
     gc188 -> (FCGV["EL"]*(RR1x1 + RR1x2))/(2*FCGV["SW"]),
     gc190 -> (FCGV["EL"]*(RR2x1 + RR2x2))/(2*FCGV["SW"]),
     gc192 -> (FCGV["EL"]*(RR3x1 + RR3x2))/(2*FCGV["SW"]),
     gc198 -> -FCGV["EL"]^2,
     gc205 -> (FCGV["CW"]*FCGV["EL"])/FCGV["SW"],
     gc206 -> FCGV["EL"]^2/FCGV["SW"]^2,
     gc209 -> -1/2*(FCGV["EL"]*(FCGV["CW"]^2 + FCGV["SW"]^2))/(FCGV["CW"]*FCGV["SW"]),
     gc210 -> -1/2*(FCGV["CW"]*FCGV["EL"])/FCGV["SW"] + (FCGV["EL"]*FCGV["SW"])/(2*FCGV["CW"]),
     gc211 -> -1/2*(FCGV["CW"]*FCGV["EL"])/FCGV["SW"] + (FCGV["EL"]*FCGV["SW"])/(2*FCGV["CW"]),
     gc212 -> -1/2*(FCGV["EL"]*(RR1x2*RR2x1 - RR1x1*RR2x2)*(FCGV["CW"]^2 + FCGV["SW"]^2))/(FCGV["CW"]*FCGV["SW"]),
     gc213 -> -1/2*(FCGV["EL"]*(RR1x2*RR3x1 - RR1x1*RR3x2)*(FCGV["CW"]^2 + FCGV["SW"]^2))/(FCGV["CW"]*FCGV["SW"]),
     gc214 -> -1/2*(FCGV["EL"]*(RR2x2*RR3x1 - RR2x1*RR3x2)*(FCGV["CW"]^2 + FCGV["SW"]^2))/(FCGV["CW"]*FCGV["SW"]),
     gc227 -> (FCGV["CW"]*FCGV["EL"]^2)/FCGV["SW"],
     gc239 -> -((FCGV["CW"]^2*FCGV["EL"]^2)/FCGV["SW"]^2),
     gc240 -> -1/3*FCGV["EL"],
     gc241 -> -1/3*FCGV["EL"],
     gc242 -> -1/3*FCGV["EL"],
     gc243 -> -FCGV["EL"],
     gc244 -> -FCGV["EL"],
     gc245 -> -FCGV["EL"],
     gc246 -> (2*FCGV["EL"])/3,
     gc247 -> (2*FCGV["EL"])/3,
     gc248 -> (2*FCGV["EL"])/3,
     gc249 -> FCGV["EL"]/(Sqrt[2]*FCGV["SW"]),
     gc250 -> FCGV["EL"]/(Sqrt[2]*FCGV["SW"]),
     gc251 -> FCGV["EL"]/(Sqrt[2]*FCGV["SW"]),
     gc252 -> (CKM2x3*FCGV["EL"])/(Sqrt[2]*FCGV["SW"]),
     gc253 -> (CKM2x1*FCGV["EL"])/(Sqrt[2]*FCGV["SW"]),
     gc254 -> (CKM2x2*FCGV["EL"])/(Sqrt[2]*FCGV["SW"]),
     gc255 -> (CKM3x3*FCGV["EL"])/(Sqrt[2]*FCGV["SW"]),
     gc256 -> (CKM3x1*FCGV["EL"])/(Sqrt[2]*FCGV["SW"]),
     gc257 -> (CKM3x2*FCGV["EL"])/(Sqrt[2]*FCGV["SW"]),
     gc258 -> (CKM1x3*FCGV["EL"])/(Sqrt[2]*FCGV["SW"]),
     gc259 -> (CKM1x1*FCGV["EL"])/(Sqrt[2]*FCGV["SW"]),
     gc260 -> (CKM1x2*FCGV["EL"])/(Sqrt[2]*FCGV["SW"]),
     gc261 -> FCGV["EL"]/(Sqrt[2]*FCGV["SW"]),
     gc262 -> FCGV["EL"]/(Sqrt[2]*FCGV["SW"]),
     gc263 -> FCGV["EL"]/(Sqrt[2]*FCGV["SW"]),
     gc264 -> (FCGV["EL"]*Conjugate[CKM2x3])/(Sqrt[2]*FCGV["SW"]),
     gc265 -> (FCGV["EL"]*Conjugate[CKM3x3])/(Sqrt[2]*FCGV["SW"]),
     gc266 -> (FCGV["EL"]*Conjugate[CKM1x3])/(Sqrt[2]*FCGV["SW"]),
     gc267 -> (FCGV["EL"]*Conjugate[CKM2x1])/(Sqrt[2]*FCGV["SW"]),
     gc268 -> (FCGV["EL"]*Conjugate[CKM3x1])/(Sqrt[2]*FCGV["SW"]),
     gc269 -> (FCGV["EL"]*Conjugate[CKM1x1])/(Sqrt[2]*FCGV["SW"]),
     gc270 -> (FCGV["EL"]*Conjugate[CKM2x2])/(Sqrt[2]*FCGV["SW"]),
     gc271 -> (FCGV["EL"]*Conjugate[CKM3x2])/(Sqrt[2]*FCGV["SW"]),
     gc272 -> (FCGV["EL"]*Conjugate[CKM1x2])/(Sqrt[2]*FCGV["SW"]),
     gc273L -> -1/6*(FCGV["EL"]*(3*FCGV["CW"]^2 + FCGV["SW"]^2))/(FCGV["CW"]*FCGV["SW"]),
     gc273R -> (FCGV["EL"]*FCGV["SW"])/(3*FCGV["CW"]),
     gc274L -> -1/6*(FCGV["EL"]*(3*FCGV["CW"]^2 + FCGV["SW"]^2))/(FCGV["CW"]*FCGV["SW"]),
     gc274R -> (FCGV["EL"]*FCGV["SW"])/(3*FCGV["CW"]),
     gc275L -> -1/6*(FCGV["EL"]*(3*FCGV["CW"]^2 + FCGV["SW"]^2))/(FCGV["CW"]*FCGV["SW"]),
     gc275R -> (FCGV["EL"]*FCGV["SW"])/(3*FCGV["CW"]),
     gc276L -> -1/2*(FCGV["EL"]*(FCGV["CW"]^2 - FCGV["SW"]^2))/(FCGV["CW"]*FCGV["SW"]),
     gc276R -> (FCGV["EL"]*FCGV["SW"])/FCGV["CW"],
     gc277L -> -1/2*(FCGV["EL"]*(FCGV["CW"]^2 - FCGV["SW"]^2))/(FCGV["CW"]*FCGV["SW"]),
     gc277R -> (FCGV["EL"]*FCGV["SW"])/FCGV["CW"],
     gc278L -> -1/2*(FCGV["EL"]*(FCGV["CW"]^2 - FCGV["SW"]^2))/(FCGV["CW"]*FCGV["SW"]),
     gc278R -> (FCGV["EL"]*FCGV["SW"])/FCGV["CW"],
     gc279L -> (FCGV["CW"]*FCGV["EL"])/(2*FCGV["SW"]) - (FCGV["EL"]*FCGV["SW"])/(6*FCGV["CW"]),
     gc279R -> (-2*FCGV["EL"]*FCGV["SW"])/(3*FCGV["CW"]),
     gc280L -> (FCGV["CW"]*FCGV["EL"])/(2*FCGV["SW"]) - (FCGV["EL"]*FCGV["SW"])/(6*FCGV["CW"]),
     gc280R -> (-2*FCGV["EL"]*FCGV["SW"])/(3*FCGV["CW"]),
     gc281L -> (FCGV["CW"]*FCGV["EL"])/(2*FCGV["SW"]) - (FCGV["EL"]*FCGV["SW"])/(6*FCGV["CW"]),
     gc281R -> (-2*FCGV["EL"]*FCGV["SW"])/(3*FCGV["CW"]),
     gc282 -> (FCGV["EL"]*(FCGV["CW"]^2 + FCGV["SW"]^2))/(2*FCGV["CW"]*FCGV["SW"]),
     gc283 -> (FCGV["EL"]*(FCGV["CW"]^2 + FCGV["SW"]^2))/(2*FCGV["CW"]*FCGV["SW"]),
     gc284 -> (FCGV["EL"]*(FCGV["CW"]^2 + FCGV["SW"]^2))/(2*FCGV["CW"]*FCGV["SW"])};

