///////////////////CODE GENERATED VIA MATHEMATICA///////////////////


#pragma once

#include <functional>
#include <string>

namespace DT{
	extern double aEWM1;
	extern double Gf;
	extern double aS;
	extern double QS;
	extern double lPhi;
	extern double lam3;
	extern double y1e;
	extern double y1m;
	extern double y1t;
	extern double GG;
	extern double Mnue;
	extern double Mnum;
	extern double Mnut;
	extern double Me;
	extern double MM;
	extern double MTA;
	extern double MU;
	extern double MC;
	extern double MT;
	extern double MD;
	extern double MS;
	extern double MB;
	extern double MZ;
	extern double MW;
	extern double mN1;
	extern double mH;
	extern double mphich;
	extern double WT;
	extern double WZ;
	extern double WW;
	extern double WN1;
	extern double WH;
	extern double Wphich;
	extern double E;
	extern double Pi;
	extern double EE;
	extern double CW2;
	extern double SW2;
	extern double CW;
	extern double SW;
	extern double g1;
	extern double g2;
	extern double v;
	extern double CKM1x1;
	extern double CKM1x2;
	extern double CKM1x3;
	extern double CKM2x1;
	extern double CKM2x2;
	extern double CKM2x3;
	extern double CKM3x1;
	extern double CKM3x2;
	extern double CKM3x3;
	extern double muH;
	extern double lH;
	extern double mPhisq;
	extern double gc7;
	extern double gc8;
	extern double gc9;
	extern double gc10;
	extern double gc11;
	extern double gc12;
	extern double gc13;
	extern double gc14;
	extern double gc15;
	extern double gc16;
	extern double gc17;
	extern double gc18;
	extern double gc19;
	extern double gc20;
	extern double gc21;
	extern double gc22;
	extern double gc23;
	extern double gc24;
	extern double gc25;
	extern double gc26;
	extern double gc27;
	extern double gc28;
	extern double gc29;
	extern double gc30;
	extern double gc31;
	extern double gc32;
	extern double gc35;
	extern double gc36;
	extern double gc37;
	extern double gc39;
	extern double gc40;
	extern double gc44;
	extern double gc45;
	extern double gc46;
	extern double gc47;
	extern double gc48;
	extern double gc49;
	extern double gc50;
	extern double gc51;
	extern double gc52;
	extern double gc53;
	extern double gc54;
	extern double gc55;
	extern double gc56;
	extern double gc57;
	extern double gc58;
	extern double gc59;
	extern double gc60;
	extern double gc61;
	extern double gc62;
	extern double gc63;
	extern double gc64;
	extern double gc65;
	extern double gc66;
	extern double gc67;
	extern double gc68;
	extern double gc69;
	extern double gc70;
	extern double gc71;
	extern double gc72;
	extern double gc73;
	extern double gc74;
	extern double gc75;
	extern double gc76;
	extern double gc77;
	extern double gc78L;
	extern double gc78R;
	extern double gc79L;
	extern double gc79R;
	extern double gc80L;
	extern double gc80R;
	extern double gc81L;
	extern double gc81R;
	extern double gc82L;
	extern double gc82R;
	extern double gc83L;
	extern double gc83R;
	extern double gc84L;
	extern double gc84R;
	extern double gc85L;
	extern double gc85R;
	extern double gc86L;
	extern double gc86R;
	extern double gc87;
	extern double gc88;
	extern double gc89;
	extern double EL;
	extern double ee;
	extern double gs;
	extern double G;
	extern double FAGS;
	struct chinfo{
		double inimass[6];
		double den_structure[6];
		double neutraldsmasses[1];
		double boundaries[9];
		bool iniswitch[3];
		std::function<double(double, double)> inifunc[3];
		std::string name[52];
		std::function<double(double, double)> amp2[52];
		std::function<double(double, double)> amp2fl[52];
		double* mass1[52];
		double* mass2[52];
		double* mass3[52];
		double* mass4[52];
	};
}
