///////////////////CODE GENERATED VIA MATHEMATICA///////////////////

#pragma once

#include <cmath>
#include <complex>

#define SUM1(arg, i, ni)                       \
    for (size_t i = 0; i < ni; i++) {          \
        res += arg;                            \
    }
#define SUM2(arg, i, ni, j, nj)           \
    for (size_t i = 0; i < ni; i++)       \
        for (size_t j = 0; j < nj; j++) { \
            res += arg;                   \
        }

namespace DT {
namespace PAR {
extern std::complex<double> I;
extern std::complex<double> We1;
extern std::complex<double> We2;
extern std::complex<double> We3;
extern std::complex<double> Wd1;
extern std::complex<double> Wd2;
extern std::complex<double> Wd3;
extern std::complex<double> Wu1;
extern std::complex<double> Wu2;
extern std::complex<double> Wu3;
extern std::complex<double> Maux;
extern std::complex<double> sqrt2;
extern std::complex<double> Pi;
extern std::complex<double> Q;
extern std::complex<double> alfSMZ;
extern std::complex<double> aS;
extern std::complex<double> aEWinv;
extern std::complex<double> Gf;
extern std::complex<double> rd;
extern std::complex<double> Msd[6];
extern std::complex<double> Msu[6];
extern std::complex<double> Msv[3];
extern std::complex<double> Mse[6];
extern std::complex<double> Mh[6];
extern std::complex<double> MHm[2];
extern std::complex<double> MZ;
extern std::complex<double> Mgo;
extern std::complex<double> MN[5];
extern std::complex<double> MC[2];
extern std::complex<double> Me[3];
extern std::complex<double> Md[3];
extern std::complex<double> Mu[3];
extern std::complex<double> Yd[3][3];
extern std::complex<double> Td[3][3];
extern std::complex<double> Ye[3][3];
extern std::complex<double> Te[3][3];
extern std::complex<double> lam;
extern std::complex<double> Tlam;
extern std::complex<double> kap;
extern std::complex<double> Tk;
extern std::complex<double> Yu[3][3];
extern std::complex<double> Tu[3][3];
extern std::complex<double> eta;
extern std::complex<double> etaS;
extern std::complex<double> PhiUL;
extern std::complex<double> PhiUR;
extern std::complex<double> vS;
extern std::complex<double> pG;
extern std::complex<double> ZD[6][6];
extern std::complex<double> ZU[6][6];
extern std::complex<double> ZV[3][3];
extern std::complex<double> ZE[6][6];
extern std::complex<double> ZH[6][6];
extern std::complex<double> ZP[2][2];
extern std::complex<double> ZN[5][5];
extern std::complex<double> UM[2][2];
extern std::complex<double> UP[2][2];
extern std::complex<double> ZEL[3][3];
extern std::complex<double> ZER[3][3];
extern std::complex<double> ZDL[3][3];
extern std::complex<double> ZDR[3][3];
extern std::complex<double> ZUL[3][3];
extern std::complex<double> ZUR[3][3];
extern std::complex<double> TBeta;
extern std::complex<double> HPP1;
extern std::complex<double> HGG1;
extern std::complex<double> HPP2;
extern std::complex<double> HGG2;
extern std::complex<double> HPP3;
extern std::complex<double> HGG3;
extern std::complex<double> HPP4;
extern std::complex<double> HGG4;
extern std::complex<double> HPP5;
extern std::complex<double> HGG5;
extern std::complex<double> HPP6;
extern std::complex<double> HGG6;
extern std::complex<double> QCDok;
extern std::complex<double> g3;
extern std::complex<double> el;
extern std::complex<double> MWm;
extern std::complex<double> TW;
extern std::complex<double> STW;
extern std::complex<double> CTW;
extern std::complex<double> TTW;
extern std::complex<double> g1;
extern std::complex<double> g2;
extern std::complex<double> v;
extern std::complex<double> vd;
extern std::complex<double> vu;

extern std::complex<double> coup1[6];
extern std::complex<double> coup2[6];
extern std::complex<double> coup3[6];
extern std::complex<double> coup4[5];
extern std::complex<double> coup5[5];
extern std::complex<double> coup6[6];
extern std::complex<double> coup7;
extern std::complex<double> coup8;
extern std::complex<double> coup9;
extern std::complex<double> coup10[5];
extern std::complex<double> coup11[5];
extern std::complex<double> coup12[6];
extern std::complex<double> coup13;
extern std::complex<double> coup14[5];
extern std::complex<double> coup15[5];
extern std::complex<double> coup16[6];
extern std::complex<double> coup17;
extern std::complex<double> coup18[5];
extern std::complex<double> coup19[5];
extern std::complex<double> coup20[6];
extern std::complex<double> coup21;
extern std::complex<double> coup22[5];
extern std::complex<double> coup23[5];
extern std::complex<double> coup24[6];
extern std::complex<double> coup25[6];
extern std::complex<double> coup26;
extern std::complex<double> coup27[6];
extern std::complex<double> coup28;
extern std::complex<double> coup29[6];
extern std::complex<double> coup30;
extern std::complex<double> coup31[6];
extern std::complex<double> coup32[6];
extern std::complex<double> coup33;
extern std::complex<double> coup34[6];
extern std::complex<double> coup35;
extern std::complex<double> coup36[6];
extern std::complex<double> coup37[6];
extern std::complex<double> coup38;
extern std::complex<double> coup39[6];
extern std::complex<double> coup40[6];
extern std::complex<double> coup41;
extern std::complex<double> coup42[2];
extern std::complex<double> coup43[2];
extern std::complex<double> coup44[2];
extern std::complex<double> coup45[2];
extern std::complex<double> coup46[6];
extern std::complex<double> coup47;
extern std::complex<double> coup48[2];
extern std::complex<double> coup49[2];
extern std::complex<double> coup50[6];
extern std::complex<double> coup51;
extern std::complex<double> coup52[2];
extern std::complex<double> coup53[2];
extern std::complex<double> coup54[6];
extern std::complex<double> coup55;
extern std::complex<double> coup56[5];
extern std::complex<double> coup57[5];
extern std::complex<double> coup58[5];
extern std::complex<double> coup59[5];
extern std::complex<double> coup60[6];
extern std::complex<double> coup61;
extern std::complex<double> coup62[6];
extern std::complex<double> coup63;
extern std::complex<double> coup64[6];
extern std::complex<double> coup65;
extern std::complex<double> coup66[6];
extern std::complex<double> coup67;
extern std::complex<double> coup68[6];
extern std::complex<double> coup69;
extern std::complex<double> coup70[2];
extern std::complex<double> coup71[2];
extern std::complex<double> coup72[2];
extern std::complex<double> coup73[2];
extern std::complex<double> coup74[6];
extern std::complex<double> coup75;
extern std::complex<double> coup76[6];
extern std::complex<double> coup77[6];
extern std::complex<double> coup78[2];
extern std::complex<double> coup79[2];
extern std::complex<double> coup80[2];
extern std::complex<double> coup81[2];
extern std::complex<double> coup82;
extern std::complex<double> coup83[3];
extern std::complex<double> coup84[3];
extern std::complex<double> coup85[3];
extern std::complex<double> coup86[3];
extern std::complex<double> coup87[3];
extern std::complex<double> coup88[3];
extern std::complex<double> coup89[6];
extern std::complex<double> coup90[6];
extern std::complex<double> coup91;
extern std::complex<double> coup92;
extern std::complex<double> coup93[6];
extern std::complex<double> coup94[6];
extern std::complex<double> coup95[6];
extern std::complex<double> coup96[6];
extern std::complex<double> coup97[6];
extern std::complex<double> coup98[6];
extern std::complex<double> coup99[6];
extern std::complex<double> coup100[6];
extern std::complex<double> coup101[6];
extern std::complex<double> coup102[6];
extern std::complex<double> coup103[6];
extern std::complex<double> coup104[6];
extern std::complex<double> coup105[6];
extern std::complex<double> coup106[6];
extern std::complex<double> coup107[6];
extern std::complex<double> coup108[6];
extern std::complex<double> coup109[6];
extern std::complex<double> coup110[6];
extern std::complex<double> coup111;
extern std::complex<double> coup112;
extern std::complex<double> coup113[6];
extern std::complex<double> coup114[6];
extern std::complex<double> coup115[6];
extern std::complex<double> coup116[6];
extern std::complex<double> coup117[6];
extern std::complex<double> coup118[6];
extern std::complex<double> coup119[6];
extern std::complex<double> coup120[6];
extern std::complex<double> coup121[6];
extern std::complex<double> coup122[6];
extern std::complex<double> coup123[6];
extern std::complex<double> coup124[6];
extern std::complex<double> coup125[6];
extern std::complex<double> coup126[6];
extern std::complex<double> coup127[6];
extern std::complex<double> coup128[6];
extern std::complex<double> coup129[6];
extern std::complex<double> coup130[6];
extern std::complex<double> coup131;
extern std::complex<double> coup132;
extern std::complex<double> coup133[6];
extern std::complex<double> coup134[6];
extern std::complex<double> coup135[6];
extern std::complex<double> coup136[6];
extern std::complex<double> coup137[6];
extern std::complex<double> coup138[6];
extern std::complex<double> coup139[6];
extern std::complex<double> coup140[6];
extern std::complex<double> coup141[6];
extern std::complex<double> coup142[6];
extern std::complex<double> coup143[6];
extern std::complex<double> coup144[6];
extern std::complex<double> coup145[6];
extern std::complex<double> coup146[6];
extern std::complex<double> coup147[6];
extern std::complex<double> coup148[6];
extern std::complex<double> coup149[6];
extern std::complex<double> coup150[6];
extern std::complex<double> coup151[5];
extern std::complex<double> coup152[5];
extern std::complex<double> coup153;
extern std::complex<double> coup154;
extern std::complex<double> coup155[5];
extern std::complex<double> coup156[5];
extern std::complex<double> coup157[5];
extern std::complex<double> coup158[5];
extern std::complex<double> coup159[5];
extern std::complex<double> coup160[5];
extern std::complex<double> coup161[5];
extern std::complex<double> coup162[5];
extern std::complex<double> coup163[2];
extern std::complex<double> coup164[2];
extern std::complex<double> coup165[2];
extern std::complex<double> coup166[2];
extern std::complex<double> coup167[2];
extern std::complex<double> coup168[2];
extern std::complex<double> coup169[2];
extern std::complex<double> coup170[2];
extern std::complex<double> coup171[5];
extern std::complex<double> coup172[5];
extern std::complex<double> coup173[2];
extern std::complex<double> coup174[2];
extern std::complex<double> coup175[2];
extern std::complex<double> coup176[2];
extern std::complex<double> coup177[3];
extern std::complex<double> coup178[3];
extern std::complex<double> coup179[3];
extern std::complex<double> coup180[3];
extern std::complex<double> coup181[3];
extern std::complex<double> coup182[3];
extern std::complex<double> coup183[6];
extern std::complex<double> coup184[6];
extern std::complex<double> coup185[6];
extern std::complex<double> coup186[6];
extern std::complex<double> coup187[6];
extern std::complex<double> coup188[6];
extern std::complex<double> coup189[6];
extern std::complex<double> coup190[6];
extern std::complex<double> coup191[6];
extern std::complex<double> coup192[6];
extern std::complex<double> coup193[6];
extern std::complex<double> coup194[6];
extern std::complex<double> coup195[6];
extern std::complex<double> coup196[6];
extern std::complex<double> coup197[6];
extern std::complex<double> coup198[6];
extern std::complex<double> coup199[6];
extern std::complex<double> coup200[6];
extern std::complex<double> coup201[6];
extern std::complex<double> coup202[6];
extern std::complex<double> coup203[6];
extern std::complex<double> coup204[6];
extern std::complex<double> coup205[6];
extern std::complex<double> coup206[6];
extern std::complex<double> coup207[6];
extern std::complex<double> coup208[6];
extern std::complex<double> coup209[6];
extern std::complex<double> coup210[6];
extern std::complex<double> coup211[6];
extern std::complex<double> coup212[6];
extern std::complex<double> coup213[6];
extern std::complex<double> coup214[6];
extern std::complex<double> coup215[6];
extern std::complex<double> coup216[6];
extern std::complex<double> coup217[6];
extern std::complex<double> coup218[6];


}  // namespace PAR
double N1N1h2h2(const double &cos_t, const double &s);
double N1N1h2h2fl(const double &cos_t, const double &s);
double N1N1h2h3(const double &cos_t, const double &s);
double N1N1h2h3fl(const double &cos_t, const double &s);
double N1N1h2h4(const double &cos_t, const double &s);
double N1N1h2h4fl(const double &cos_t, const double &s);
double N1N1h2h5(const double &cos_t, const double &s);
double N1N1h2h5fl(const double &cos_t, const double &s);
double N1N1h2h6(const double &cos_t, const double &s);
double N1N1h2h6fl(const double &cos_t, const double &s);
double N1N1h3h3(const double &cos_t, const double &s);
double N1N1h3h3fl(const double &cos_t, const double &s);
double N1N1h3h4(const double &cos_t, const double &s);
double N1N1h3h4fl(const double &cos_t, const double &s);
double N1N1h3h5(const double &cos_t, const double &s);
double N1N1h3h5fl(const double &cos_t, const double &s);
double N1N1h3h6(const double &cos_t, const double &s);
double N1N1h3h6fl(const double &cos_t, const double &s);
double N1N1h4h4(const double &cos_t, const double &s);
double N1N1h4h4fl(const double &cos_t, const double &s);
double N1N1h4h5(const double &cos_t, const double &s);
double N1N1h4h5fl(const double &cos_t, const double &s);
double N1N1h4h6(const double &cos_t, const double &s);
double N1N1h4h6fl(const double &cos_t, const double &s);
double N1N1h5h5(const double &cos_t, const double &s);
double N1N1h5h5fl(const double &cos_t, const double &s);
double N1N1h5h6(const double &cos_t, const double &s);
double N1N1h5h6fl(const double &cos_t, const double &s);
double N1N1h6h6(const double &cos_t, const double &s);
double N1N1h6h6fl(const double &cos_t, const double &s);
double N1N1Hpm1Hpm1(const double &cos_t, const double &s);
double N1N1Hpm1Hpm1fl(const double &cos_t, const double &s);
double N1N1Hpm1Hpm2(const double &cos_t, const double &s);
double N1N1Hpm1Hpm2fl(const double &cos_t, const double &s);
double N1N1Hpm2Hpm2(const double &cos_t, const double &s);
double N1N1Hpm2Hpm2fl(const double &cos_t, const double &s);
double N1N1h2Z(const double &cos_t, const double &s);
double N1N1h2Zfl(const double &cos_t, const double &s);
double N1N1h3Z(const double &cos_t, const double &s);
double N1N1h3Zfl(const double &cos_t, const double &s);
double N1N1h4Z(const double &cos_t, const double &s);
double N1N1h4Zfl(const double &cos_t, const double &s);
double N1N1h5Z(const double &cos_t, const double &s);
double N1N1h5Zfl(const double &cos_t, const double &s);
double N1N1h6Z(const double &cos_t, const double &s);
double N1N1h6Zfl(const double &cos_t, const double &s);
double N1N1Hpm1W(const double &cos_t, const double &s);
double N1N1Hpm1Wfl(const double &cos_t, const double &s);
double N1N1Hpm2W(const double &cos_t, const double &s);
double N1N1Hpm2Wfl(const double &cos_t, const double &s);
double N1N1ZZ(const double &cos_t, const double &s);
double N1N1ZZfl(const double &cos_t, const double &s);
double N1N1WW(const double &cos_t, const double &s);
double N1N1WWfl(const double &cos_t, const double &s);
double N1N1v1v1(const double &cos_t, const double &s);
double N1N1v1v1fl(const double &cos_t, const double &s);
double N1N1v2v2(const double &cos_t, const double &s);
double N1N1v2v2fl(const double &cos_t, const double &s);
double N1N1v3v3(const double &cos_t, const double &s);
double N1N1v3v3fl(const double &cos_t, const double &s);
double N1N1e1e1(const double &cos_t, const double &s);
double N1N1e1e1fl(const double &cos_t, const double &s);
double N1N1e2e2(const double &cos_t, const double &s);
double N1N1e2e2fl(const double &cos_t, const double &s);
double N1N1e3e3(const double &cos_t, const double &s);
double N1N1e3e3fl(const double &cos_t, const double &s);
double N1N1u1u1(const double &cos_t, const double &s);
double N1N1u1u1fl(const double &cos_t, const double &s);
double N1N1u2u2(const double &cos_t, const double &s);
double N1N1u2u2fl(const double &cos_t, const double &s);
double N1N1u3u3(const double &cos_t, const double &s);
double N1N1u3u3fl(const double &cos_t, const double &s);
double N1N1d1d1(const double &cos_t, const double &s);
double N1N1d1d1fl(const double &cos_t, const double &s);
double N1N1d2d2(const double &cos_t, const double &s);
double N1N1d2d2fl(const double &cos_t, const double &s);
double N1N1d3d3(const double &cos_t, const double &s);
double N1N1d3d3fl(const double &cos_t, const double &s);
double N1N2h2h2(const double &cos_t, const double &s);
double N1N2h2h2fl(const double &cos_t, const double &s);
double N1N2h2h3(const double &cos_t, const double &s);
double N1N2h2h3fl(const double &cos_t, const double &s);
double N1N2h2h4(const double &cos_t, const double &s);
double N1N2h2h4fl(const double &cos_t, const double &s);
double N1N2h2h5(const double &cos_t, const double &s);
double N1N2h2h5fl(const double &cos_t, const double &s);
double N1N2h2h6(const double &cos_t, const double &s);
double N1N2h2h6fl(const double &cos_t, const double &s);
double N1N2h3h3(const double &cos_t, const double &s);
double N1N2h3h3fl(const double &cos_t, const double &s);
double N1N2h3h4(const double &cos_t, const double &s);
double N1N2h3h4fl(const double &cos_t, const double &s);
double N1N2h3h5(const double &cos_t, const double &s);
double N1N2h3h5fl(const double &cos_t, const double &s);
double N1N2h3h6(const double &cos_t, const double &s);
double N1N2h3h6fl(const double &cos_t, const double &s);
double N1N2h4h4(const double &cos_t, const double &s);
double N1N2h4h4fl(const double &cos_t, const double &s);
double N1N2h4h5(const double &cos_t, const double &s);
double N1N2h4h5fl(const double &cos_t, const double &s);
double N1N2h4h6(const double &cos_t, const double &s);
double N1N2h4h6fl(const double &cos_t, const double &s);
double N1N2h5h5(const double &cos_t, const double &s);
double N1N2h5h5fl(const double &cos_t, const double &s);
double N1N2h5h6(const double &cos_t, const double &s);
double N1N2h5h6fl(const double &cos_t, const double &s);
double N1N2h6h6(const double &cos_t, const double &s);
double N1N2h6h6fl(const double &cos_t, const double &s);
double N1N2Hpm1Hpm1(const double &cos_t, const double &s);
double N1N2Hpm1Hpm1fl(const double &cos_t, const double &s);
double N1N2Hpm1Hpm2(const double &cos_t, const double &s);
double N1N2Hpm1Hpm2fl(const double &cos_t, const double &s);
double N1N2Hpm2Hpm2(const double &cos_t, const double &s);
double N1N2Hpm2Hpm2fl(const double &cos_t, const double &s);
double N1N2h2Z(const double &cos_t, const double &s);
double N1N2h2Zfl(const double &cos_t, const double &s);
double N1N2h3Z(const double &cos_t, const double &s);
double N1N2h3Zfl(const double &cos_t, const double &s);
double N1N2h4Z(const double &cos_t, const double &s);
double N1N2h4Zfl(const double &cos_t, const double &s);
double N1N2h5Z(const double &cos_t, const double &s);
double N1N2h5Zfl(const double &cos_t, const double &s);
double N1N2h6Z(const double &cos_t, const double &s);
double N1N2h6Zfl(const double &cos_t, const double &s);
double N1N2Hpm1W(const double &cos_t, const double &s);
double N1N2Hpm1Wfl(const double &cos_t, const double &s);
double N1N2Hpm2W(const double &cos_t, const double &s);
double N1N2Hpm2Wfl(const double &cos_t, const double &s);
double N1N2ZZ(const double &cos_t, const double &s);
double N1N2ZZfl(const double &cos_t, const double &s);
double N1N2WW(const double &cos_t, const double &s);
double N1N2WWfl(const double &cos_t, const double &s);
double N1N2v1v1(const double &cos_t, const double &s);
double N1N2v1v1fl(const double &cos_t, const double &s);
double N1N2v2v2(const double &cos_t, const double &s);
double N1N2v2v2fl(const double &cos_t, const double &s);
double N1N2v3v3(const double &cos_t, const double &s);
double N1N2v3v3fl(const double &cos_t, const double &s);
double N1N2e1e1(const double &cos_t, const double &s);
double N1N2e1e1fl(const double &cos_t, const double &s);
double N1N2e2e2(const double &cos_t, const double &s);
double N1N2e2e2fl(const double &cos_t, const double &s);
double N1N2e3e3(const double &cos_t, const double &s);
double N1N2e3e3fl(const double &cos_t, const double &s);
double N1N2u1u1(const double &cos_t, const double &s);
double N1N2u1u1fl(const double &cos_t, const double &s);
double N1N2u2u2(const double &cos_t, const double &s);
double N1N2u2u2fl(const double &cos_t, const double &s);
double N1N2u3u3(const double &cos_t, const double &s);
double N1N2u3u3fl(const double &cos_t, const double &s);
double N1N2d1d1(const double &cos_t, const double &s);
double N1N2d1d1fl(const double &cos_t, const double &s);
double N1N2d2d2(const double &cos_t, const double &s);
double N1N2d2d2fl(const double &cos_t, const double &s);
double N1N2d3d3(const double &cos_t, const double &s);
double N1N2d3d3fl(const double &cos_t, const double &s);


}  // namespace DT
