(* Patched for use with FeynCalc *)
(* * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * *)
(*                                                                             *)
(*         This file has been automatically generated by FeynRules.            *)
(*                                                                             *)
(* * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * *)


FR$ModelInformation={
  ModelName->"MLDM_real",
  Authors -> {"Adil Jueid"},
  Version -> "1.0",
  Date -> "14-11-2022",
  Institutions -> {"Center for Theoretical Physics of the Universe"},
  Emails -> {"adiljueid@ibs.re.kr"},
  URLs -> {"Ongoing"}};

FR$ClassesTranslation={ve -> F[1], vm -> F[2], vt -> F[3], e -> F[4], m -> F[5], ta -> F[6], u -> F[7], c -> F[8], t -> F[9], d -> F[10], s -> F[11], b -> F[12], A -> V[1], Z -> V[2], W -> V[3], G -> V[4], ghA -> U[1], ghZ -> U[2], ghWp -> U[3], ghWm -> U[4], ghG -> U[5], N1 -> F[13], h -> S[1], phich -> S[2]};

FR$InteractionOrderPerturbativeExpansion={{NP, 0}, {QCD, 0}, {QED, 0}};

FR$GoldstoneList={};

(*     Declared indices    *)

IndexRange[ Index[Generation] ] = Range[ 3 ]

IndexRange[ Index[Colour] ] = NoUnfold[ Range[ 3 ] ]

IndexRange[ Index[Gluon] ] = NoUnfold[ Range[ 8 ] ]

IndexRange[ Index[SU2W] ] = Range[ 3 ]

(*     Declared particles    *)

M$ClassesDescription = {
F[1] == {
    SelfConjugate -> False,
    PropagatorType -> Straight,
    PropagatorArrow -> Forward,
    Mass -> Mnue,
    Indices -> {},
    PropagatorLabel -> "ve" },

F[2] == {
    SelfConjugate -> False,
    PropagatorType -> Straight,
    PropagatorArrow -> Forward,
    Mass -> Mnum,
    Indices -> {},
    PropagatorLabel -> "vm" },

F[3] == {
    SelfConjugate -> False,
    PropagatorType -> Straight,
    PropagatorArrow -> Forward,
    Mass -> Mnut,
    Indices -> {},
    PropagatorLabel -> "vt" },

F[4] == {
    SelfConjugate -> False,
    QuantumNumbers -> {-Q},
    PropagatorType -> Straight,
    PropagatorArrow -> Forward,
    Mass -> Me,
    Indices -> {},
    PropagatorLabel -> "e" },

F[5] == {
    SelfConjugate -> False,
    QuantumNumbers -> {-Q},
    PropagatorType -> Straight,
    PropagatorArrow -> Forward,
    Mass -> FCGV["MM"],
    Indices -> {},
    PropagatorLabel -> "m" },

F[6] == {
    SelfConjugate -> False,
    QuantumNumbers -> {-Q},
    PropagatorType -> Straight,
    PropagatorArrow -> Forward,
    Mass -> MTA,
    Indices -> {},
    PropagatorLabel -> "ta" },

F[7] == {
    SelfConjugate -> False,
    QuantumNumbers -> {(2*Q)/3},
    PropagatorType -> Straight,
    PropagatorArrow -> Forward,
    Mass -> FCGV["MU"],
    Indices -> {Index[Colour]},
    PropagatorLabel -> "u" },

F[8] == {
    SelfConjugate -> False,
    QuantumNumbers -> {(2*Q)/3},
    PropagatorType -> Straight,
    PropagatorArrow -> Forward,
    Mass -> FCGV["MC"],
    Indices -> {Index[Colour]},
    PropagatorLabel -> "c" },

F[9] == {
    SelfConjugate -> False,
    QuantumNumbers -> {(2*Q)/3},
    PropagatorType -> Straight,
    PropagatorArrow -> Forward,
    Mass -> FCGV["MT"],
    Indices -> {Index[Colour]},
    PropagatorLabel -> "t" },

F[10] == {
    SelfConjugate -> False,
    QuantumNumbers -> {-1/3*Q},
    PropagatorType -> Straight,
    PropagatorArrow -> Forward,
    Mass -> FCGV["MD"],
    Indices -> {Index[Colour]},
    PropagatorLabel -> "d" },

F[11] == {
    SelfConjugate -> False,
    QuantumNumbers -> {-1/3*Q},
    PropagatorType -> Straight,
    PropagatorArrow -> Forward,
    Mass -> FCGV["MS"],
    Indices -> {Index[Colour]},
    PropagatorLabel -> "s" },

F[12] == {
    SelfConjugate -> False,
    QuantumNumbers -> {-1/3*Q},
    PropagatorType -> Straight,
    PropagatorArrow -> Forward,
    Mass -> FCGV["MB"],
    Indices -> {Index[Colour]},
    PropagatorLabel -> "b" },

V[1] == {
    SelfConjugate -> True,
    PropagatorType -> Sine,
    PropagatorArrow -> None,
    Mass -> 0,
    Indices -> {},
    PropagatorLabel -> "A" },

V[2] == {
    SelfConjugate -> True,
    PropagatorType -> Sine,
    PropagatorArrow -> None,
    Mass -> FCGV["MZ"],
    Indices -> {},
    PropagatorLabel -> "Z" },

V[3] == {
    SelfConjugate -> False,
    QuantumNumbers -> {Q},
    PropagatorType -> Sine,
    PropagatorArrow -> Forward,
    Mass -> FCGV["MW"],
    Indices -> {},
    PropagatorLabel -> "W" },

V[4] == {
    SelfConjugate -> True,
    PropagatorType -> Cycles,
    PropagatorArrow -> None,
    Mass -> 0,
    Indices -> {Index[Gluon]},
    PropagatorLabel -> "G" },

U[1] == {
    SelfConjugate -> False,
    QuantumNumbers -> {GhostNumber},
    PropagatorType -> GhostDash,
    PropagatorArrow -> Forward,
    Mass -> 0,
    Indices -> {},
    PropagatorLabel -> "ghA" },

U[2] == {
    SelfConjugate -> False,
    QuantumNumbers -> {GhostNumber},
    PropagatorType -> GhostDash,
    PropagatorArrow -> Forward,
    Mass -> FCGV["MZ"],
    Indices -> {},
    PropagatorLabel -> "ghZ" },

U[3] == {
    SelfConjugate -> False,
    QuantumNumbers -> {Q, GhostNumber},
    PropagatorType -> GhostDash,
    PropagatorArrow -> Forward,
    Mass -> FCGV["MW"],
    Indices -> {},
    PropagatorLabel -> "ghWp" },

U[4] == {
    SelfConjugate -> False,
    QuantumNumbers -> {-Q, GhostNumber},
    PropagatorType -> GhostDash,
    PropagatorArrow -> Forward,
    Mass -> FCGV["MW"],
    Indices -> {},
    PropagatorLabel -> "ghWm" },

U[5] == {
    SelfConjugate -> False,
    QuantumNumbers -> {GhostNumber},
    PropagatorType -> GhostDash,
    PropagatorArrow -> Forward,
    Mass -> 0,
    Indices -> {Index[Gluon]},
    PropagatorLabel -> "ghG" },

F[13] == {
    SelfConjugate -> True,
    PropagatorType -> Straight,
    PropagatorArrow -> None,
    Mass -> mN1,
    Indices -> {},
    PropagatorLabel -> "N1" },

S[1] == {
    SelfConjugate -> True,
    PropagatorType -> ScalarDash,
    PropagatorArrow -> None,
    Mass -> mH,
    Indices -> {},
    PropagatorLabel -> "h" },

S[2] == {
    SelfConjugate -> False,
    QuantumNumbers -> {Q},
    PropagatorType -> ScalarDash,
    PropagatorArrow -> Forward,
    Mass -> mphich,
    Indices -> {},
    PropagatorLabel -> "phich" }
}


(*        Definitions       *)

FAGaugeXi[ F[13] ] = FAGaugeXi[F[10]];
FAGaugeXi[ S[2] ] = FAGaugeXi[S[4]];

Mnue[ ___ ] := Mnue;
Mnum[ ___ ] := Mnum;
Mnut[ ___ ] := Mnut;
Me[ ___ ] := Me;
FCGV["MM"][ ___ ] := FCGV["MM"];
MTA[ ___ ] := MTA;
FCGV["MU"][ ___ ] := FCGV["MU"];
FCGV["MC"][ ___ ] := FCGV["MC"];
FCGV["MT"][ ___ ] := FCGV["MT"];
FCGV["MD"][ ___ ] := FCGV["MD"];
FCGV["MS"][ ___ ] := FCGV["MS"];
FCGV["MB"][ ___ ] := FCGV["MB"];
FCGV["MZ"][ ___ ] := FCGV["MZ"];
FCGV["MW"][ ___ ] := FCGV["MW"];
mN1[ ___ ] := mN1;
mH[ ___ ] := mH;
mphich[ ___ ] := mphich;


TheLabel[ F[7, {__}] ] := TheLabel[F[7]];
TheLabel[ F[8, {__}] ] := TheLabel[F[8]];
TheLabel[ F[9, {__}] ] := TheLabel[F[9]];
TheLabel[ F[10, {__}] ] := TheLabel[F[10]];
TheLabel[ F[11, {__}] ] := TheLabel[F[11]];
TheLabel[ F[12, {__}] ] := TheLabel[F[12]];
TheLabel[ V[4, {__}] ] := TheLabel[V[4]];
TheLabel[ U[5, {__}] ] := TheLabel[U[5]];


(*      Couplings (calculated by FeynRules)      *)

M$CouplingMatrices = {

C[ S[1] , S[1] , S[1] , S[1] ] == {{(-6*I)*lH, 0}},

C[ S[1] , S[1] , S[2] , -S[2] ] == {{(-I)*lam3, 0}},

C[ S[2] , S[2] , -S[2] , -S[2] ] == {{(-4*I)*lPhi, 0}},

C[ S[1] , S[1] , S[1] ] == {{(-6*I)*lH*v, 0}},

C[ S[1] , S[2] , -S[2] ] == {{(-I)*lam3*v, 0}},

C[ S[2] , -S[2] , V[1] , V[1] ] == {{(2*I)*FCGV["EL"]^2, 0}},

C[ S[2] , -S[2] , V[1] ] == {{(-I)*gc7, 0}, {I*gc7, 0}},

C[ -F[4] , F[13] , -S[2] ] == {{I*gc8, 0}, {I*gc8, 0}},

C[ -F[5] , F[13] , -S[2] ] == {{I*gc9, 0}, {I*gc9, 0}},

C[ F[13] , F[4] , S[2] ] == {{I*gc10, 0}, {I*gc10, 0}},

C[ F[13] , F[5] , S[2] ] == {{I*gc11, 0}, {I*gc11, 0}},

C[ F[13] , F[6] , S[2] ] == {{I*gc12, 0}, {I*gc12, 0}},

C[ -F[6] , F[13] , -S[2] ] == {{I*gc13, 0}, {I*gc13, 0}},

C[ -U[5, {e1x1}] , U[5, {e2x1}] , V[4, {e3x2}] ] == {{gc14*FASUNF[e3x2, e1x1, e2x1], 0}, {gc14*FASUNF[e3x2, e1x1, e2x1], 0}, {0, 0}},

C[ V[4, {e1x2}] , V[4, {e2x2}] , V[4, {e3x2}] ] == {{-(gc15*FASUNF[e1x2, e2x2, e3x2]), 0}, {gc15*FASUNF[e1x2, e2x2, e3x2], 0}, {gc15*FASUNF[e1x2, e2x2, e3x2], 0}, {-(gc15*FASUNF[e1x2, e2x2, e3x2]), 0}, {-(gc15*FASUNF[e1x2, e2x2, e3x2]), 0}, {gc15*FASUNF[e1x2, e2x2, e3x2], 0}},

C[ V[4, {e1x2}] , V[4, {e2x2}] , V[4, {e3x2}] , V[4, {e4x2}] ] == {{(-I)*gc16*(FASUNF[e1x2, e2x2, e3x2, e4x2] + FASUNF[e1x2, e3x2, e2x2, e4x2]), 0}, {I*gc16*(FASUNF[e1x2, e2x2, e3x2, e4x2] - FASUNF[e1x2, e4x2, e2x2, e3x2]), 0}, {I*gc16*(FASUNF[e1x2, e3x2, e2x2, e4x2] + FASUNF[e1x2, e4x2, e2x2, e3x2]), 0}},

C[ -F[12, {e1x2}] , F[12, {e2x2}] , S[1] ] == {{I*gc17*IndexDelta[e1x2, e2x2], 0}, {I*gc17*IndexDelta[e1x2, e2x2], 0}},

C[ -F[10, {e1x2}] , F[10, {e2x2}] , S[1] ] == {{I*gc18*IndexDelta[e1x2, e2x2], 0}, {I*gc18*IndexDelta[e1x2, e2x2], 0}},

C[ -F[11, {e1x2}] , F[11, {e2x2}] , S[1] ] == {{I*gc19*IndexDelta[e1x2, e2x2], 0}, {I*gc19*IndexDelta[e1x2, e2x2], 0}},

C[ -F[4] , F[4] , S[1] ] == {{I*gc20, 0}, {I*gc20, 0}},

C[ -F[5] , F[5] , S[1] ] == {{I*gc21, 0}, {I*gc21, 0}},

C[ -F[6] , F[6] , S[1] ] == {{I*gc22, 0}, {I*gc22, 0}},

C[ -F[8, {e1x2}] , F[8, {e2x2}] , S[1] ] == {{I*gc23*IndexDelta[e1x2, e2x2], 0}, {I*gc23*IndexDelta[e1x2, e2x2], 0}},

C[ -F[9, {e1x2}] , F[9, {e2x2}] , S[1] ] == {{I*gc24*IndexDelta[e1x2, e2x2], 0}, {I*gc24*IndexDelta[e1x2, e2x2], 0}},

C[ -F[7, {e1x2}] , F[7, {e2x2}] , S[1] ] == {{I*gc25*IndexDelta[e1x2, e2x2], 0}, {I*gc25*IndexDelta[e1x2, e2x2], 0}},

C[ -F[12, {e1x2}] , F[12, {e2x2}] , V[4, {e3x2}] ] == {{I*gc26*FASUNT[e3x2, e1x2, e2x2], 0}, {I*gc26*FASUNT[e3x2, e1x2, e2x2], 0}},

C[ -F[10, {e1x2}] , F[10, {e2x2}] , V[4, {e3x2}] ] == {{I*gc27*FASUNT[e3x2, e1x2, e2x2], 0}, {I*gc27*FASUNT[e3x2, e1x2, e2x2], 0}},

C[ -F[11, {e1x2}] , F[11, {e2x2}] , V[4, {e3x2}] ] == {{I*gc28*FASUNT[e3x2, e1x2, e2x2], 0}, {I*gc28*FASUNT[e3x2, e1x2, e2x2], 0}},

C[ -F[8, {e1x2}] , F[8, {e2x2}] , V[4, {e3x2}] ] == {{I*gc29*FASUNT[e3x2, e1x2, e2x2], 0}, {I*gc29*FASUNT[e3x2, e1x2, e2x2], 0}},

C[ -F[9, {e1x2}] , F[9, {e2x2}] , V[4, {e3x2}] ] == {{I*gc30*FASUNT[e3x2, e1x2, e2x2], 0}, {I*gc30*FASUNT[e3x2, e1x2, e2x2], 0}},

C[ -F[7, {e1x2}] , F[7, {e2x2}] , V[4, {e3x2}] ] == {{I*gc31*FASUNT[e3x2, e1x2, e2x2], 0}, {I*gc31*FASUNT[e3x2, e1x2, e2x2], 0}},

C[ V[1] , V[3] , -V[3] ] == {{(-I)*gc32, 0}, {I*gc32, 0}, {I*gc32, 0}, {(-I)*gc32, 0}, {(-I)*gc32, 0}, {I*gc32, 0}},

C[ S[1] , S[1] , V[3] , -V[3] ] == {{((I/2)*FCGV["EL"]^2)/FCGV["SW"]^2, 0}},

C[ S[1] , V[3] , -V[3] ] == {{((I/2)*FCGV["EL"]^2*v)/FCGV["SW"]^2, 0}},

C[ V[1] , V[1] , V[3] , -V[3] ] == {{(-I)*gc35, 0}, {(-I)*gc35, 0}, {(2*I)*gc35, 0}},

C[ V[3] , -V[3] , V[2] ] == {{(-I)*gc36, 0}, {I*gc36, 0}, {I*gc36, 0}, {(-I)*gc36, 0}, {(-I)*gc36, 0}, {I*gc36, 0}},

C[ V[3] , V[3] , -V[3] , -V[3] ] == {{(-I)*gc37, 0}, {(-I)*gc37, 0}, {(2*I)*gc37, 0}},

C[ S[2] , -S[2] , V[1] , V[2] ] == {{((-2*I)*FCGV["EL"]^2*FCGV["SW"])/FCGV["CW"], 0}},

C[ S[2] , -S[2] , V[2] ] == {{(-I)*gc39, 0}, {I*gc39, 0}},

C[ V[1] , V[3] , -V[3] , V[2] ] == {{(-2*I)*gc40, 0}, {I*gc40, 0}, {I*gc40, 0}},

C[ S[1] , S[1] , V[2] , V[2] ] == {{((I/2)*FCGV["EL"]^2*(FCGV["CW"]^2 + FCGV["SW"]^2)^2)/(FCGV["CW"]^2*FCGV["SW"]^2), 0}},

C[ S[2] , -S[2] , V[2] , V[2] ] == {{((2*I)*FCGV["EL"]^2*FCGV["SW"]^2)/FCGV["CW"]^2, 0}},

C[ S[1] , V[2] , V[2] ] == {{((I/2)*FCGV["EL"]^2*(FCGV["CW"]^2 + FCGV["SW"]^2)^2*v)/(FCGV["CW"]^2*FCGV["SW"]^2), 0}},

C[ V[3] , -V[3] , V[2] , V[2] ] == {{(-I)*gc44, 0}, {(-I)*gc44, 0}, {(2*I)*gc44, 0}},

C[ -F[12, {e1x2}] , F[12, {e2x2}] , V[1] ] == {{I*gc45*IndexDelta[e1x2, e2x2], 0}, {I*gc45*IndexDelta[e1x2, e2x2], 0}},

C[ -F[10, {e1x2}] , F[10, {e2x2}] , V[1] ] == {{I*gc46*IndexDelta[e1x2, e2x2], 0}, {I*gc46*IndexDelta[e1x2, e2x2], 0}},

C[ -F[11, {e1x2}] , F[11, {e2x2}] , V[1] ] == {{I*gc47*IndexDelta[e1x2, e2x2], 0}, {I*gc47*IndexDelta[e1x2, e2x2], 0}},

C[ -F[4] , F[4] , V[1] ] == {{I*gc48, 0}, {I*gc48, 0}},

C[ -F[5] , F[5] , V[1] ] == {{I*gc49, 0}, {I*gc49, 0}},

C[ -F[6] , F[6] , V[1] ] == {{I*gc50, 0}, {I*gc50, 0}},

C[ -F[8, {e1x2}] , F[8, {e2x2}] , V[1] ] == {{I*gc51*IndexDelta[e1x2, e2x2], 0}, {I*gc51*IndexDelta[e1x2, e2x2], 0}},

C[ -F[9, {e1x2}] , F[9, {e2x2}] , V[1] ] == {{I*gc52*IndexDelta[e1x2, e2x2], 0}, {I*gc52*IndexDelta[e1x2, e2x2], 0}},

C[ -F[7, {e1x2}] , F[7, {e2x2}] , V[1] ] == {{I*gc53*IndexDelta[e1x2, e2x2], 0}, {I*gc53*IndexDelta[e1x2, e2x2], 0}},

C[ -F[1] , F[4] , V[3] ] == {{I*gc54, 0}, {0, 0}},

C[ -F[2] , F[5] , V[3] ] == {{I*gc55, 0}, {0, 0}},

C[ -F[3] , F[6] , V[3] ] == {{I*gc56, 0}, {0, 0}},

C[ -F[8, {e1x2}] , F[12, {e2x2}] , V[3] ] == {{I*gc57*IndexDelta[e1x2, e2x2], 0}, {0, 0}},

C[ -F[8, {e1x2}] , F[10, {e2x2}] , V[3] ] == {{I*gc58*IndexDelta[e1x2, e2x2], 0}, {0, 0}},

C[ -F[8, {e1x2}] , F[11, {e2x2}] , V[3] ] == {{I*gc59*IndexDelta[e1x2, e2x2], 0}, {0, 0}},

C[ -F[9, {e1x2}] , F[12, {e2x2}] , V[3] ] == {{I*gc60*IndexDelta[e1x2, e2x2], 0}, {0, 0}},

C[ -F[9, {e1x2}] , F[10, {e2x2}] , V[3] ] == {{I*gc61*IndexDelta[e1x2, e2x2], 0}, {0, 0}},

C[ -F[9, {e1x2}] , F[11, {e2x2}] , V[3] ] == {{I*gc62*IndexDelta[e1x2, e2x2], 0}, {0, 0}},

C[ -F[7, {e1x2}] , F[12, {e2x2}] , V[3] ] == {{I*gc63*IndexDelta[e1x2, e2x2], 0}, {0, 0}},

C[ -F[7, {e1x2}] , F[10, {e2x2}] , V[3] ] == {{I*gc64*IndexDelta[e1x2, e2x2], 0}, {0, 0}},

C[ -F[7, {e1x2}] , F[11, {e2x2}] , V[3] ] == {{I*gc65*IndexDelta[e1x2, e2x2], 0}, {0, 0}},

C[ -F[4] , F[1] , -V[3] ] == {{I*gc66, 0}, {0, 0}},

C[ -F[5] , F[2] , -V[3] ] == {{I*gc67, 0}, {0, 0}},

C[ -F[6] , F[3] , -V[3] ] == {{I*gc68, 0}, {0, 0}},

C[ -F[12, {e1x2}] , F[8, {e2x2}] , -V[3] ] == {{I*gc69*IndexDelta[e1x2, e2x2], 0}, {0, 0}},

C[ -F[12, {e1x2}] , F[9, {e2x2}] , -V[3] ] == {{I*gc70*IndexDelta[e1x2, e2x2], 0}, {0, 0}},

C[ -F[12, {e1x2}] , F[7, {e2x2}] , -V[3] ] == {{I*gc71*IndexDelta[e1x2, e2x2], 0}, {0, 0}},

C[ -F[10, {e1x2}] , F[8, {e2x2}] , -V[3] ] == {{I*gc72*IndexDelta[e1x2, e2x2], 0}, {0, 0}},

C[ -F[10, {e1x2}] , F[9, {e2x2}] , -V[3] ] == {{I*gc73*IndexDelta[e1x2, e2x2], 0}, {0, 0}},

C[ -F[10, {e1x2}] , F[7, {e2x2}] , -V[3] ] == {{I*gc74*IndexDelta[e1x2, e2x2], 0}, {0, 0}},

C[ -F[11, {e1x2}] , F[8, {e2x2}] , -V[3] ] == {{I*gc75*IndexDelta[e1x2, e2x2], 0}, {0, 0}},

C[ -F[11, {e1x2}] , F[9, {e2x2}] , -V[3] ] == {{I*gc76*IndexDelta[e1x2, e2x2], 0}, {0, 0}},

C[ -F[11, {e1x2}] , F[7, {e2x2}] , -V[3] ] == {{I*gc77*IndexDelta[e1x2, e2x2], 0}, {0, 0}},

C[ -F[12, {e1x2}] , F[12, {e2x2}] , V[2] ] == {{I*gc78L*IndexDelta[e1x2, e2x2], 0}, {I*gc78R*IndexDelta[e1x2, e2x2], 0}},

C[ -F[10, {e1x2}] , F[10, {e2x2}] , V[2] ] == {{I*gc79L*IndexDelta[e1x2, e2x2], 0}, {I*gc79R*IndexDelta[e1x2, e2x2], 0}},

C[ -F[11, {e1x2}] , F[11, {e2x2}] , V[2] ] == {{I*gc80L*IndexDelta[e1x2, e2x2], 0}, {I*gc80R*IndexDelta[e1x2, e2x2], 0}},

C[ -F[4] , F[4] , V[2] ] == {{I*gc81L, 0}, {I*gc81R, 0}},

C[ -F[5] , F[5] , V[2] ] == {{I*gc82L, 0}, {I*gc82R, 0}},

C[ -F[6] , F[6] , V[2] ] == {{I*gc83L, 0}, {I*gc83R, 0}},

C[ -F[8, {e1x2}] , F[8, {e2x2}] , V[2] ] == {{I*gc84L*IndexDelta[e1x2, e2x2], 0}, {I*gc84R*IndexDelta[e1x2, e2x2], 0}},

C[ -F[9, {e1x2}] , F[9, {e2x2}] , V[2] ] == {{I*gc85L*IndexDelta[e1x2, e2x2], 0}, {I*gc85R*IndexDelta[e1x2, e2x2], 0}},

C[ -F[7, {e1x2}] , F[7, {e2x2}] , V[2] ] == {{I*gc86L*IndexDelta[e1x2, e2x2], 0}, {I*gc86R*IndexDelta[e1x2, e2x2], 0}},

C[ -F[1] , F[1] , V[2] ] == {{I*gc87, 0}, {0, 0}},

C[ -F[2] , F[2] , V[2] ] == {{I*gc88, 0}, {0, 0}},

C[ -F[3] , F[3] , V[2] ] == {{I*gc89, 0}, {0, 0}}

}

(* * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * *)

(* Parameter replacement lists (These lists were created by FeynRules) *)

(* FA Couplings *)

M$FACouplings = {
     gc7 -> -FCGV["EL"],
     gc8 -> -y1e,
     gc9 -> -y1m,
     gc10 -> -y1e,
     gc11 -> -y1m,
     gc12 -> -y1t,
     gc13 -> -y1t,
     gc14 -> FAGS,
     gc15 -> -FAGS,
     gc16 -> -FAGS^2,
     gc17 -> -(FCGV["MB"]/v),
     gc18 -> -(FCGV["MD"]/v),
     gc19 -> -(FCGV["MS"]/v),
     gc20 -> -(Me/v),
     gc21 -> -(FCGV["MM"]/v),
     gc22 -> -(MTA/v),
     gc23 -> -(FCGV["MC"]/v),
     gc24 -> -(FCGV["MT"]/v),
     gc25 -> -(FCGV["MU"]/v),
     gc26 -> FAGS,
     gc27 -> FAGS,
     gc28 -> FAGS,
     gc29 -> FAGS,
     gc30 -> FAGS,
     gc31 -> FAGS,
     gc32 -> FCGV["EL"],
     gc35 -> -FCGV["EL"]^2,
     gc36 -> (FCGV["CW"]*FCGV["EL"])/FCGV["SW"],
     gc37 -> FCGV["EL"]^2/FCGV["SW"]^2,
     gc39 -> (FCGV["EL"]*FCGV["SW"])/FCGV["CW"],
     gc40 -> (FCGV["CW"]*FCGV["EL"]^2)/FCGV["SW"],
     gc44 -> -((FCGV["CW"]^2*FCGV["EL"]^2)/FCGV["SW"]^2),
     gc45 -> -1/3*FCGV["EL"],
     gc46 -> -1/3*FCGV["EL"],
     gc47 -> -1/3*FCGV["EL"],
     gc48 -> -FCGV["EL"],
     gc49 -> -FCGV["EL"],
     gc50 -> -FCGV["EL"],
     gc51 -> (2*FCGV["EL"])/3,
     gc52 -> (2*FCGV["EL"])/3,
     gc53 -> (2*FCGV["EL"])/3,
     gc54 -> FCGV["EL"]/(Sqrt[2]*FCGV["SW"]),
     gc55 -> FCGV["EL"]/(Sqrt[2]*FCGV["SW"]),
     gc56 -> FCGV["EL"]/(Sqrt[2]*FCGV["SW"]),
     gc57 -> (CKM2x3*FCGV["EL"])/(Sqrt[2]*FCGV["SW"]),
     gc58 -> (CKM2x1*FCGV["EL"])/(Sqrt[2]*FCGV["SW"]),
     gc59 -> (CKM2x2*FCGV["EL"])/(Sqrt[2]*FCGV["SW"]),
     gc60 -> (CKM3x3*FCGV["EL"])/(Sqrt[2]*FCGV["SW"]),
     gc61 -> (CKM3x1*FCGV["EL"])/(Sqrt[2]*FCGV["SW"]),
     gc62 -> (CKM3x2*FCGV["EL"])/(Sqrt[2]*FCGV["SW"]),
     gc63 -> (CKM1x3*FCGV["EL"])/(Sqrt[2]*FCGV["SW"]),
     gc64 -> (CKM1x1*FCGV["EL"])/(Sqrt[2]*FCGV["SW"]),
     gc65 -> (CKM1x2*FCGV["EL"])/(Sqrt[2]*FCGV["SW"]),
     gc66 -> FCGV["EL"]/(Sqrt[2]*FCGV["SW"]),
     gc67 -> FCGV["EL"]/(Sqrt[2]*FCGV["SW"]),
     gc68 -> FCGV["EL"]/(Sqrt[2]*FCGV["SW"]),
     gc69 -> (FCGV["EL"]*Conjugate[CKM2x3])/(Sqrt[2]*FCGV["SW"]),
     gc70 -> (FCGV["EL"]*Conjugate[CKM3x3])/(Sqrt[2]*FCGV["SW"]),
     gc71 -> (FCGV["EL"]*Conjugate[CKM1x3])/(Sqrt[2]*FCGV["SW"]),
     gc72 -> (FCGV["EL"]*Conjugate[CKM2x1])/(Sqrt[2]*FCGV["SW"]),
     gc73 -> (FCGV["EL"]*Conjugate[CKM3x1])/(Sqrt[2]*FCGV["SW"]),
     gc74 -> (FCGV["EL"]*Conjugate[CKM1x1])/(Sqrt[2]*FCGV["SW"]),
     gc75 -> (FCGV["EL"]*Conjugate[CKM2x2])/(Sqrt[2]*FCGV["SW"]),
     gc76 -> (FCGV["EL"]*Conjugate[CKM3x2])/(Sqrt[2]*FCGV["SW"]),
     gc77 -> (FCGV["EL"]*Conjugate[CKM1x2])/(Sqrt[2]*FCGV["SW"]),
     gc78L -> -1/6*(FCGV["EL"]*(3*FCGV["CW"]^2 + FCGV["SW"]^2))/(FCGV["CW"]*FCGV["SW"]),
     gc78R -> (FCGV["EL"]*FCGV["SW"])/(3*FCGV["CW"]),
     gc79L -> -1/6*(FCGV["EL"]*(3*FCGV["CW"]^2 + FCGV["SW"]^2))/(FCGV["CW"]*FCGV["SW"]),
     gc79R -> (FCGV["EL"]*FCGV["SW"])/(3*FCGV["CW"]),
     gc80L -> -1/6*(FCGV["EL"]*(3*FCGV["CW"]^2 + FCGV["SW"]^2))/(FCGV["CW"]*FCGV["SW"]),
     gc80R -> (FCGV["EL"]*FCGV["SW"])/(3*FCGV["CW"]),
     gc81L -> -1/2*(FCGV["EL"]*(FCGV["CW"]^2 - FCGV["SW"]^2))/(FCGV["CW"]*FCGV["SW"]),
     gc81R -> (FCGV["EL"]*FCGV["SW"])/FCGV["CW"],
     gc82L -> -1/2*(FCGV["EL"]*(FCGV["CW"]^2 - FCGV["SW"]^2))/(FCGV["CW"]*FCGV["SW"]),
     gc82R -> (FCGV["EL"]*FCGV["SW"])/FCGV["CW"],
     gc83L -> -1/2*(FCGV["EL"]*(FCGV["CW"]^2 - FCGV["SW"]^2))/(FCGV["CW"]*FCGV["SW"]),
     gc83R -> (FCGV["EL"]*FCGV["SW"])/FCGV["CW"],
     gc84L -> (FCGV["CW"]*FCGV["EL"])/(2*FCGV["SW"]) - (FCGV["EL"]*FCGV["SW"])/(6*FCGV["CW"]),
     gc84R -> (-2*FCGV["EL"]*FCGV["SW"])/(3*FCGV["CW"]),
     gc85L -> (FCGV["CW"]*FCGV["EL"])/(2*FCGV["SW"]) - (FCGV["EL"]*FCGV["SW"])/(6*FCGV["CW"]),
     gc85R -> (-2*FCGV["EL"]*FCGV["SW"])/(3*FCGV["CW"]),
     gc86L -> (FCGV["CW"]*FCGV["EL"])/(2*FCGV["SW"]) - (FCGV["EL"]*FCGV["SW"])/(6*FCGV["CW"]),
     gc86R -> (-2*FCGV["EL"]*FCGV["SW"])/(3*FCGV["CW"]),
     gc87 -> (FCGV["EL"]*(FCGV["CW"]^2 + FCGV["SW"]^2))/(2*FCGV["CW"]*FCGV["SW"]),
     gc88 -> (FCGV["EL"]*(FCGV["CW"]^2 + FCGV["SW"]^2))/(2*FCGV["CW"]*FCGV["SW"]),
     gc89 -> (FCGV["EL"]*(FCGV["CW"]^2 + FCGV["SW"]^2))/(2*FCGV["CW"]*FCGV["SW"])};

