///////////////////CODE GENERATED VIA MATHEMATICA///////////////////


#pragma once

#include <cmath>

namespace DT{
	extern double aEWM1;
	extern double Gf;
	extern double MMZ;
	extern double MMW;
	extern double MMC;
	extern double MMB;
	extern double MMT;
	extern double aS;
	extern double QS;
	extern double aDM;
	extern double mmH1;
	extern double mmH2;
	extern double mmH3;
	extern double mmA0;
	extern double mmHch;
	extern double m11;
	extern double lam1;
	extern double lam7;
	extern double GG;
	extern double Mnue;
	extern double Mnum;
	extern double Mnut;
	extern double Me;
	extern double MM;
	extern double MTA;
	extern double MU;
	extern double MD;
	extern double MS;
	extern double WT;
	extern double WZ;
	extern double WW;
	extern double WH1;
	extern double WH2;
	extern double WH3;
	extern double WA0;
	extern double WHch;
	extern double E;
	extern double Pi;
	extern double MZ;
	extern double MW;
	extern double MC;
	extern double MB;
	extern double MT;
	extern double EE;
	extern double CW2;
	extern double SW2;
	extern double CW;
	extern double SW;
	extern double g1;
	extern double g2;
	extern double v;
	extern double CKM1x1;
	extern double CKM1x2;
	extern double CKM1x3;
	extern double CKM2x1;
	extern double CKM2x2;
	extern double CKM2x3;
	extern double CKM3x1;
	extern double CKM3x2;
	extern double CKM3x3;
	extern double MH1;
	extern double MH2;
	extern double MH3;
	extern double MA0;
	extern double MHch;
	extern double lam2;
	extern double lam3;
	extern double lam4;
	extern double lam5;
	extern double lam6;
	extern double lam8;
	extern double m22;
	extern double ms;
	extern double GH;
	extern double vs;
	extern double token1;
	extern double token2;
	extern double token3;
	extern double token4;
	extern double token5;
	extern double token6;
	extern double token7;
	extern double token8;
	extern double token9;
	extern double token10;
	extern double token11;
	extern double token12;
	extern double token13;
	extern double token14;
	extern double token15;
	extern double token16;
	extern double token17;
	extern double token18;
	extern double token19;
	extern double token20;
	extern double token21;
	extern double token22;
	extern double token23;
	extern double token24;
	extern double token25;
	extern double token26;
	extern double token27;
	extern double token28;
	extern double token29;
	extern double token30;
	extern double token31;
	extern double token32;
	extern double token33;
	extern double token34;
	extern double token35;
	extern double token36;
	extern double token37;
	extern double token38;
	extern double token39;
	extern double token40;
	extern double token41;
	extern double token42;
	extern double token43;
	extern double token44;
	extern double token45;
	extern double token46;
	extern double token47;
	extern double token48;
	extern double token49;
	extern double token50;
	extern double token51;
	extern double token52;
	extern double token53;
	extern double token54;
	extern double token55;
	extern double token56;
	extern double token57;
	extern double token58;
	extern double token59;
	extern double token60;
	extern double token61;
	extern double token62;
	extern double token63;
	extern double token64;
	extern double token65;
	extern double token66;
	extern double token67;
	extern double token68;
	extern double token69;
	extern double token70;
	extern double token71;
	extern double token72;
	extern double token73;
	extern double token74;
	extern double token75;
	extern double token76;
	extern double token77;
	extern double token78;
	extern double token79;
	extern double token80;
	extern double token81;
	extern double token82;
	extern double token83;
	extern double token84;
	extern double token85;
	extern double token86;
	extern double token87;
	extern double token88;
	extern double token89;
	extern double token90;
	extern double token91;
	extern double token92;
	extern double token93;
	extern double token94;
	extern double token95;
	extern double token96;
	extern double token97;
	extern double token98;
	extern double token99;
	extern double EL;
	extern double ee;
	extern double gs;
	extern double G;
	extern double FAGS;

	double H3H3H1H1(const double &cos_t, const double &s);
	double H3H3H1H2(const double &cos_t, const double &s);
	double H3H3H2H2(const double &cos_t, const double &s);
	double H3H3ZZ(const double &cos_t, const double &s);
	double H3H3wW(const double &cos_t, const double &s);
	double H3H3Ee(const double &cos_t, const double &s);
	double H3H3Mm(const double &cos_t, const double &s);
	double H3H3TAta(const double &cos_t, const double &s);
	double H3H3Uu(const double &cos_t, const double &s);
	double H3H3Cc(const double &cos_t, const double &s);
	double H3H3Tt(const double &cos_t, const double &s);
	double H3H3Dd(const double &cos_t, const double &s);
	double H3H3Ss(const double &cos_t, const double &s);
	double H3H3Bb(const double &cos_t, const double &s);
	double H3A0H1Z(const double &cos_t, const double &s);
	double H3A0H2Z(const double &cos_t, const double &s);
	double H3A0wW(const double &cos_t, const double &s);
	double H3A0VEve(const double &cos_t, const double &s);
	double H3A0VMvm(const double &cos_t, const double &s);
	double H3A0VTvt(const double &cos_t, const double &s);
	double H3A0Ee(const double &cos_t, const double &s);
	double H3A0Mm(const double &cos_t, const double &s);
	double H3A0TAta(const double &cos_t, const double &s);
	double H3A0Uu(const double &cos_t, const double &s);
	double H3A0Cc(const double &cos_t, const double &s);
	double H3A0Tt(const double &cos_t, const double &s);
	double H3A0Dd(const double &cos_t, const double &s);
	double H3A0Ss(const double &cos_t, const double &s);
	double H3A0Bb(const double &cos_t, const double &s);
	double H3HchH1W(const double &cos_t, const double &s);
	double H3HchH2W(const double &cos_t, const double &s);
	double H3HchAW(const double &cos_t, const double &s);
	double H3HchZW(const double &cos_t, const double &s);
	double H3HchveE(const double &cos_t, const double &s);
	double H3HchvmM(const double &cos_t, const double &s);
	double H3HchvtTA(const double &cos_t, const double &s);
	double H3HchuD(const double &cos_t, const double &s);
	double H3HchuS(const double &cos_t, const double &s);
	double H3HchuB(const double &cos_t, const double &s);
	double H3HchcD(const double &cos_t, const double &s);
	double H3HchcS(const double &cos_t, const double &s);
	double H3HchcB(const double &cos_t, const double &s);
	double H3HchtD(const double &cos_t, const double &s);
	double H3HchtS(const double &cos_t, const double &s);
	double H3HchtB(const double &cos_t, const double &s);
	double A0A0H1H1(const double &cos_t, const double &s);
	double A0A0H1H2(const double &cos_t, const double &s);
	double A0A0H2H2(const double &cos_t, const double &s);
	double A0A0ZZ(const double &cos_t, const double &s);
	double A0A0wW(const double &cos_t, const double &s);
	double A0A0Ee(const double &cos_t, const double &s);
	double A0A0Mm(const double &cos_t, const double &s);
	double A0A0TAta(const double &cos_t, const double &s);
	double A0A0Uu(const double &cos_t, const double &s);
	double A0A0Cc(const double &cos_t, const double &s);
	double A0A0Tt(const double &cos_t, const double &s);
	double A0A0Dd(const double &cos_t, const double &s);
	double A0A0Ss(const double &cos_t, const double &s);
	double A0A0Bb(const double &cos_t, const double &s);
	double A0HchH1W(const double &cos_t, const double &s);
	double A0HchH2W(const double &cos_t, const double &s);
	double A0HchAW(const double &cos_t, const double &s);
	double A0HchZW(const double &cos_t, const double &s);
	double A0HchveE(const double &cos_t, const double &s);
	double A0HchvmM(const double &cos_t, const double &s);
	double A0HchvtTA(const double &cos_t, const double &s);
	double A0HchuD(const double &cos_t, const double &s);
	double A0HchuS(const double &cos_t, const double &s);
	double A0HchuB(const double &cos_t, const double &s);
	double A0HchcD(const double &cos_t, const double &s);
	double A0HchcS(const double &cos_t, const double &s);
	double A0HchcB(const double &cos_t, const double &s);
	double A0HchtD(const double &cos_t, const double &s);
	double A0HchtS(const double &cos_t, const double &s);
	double A0HchtB(const double &cos_t, const double &s);
	double HchHchWW(const double &cos_t, const double &s);
	double HchHCHH1H1(const double &cos_t, const double &s);
	double HchHCHH1H2(const double &cos_t, const double &s);
	double HchHCHH2H2(const double &cos_t, const double &s);
	double HchHCHH1A(const double &cos_t, const double &s);
	double HchHCHH1Z(const double &cos_t, const double &s);
	double HchHCHH2A(const double &cos_t, const double &s);
	double HchHCHH2Z(const double &cos_t, const double &s);
	double HchHCHAA(const double &cos_t, const double &s);
	double HchHCHAZ(const double &cos_t, const double &s);
	double HchHCHZZ(const double &cos_t, const double &s);
	double HchHCHwW(const double &cos_t, const double &s);
	double HchHCHVEve(const double &cos_t, const double &s);
	double HchHCHVMvm(const double &cos_t, const double &s);
	double HchHCHVTvt(const double &cos_t, const double &s);
	double HchHCHEe(const double &cos_t, const double &s);
	double HchHCHMm(const double &cos_t, const double &s);
	double HchHCHTAta(const double &cos_t, const double &s);
	double HchHCHUu(const double &cos_t, const double &s);
	double HchHCHCc(const double &cos_t, const double &s);
	double HchHCHTt(const double &cos_t, const double &s);
	double HchHCHDd(const double &cos_t, const double &s);
	double HchHCHSs(const double &cos_t, const double &s);
	double HchHCHBb(const double &cos_t, const double &s);
	double H3H3H1H1fl(const double &cos_t, const double &s);
	double H3H3H1H2fl(const double &cos_t, const double &s);
	double H3H3H2H2fl(const double &cos_t, const double &s);
	double H3H3ZZfl(const double &cos_t, const double &s);
	double H3H3wWfl(const double &cos_t, const double &s);
	double H3H3Eefl(const double &cos_t, const double &s);
	double H3H3Mmfl(const double &cos_t, const double &s);
	double H3H3TAtafl(const double &cos_t, const double &s);
	double H3H3Uufl(const double &cos_t, const double &s);
	double H3H3Ccfl(const double &cos_t, const double &s);
	double H3H3Ttfl(const double &cos_t, const double &s);
	double H3H3Ddfl(const double &cos_t, const double &s);
	double H3H3Ssfl(const double &cos_t, const double &s);
	double H3H3Bbfl(const double &cos_t, const double &s);
	double H3A0H1Zfl(const double &cos_t, const double &s);
	double H3A0H2Zfl(const double &cos_t, const double &s);
	double H3A0wWfl(const double &cos_t, const double &s);
	double H3A0VEvefl(const double &cos_t, const double &s);
	double H3A0VMvmfl(const double &cos_t, const double &s);
	double H3A0VTvtfl(const double &cos_t, const double &s);
	double H3A0Eefl(const double &cos_t, const double &s);
	double H3A0Mmfl(const double &cos_t, const double &s);
	double H3A0TAtafl(const double &cos_t, const double &s);
	double H3A0Uufl(const double &cos_t, const double &s);
	double H3A0Ccfl(const double &cos_t, const double &s);
	double H3A0Ttfl(const double &cos_t, const double &s);
	double H3A0Ddfl(const double &cos_t, const double &s);
	double H3A0Ssfl(const double &cos_t, const double &s);
	double H3A0Bbfl(const double &cos_t, const double &s);
	double H3HchH1Wfl(const double &cos_t, const double &s);
	double H3HchH2Wfl(const double &cos_t, const double &s);
	double H3HchAWfl(const double &cos_t, const double &s);
	double H3HchZWfl(const double &cos_t, const double &s);
	double H3HchveEfl(const double &cos_t, const double &s);
	double H3HchvmMfl(const double &cos_t, const double &s);
	double H3HchvtTAfl(const double &cos_t, const double &s);
	double H3HchuDfl(const double &cos_t, const double &s);
	double H3HchuSfl(const double &cos_t, const double &s);
	double H3HchuBfl(const double &cos_t, const double &s);
	double H3HchcDfl(const double &cos_t, const double &s);
	double H3HchcSfl(const double &cos_t, const double &s);
	double H3HchcBfl(const double &cos_t, const double &s);
	double H3HchtDfl(const double &cos_t, const double &s);
	double H3HchtSfl(const double &cos_t, const double &s);
	double H3HchtBfl(const double &cos_t, const double &s);
	double A0A0H1H1fl(const double &cos_t, const double &s);
	double A0A0H1H2fl(const double &cos_t, const double &s);
	double A0A0H2H2fl(const double &cos_t, const double &s);
	double A0A0ZZfl(const double &cos_t, const double &s);
	double A0A0wWfl(const double &cos_t, const double &s);
	double A0A0Eefl(const double &cos_t, const double &s);
	double A0A0Mmfl(const double &cos_t, const double &s);
	double A0A0TAtafl(const double &cos_t, const double &s);
	double A0A0Uufl(const double &cos_t, const double &s);
	double A0A0Ccfl(const double &cos_t, const double &s);
	double A0A0Ttfl(const double &cos_t, const double &s);
	double A0A0Ddfl(const double &cos_t, const double &s);
	double A0A0Ssfl(const double &cos_t, const double &s);
	double A0A0Bbfl(const double &cos_t, const double &s);
	double A0HchH1Wfl(const double &cos_t, const double &s);
	double A0HchH2Wfl(const double &cos_t, const double &s);
	double A0HchAWfl(const double &cos_t, const double &s);
	double A0HchZWfl(const double &cos_t, const double &s);
	double A0HchveEfl(const double &cos_t, const double &s);
	double A0HchvmMfl(const double &cos_t, const double &s);
	double A0HchvtTAfl(const double &cos_t, const double &s);
	double A0HchuDfl(const double &cos_t, const double &s);
	double A0HchuSfl(const double &cos_t, const double &s);
	double A0HchuBfl(const double &cos_t, const double &s);
	double A0HchcDfl(const double &cos_t, const double &s);
	double A0HchcSfl(const double &cos_t, const double &s);
	double A0HchcBfl(const double &cos_t, const double &s);
	double A0HchtDfl(const double &cos_t, const double &s);
	double A0HchtSfl(const double &cos_t, const double &s);
	double A0HchtBfl(const double &cos_t, const double &s);
	double HchHchWWfl(const double &cos_t, const double &s);
	double HchHCHH1H1fl(const double &cos_t, const double &s);
	double HchHCHH1H2fl(const double &cos_t, const double &s);
	double HchHCHH2H2fl(const double &cos_t, const double &s);
	double HchHCHH1Afl(const double &cos_t, const double &s);
	double HchHCHH1Zfl(const double &cos_t, const double &s);
	double HchHCHH2Afl(const double &cos_t, const double &s);
	double HchHCHH2Zfl(const double &cos_t, const double &s);
	double HchHCHAAfl(const double &cos_t, const double &s);
	double HchHCHAZfl(const double &cos_t, const double &s);
	double HchHCHZZfl(const double &cos_t, const double &s);
	double HchHCHwWfl(const double &cos_t, const double &s);
	double HchHCHVEvefl(const double &cos_t, const double &s);
	double HchHCHVMvmfl(const double &cos_t, const double &s);
	double HchHCHVTvtfl(const double &cos_t, const double &s);
	double HchHCHEefl(const double &cos_t, const double &s);
	double HchHCHMmfl(const double &cos_t, const double &s);
	double HchHCHTAtafl(const double &cos_t, const double &s);
	double HchHCHUufl(const double &cos_t, const double &s);
	double HchHCHCcfl(const double &cos_t, const double &s);
	double HchHCHTtfl(const double &cos_t, const double &s);
	double HchHCHDdfl(const double &cos_t, const double &s);
	double HchHCHSsfl(const double &cos_t, const double &s);
	double HchHCHBbfl(const double &cos_t, const double &s);
	double H3H3(const double &cos_t, const double &s);
	double H3A0(const double &cos_t, const double &s);
	double H3Hch(const double &cos_t, const double &s);
	double A0A0(const double &cos_t, const double &s);
	double A0Hch(const double &cos_t, const double &s);
	double HchHch(const double &cos_t, const double &s);
	double wH1H1H1();
	double wH1H1H2();
	double wH1H2H2();
	double wH1H3H3();
	double wH1A0A0();
	double wH1HCHHch();
	double wH1ZZ();
	double wH1wW();
	double wH1Ee();
	double wH1Mm();
	double wH1TAta();
	double wH1Uu();
	double wH1Cc();
	double wH1Tt();
	double wH1Dd();
	double wH1Ss();
	double wH1Bb();
	double wH2H1H1();
	double wH2H1H2();
	double wH2H2H2();
	double wH2H3H3();
	double wH2A0A0();
	double wH2HCHHch();
	double wH2ZZ();
	double wH2wW();
	double wH2Ee();
	double wH2Mm();
	double wH2TAta();
	double wH2Uu();
	double wH2Cc();
	double wH2Tt();
	double wH2Dd();
	double wH2Ss();
	double wH2Bb();
	double wwH1(const double QCDaS);
	double wwH2(const double QCDaS);
}
