(* Patched for use with FeynCalc *)
(* * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * *)
(*                                                                             *)
(*         This file has been automatically generated by FeynRules.            *)
(*                                                                             *)
(* * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * *)


FR$ModelInformation={
  ModelName->"TRSM",
  Authors -> {"R. Capucha"},
  Version -> "1.0",
  Date -> "16. 05. 2022",
  Institutions -> {"CFTC, FCUL"},
  Emails -> {"rodrigocapucha@hotmail.com"}};

FR$ClassesTranslation={ve -> F[1], vm -> F[2], vt -> F[3], e -> F[4], mu -> F[5], ta -> F[6], u -> F[7], c -> F[8], t -> F[9], d -> F[10], s -> F[11], b -> F[12], A -> V[1], Z -> V[2], W -> V[3], G -> V[4], ghA -> U[1], ghZ -> U[2], ghWp -> U[3], ghWm -> U[4], ghG -> U[5], H -> S[1], G0 -> S[2], GP -> S[3], Chi -> S[4], Psi -> S[5]};

FR$InteractionOrderPerturbativeExpansion={{HIG, 0}, {QCD, 0}, {QED, 0}};

FR$GoldstoneList={S[2], S[3]};

(*     Declared indices    *)

IndexRange[ Index[Generation] ] = Range[ 3 ]

IndexRange[ Index[Colour] ] = NoUnfold[ Range[ 3 ] ]

IndexRange[ Index[SU2D] ] = Range[ 2 ]

IndexRange[ Index[Gluon] ] = NoUnfold[ Range[ 8 ] ]

IndexRange[ Index[SU2W] ] = Range[ 3 ]

(*     Declared particles    *)

M$ClassesDescription = {
F[1] == {
    SelfConjugate -> False,
    QuantumNumbers -> {LeptonNumber},
    PropagatorType -> Straight,
    PropagatorArrow -> Forward,
    Mass -> 0,
    Indices -> {},
    PropagatorLabel -> "ve" },

F[2] == {
    SelfConjugate -> False,
    QuantumNumbers -> {LeptonNumber},
    PropagatorType -> Straight,
    PropagatorArrow -> Forward,
    Mass -> 0,
    Indices -> {},
    PropagatorLabel -> "vm" },

F[3] == {
    SelfConjugate -> False,
    QuantumNumbers -> {LeptonNumber},
    PropagatorType -> Straight,
    PropagatorArrow -> Forward,
    Mass -> 0,
    Indices -> {},
    PropagatorLabel -> "vt" },

F[4] == {
    SelfConjugate -> False,
    QuantumNumbers -> {-Q, LeptonNumber},
    PropagatorType -> Straight,
    PropagatorArrow -> Forward,
    Mass -> Me,
    Indices -> {},
    PropagatorLabel -> "e" },

F[5] == {
    SelfConjugate -> False,
    QuantumNumbers -> {-Q, LeptonNumber},
    PropagatorType -> Straight,
    PropagatorArrow -> Forward,
    Mass -> MMU,
    Indices -> {},
    PropagatorLabel -> "mu" },

F[6] == {
    SelfConjugate -> False,
    QuantumNumbers -> {-Q, LeptonNumber},
    PropagatorType -> Straight,
    PropagatorArrow -> Forward,
    Mass -> MTA,
    Indices -> {},
    PropagatorLabel -> "ta" },

F[7] == {
    SelfConjugate -> False,
    QuantumNumbers -> {(2*Q)/3},
    PropagatorType -> Straight,
    PropagatorArrow -> Forward,
    Mass -> FCGV["MU"],
    Indices -> {Index[Colour]},
    PropagatorLabel -> "u" },

F[8] == {
    SelfConjugate -> False,
    QuantumNumbers -> {(2*Q)/3},
    PropagatorType -> Straight,
    PropagatorArrow -> Forward,
    Mass -> FCGV["MC"],
    Indices -> {Index[Colour]},
    PropagatorLabel -> "c" },

F[9] == {
    SelfConjugate -> False,
    QuantumNumbers -> {(2*Q)/3},
    PropagatorType -> Straight,
    PropagatorArrow -> Forward,
    Mass -> FCGV["MT"],
    Indices -> {Index[Colour]},
    PropagatorLabel -> "t" },

F[10] == {
    SelfConjugate -> False,
    QuantumNumbers -> {-1/3*Q},
    PropagatorType -> Straight,
    PropagatorArrow -> Forward,
    Mass -> FCGV["MD"],
    Indices -> {Index[Colour]},
    PropagatorLabel -> "d" },

F[11] == {
    SelfConjugate -> False,
    QuantumNumbers -> {-1/3*Q},
    PropagatorType -> Straight,
    PropagatorArrow -> Forward,
    Mass -> FCGV["MS"],
    Indices -> {Index[Colour]},
    PropagatorLabel -> "s" },

F[12] == {
    SelfConjugate -> False,
    QuantumNumbers -> {-1/3*Q},
    PropagatorType -> Straight,
    PropagatorArrow -> Forward,
    Mass -> FCGV["MB"],
    Indices -> {Index[Colour]},
    PropagatorLabel -> "b" },

V[1] == {
    SelfConjugate -> True,
    PropagatorType -> Sine,
    PropagatorArrow -> None,
    Mass -> 0,
    Indices -> {},
    PropagatorLabel -> "A" },

V[2] == {
    SelfConjugate -> True,
    PropagatorType -> Sine,
    PropagatorArrow -> None,
    Mass -> FCGV["MZ"],
    Indices -> {},
    PropagatorLabel -> "Z" },

V[3] == {
    SelfConjugate -> False,
    QuantumNumbers -> {Q},
    PropagatorType -> Sine,
    PropagatorArrow -> Forward,
    Mass -> FCGV["MW"],
    Indices -> {},
    PropagatorLabel -> "W" },

V[4] == {
    SelfConjugate -> True,
    PropagatorType -> Cycles,
    PropagatorArrow -> None,
    Mass -> 0,
    Indices -> {Index[Gluon]},
    PropagatorLabel -> "G" },

U[1] == {
    SelfConjugate -> False,
    QuantumNumbers -> {GhostNumber},
    PropagatorType -> GhostDash,
    PropagatorArrow -> Forward,
    Mass -> 0,
    Indices -> {},
    PropagatorLabel -> "ghA" },

U[2] == {
    SelfConjugate -> False,
    QuantumNumbers -> {GhostNumber},
    PropagatorType -> GhostDash,
    PropagatorArrow -> Forward,
    Mass -> FCGV["MZ"],
    Indices -> {},
    PropagatorLabel -> "ghZ" },

U[3] == {
    SelfConjugate -> False,
    QuantumNumbers -> {GhostNumber, Q},
    PropagatorType -> GhostDash,
    PropagatorArrow -> Forward,
    Mass -> FCGV["MW"],
    Indices -> {},
    PropagatorLabel -> "ghWp" },

U[4] == {
    SelfConjugate -> False,
    QuantumNumbers -> {GhostNumber, -Q},
    PropagatorType -> GhostDash,
    PropagatorArrow -> Forward,
    Mass -> FCGV["MW"],
    Indices -> {},
    PropagatorLabel -> "ghWm" },

U[5] == {
    SelfConjugate -> False,
    QuantumNumbers -> {GhostNumber},
    PropagatorType -> GhostDash,
    PropagatorArrow -> Forward,
    Mass -> 0,
    Indices -> {Index[Gluon]},
    PropagatorLabel -> "ghG" },

S[1] == {
    SelfConjugate -> True,
    PropagatorType -> ScalarDash,
    PropagatorArrow -> None,
    Mass -> FCGV["MH"],
    Indices -> {},
    PropagatorLabel -> "H" },

S[2] == {
    SelfConjugate -> True,
    PropagatorType -> ScalarDash,
    PropagatorArrow -> None,
    Mass -> FCGV["MZ"],
    Indices -> {},
    PropagatorLabel -> "G0" },

S[3] == {
    SelfConjugate -> False,
    QuantumNumbers -> {Q},
    PropagatorType -> ScalarDash,
    PropagatorArrow -> None,
    Mass -> FCGV["MW"],
    Indices -> {},
    PropagatorLabel -> "GP" },

S[4] == {
    SelfConjugate -> True,
    PropagatorType -> ScalarDash,
    PropagatorArrow -> None,
    Mass -> MChi,
    Indices -> {},
    PropagatorLabel -> "Chi" },

S[5] == {
    SelfConjugate -> True,
    PropagatorType -> ScalarDash,
    PropagatorArrow -> None,
    Mass -> MPsi,
    Indices -> {},
    PropagatorLabel -> "Psi" }
}


(*        Definitions       *)

FAGaugeXi[ U[3] ] = FAGaugeXi[U[31]];
FAGaugeXi[ U[4] ] = FAGaugeXi[U[32]];
FAGaugeXi[ U[5] ] = FAGaugeXi[U[4]];

Me[ ___ ] := Me;
MMU[ ___ ] := MMU;
MTA[ ___ ] := MTA;
FCGV["MU"][ ___ ] := FCGV["MU"];
FCGV["MC"][ ___ ] := FCGV["MC"];
FCGV["MT"][ ___ ] := FCGV["MT"];
FCGV["MD"][ ___ ] := FCGV["MD"];
FCGV["MS"][ ___ ] := FCGV["MS"];
FCGV["MB"][ ___ ] := FCGV["MB"];
FCGV["MZ"][ ___ ] := FCGV["MZ"];
FCGV["MW"][ ___ ] := FCGV["MW"];
FCGV["MH"][ ___ ] := FCGV["MH"];
MChi[ ___ ] := MChi;
MPsi[ ___ ] := MPsi;


TheLabel[ F[7, {__}] ] := TheLabel[F[7]];
TheLabel[ F[8, {__}] ] := TheLabel[F[8]];
TheLabel[ F[9, {__}] ] := TheLabel[F[9]];
TheLabel[ F[10, {__}] ] := TheLabel[F[10]];
TheLabel[ F[11, {__}] ] := TheLabel[F[11]];
TheLabel[ F[12, {__}] ] := TheLabel[F[12]];
TheLabel[ V[4, {__}] ] := TheLabel[V[4]];
TheLabel[ U[5, {__}] ] := TheLabel[U[5]];


(*      Couplings (calculated by FeynRules)      *)

M$CouplingMatrices = {

C[ S[2] , S[2] , S[2] , S[2] ] == {{(-6*I)*lam, 0}},

C[ S[2] , S[2] , S[3] , -S[3] ] == {{(-2*I)*lam, 0}},

C[ S[3] , S[3] , -S[3] , -S[3] ] == {{(-4*I)*lam, 0}},

C[ S[2] , S[2] , S[1] , S[1] ] == {{(-2*I)*lam, 0}},

C[ S[3] , -S[3] , S[1] , S[1] ] == {{(-2*I)*lam, 0}},

C[ S[1] , S[1] , S[1] , S[1] ] == {{(-6*I)*lam, 0}},

C[ S[2] , S[2] , S[1] ] == {{(-2*I)*lam*vev, 0}},

C[ S[3] , -S[3] , S[1] ] == {{(-2*I)*lam*vev, 0}},

C[ S[1] , S[1] , S[1] ] == {{(-6*I)*lam*vev, 0}},

C[ S[3] , -S[3] , V[1] , V[1] ] == {{(2*I)*FCGV["EL"]^2, 0}},

C[ S[4] , S[4] , S[2] , S[2] ] == {{(-I)*(lam12*Cos[alpha]^2 + lam123*Cos[alpha]*Sin[alpha] + lam13*Sin[alpha]^2), 0}},

C[ S[4] , S[4] , S[3] , -S[3] ] == {{(-I)*(lam12*Cos[alpha]^2 + lam123*Cos[alpha]*Sin[alpha] + lam13*Sin[alpha]^2), 0}},

C[ S[4] , S[4] , S[1] , S[1] ] == {{(-I)*(lam12*Cos[alpha]^2 + lam123*Cos[alpha]*Sin[alpha] + lam13*Sin[alpha]^2), 0}},

C[ S[4] , S[2] , S[2] , S[5] ] == {{(-1/2*I)*(lam123*Cos[2*alpha] + (-lam12 + lam13)*Sin[2*alpha]), 0}},

C[ S[4] , S[3] , -S[3] , S[5] ] == {{(-1/2*I)*(lam123*Cos[2*alpha] + (-lam12 + lam13)*Sin[2*alpha]), 0}},

C[ S[4] , S[1] , S[1] , S[5] ] == {{(-1/2*I)*(lam123*Cos[2*alpha] + (-lam12 + lam13)*Sin[2*alpha]), 0}},

C[ S[2] , S[2] , S[5] , S[5] ] == {{(-I)*(lam13*Cos[alpha]^2 - lam123*Cos[alpha]*Sin[alpha] + lam12*Sin[alpha]^2), 0}},

C[ S[3] , -S[3] , S[5] , S[5] ] == {{(-I)*(lam13*Cos[alpha]^2 - lam123*Cos[alpha]*Sin[alpha] + lam12*Sin[alpha]^2), 0}},

C[ S[1] , S[1] , S[5] , S[5] ] == {{(-I)*(lam13*Cos[alpha]^2 - lam123*Cos[alpha]*Sin[alpha] + lam12*Sin[alpha]^2), 0}},

C[ S[4] , S[4] , S[1] ] == {{(-I)*vev*(lam12*Cos[alpha]^2 + lam123*Cos[alpha]*Sin[alpha] + lam13*Sin[alpha]^2), 0}},

C[ S[4] , S[1] , S[5] ] == {{(-1/2*I)*vev*(lam123*Cos[2*alpha] + (-lam12 + lam13)*Sin[2*alpha]), 0}},

C[ S[1] , S[5] , S[5] ] == {{(-I)*vev*(lam13*Cos[alpha]^2 - lam123*Cos[alpha]*Sin[alpha] + lam12*Sin[alpha]^2), 0}},

C[ S[4] , S[4] , S[4] , S[4] ] == {{(-6*I)*(lam2*Cos[alpha]^4 + lam223*Cos[alpha]^3*Sin[alpha] + lam23*Cos[alpha]^2*Sin[alpha]^2 + lam332*Cos[alpha]*Sin[alpha]^3 + lam3*Sin[alpha]^4), 0}},

C[ S[4] , S[4] , S[4] , S[5] ] == {{((-3*I)/4)*((lam223 + lam332)*Cos[2*alpha] + (lam223 - lam332)*Cos[4*alpha] - 2*(lam2 - lam3 + (lam2 - lam23 + lam3)*Cos[2*alpha])*Sin[2*alpha]), 0}},

C[ S[4] , S[4] , S[5] , S[5] ] == {{(I/4)*(-3*lam2 - lam23 - 3*lam3 + 3*(lam2 - lam23 + lam3)*Cos[4*alpha] + 3*(lam223 - lam332)*Sin[4*alpha]), 0}},

C[ S[4] , S[5] , S[5] , S[5] ] == {{((-3*I)/4)*((lam223 + lam332)*Cos[2*alpha] + (-lam223 + lam332)*Cos[4*alpha] + 2*(-lam2 + lam3 + (lam2 - lam23 + lam3)*Cos[2*alpha])*Sin[2*alpha]), 0}},

C[ S[5] , S[5] , S[5] , S[5] ] == {{(-6*I)*(lam3*Cos[alpha]^4 - lam332*Cos[alpha]^3*Sin[alpha] + lam23*Cos[alpha]^2*Sin[alpha]^2 - lam223*Cos[alpha]*Sin[alpha]^3 + lam2*Sin[alpha]^4), 0}},

C[ S[3] , -S[3] , V[1] ] == {{(-I)*gc28, 0}, {I*gc28, 0}},

C[ S[1] , V[1] , V[1] ] == {{(-I)*gc29, 0}, {I*gc29, 0}, {0, 0}},

C[ S[1] , V[4, {e1x2}] , V[4, {e2x2}] ] == {{(-I)*gc30*IndexDelta[e1x2, e2x2], 0}, {I*gc30*IndexDelta[e1x2, e2x2], 0}, {0, 0}},

C[ -U[1] , U[4] , V[3] ] == {{I*gc31, 0}, {I*gc31, 0}, {0, 0}},

C[ -U[1] , U[3] , -V[3] ] == {{I*gc32, 0}, {I*gc32, 0}, {0, 0}},

C[ -S[3] , -U[4] , U[1] ] == {{(FCGV["EL"]^2*vev)/(2*sw), 0}},

C[ -U[4] , U[1] , -V[3] ] == {{I*gc34, 0}, {I*gc34, 0}, {0, 0}},

C[ S[2] , -U[4] , U[4] ] == {{-1/4*(FCGV["EL"]^2*vev)/sw^2, 0}},

C[ S[1] , -U[4] , U[4] ] == {{((-1/4*I)*FCGV["EL"]^2*vev)/sw^2, 0}},

C[ -U[4] , U[4] , V[1] ] == {{I*gc37, 0}, {I*gc37, 0}, {0, 0}},

C[ -U[4] , U[4] , V[2] ] == {{I*gc38, 0}, {I*gc38, 0}, {0, 0}},

C[ -S[3] , -U[4] , U[2] ] == {{(FCGV["EL"]^2*(cw - sw)*(cw + sw)*vev)/(4*cw*sw^2), 0}},

C[ -U[4] , U[2] , -V[3] ] == {{I*gc40, 0}, {I*gc40, 0}, {0, 0}},

C[ S[3] , -U[3] , U[1] ] == {{-1/2*(FCGV["EL"]^2*vev)/sw, 0}},

C[ -U[3] , U[1] , V[3] ] == {{I*gc42, 0}, {I*gc42, 0}, {0, 0}},

C[ S[2] , -U[3] , U[3] ] == {{(FCGV["EL"]^2*vev)/(4*sw^2), 0}},

C[ S[1] , -U[3] , U[3] ] == {{((-1/4*I)*FCGV["EL"]^2*vev)/sw^2, 0}},

C[ -U[3] , U[3] , V[1] ] == {{I*gc45, 0}, {I*gc45, 0}, {0, 0}},

C[ -U[3] , U[3] , V[2] ] == {{I*gc46, 0}, {I*gc46, 0}, {0, 0}},

C[ S[3] , -U[3] , U[2] ] == {{-1/4*(FCGV["EL"]^2*(cw - sw)*(cw + sw)*vev)/(cw*sw^2), 0}},

C[ -U[3] , U[2] , V[3] ] == {{I*gc48, 0}, {I*gc48, 0}, {0, 0}},

C[ S[3] , -U[2] , U[4] ] == {{(FCGV["EL"]^2*(cw^2 + sw^2)*vev)/(4*cw*sw^2), 0}},

C[ -U[2] , U[4] , V[3] ] == {{I*gc50, 0}, {I*gc50, 0}, {0, 0}},

C[ -S[3] , -U[2] , U[3] ] == {{-1/4*(FCGV["EL"]^2*(cw^2 + sw^2)*vev)/(cw*sw^2), 0}},

C[ -U[2] , U[3] , -V[3] ] == {{I*gc52, 0}, {I*gc52, 0}, {0, 0}},

C[ S[1] , -U[2] , U[2] ] == {{((-1/4*I)*FCGV["EL"]^2*(cw^2 + sw^2)^2*vev)/(cw^2*sw^2), 0}},

C[ -U[5, {e1x1}] , U[5, {e2x1}] , V[4, {e3x2}] ] == {{gc54*FASUNF[e3x2, e1x1, e2x1], 0}, {gc54*FASUNF[e3x2, e1x1, e2x1], 0}, {0, 0}},

C[ V[4, {e1x2}] , V[4, {e2x2}] , V[4, {e3x2}] ] == {{-(gc55*FASUNF[e1x2, e2x2, e3x2]), 0}, {gc55*FASUNF[e1x2, e2x2, e3x2], 0}, {gc55*FASUNF[e1x2, e2x2, e3x2], 0}, {-(gc55*FASUNF[e1x2, e2x2, e3x2]), 0}, {-(gc55*FASUNF[e1x2, e2x2, e3x2]), 0}, {gc55*FASUNF[e1x2, e2x2, e3x2], 0}},

C[ V[4, {e1x2}] , V[4, {e2x2}] , V[4, {e3x2}] , V[4, {e4x2}] ] == {{(-I)*gc56*(FASUNF[e1x2, e2x2, e3x2, e4x2] + FASUNF[e1x2, e3x2, e2x2, e4x2]), 0}, {I*gc56*(FASUNF[e1x2, e2x2, e3x2, e4x2] - FASUNF[e1x2, e4x2, e2x2, e3x2]), 0}, {I*gc56*(FASUNF[e1x2, e3x2, e2x2, e4x2] + FASUNF[e1x2, e4x2, e2x2, e3x2]), 0}},

C[ S[1] , V[4, {e1x2}] , V[4, {e2x2}] , V[4, {e3x2}] ] == {{-(gc57*FASUNF[e1x2, e2x2, e3x2]), 0}, {gc57*FASUNF[e1x2, e2x2, e3x2], 0}, {gc57*FASUNF[e1x2, e2x2, e3x2], 0}, {-(gc57*FASUNF[e1x2, e2x2, e3x2]), 0}, {-(gc57*FASUNF[e1x2, e2x2, e3x2]), 0}, {gc57*FASUNF[e1x2, e2x2, e3x2], 0}},

C[ S[1] , V[4, {e1x2}] , V[4, {e2x2}] , V[4, {e3x2}] , V[4, {e4x2}] ] == {{(-I)*gc58*(FASUNF[e1x2, e2x2, e3x2, e4x2] + FASUNF[e1x2, e3x2, e2x2, e4x2]), 0}, {I*gc58*(FASUNF[e1x2, e2x2, e3x2, e4x2] - FASUNF[e1x2, e4x2, e2x2, e3x2]), 0}, {I*gc58*(FASUNF[e1x2, e3x2, e2x2, e4x2] + FASUNF[e1x2, e4x2, e2x2, e3x2]), 0}},

C[ -F[12, {e1x2}] , F[8, {e2x2}] , -S[3] ] == {{gc59L*IndexDelta[e1x2, e2x2], 0}, {gc59R*IndexDelta[e1x2, e2x2], 0}},

C[ -F[12, {e1x2}] , F[9, {e2x2}] , -S[3] ] == {{gc60L*IndexDelta[e1x2, e2x2], 0}, {gc60R*IndexDelta[e1x2, e2x2], 0}},

C[ -F[12, {e1x2}] , F[7, {e2x2}] , -S[3] ] == {{gc61L*IndexDelta[e1x2, e2x2], 0}, {gc61R*IndexDelta[e1x2, e2x2], 0}},

C[ -F[10, {e1x2}] , F[8, {e2x2}] , -S[3] ] == {{gc62L*IndexDelta[e1x2, e2x2], 0}, {gc62R*IndexDelta[e1x2, e2x2], 0}},

C[ -F[10, {e1x2}] , F[9, {e2x2}] , -S[3] ] == {{gc63L*IndexDelta[e1x2, e2x2], 0}, {gc63R*IndexDelta[e1x2, e2x2], 0}},

C[ -F[10, {e1x2}] , F[7, {e2x2}] , -S[3] ] == {{gc64L*IndexDelta[e1x2, e2x2], 0}, {gc64R*IndexDelta[e1x2, e2x2], 0}},

C[ -F[11, {e1x2}] , F[8, {e2x2}] , -S[3] ] == {{gc65L*IndexDelta[e1x2, e2x2], 0}, {gc65R*IndexDelta[e1x2, e2x2], 0}},

C[ -F[11, {e1x2}] , F[9, {e2x2}] , -S[3] ] == {{gc66L*IndexDelta[e1x2, e2x2], 0}, {gc66R*IndexDelta[e1x2, e2x2], 0}},

C[ -F[11, {e1x2}] , F[7, {e2x2}] , -S[3] ] == {{gc67L*IndexDelta[e1x2, e2x2], 0}, {gc67R*IndexDelta[e1x2, e2x2], 0}},

C[ -F[12, {e1x2}] , F[12, {e2x2}] , S[2] ] == {{gc68L*IndexDelta[e1x2, e2x2], 0}, {gc68R*IndexDelta[e1x2, e2x2], 0}},

C[ -F[10, {e1x2}] , F[10, {e2x2}] , S[2] ] == {{gc69L*IndexDelta[e1x2, e2x2], 0}, {gc69R*IndexDelta[e1x2, e2x2], 0}},

C[ -F[11, {e1x2}] , F[11, {e2x2}] , S[2] ] == {{gc70L*IndexDelta[e1x2, e2x2], 0}, {gc70R*IndexDelta[e1x2, e2x2], 0}},

C[ -F[12, {e1x2}] , F[12, {e2x2}] , S[1] ] == {{I*gc71*IndexDelta[e1x2, e2x2], 0}, {I*gc71*IndexDelta[e1x2, e2x2], 0}},

C[ -F[10, {e1x2}] , F[10, {e2x2}] , S[1] ] == {{I*gc72*IndexDelta[e1x2, e2x2], 0}, {I*gc72*IndexDelta[e1x2, e2x2], 0}},

C[ -F[11, {e1x2}] , F[11, {e2x2}] , S[1] ] == {{I*gc73*IndexDelta[e1x2, e2x2], 0}, {I*gc73*IndexDelta[e1x2, e2x2], 0}},

C[ -F[4] , F[1] , -S[3] ] == {{gc74, 0}, {0, 0}},

C[ -F[5] , F[2] , -S[3] ] == {{gc75, 0}, {0, 0}},

C[ -F[6] , F[3] , -S[3] ] == {{gc76, 0}, {0, 0}},

C[ -F[4] , F[4] , S[2] ] == {{gc77L, 0}, {gc77R, 0}},

C[ -F[5] , F[5] , S[2] ] == {{gc78L, 0}, {gc78R, 0}},

C[ -F[6] , F[6] , S[2] ] == {{gc79L, 0}, {gc79R, 0}},

C[ -F[4] , F[4] , S[1] ] == {{I*gc80, 0}, {I*gc80, 0}},

C[ -F[5] , F[5] , S[1] ] == {{I*gc81, 0}, {I*gc81, 0}},

C[ -F[6] , F[6] , S[1] ] == {{I*gc82, 0}, {I*gc82, 0}},

C[ -F[8, {e1x2}] , F[12, {e2x2}] , S[3] ] == {{gc83L*IndexDelta[e1x2, e2x2], 0}, {gc83R*IndexDelta[e1x2, e2x2], 0}},

C[ -F[8, {e1x2}] , F[10, {e2x2}] , S[3] ] == {{gc84L*IndexDelta[e1x2, e2x2], 0}, {gc84R*IndexDelta[e1x2, e2x2], 0}},

C[ -F[8, {e1x2}] , F[11, {e2x2}] , S[3] ] == {{gc85L*IndexDelta[e1x2, e2x2], 0}, {gc85R*IndexDelta[e1x2, e2x2], 0}},

C[ -F[9, {e1x2}] , F[12, {e2x2}] , S[3] ] == {{gc86L*IndexDelta[e1x2, e2x2], 0}, {gc86R*IndexDelta[e1x2, e2x2], 0}},

C[ -F[9, {e1x2}] , F[10, {e2x2}] , S[3] ] == {{gc87L*IndexDelta[e1x2, e2x2], 0}, {gc87R*IndexDelta[e1x2, e2x2], 0}},

C[ -F[9, {e1x2}] , F[11, {e2x2}] , S[3] ] == {{gc88L*IndexDelta[e1x2, e2x2], 0}, {gc88R*IndexDelta[e1x2, e2x2], 0}},

C[ -F[7, {e1x2}] , F[12, {e2x2}] , S[3] ] == {{gc89L*IndexDelta[e1x2, e2x2], 0}, {gc89R*IndexDelta[e1x2, e2x2], 0}},

C[ -F[7, {e1x2}] , F[10, {e2x2}] , S[3] ] == {{gc90L*IndexDelta[e1x2, e2x2], 0}, {gc90R*IndexDelta[e1x2, e2x2], 0}},

C[ -F[7, {e1x2}] , F[11, {e2x2}] , S[3] ] == {{gc91L*IndexDelta[e1x2, e2x2], 0}, {gc91R*IndexDelta[e1x2, e2x2], 0}},

C[ -F[8, {e1x2}] , F[8, {e2x2}] , S[2] ] == {{gc92L*IndexDelta[e1x2, e2x2], 0}, {gc92R*IndexDelta[e1x2, e2x2], 0}},

C[ -F[9, {e1x2}] , F[9, {e2x2}] , S[2] ] == {{gc93L*IndexDelta[e1x2, e2x2], 0}, {gc93R*IndexDelta[e1x2, e2x2], 0}},

C[ -F[7, {e1x2}] , F[7, {e2x2}] , S[2] ] == {{gc94L*IndexDelta[e1x2, e2x2], 0}, {gc94R*IndexDelta[e1x2, e2x2], 0}},

C[ -F[8, {e1x2}] , F[8, {e2x2}] , S[1] ] == {{I*gc95*IndexDelta[e1x2, e2x2], 0}, {I*gc95*IndexDelta[e1x2, e2x2], 0}},

C[ -F[9, {e1x2}] , F[9, {e2x2}] , S[1] ] == {{I*gc96*IndexDelta[e1x2, e2x2], 0}, {I*gc96*IndexDelta[e1x2, e2x2], 0}},

C[ -F[7, {e1x2}] , F[7, {e2x2}] , S[1] ] == {{I*gc97*IndexDelta[e1x2, e2x2], 0}, {I*gc97*IndexDelta[e1x2, e2x2], 0}},

C[ S[2] , -S[3] , V[1] , V[3] ] == {{((-1/2*I)*FCGV["EL"]^2)/sw, 0}},

C[ -S[3] , S[1] , V[1] , V[3] ] == {{-1/2*FCGV["EL"]^2/sw, 0}},

C[ -S[3] , V[1] , V[3] ] == {{0, 0}, {0, 0}, {gc100, 0}},

C[ S[2] , -S[3] , V[3] ] == {{(-I)*gc101, 0}, {I*gc101, 0}},

C[ -S[3] , S[1] , V[3] ] == {{-gc102, 0}, {gc102, 0}},

C[ V[1] , V[3] , -V[3] ] == {{(-I)*gc103, 0}, {I*gc103, 0}, {I*gc103, 0}, {(-I)*gc103, 0}, {(-I)*gc103, 0}, {I*gc103, 0}},

C[ S[2] , S[3] , V[1] , -V[3] ] == {{((-1/2*I)*FCGV["EL"]^2)/sw, 0}},

C[ S[3] , S[1] , V[1] , -V[3] ] == {{FCGV["EL"]^2/(2*sw), 0}},

C[ S[3] , V[1] , -V[3] ] == {{0, 0}, {0, 0}, {gc106, 0}},

C[ S[2] , S[3] , -V[3] ] == {{(-I)*gc107, 0}, {I*gc107, 0}},

C[ S[3] , S[1] , -V[3] ] == {{-gc108, 0}, {gc108, 0}},

C[ S[2] , S[2] , V[3] , -V[3] ] == {{((I/2)*FCGV["EL"]^2)/sw^2, 0}},

C[ S[3] , -S[3] , V[3] , -V[3] ] == {{((I/2)*FCGV["EL"]^2)/sw^2, 0}},

C[ S[1] , S[1] , V[3] , -V[3] ] == {{((I/2)*FCGV["EL"]^2)/sw^2, 0}},

C[ S[1] , V[3] , -V[3] ] == {{0, 0}, {0, 0}, {I*gc112, 0}},

C[ V[1] , V[1] , V[3] , -V[3] ] == {{(-I)*gc113, 0}, {(-I)*gc113, 0}, {(2*I)*gc113, 0}},

C[ V[3] , -V[3] , V[2] ] == {{(-I)*gc114, 0}, {I*gc114, 0}, {I*gc114, 0}, {(-I)*gc114, 0}, {(-I)*gc114, 0}, {I*gc114, 0}},

C[ V[3] , V[3] , -V[3] , -V[3] ] == {{(-I)*gc115, 0}, {(-I)*gc115, 0}, {(2*I)*gc115, 0}},

C[ -F[1] , F[4] , S[3] ] == {{0, 0}, {gc116R, 0}},

C[ -F[2] , F[5] , S[3] ] == {{0, 0}, {gc117R, 0}},

C[ -F[3] , F[6] , S[3] ] == {{0, 0}, {gc118R, 0}},

C[ S[3] , -S[3] , V[1] , V[2] ] == {{(I*FCGV["EL"]^2*(cw - sw)*(cw + sw))/(cw*sw), 0}},

C[ S[2] , S[1] , V[2] ] == {{-gc120, 0}, {gc120, 0}},

C[ S[3] , -S[3] , V[2] ] == {{(-I)*gc121, 0}, {I*gc121, 0}},

C[ S[2] , -S[3] , V[3] , V[2] ] == {{((I/2)*FCGV["EL"]^2)/cw, 0}},

C[ -S[3] , S[1] , V[3] , V[2] ] == {{FCGV["EL"]^2/(2*cw), 0}},

C[ -S[3] , V[3] , V[2] ] == {{0, 0}, {0, 0}, {gc124, 0}},

C[ S[2] , S[3] , -V[3] , V[2] ] == {{((I/2)*FCGV["EL"]^2)/cw, 0}},

C[ S[3] , S[1] , -V[3] , V[2] ] == {{-1/2*FCGV["EL"]^2/cw, 0}},

C[ S[3] , -V[3] , V[2] ] == {{0, 0}, {0, 0}, {gc127, 0}},

C[ V[1] , V[3] , -V[3] , V[2] ] == {{(-2*I)*gc128, 0}, {I*gc128, 0}, {I*gc128, 0}},

C[ S[2] , S[2] , V[2] , V[2] ] == {{((I/2)*FCGV["EL"]^2*(cw^2 + sw^2)^2)/(cw^2*sw^2), 0}},

C[ S[3] , -S[3] , V[2] , V[2] ] == {{((I/2)*FCGV["EL"]^2*(cw - sw)^2*(cw + sw)^2)/(cw^2*sw^2), 0}},

C[ S[1] , S[1] , V[2] , V[2] ] == {{((I/2)*FCGV["EL"]^2*(cw^2 + sw^2)^2)/(cw^2*sw^2), 0}},

C[ S[1] , V[2] , V[2] ] == {{0, 0}, {0, 0}, {I*gc132, 0}},

C[ V[3] , -V[3] , V[2] , V[2] ] == {{(-I)*gc133, 0}, {(-I)*gc133, 0}, {(2*I)*gc133, 0}},

C[ -F[4] , F[4] , V[1] ] == {{I*gc134, 0}, {I*gc134, 0}},

C[ -F[5] , F[5] , V[1] ] == {{I*gc135, 0}, {I*gc135, 0}},

C[ -F[6] , F[6] , V[1] ] == {{I*gc136, 0}, {I*gc136, 0}},

C[ -F[8, {e1x2}] , F[8, {e2x2}] , V[1] ] == {{I*gc137*IndexDelta[e1x2, e2x2], 0}, {I*gc137*IndexDelta[e1x2, e2x2], 0}},

C[ -F[9, {e1x2}] , F[9, {e2x2}] , V[1] ] == {{I*gc138*IndexDelta[e1x2, e2x2], 0}, {I*gc138*IndexDelta[e1x2, e2x2], 0}},

C[ -F[7, {e1x2}] , F[7, {e2x2}] , V[1] ] == {{I*gc139*IndexDelta[e1x2, e2x2], 0}, {I*gc139*IndexDelta[e1x2, e2x2], 0}},

C[ -F[12, {e1x2}] , F[12, {e2x2}] , V[1] ] == {{I*gc140*IndexDelta[e1x2, e2x2], 0}, {I*gc140*IndexDelta[e1x2, e2x2], 0}},

C[ -F[10, {e1x2}] , F[10, {e2x2}] , V[1] ] == {{I*gc141*IndexDelta[e1x2, e2x2], 0}, {I*gc141*IndexDelta[e1x2, e2x2], 0}},

C[ -F[11, {e1x2}] , F[11, {e2x2}] , V[1] ] == {{I*gc142*IndexDelta[e1x2, e2x2], 0}, {I*gc142*IndexDelta[e1x2, e2x2], 0}},

C[ -F[8, {e1x2}] , F[8, {e2x2}] , V[4, {e3x2}] ] == {{I*gc143*FASUNT[e3x2, e1x2, e2x2], 0}, {I*gc143*FASUNT[e3x2, e1x2, e2x2], 0}},

C[ -F[9, {e1x2}] , F[9, {e2x2}] , V[4, {e3x2}] ] == {{I*gc144*FASUNT[e3x2, e1x2, e2x2], 0}, {I*gc144*FASUNT[e3x2, e1x2, e2x2], 0}},

C[ -F[7, {e1x2}] , F[7, {e2x2}] , V[4, {e3x2}] ] == {{I*gc145*FASUNT[e3x2, e1x2, e2x2], 0}, {I*gc145*FASUNT[e3x2, e1x2, e2x2], 0}},

C[ -F[12, {e1x2}] , F[12, {e2x2}] , V[4, {e3x2}] ] == {{I*gc146*FASUNT[e3x2, e1x2, e2x2], 0}, {I*gc146*FASUNT[e3x2, e1x2, e2x2], 0}},

C[ -F[10, {e1x2}] , F[10, {e2x2}] , V[4, {e3x2}] ] == {{I*gc147*FASUNT[e3x2, e1x2, e2x2], 0}, {I*gc147*FASUNT[e3x2, e1x2, e2x2], 0}},

C[ -F[11, {e1x2}] , F[11, {e2x2}] , V[4, {e3x2}] ] == {{I*gc148*FASUNT[e3x2, e1x2, e2x2], 0}, {I*gc148*FASUNT[e3x2, e1x2, e2x2], 0}},

C[ -F[8, {e1x2}] , F[12, {e2x2}] , V[3] ] == {{I*gc149*IndexDelta[e1x2, e2x2], 0}, {0, 0}},

C[ -F[8, {e1x2}] , F[10, {e2x2}] , V[3] ] == {{I*gc150*IndexDelta[e1x2, e2x2], 0}, {0, 0}},

C[ -F[8, {e1x2}] , F[11, {e2x2}] , V[3] ] == {{I*gc151*IndexDelta[e1x2, e2x2], 0}, {0, 0}},

C[ -F[9, {e1x2}] , F[12, {e2x2}] , V[3] ] == {{I*gc152*IndexDelta[e1x2, e2x2], 0}, {0, 0}},

C[ -F[9, {e1x2}] , F[10, {e2x2}] , V[3] ] == {{I*gc153*IndexDelta[e1x2, e2x2], 0}, {0, 0}},

C[ -F[9, {e1x2}] , F[11, {e2x2}] , V[3] ] == {{I*gc154*IndexDelta[e1x2, e2x2], 0}, {0, 0}},

C[ -F[7, {e1x2}] , F[12, {e2x2}] , V[3] ] == {{I*gc155*IndexDelta[e1x2, e2x2], 0}, {0, 0}},

C[ -F[7, {e1x2}] , F[10, {e2x2}] , V[3] ] == {{I*gc156*IndexDelta[e1x2, e2x2], 0}, {0, 0}},

C[ -F[7, {e1x2}] , F[11, {e2x2}] , V[3] ] == {{I*gc157*IndexDelta[e1x2, e2x2], 0}, {0, 0}},

C[ -F[12, {e1x2}] , F[8, {e2x2}] , -V[3] ] == {{I*gc158*IndexDelta[e1x2, e2x2], 0}, {0, 0}},

C[ -F[12, {e1x2}] , F[9, {e2x2}] , -V[3] ] == {{I*gc159*IndexDelta[e1x2, e2x2], 0}, {0, 0}},

C[ -F[12, {e1x2}] , F[7, {e2x2}] , -V[3] ] == {{I*gc160*IndexDelta[e1x2, e2x2], 0}, {0, 0}},

C[ -F[10, {e1x2}] , F[8, {e2x2}] , -V[3] ] == {{I*gc161*IndexDelta[e1x2, e2x2], 0}, {0, 0}},

C[ -F[10, {e1x2}] , F[9, {e2x2}] , -V[3] ] == {{I*gc162*IndexDelta[e1x2, e2x2], 0}, {0, 0}},

C[ -F[10, {e1x2}] , F[7, {e2x2}] , -V[3] ] == {{I*gc163*IndexDelta[e1x2, e2x2], 0}, {0, 0}},

C[ -F[11, {e1x2}] , F[8, {e2x2}] , -V[3] ] == {{I*gc164*IndexDelta[e1x2, e2x2], 0}, {0, 0}},

C[ -F[11, {e1x2}] , F[9, {e2x2}] , -V[3] ] == {{I*gc165*IndexDelta[e1x2, e2x2], 0}, {0, 0}},

C[ -F[11, {e1x2}] , F[7, {e2x2}] , -V[3] ] == {{I*gc166*IndexDelta[e1x2, e2x2], 0}, {0, 0}},

C[ -F[1] , F[4] , V[3] ] == {{I*gc167, 0}, {0, 0}},

C[ -F[2] , F[5] , V[3] ] == {{I*gc168, 0}, {0, 0}},

C[ -F[3] , F[6] , V[3] ] == {{I*gc169, 0}, {0, 0}},

C[ -F[4] , F[1] , -V[3] ] == {{I*gc170, 0}, {0, 0}},

C[ -F[5] , F[2] , -V[3] ] == {{I*gc171, 0}, {0, 0}},

C[ -F[6] , F[3] , -V[3] ] == {{I*gc172, 0}, {0, 0}},

C[ -F[8, {e1x2}] , F[8, {e2x2}] , V[2] ] == {{I*gc173L*IndexDelta[e1x2, e2x2], 0}, {I*gc173R*IndexDelta[e1x2, e2x2], 0}},

C[ -F[9, {e1x2}] , F[9, {e2x2}] , V[2] ] == {{I*gc174L*IndexDelta[e1x2, e2x2], 0}, {I*gc174R*IndexDelta[e1x2, e2x2], 0}},

C[ -F[7, {e1x2}] , F[7, {e2x2}] , V[2] ] == {{I*gc175L*IndexDelta[e1x2, e2x2], 0}, {I*gc175R*IndexDelta[e1x2, e2x2], 0}},

C[ -F[12, {e1x2}] , F[12, {e2x2}] , V[2] ] == {{I*gc176L*IndexDelta[e1x2, e2x2], 0}, {I*gc176R*IndexDelta[e1x2, e2x2], 0}},

C[ -F[10, {e1x2}] , F[10, {e2x2}] , V[2] ] == {{I*gc177L*IndexDelta[e1x2, e2x2], 0}, {I*gc177R*IndexDelta[e1x2, e2x2], 0}},

C[ -F[11, {e1x2}] , F[11, {e2x2}] , V[2] ] == {{I*gc178L*IndexDelta[e1x2, e2x2], 0}, {I*gc178R*IndexDelta[e1x2, e2x2], 0}},

C[ -F[1] , F[1] , V[2] ] == {{I*gc179, 0}, {0, 0}},

C[ -F[2] , F[2] , V[2] ] == {{I*gc180, 0}, {0, 0}},

C[ -F[3] , F[3] , V[2] ] == {{I*gc181, 0}, {0, 0}},

C[ -F[4] , F[4] , V[2] ] == {{I*gc182L, 0}, {I*gc182R, 0}},

C[ -F[5] , F[5] , V[2] ] == {{I*gc183L, 0}, {I*gc183R, 0}},

C[ -F[6] , F[6] , V[2] ] == {{I*gc184L, 0}, {I*gc184R, 0}}

}

(* * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * *)

(* Parameter replacement lists (These lists were created by FeynRules) *)

(* FA Couplings *)

M$FACouplings = {
     gc28 -> -FCGV["EL"],
     gc29 -> AH,
     gc30 -> GH,
     gc31 -> FCGV["EL"],
     gc32 -> -FCGV["EL"],
     gc34 -> FCGV["EL"],
     gc37 -> -FCGV["EL"],
     gc38 -> -((cw*FCGV["EL"])/sw),
     gc40 -> (cw*FCGV["EL"])/sw,
     gc42 -> -FCGV["EL"],
     gc45 -> FCGV["EL"],
     gc46 -> (cw*FCGV["EL"])/sw,
     gc48 -> -((cw*FCGV["EL"])/sw),
     gc50 -> (cw*FCGV["EL"])/sw,
     gc52 -> -((cw*FCGV["EL"])/sw),
     gc54 -> FAGS,
     gc55 -> -FAGS,
     gc56 -> -FAGS^2,
     gc57 -> -(GH*FAGS),
     gc58 -> -(GH*FAGS^2),
     gc59L -> yb*Conjugate[CKM2x3],
     gc59R -> -(yc*Conjugate[CKM2x3]),
     gc60L -> yb*Conjugate[CKM3x3],
     gc60R -> -(yt*Conjugate[CKM3x3]),
     gc61L -> yb*Conjugate[CKM1x3],
     gc61R -> -(yup*Conjugate[CKM1x3]),
     gc62L -> ydo*Conjugate[CKM2x1],
     gc62R -> -(yc*Conjugate[CKM2x1]),
     gc63L -> ydo*Conjugate[CKM3x1],
     gc63R -> -(yt*Conjugate[CKM3x1]),
     gc64L -> ydo*Conjugate[CKM1x1],
     gc64R -> -(yup*Conjugate[CKM1x1]),
     gc65L -> ys*Conjugate[CKM2x2],
     gc65R -> -(yc*Conjugate[CKM2x2]),
     gc66L -> ys*Conjugate[CKM3x2],
     gc66R -> -(yt*Conjugate[CKM3x2]),
     gc67L -> ys*Conjugate[CKM1x2],
     gc67R -> -(yup*Conjugate[CKM1x2]),
     gc68L -> -(yb/Sqrt[2]),
     gc68R -> yb/Sqrt[2],
     gc69L -> -(ydo/Sqrt[2]),
     gc69R -> ydo/Sqrt[2],
     gc70L -> -(ys/Sqrt[2]),
     gc70R -> ys/Sqrt[2],
     gc71 -> -(yb/Sqrt[2]),
     gc72 -> -(ydo/Sqrt[2]),
     gc73 -> -(ys/Sqrt[2]),
     gc74 -> ye,
     gc75 -> ym,
     gc76 -> ytau,
     gc77L -> -(ye/Sqrt[2]),
     gc77R -> ye/Sqrt[2],
     gc78L -> -(ym/Sqrt[2]),
     gc78R -> ym/Sqrt[2],
     gc79L -> -(ytau/Sqrt[2]),
     gc79R -> ytau/Sqrt[2],
     gc80 -> -(ye/Sqrt[2]),
     gc81 -> -(ym/Sqrt[2]),
     gc82 -> -(ytau/Sqrt[2]),
     gc83L -> CKM2x3*yc,
     gc83R -> -(CKM2x3*yb),
     gc84L -> CKM2x1*yc,
     gc84R -> -(CKM2x1*ydo),
     gc85L -> CKM2x2*yc,
     gc85R -> -(CKM2x2*ys),
     gc86L -> CKM3x3*yt,
     gc86R -> -(CKM3x3*yb),
     gc87L -> CKM3x1*yt,
     gc87R -> -(CKM3x1*ydo),
     gc88L -> CKM3x2*yt,
     gc88R -> -(CKM3x2*ys),
     gc89L -> CKM1x3*yup,
     gc89R -> -(CKM1x3*yb),
     gc90L -> CKM1x1*yup,
     gc90R -> -(CKM1x1*ydo),
     gc91L -> CKM1x2*yup,
     gc91R -> -(CKM1x2*ys),
     gc92L -> yc/Sqrt[2],
     gc92R -> -(yc/Sqrt[2]),
     gc93L -> yt/Sqrt[2],
     gc93R -> -(yt/Sqrt[2]),
     gc94L -> yup/Sqrt[2],
     gc94R -> -(yup/Sqrt[2]),
     gc95 -> -(yc/Sqrt[2]),
     gc96 -> -(yt/Sqrt[2]),
     gc97 -> -(yup/Sqrt[2]),
     gc100 -> -1/2*(FCGV["EL"]^2*vev)/sw,
     gc101 -> FCGV["EL"]/(2*sw),
     gc102 -> -1/2*FCGV["EL"]/sw,
     gc103 -> FCGV["EL"],
     gc106 -> (FCGV["EL"]^2*vev)/(2*sw),
     gc107 -> -1/2*FCGV["EL"]/sw,
     gc108 -> -1/2*FCGV["EL"]/sw,
     gc112 -> (FCGV["EL"]^2*vev)/(2*sw^2),
     gc113 -> -FCGV["EL"]^2,
     gc114 -> (cw*FCGV["EL"])/sw,
     gc115 -> FCGV["EL"]^2/sw^2,
     gc116R -> -ye,
     gc117R -> -ym,
     gc118R -> -ytau,
     gc120 -> -1/2*(FCGV["EL"]*(cw^2 + sw^2))/(cw*sw),
     gc121 -> -1/2*(cw*FCGV["EL"])/sw + (FCGV["EL"]*sw)/(2*cw),
     gc124 -> (FCGV["EL"]^2*vev)/(2*cw),
     gc127 -> -1/2*(FCGV["EL"]^2*vev)/cw,
     gc128 -> (cw*FCGV["EL"]^2)/sw,
     gc132 -> (FCGV["EL"]^2*(cw^2 + sw^2)^2*vev)/(2*cw^2*sw^2),
     gc133 -> -((cw^2*FCGV["EL"]^2)/sw^2),
     gc134 -> -FCGV["EL"],
     gc135 -> -FCGV["EL"],
     gc136 -> -FCGV["EL"],
     gc137 -> (2*FCGV["EL"])/3,
     gc138 -> (2*FCGV["EL"])/3,
     gc139 -> (2*FCGV["EL"])/3,
     gc140 -> -1/3*FCGV["EL"],
     gc141 -> -1/3*FCGV["EL"],
     gc142 -> -1/3*FCGV["EL"],
     gc143 -> FAGS,
     gc144 -> FAGS,
     gc145 -> FAGS,
     gc146 -> FAGS,
     gc147 -> FAGS,
     gc148 -> FAGS,
     gc149 -> (CKM2x3*FCGV["EL"])/(Sqrt[2]*sw),
     gc150 -> (CKM2x1*FCGV["EL"])/(Sqrt[2]*sw),
     gc151 -> (CKM2x2*FCGV["EL"])/(Sqrt[2]*sw),
     gc152 -> (CKM3x3*FCGV["EL"])/(Sqrt[2]*sw),
     gc153 -> (CKM3x1*FCGV["EL"])/(Sqrt[2]*sw),
     gc154 -> (CKM3x2*FCGV["EL"])/(Sqrt[2]*sw),
     gc155 -> (CKM1x3*FCGV["EL"])/(Sqrt[2]*sw),
     gc156 -> (CKM1x1*FCGV["EL"])/(Sqrt[2]*sw),
     gc157 -> (CKM1x2*FCGV["EL"])/(Sqrt[2]*sw),
     gc158 -> (FCGV["EL"]*Conjugate[CKM2x3])/(Sqrt[2]*sw),
     gc159 -> (FCGV["EL"]*Conjugate[CKM3x3])/(Sqrt[2]*sw),
     gc160 -> (FCGV["EL"]*Conjugate[CKM1x3])/(Sqrt[2]*sw),
     gc161 -> (FCGV["EL"]*Conjugate[CKM2x1])/(Sqrt[2]*sw),
     gc162 -> (FCGV["EL"]*Conjugate[CKM3x1])/(Sqrt[2]*sw),
     gc163 -> (FCGV["EL"]*Conjugate[CKM1x1])/(Sqrt[2]*sw),
     gc164 -> (FCGV["EL"]*Conjugate[CKM2x2])/(Sqrt[2]*sw),
     gc165 -> (FCGV["EL"]*Conjugate[CKM3x2])/(Sqrt[2]*sw),
     gc166 -> (FCGV["EL"]*Conjugate[CKM1x2])/(Sqrt[2]*sw),
     gc167 -> FCGV["EL"]/(Sqrt[2]*sw),
     gc168 -> FCGV["EL"]/(Sqrt[2]*sw),
     gc169 -> FCGV["EL"]/(Sqrt[2]*sw),
     gc170 -> FCGV["EL"]/(Sqrt[2]*sw),
     gc171 -> FCGV["EL"]/(Sqrt[2]*sw),
     gc172 -> FCGV["EL"]/(Sqrt[2]*sw),
     gc173L -> (cw*FCGV["EL"])/(2*sw) - (FCGV["EL"]*sw)/(6*cw),
     gc173R -> (-2*FCGV["EL"]*sw)/(3*cw),
     gc174L -> (cw*FCGV["EL"])/(2*sw) - (FCGV["EL"]*sw)/(6*cw),
     gc174R -> (-2*FCGV["EL"]*sw)/(3*cw),
     gc175L -> (cw*FCGV["EL"])/(2*sw) - (FCGV["EL"]*sw)/(6*cw),
     gc175R -> (-2*FCGV["EL"]*sw)/(3*cw),
     gc176L -> -1/6*(FCGV["EL"]*(3*cw^2 + sw^2))/(cw*sw),
     gc176R -> (FCGV["EL"]*sw)/(3*cw),
     gc177L -> -1/6*(FCGV["EL"]*(3*cw^2 + sw^2))/(cw*sw),
     gc177R -> (FCGV["EL"]*sw)/(3*cw),
     gc178L -> -1/6*(FCGV["EL"]*(3*cw^2 + sw^2))/(cw*sw),
     gc178R -> (FCGV["EL"]*sw)/(3*cw),
     gc179 -> (FCGV["EL"]*(cw^2 + sw^2))/(2*cw*sw),
     gc180 -> (FCGV["EL"]*(cw^2 + sw^2))/(2*cw*sw),
     gc181 -> (FCGV["EL"]*(cw^2 + sw^2))/(2*cw*sw),
     gc182L -> -1/2*(FCGV["EL"]*(cw^2 - sw^2))/(cw*sw),
     gc182R -> (FCGV["EL"]*sw)/cw,
     gc183L -> -1/2*(FCGV["EL"]*(cw^2 - sw^2))/(cw*sw),
     gc183R -> (FCGV["EL"]*sw)/cw,
     gc184L -> -1/2*(FCGV["EL"]*(cw^2 - sw^2))/(cw*sw),
     gc184R -> (FCGV["EL"]*sw)/cw};

