///////////////////CODE GENERATED VIA MATHEMATICA///////////////////


#pragma once

#include <cmath>

namespace DT{
namespace PAR{
	extern double aEWM1;
	extern double Gf;
	extern double aS;
	extern double ymdo;
	extern double ymup;
	extern double yms;
	extern double ymc;
	extern double ymb;
	extern double ymt;
	extern double yme;
	extern double ymm;
	extern double ymtau;
	extern double cabi;
	extern double mMChi;
	extern double mMPsi;
	extern double alpha;
	extern double lam2;
	extern double lam3;
	extern double lam12;
	extern double lam13;
	extern double lam23;
	extern double lam123;
	extern double lam223;
	extern double lam332;
	extern double GG;
	extern double Me;
	extern double MMU;
	extern double MTA;
	extern double MU;
	extern double MC;
	extern double MT;
	extern double MD;
	extern double MS;
	extern double MB;
	extern double MZ;
	extern double MH;
	extern double WT;
	extern double WZ;
	extern double WW;
	extern double WH;
	extern double WChi;
	extern double WPsi;
	extern double E;
	extern double Pi;
	extern double aEW;
	extern double MW;
	extern double sw2;
	extern double EE;
	extern double cw;
	extern double sw;
	extern double vev;
	extern double lam;
	extern double muH;
	extern double MChi;
	extern double MPsi;
	extern double m22sq;
	extern double m33sq;
	extern double m23sq;
	extern double gw;
	extern double g1;
	extern double ye;
	extern double ym;
	extern double ytau;
	extern double yup;
	extern double yc;
	extern double yt;
	extern double ydo;
	extern double ys;
	extern double yb;
	extern double CKM1x1;
	extern double CKM1x2;
	extern double CKM1x3;
	extern double CKM2x1;
	extern double CKM2x2;
	extern double CKM2x3;
	extern double CKM3x1;
	extern double CKM3x2;
	extern double CKM3x3;
	extern double CKMnew1x1;
	extern double CKMnew1x2;
	extern double CKMnew1x3;
	extern double CKMnew2x1;
	extern double CKMnew2x2;
	extern double CKMnew2x3;
	extern double CKMnew3x1;
	extern double CKMnew3x2;
	extern double CKMnew3x3;
	extern double AH;
	extern double GH;
	extern double I1a11;
	extern double I1a12;
	extern double I1a13;
	extern double I1a21;
	extern double I1a22;
	extern double I1a23;
	extern double I1a31;
	extern double I1a32;
	extern double I1a33;
	extern double I2a11;
	extern double I2a12;
	extern double I2a13;
	extern double I2a21;
	extern double I2a22;
	extern double I2a23;
	extern double I2a31;
	extern double I2a32;
	extern double I2a33;
	extern double I3a11;
	extern double I3a12;
	extern double I3a13;
	extern double I3a21;
	extern double I3a22;
	extern double I3a23;
	extern double I3a31;
	extern double I3a32;
	extern double I3a33;
	extern double I4a11;
	extern double I4a12;
	extern double I4a13;
	extern double I4a21;
	extern double I4a22;
	extern double I4a23;
	extern double I4a31;
	extern double I4a32;
	extern double I4a33;
	extern double token1;
	extern double token2;
	extern double token3;
	extern double token4;
	extern double token5;
	extern double token6;
	extern double token7;
	extern double token8;
	extern double token9;
	extern double token10;
	extern double token11;
	extern double token12;
	extern double token13;
	extern double token14;
	extern double token15;
	extern double token16;
	extern double token17;
	extern double token18;
	extern double token19;
	extern double token20;
	extern double token21;
	extern double token22;
	extern double token23;
	extern double token24;
	extern double token25;
	extern double token26;
	extern double token27;
	extern double token28;
	extern double token29;
	extern double token30;
	extern double token31;
	extern double token32;
	extern double token33;
	extern double token34;
	extern double token35;
	extern double token36;
	extern double token37;
	extern double token38;
	extern double EL;
	extern double ee;
	extern double gs;
	extern double G;
	extern double FAGS;
}
	double ChiChiHH(const double &cos_t, const double &s);
	double ChiChiAA(const double &cos_t, const double &s);
	double ChiChiZZ(const double &cos_t, const double &s);
	double ChiChiwW(const double &cos_t, const double &s);
	double ChiChiGG(const double &cos_t, const double &s);
	double ChiChiEe(const double &cos_t, const double &s);
	double ChiChiMUmu(const double &cos_t, const double &s);
	double ChiChiTAta(const double &cos_t, const double &s);
	double ChiChiUu(const double &cos_t, const double &s);
	double ChiChiCc(const double &cos_t, const double &s);
	double ChiChiTt(const double &cos_t, const double &s);
	double ChiChiDd(const double &cos_t, const double &s);
	double ChiChiSs(const double &cos_t, const double &s);
	double ChiChiBb(const double &cos_t, const double &s);
	double ChiPsiHH(const double &cos_t, const double &s);
	double ChiPsiAA(const double &cos_t, const double &s);
	double ChiPsiZZ(const double &cos_t, const double &s);
	double ChiPsiwW(const double &cos_t, const double &s);
	double ChiPsiGG(const double &cos_t, const double &s);
	double ChiPsiEe(const double &cos_t, const double &s);
	double ChiPsiMUmu(const double &cos_t, const double &s);
	double ChiPsiTAta(const double &cos_t, const double &s);
	double ChiPsiUu(const double &cos_t, const double &s);
	double ChiPsiCc(const double &cos_t, const double &s);
	double ChiPsiTt(const double &cos_t, const double &s);
	double ChiPsiDd(const double &cos_t, const double &s);
	double ChiPsiSs(const double &cos_t, const double &s);
	double ChiPsiBb(const double &cos_t, const double &s);
	double PsiPsiHH(const double &cos_t, const double &s);
	double PsiPsiAA(const double &cos_t, const double &s);
	double PsiPsiZZ(const double &cos_t, const double &s);
	double PsiPsiwW(const double &cos_t, const double &s);
	double PsiPsiGG(const double &cos_t, const double &s);
	double PsiPsiEe(const double &cos_t, const double &s);
	double PsiPsiMUmu(const double &cos_t, const double &s);
	double PsiPsiTAta(const double &cos_t, const double &s);
	double PsiPsiUu(const double &cos_t, const double &s);
	double PsiPsiCc(const double &cos_t, const double &s);
	double PsiPsiTt(const double &cos_t, const double &s);
	double PsiPsiDd(const double &cos_t, const double &s);
	double PsiPsiSs(const double &cos_t, const double &s);
	double PsiPsiBb(const double &cos_t, const double &s);
	double ChiChiHHfl(const double &cos_t, const double &s);
	double ChiChiAAfl(const double &cos_t, const double &s);
	double ChiChiZZfl(const double &cos_t, const double &s);
	double ChiChiwWfl(const double &cos_t, const double &s);
	double ChiChiGGfl(const double &cos_t, const double &s);
	double ChiChiEefl(const double &cos_t, const double &s);
	double ChiChiMUmufl(const double &cos_t, const double &s);
	double ChiChiTAtafl(const double &cos_t, const double &s);
	double ChiChiUufl(const double &cos_t, const double &s);
	double ChiChiCcfl(const double &cos_t, const double &s);
	double ChiChiTtfl(const double &cos_t, const double &s);
	double ChiChiDdfl(const double &cos_t, const double &s);
	double ChiChiSsfl(const double &cos_t, const double &s);
	double ChiChiBbfl(const double &cos_t, const double &s);
	double ChiPsiHHfl(const double &cos_t, const double &s);
	double ChiPsiAAfl(const double &cos_t, const double &s);
	double ChiPsiZZfl(const double &cos_t, const double &s);
	double ChiPsiwWfl(const double &cos_t, const double &s);
	double ChiPsiGGfl(const double &cos_t, const double &s);
	double ChiPsiEefl(const double &cos_t, const double &s);
	double ChiPsiMUmufl(const double &cos_t, const double &s);
	double ChiPsiTAtafl(const double &cos_t, const double &s);
	double ChiPsiUufl(const double &cos_t, const double &s);
	double ChiPsiCcfl(const double &cos_t, const double &s);
	double ChiPsiTtfl(const double &cos_t, const double &s);
	double ChiPsiDdfl(const double &cos_t, const double &s);
	double ChiPsiSsfl(const double &cos_t, const double &s);
	double ChiPsiBbfl(const double &cos_t, const double &s);
	double PsiPsiHHfl(const double &cos_t, const double &s);
	double PsiPsiAAfl(const double &cos_t, const double &s);
	double PsiPsiZZfl(const double &cos_t, const double &s);
	double PsiPsiwWfl(const double &cos_t, const double &s);
	double PsiPsiGGfl(const double &cos_t, const double &s);
	double PsiPsiEefl(const double &cos_t, const double &s);
	double PsiPsiMUmufl(const double &cos_t, const double &s);
	double PsiPsiTAtafl(const double &cos_t, const double &s);
	double PsiPsiUufl(const double &cos_t, const double &s);
	double PsiPsiCcfl(const double &cos_t, const double &s);
	double PsiPsiTtfl(const double &cos_t, const double &s);
	double PsiPsiDdfl(const double &cos_t, const double &s);
	double PsiPsiSsfl(const double &cos_t, const double &s);
	double PsiPsiBbfl(const double &cos_t, const double &s);
	double wHHH();
	double wHChiChi();
	double wHChiPsi();
	double wHPsiPsi();
	double wHAA();
	double wHZZ();
	double wHwW();
	double wHGG();
	double wHEe();
	double wHMUmu();
	double wHTAta();
	double wHUu();
	double wHCc();
	double wHTt();
	double wHDd();
	double wHSs();
	double wHBb();
	double wwH(const double QCDaS);
}
