///////////////////CODE GENERATED VIA MATHEMATICA///////////////////


#pragma once

#include <cmath>

namespace DT{
	extern double aEWM1;
	extern double Gf;
	extern double aS;
	extern double ymdo;
	extern double ymup;
	extern double yms;
	extern double ymc;
	extern double ymb;
	extern double ymt;
	extern double yme;
	extern double ymm;
	extern double ymtau;
	extern double cabi;
	extern double mMChi;
	extern double mMPsi;
	extern double alpha;
	extern double lam2;
	extern double lam3;
	extern double lam12;
	extern double lam13;
	extern double lam23;
	extern double lam123;
	extern double lam223;
	extern double lam332;
	extern double GG;
	extern double Me;
	extern double MMU;
	extern double MTA;
	extern double MU;
	extern double MC;
	extern double MT;
	extern double MD;
	extern double MS;
	extern double MB;
	extern double MZ;
	extern double MH;
	extern double WT;
	extern double WZ;
	extern double WW;
	extern double WH;
	extern double WChi;
	extern double WPsi;
	extern double E;
	extern double Pi;
	extern double vev;
	extern double lam;
	extern double muH;
	extern double MChi;
	extern double MPsi;
	extern double m22sq;
	extern double m33sq;
	extern double m23sq;
	extern double aEW;
	extern double MW;
	extern double sw2;
	extern double EE;
	extern double cw;
	extern double sw;
	extern double gw;
	extern double g1;
	extern double ye;
	extern double ym;
	extern double ytau;
	extern double yup;
	extern double yc;
	extern double yt;
	extern double ydo;
	extern double ys;
	extern double yb;
	extern double CKM1x1;
	extern double CKM1x2;
	extern double CKM1x3;
	extern double CKM2x1;
	extern double CKM2x2;
	extern double CKM2x3;
	extern double CKM3x1;
	extern double CKM3x2;
	extern double CKM3x3;
	extern double CKMnew1x1;
	extern double CKMnew1x2;
	extern double CKMnew1x3;
	extern double CKMnew2x1;
	extern double CKMnew2x2;
	extern double CKMnew2x3;
	extern double CKMnew3x1;
	extern double CKMnew3x2;
	extern double CKMnew3x3;
	extern double AH;
	extern double GH;
	extern double I1a11;
	extern double I1a12;
	extern double I1a13;
	extern double I1a21;
	extern double I1a22;
	extern double I1a23;
	extern double I1a31;
	extern double I1a32;
	extern double I1a33;
	extern double I2a11;
	extern double I2a12;
	extern double I2a13;
	extern double I2a21;
	extern double I2a22;
	extern double I2a23;
	extern double I2a31;
	extern double I2a32;
	extern double I2a33;
	extern double I3a11;
	extern double I3a12;
	extern double I3a13;
	extern double I3a21;
	extern double I3a22;
	extern double I3a23;
	extern double I3a31;
	extern double I3a32;
	extern double I3a33;
	extern double I4a11;
	extern double I4a12;
	extern double I4a13;
	extern double I4a21;
	extern double I4a22;
	extern double I4a23;
	extern double I4a31;
	extern double I4a32;
	extern double I4a33;
	extern double gc28;
	extern double gc29;
	extern double gc30;
	extern double gc31;
	extern double gc32;
	extern double gc34;
	extern double gc37;
	extern double gc38;
	extern double gc40;
	extern double gc42;
	extern double gc45;
	extern double gc46;
	extern double gc48;
	extern double gc50;
	extern double gc52;
	extern double gc54;
	extern double gc55;
	extern double gc56;
	extern double gc57;
	extern double gc58;
	extern double gc59L;
	extern double gc59R;
	extern double gc60L;
	extern double gc60R;
	extern double gc61L;
	extern double gc61R;
	extern double gc62L;
	extern double gc62R;
	extern double gc63L;
	extern double gc63R;
	extern double gc64L;
	extern double gc64R;
	extern double gc65L;
	extern double gc65R;
	extern double gc66L;
	extern double gc66R;
	extern double gc67L;
	extern double gc67R;
	extern double gc68L;
	extern double gc68R;
	extern double gc69L;
	extern double gc69R;
	extern double gc70L;
	extern double gc70R;
	extern double gc71;
	extern double gc72;
	extern double gc73;
	extern double gc74;
	extern double gc75;
	extern double gc76;
	extern double gc77L;
	extern double gc77R;
	extern double gc78L;
	extern double gc78R;
	extern double gc79L;
	extern double gc79R;
	extern double gc80;
	extern double gc81;
	extern double gc82;
	extern double gc83L;
	extern double gc83R;
	extern double gc84L;
	extern double gc84R;
	extern double gc85L;
	extern double gc85R;
	extern double gc86L;
	extern double gc86R;
	extern double gc87L;
	extern double gc87R;
	extern double gc88L;
	extern double gc88R;
	extern double gc89L;
	extern double gc89R;
	extern double gc90L;
	extern double gc90R;
	extern double gc91L;
	extern double gc91R;
	extern double gc92L;
	extern double gc92R;
	extern double gc93L;
	extern double gc93R;
	extern double gc94L;
	extern double gc94R;
	extern double gc95;
	extern double gc96;
	extern double gc97;
	extern double gc100;
	extern double gc101;
	extern double gc102;
	extern double gc103;
	extern double gc106;
	extern double gc107;
	extern double gc108;
	extern double gc112;
	extern double gc113;
	extern double gc114;
	extern double gc115;
	extern double gc116R;
	extern double gc117R;
	extern double gc118R;
	extern double gc120;
	extern double gc121;
	extern double gc124;
	extern double gc127;
	extern double gc128;
	extern double gc132;
	extern double gc133;
	extern double gc134;
	extern double gc135;
	extern double gc136;
	extern double gc137;
	extern double gc138;
	extern double gc139;
	extern double gc140;
	extern double gc141;
	extern double gc142;
	extern double gc143;
	extern double gc144;
	extern double gc145;
	extern double gc146;
	extern double gc147;
	extern double gc148;
	extern double gc149;
	extern double gc150;
	extern double gc151;
	extern double gc152;
	extern double gc153;
	extern double gc154;
	extern double gc155;
	extern double gc156;
	extern double gc157;
	extern double gc158;
	extern double gc159;
	extern double gc160;
	extern double gc161;
	extern double gc162;
	extern double gc163;
	extern double gc164;
	extern double gc165;
	extern double gc166;
	extern double gc167;
	extern double gc168;
	extern double gc169;
	extern double gc170;
	extern double gc171;
	extern double gc172;
	extern double gc173L;
	extern double gc173R;
	extern double gc174L;
	extern double gc174R;
	extern double gc175L;
	extern double gc175R;
	extern double gc176L;
	extern double gc176R;
	extern double gc177L;
	extern double gc177R;
	extern double gc178L;
	extern double gc178R;
	extern double gc179;
	extern double gc180;
	extern double gc181;
	extern double gc182L;
	extern double gc182R;
	extern double gc183L;
	extern double gc183R;
	extern double gc184L;
	extern double gc184R;
	extern double EL;
	extern double ee;
	extern double gs;
	extern double G;
	extern double FAGS;

	double ChiChiHH(const double &cos_t, const double &s);
	double ChiChiAA(const double &cos_t, const double &s);
	double ChiChiZZ(const double &cos_t, const double &s);
	double ChiChiwW(const double &cos_t, const double &s);
	double ChiChiGG(const double &cos_t, const double &s);
	double ChiChiEe(const double &cos_t, const double &s);
	double ChiChiMUmu(const double &cos_t, const double &s);
	double ChiChiTAta(const double &cos_t, const double &s);
	double ChiChiUu(const double &cos_t, const double &s);
	double ChiChiCc(const double &cos_t, const double &s);
	double ChiChiTt(const double &cos_t, const double &s);
	double ChiChiDd(const double &cos_t, const double &s);
	double ChiChiSs(const double &cos_t, const double &s);
	double ChiChiBb(const double &cos_t, const double &s);
	double ChiChiChiPsi(const double &cos_t, const double &s);
	double ChiChiPsiPsi(const double &cos_t, const double &s);
	double ChiPsiHH(const double &cos_t, const double &s);
	double ChiPsiAA(const double &cos_t, const double &s);
	double ChiPsiZZ(const double &cos_t, const double &s);
	double ChiPsiwW(const double &cos_t, const double &s);
	double ChiPsiGG(const double &cos_t, const double &s);
	double ChiPsiEe(const double &cos_t, const double &s);
	double ChiPsiMUmu(const double &cos_t, const double &s);
	double ChiPsiTAta(const double &cos_t, const double &s);
	double ChiPsiUu(const double &cos_t, const double &s);
	double ChiPsiCc(const double &cos_t, const double &s);
	double ChiPsiTt(const double &cos_t, const double &s);
	double ChiPsiDd(const double &cos_t, const double &s);
	double ChiPsiSs(const double &cos_t, const double &s);
	double ChiPsiBb(const double &cos_t, const double &s);
	double PsiPsiHH(const double &cos_t, const double &s);
	double PsiPsiAA(const double &cos_t, const double &s);
	double PsiPsiZZ(const double &cos_t, const double &s);
	double PsiPsiwW(const double &cos_t, const double &s);
	double PsiPsiGG(const double &cos_t, const double &s);
	double PsiPsiEe(const double &cos_t, const double &s);
	double PsiPsiMUmu(const double &cos_t, const double &s);
	double PsiPsiTAta(const double &cos_t, const double &s);
	double PsiPsiUu(const double &cos_t, const double &s);
	double PsiPsiCc(const double &cos_t, const double &s);
	double PsiPsiTt(const double &cos_t, const double &s);
	double PsiPsiDd(const double &cos_t, const double &s);
	double PsiPsiSs(const double &cos_t, const double &s);
	double PsiPsiBb(const double &cos_t, const double &s);
	double ChiChiHHfl(const double &cos_t, const double &s);
	double ChiChiAAfl(const double &cos_t, const double &s);
	double ChiChiZZfl(const double &cos_t, const double &s);
	double ChiChiwWfl(const double &cos_t, const double &s);
	double ChiChiGGfl(const double &cos_t, const double &s);
	double ChiChiEefl(const double &cos_t, const double &s);
	double ChiChiMUmufl(const double &cos_t, const double &s);
	double ChiChiTAtafl(const double &cos_t, const double &s);
	double ChiChiUufl(const double &cos_t, const double &s);
	double ChiChiCcfl(const double &cos_t, const double &s);
	double ChiChiTtfl(const double &cos_t, const double &s);
	double ChiChiDdfl(const double &cos_t, const double &s);
	double ChiChiSsfl(const double &cos_t, const double &s);
	double ChiChiBbfl(const double &cos_t, const double &s);
	double ChiChiChiPsifl(const double &cos_t, const double &s);
	double ChiChiPsiPsifl(const double &cos_t, const double &s);
	double ChiPsiHHfl(const double &cos_t, const double &s);
	double ChiPsiAAfl(const double &cos_t, const double &s);
	double ChiPsiZZfl(const double &cos_t, const double &s);
	double ChiPsiwWfl(const double &cos_t, const double &s);
	double ChiPsiGGfl(const double &cos_t, const double &s);
	double ChiPsiEefl(const double &cos_t, const double &s);
	double ChiPsiMUmufl(const double &cos_t, const double &s);
	double ChiPsiTAtafl(const double &cos_t, const double &s);
	double ChiPsiUufl(const double &cos_t, const double &s);
	double ChiPsiCcfl(const double &cos_t, const double &s);
	double ChiPsiTtfl(const double &cos_t, const double &s);
	double ChiPsiDdfl(const double &cos_t, const double &s);
	double ChiPsiSsfl(const double &cos_t, const double &s);
	double ChiPsiBbfl(const double &cos_t, const double &s);
	double PsiPsiHHfl(const double &cos_t, const double &s);
	double PsiPsiAAfl(const double &cos_t, const double &s);
	double PsiPsiZZfl(const double &cos_t, const double &s);
	double PsiPsiwWfl(const double &cos_t, const double &s);
	double PsiPsiGGfl(const double &cos_t, const double &s);
	double PsiPsiEefl(const double &cos_t, const double &s);
	double PsiPsiMUmufl(const double &cos_t, const double &s);
	double PsiPsiTAtafl(const double &cos_t, const double &s);
	double PsiPsiUufl(const double &cos_t, const double &s);
	double PsiPsiCcfl(const double &cos_t, const double &s);
	double PsiPsiTtfl(const double &cos_t, const double &s);
	double PsiPsiDdfl(const double &cos_t, const double &s);
	double PsiPsiSsfl(const double &cos_t, const double &s);
	double PsiPsiBbfl(const double &cos_t, const double &s);
	double ChiChi(const double &cos_t, const double &s);
	double ChiPsi(const double &cos_t, const double &s);
	double PsiPsi(const double &cos_t, const double &s);
}
